Add route name to output envoy config
solo-io/gloo pull request #10010
Opened 2024-09-10 17:40 UTC by npolshakova

# Description

RouteOptions JWT PR added unique name for HTTPRoute routes: https://github.com/solo-io/solo-projects/pull/6788/files#diff-e63ec6ccf19f856877aa52c64a5797245fa30a435e5803180875e5f19ca4cb56 

## API changes
None

## Code changes
None, only changed translator envoy expected output

## CI changes
TODO: sanity check CI is running the unit tests

## Docs changes
NONE

# Context
https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1725975132629659

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2024-09-10 17:46 UTC, npolshakova commented
/kick build bot failed to start: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=5e3023ae-8e7a-484a-a4cb-469102df0026

2024-09-10 17:47 UTC, timflannagan approved these changes

2024-09-10 22:29 UTC, npolshakova commented on projects/gateway2/translator/testutils/outputs/route-sort.yaml
> +            name: route-1-infra-0
This is the config that's generating it:
```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-1
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: RegularExpression
        value: /a/.*
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: RegularExpression
        value: /b/c/.*
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: Exact
        value: /a/1
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: Exact
        value: /a/1/2
    backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-2
  namespace: infra
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /x
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /x/1
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: RegularExpression
        value: /x/.*
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: RegularExpression
        value: /x/y/.*
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: Exact
        value: /x/1
    backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: Exact
        value: /x/1/2
    backendRefs:
    - name: example-svc
      port: 80
```

The rule to create the unique name is: `name-namespace-id`. So in this case the route is `route-1`, namespace is `infra`, and this is the first route:
```
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - name: example-svc
      port: 80
```

2024-09-10 22:31 UTC, npolshakova commented on projects/gateway2/translator/testutils/outputs/route-sort.yaml
> +            name: route-1-infra-0
Hm... but I see what you mean. This one should be id=0:
```
          - matchers:
            - exact: /a/1/2
            options: {}
            name: route-1-infra-0
            routeAction:
              single:
                kube:
                  port: 80
                  ref:
                    name: example-svc
                    namespace: infra
```

2024-09-10 22:33 UTC, npolshakova commented on projects/gateway2/translator/testutils/outputs/route-sort.yaml
> +            name: route-1-infra-0
Ah, I think the rule also needs to be included in the name...

2024-09-11 02:03 UTC, npolshakova commented on projects/gateway2/translator/testutils/outputs/route-sort.yaml
> +            name: route-1-infra-0
Okay updated this in https://github.com/solo-io/gloo/pull/10010/commits/180495c91d68a92f2963719de030b9fe087fb0c2 but might be good to have a discussion offline if that's the best way of handling the uniqueness

2024-09-11 02:24 UTC, timflannagan commented on projects/gateway2/translator/testutils/outputs/route-sort.yaml
> +            name: route-1-infra-0
Totally agree. At a glance, it seems reasonable but I'd recommend starting a thread to get thoughts from other folks.

2024-09-11 12:52 UTC, EItanya requested changes

2024-09-11 12:52 UTC, EItanya commented on projects/gateway2/query/httproute.go
> +	return fmt.Sprintf("%s-%s-%d-%d", hr.GetName(), hr.GetNamespace(), ruleHash, index)
Is there a length constraint we need to worry about here?

2024-09-11 13:41 UTC, npolshakova commented on projects/gateway2/query/httproute.go
> +	return fmt.Sprintf("%s-%s-%d-%d", hr.GetName(), hr.GetNamespace(), ruleHash, index)
So we can either use the hash here or the index from `for ruleIdx, rule := range route.Spec.Rules`:
```
Alternative approaches:
1. name-namespace-ruleHash-index
2. name-namespace-ruleIndex-matchesIndex
```

The[ route name](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route.proto#config-route-v3-routeconfiguration) is just a string in envoy, so the limit is just the proto limit:
```
A string must always contain UTF-8 encoded[5] or 7-bit ASCII text, and cannot be longer than 232.
```

So we could run into the limit if the name + namespace is extremely long that appending the hash + index puts it over the edge. I can add a check here and error if it's too long. The `ruleIndex-matchIndex` is a little shorter, but would still potentially run into this issue.

2024-09-11 13:52 UTC, EItanya commented on projects/gateway2/query/httproute.go
> +	return fmt.Sprintf("%s-%s-%d-%d", hr.GetName(), hr.GetNamespace(), ruleHash, index)
My bad., I don't see any length constraint [here](https://github.com/envoyproxy/envoy/blob/7b8baff1758f0a584dcc3cb657b5032000bcb3d7/api/envoy/config/route/v3/route_components.proto#L257C1-L258C1) so I think we're good to go.

2024-09-11 13:52 UTC, EItanya approved these changes

2024-09-11 14:45 UTC, lgadban commented on projects/gateway2/query/httproute.go
> +func (hr *HTTPRouteInfo) UniqueRouteName(index int, ruleHash uint64) string {
godoc comment should be updated explaining what ruleHash is

2024-09-11 14:51 UTC, lgadban commented on projects/gateway2/query/httproute.go
> +	return fmt.Sprintf("%s-%s-%d-%d", hr.GetName(), hr.GetNamespace(), ruleHash, index)
The rule index makes it actually parse-able by a human -- is there a benefit to using the rulehash?

2024-09-11 15:37 UTC, npolshakova commented on projects/gateway2/query/httproute.go
> +func (hr *HTTPRouteInfo) UniqueRouteName(index int, ruleHash uint64) string {
Updated comment to describe rule index and match index

2024-09-11 17:31 UTC, sam-heilbron approved these changes

2024-09-11 18:15 UTC, merged