platform agnostic lb ep hash
solo-io/gloo pull request #10396
Opened 2024-11-22 22:36 UTC by stevenctl

# Description

  Don't use native endian-ness when generating hashes.
      This creates difficulty reproducing tests on different machines
      where the hashes end up in goldenfiles.

2024-11-23 17:42 UTC, yuval-k commented on projects/gateway2/krtcollections/endpoints_test.go
> +func combineHashes(hash1, hash2 uint64) uint64 {
why this change?

2024-11-25 16:29 UTC, yuval-k requested changes
also, there's a change needed  in `projects/gateway2/utils/hash.go` in HashUint64

2024-11-25 18:01 UTC, stevenctl commented on projects/gateway2/proxy_syncer/cla.go
> +
reverting it

2024-11-25 22:09 UTC, yuval-k commented on projects/gateway2/proxy_syncer/cla.go
> -		EndpointsHash: ep.LbEpsEqualityHash ^ additionalHash,
revert this change?

2024-11-25 22:52 UTC, yuval-k approved these changes

2024-11-26 00:39 UTC, lgadban commented on changelog/v1.18.0-rc3/platform-agnostic-lbephash.yaml
> +      Don't use xor or native endian-ness when generating hashes.
can we update changelog (and PR description) to reflect that we are keeping xor ?

2024-11-26 15:23 UTC, merged