Bump moby 1.18
solo-io/gloo pull request #10437
Opened 2024-12-04 23:17 UTC by bewebi

# Description

- Bump pinned moby version from v24.0.7 to v26.0.0

# Context

https://github.com/advisories/GHSA-2mj3-vfvx-fc43 and https://github.com/advisories/GHSA-gh5c-3h97-2f3q were identified in moby/moby v24.0.7 so we are bumping to v26.0.0, which resolves these

Images build cleanly without further modifications

There was discussion around alternatives to pinning `moby/moby` [here](https://solo-io-corp.slack.com/archives/C083Z2EPSPJ/p1733330034752289)

The docs site was failing to build due to an edge case that occurs when there are fewer than four GA branches being scanned for vulnerabilities
The original PR included some changes, which are not needed on LTS branchs, but for some reason a seemingly empty diff is still present on one docs file

## Testing steps

Build images locally via:
```
VERSION=0.0.0-test make -B docker-standard
```
Scan locally via:
```
VERSION=0.0.0-test make scan-version
```
Observe the final log line like:
```
{"level":"info","ts":"2024-12-04T18:17:12.442-0500","caller":"commands/scan_version.go:31","msg":"No vulnerabilities found"}
```

## Notes for reviewers

Changelog references 1.17 issue and therefore does not resolve

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-12-04 23:25 UTC, andy-fong approved these changes

2024-12-04 23:27 UTC, andy-fong requested changes

2024-12-04 23:27 UTC, andy-fong commented on changelog/v1.19.0-beta1/bump-moby.yaml
> +changelog:
actually, I missed that this is merging to 1.18.x branch. So, the changelog should not be in v1.19.0?

2024-12-04 23:44 UTC, sam-heilbron approved these changes

2024-12-05 00:37 UTC, jenshu approved these changes

2024-12-05 15:57 UTC, andy-fong approved these changes

2024-12-05 16:59 UTC, merged