initial commit
solo-io/gloo pull request #3588
Opened 2020-09-02 19:14 UTC by mlholland

# Description

Adds a use_tls flag to consul upstream configs, which causes gloo to use HTTPS when communicating with that upstream if true. 

The passing test indicates that it works as expected, but I'd like to figure out how to smoke test it locally before changing this to a real PR.

# Context

https://github.com/solo-io/gloo/issues/2544

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

2020-09-02 19:55 UTC, kdorosh commented on projects/gloo/api/v1/options/consul/consul.proto
> +    bool  use_tls = 8;
super nits,
```suggestion
    // Whether or not to use HTTP (false, default) or HTTPS (true) when communicating with this consul upstream.
    // If this configuration includes an SSL config, HTTPS is always used and this value is ignored.
    bool use_tls = 8;
```

2020-09-02 20:01 UTC, mlholland commented on projects/gloo/api/v1/options/consul/consul.proto
> +    bool  use_tls = 8;
changing locally, since this'll affect generated files.

2020-09-02 20:02 UTC, kdorosh commented on projects/gloo/pkg/plugins/consul/plugin.go
>  		scheme = "https"
close. the logic for `spec.UseTls` should be used on the `ProcessUpstream` function and set the transport socket, similar to:
See here: https://github.com/solo-io/gloo/blob/a15ebb34ca1273489fa30853454b18e7c0a4741e/projects/gloo/pkg/plugins/static/plugin.go#L102-L115

as noted here: https://github.com/solo-io/gloo/issues/2583#issue-579559337

2020-09-03 18:41 UTC, mlholland commented on projects/gloo/pkg/plugins/consul/plugin.go
>  		scheme = "https"
Done

2020-09-04 17:20 UTC, kdorosh requested changes
still need to address https://github.com/solo-io/gloo/pull/3588/files#r482385206 , further we should have auto detection for port 443

2020-09-09 17:35 UTC, kdorosh commented on projects/gloo/pkg/plugins/consul/eds.go
> +			p.upstreamHttpsMap[upstream.Metadata.Namespace + upstream.Metadata.Name] = true
we could use `upstream.Ref().Key()` here as the key

2020-09-09 17:37 UTC, kdorosh commented on projects/gloo/pkg/plugins/consul/plugin.go
> +	}
we won't want to change the cluster to static, we will still be providing endpoints via sds

2020-09-09 17:46 UTC, kdorosh reviewed
good start,

also note that we may want to update UDS to set `useTls` to true when port is 443: https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/upstreams/consul/upstream_client.go#L86

2020-09-09 17:47 UTC, kdorosh commented on projects/gloo/api/v1/options/consul/consul.proto
> +    bool use_tls = 8;
BoolVal so this is nillable?

2020-09-09 19:03 UTC, mlholland commented on projects/gloo/pkg/plugins/consul/plugin.go
> +	}
honestly not sure how that got added in, removing

2020-09-10 17:15 UTC, mlholland commented on projects/gloo/api/v1/options/consul/consul.proto
> +    bool use_tls = 8;
done

2020-09-10 17:15 UTC, mlholland commented on projects/gloo/pkg/plugins/consul/eds.go
> +			p.upstreamHttpsMap[upstream.Metadata.Namespace + upstream.Metadata.Name] = true
done

2020-09-14 14:40 UTC, closed without merging