[WIP] Add helm value for stats prefix rewrite #3752
solo-io/gloo pull request #3759
Opened 2020-10-19 04:05 UTC by andylibrian

# Description

This PR adds a helm value for stats prefix rewrite

Currently it's hard-coded to `/stats/prometheus`. To integrate with
Datadog, or other monitoring system, we need to be able to change
the envoy stats endpoint.

# Context

I want to setup Datadog integration to monitor envoy as described in the docs https://docs.solo.io/gloo/latest/guides/integrations/datadog/. But there is a manual step to update the configmap.
I want to eliminate the manual step so that I can automate it.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

fixes #3752

2020-10-19 17:25 UTC, kdorosh commented on changelog/v1.6.0-beta4/helm-value-for-stats-prefix-rewrite.yaml
> +      Add a helm value for stats prefix rewrite. This allows to integrate with other monitoring system instead of just Prometheus.
nit, grammar
```suggestion
      Add a helm value for stats prefix rewrite. This allows Gloo to integrate with other monitoring systems instead of just Prometheus, by setting the `global.glooStats.routePrefixRewrite` helm value.
```

2020-10-19 17:27 UTC, kdorosh commented on install/helm/gloo/generate/values.go
> +	RoutePrefixRewrite *string `json:"routePrefixRewrite,omitempty" desc:"The envoy stats endpoint to which the metrics endpoint is rewritten"`
nit, grammar
```suggestion
	RoutePrefixRewrite *string `json:"routePrefixRewrite,omitempty" desc:"The envoy stats endpoint to which the metrics are written"`
```
this will require codegen again, since this ends up in our generated helm docs

2020-10-19 17:37 UTC, kdorosh commented on install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
> +                                prefix_rewrite: {{ $statsConfig.routePrefixRewrite }}
this isn't the only place we need this change. we will also need it:
- https://github.com/solo-io/gloo/blob/f82f098a442ae595c83a196ba433704043a3acc1/install/helm/gloo/templates/30-knative-internal-proxy-configmap.yaml#L79
- https://github.com/solo-io/gloo/blob/a1c855be2fa47588eeb84dd69f2405178c32b8dc/install/helm/gloo/templates/12-ingress-proxy-configmap.yaml#L78
- https://github.com/solo-io/gloo/blob/f82f098a442ae595c83a196ba433704043a3acc1/install/helm/gloo/templates/15-clusteringress-proxy-configmap.yaml#L79
- https://github.com/solo-io/gloo/blob/f82f098a442ae595c83a196ba433704043a3acc1/install/helm/gloo/templates/27-knative-external-proxy-configmap.yaml#L79

2020-10-19 17:38 UTC, kdorosh requested changes
needs the same change in a couple more places, couple nits

2020-10-20 02:50 UTC, andylibrian commented on install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
> +                                prefix_rewrite: {{ $statsConfig.routePrefixRewrite }}
I have a couple of questions for those files:

1. Those `.stats` values are different with the file I've updated. The one I've modified has `stats.enabled`, while those don't have one. For example in `12-ingress-proxy-configmap.yaml`, this `if` block  `{{- if .Values.ingressProxy.deployment.stats }}`, I don't see this value in `install/helm/gloo/generate/values.go` or in `docs/content/reference/values.txt`. It's not in `install/helm/gloo/values-template.yaml` either. Isn't it supposed to be there?

2. Currently those values don't coalesce with `.Values.global.glooStats`. So, for now let's just read from `.global.glooStats.routePrefixRewrite`?

2020-10-20 14:18 UTC, kdorosh commented on install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
> +                                prefix_rewrite: {{ $statsConfig.routePrefixRewrite }}
1. We should add that missing go struct to the helm generate code, and that will fix the docs upon redoing codegen, by adding here https://github.com/solo-io/gloo/blob/dcce5e2e133070d0155f2804e1cd8ebf7fd3f945/install/helm/gloo/generate/values.go#L407
2. sure, it's probably out of scope to add the stats coalesce logic to the other configmaps in this pr, even though we will likely want that at some point in the future

2020-10-20 14:19 UTC, kdorosh commented
/test

2020-10-20 14:35 UTC, EItanya commented
/kick

2020-10-20 14:51 UTC, kdorosh approved these changes
not going to hold the pr back for a small docs nit

2020-10-20 14:54 UTC, merged

2020-10-21 09:45 UTC, andylibrian commented on install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
> +                                prefix_rewrite: {{ $statsConfig.routePrefixRewrite }}
Sounds good, thanks for the review. I opened a new PR to update those other config maps: https://github.com/solo-io/gloo/pull/3779