Docs firebase rework
solo-io/gloo pull request #3837
Opened 2020-11-09 19:13 UTC by EItanya

# Description

Transition Gloo docs to firebase hosting

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-11-10 16:30 UTC, kdorosh commented on docs/build-docs.sh
> +# Update this array with all versions of SMH to include in the versioned docs website.
still references SMH

2020-11-10 16:36 UTC, kdorosh commented on docs/old-version-marker.sh
> -EOF
we don't want to lose robots.txt on the older versions of the docs site

2020-11-10 16:38 UTC, kdorosh commented on docs/conf/conf.d/default.conf
> -  gzip_min_length 1100;
we don't want to lose gzip, this gave us a nice performance improvement

2020-11-10 16:41 UTC, kdorosh requested changes
some small things we still want to port over, looks good so far!

2020-11-10 18:58 UTC, EItanya commented on docs/conf/conf.d/default.conf
> -  gzip_min_length 1100;
This is nginx config, no longer valid

2020-11-10 18:59 UTC, EItanya commented on docs/old-version-marker.sh
> -EOF
I could not find how this was used anywhere. Can you show me how it's being used currently in old versions so I can make sure it stays in

2020-11-10 21:41 UTC, kdorosh commented on docs/old-version-marker.sh
> -EOF
we were initially misusing it, we probably want to use https://developers.google.com/search/reference/robots_meta_tag instead

2020-11-10 21:41 UTC, kdorosh commented on docs/conf/conf.d/default.conf
> -  gzip_min_length 1100;
by default, firebase gzips your files https://stackoverflow.com/questions/34318491/serving-gzipped-files-on-firebase-hosting so happy to resolve this

2020-11-10 22:27 UTC, EItanya commented on docs/old-version-marker.sh
> -EOF
This will require overwriting another layout most likely, is this something we could potentially do in a follow-up?

2020-11-11 00:01 UTC, kdorosh commented on docs/old-version-marker.sh
> -EOF
sure, opened https://github.com/solo-io/gloo/issues/3847 to track

2020-11-11 00:02 UTC, kdorosh approved these changes

2020-11-11 00:02 UTC, merged