[WIP] Expose tracing configuration through dynamic listener
solo-io/gloo pull request #3838
Opened 2020-11-09 19:51 UTC by sam-heilbron

# Description

Envoy v3 allows tracing to be configured at the listener level. We want to support this as well, and expose it on the Gloo API.

# Context

Previously, Envoy v2 allowed tracing to be configured at the bootstrap/global level. In v3, they changed it to be at the listener level. This PR updates the Gloo API to be compatible.

A follow up PR will be used to remove the default configuration from the bootstrap level.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2020-11-09 20:22 UTC, sam-heilbron commented
/kick

2020-11-09 20:58 UTC, EItanya commented
A couple of things to bring up here before merging:
1. Do we want to add this config into the helm chart in this PR or a follow up?
2. Do we want to add tracing regression tests now as well?

At the very least I would like to see e2e tests similar to https://github.com/solo-io/gloo/blob/master/test/e2e/zipkin_test.go

2020-11-09 21:20 UTC, sam-heilbron commented
> A couple of things to bring up here before merging:
> 
> 1. Do we want to add this config into the helm chart in this PR or a follow up?

I thought I would add the config into the helm chart in a follow up. The goal was to have each PR introduce a single change: first to support config, second to implement it. Since the helm change will be small enough, I'm happy to do it as part of this PR. What do you think is best?

> 2. Do we want to add tracing regression tests now as well?
> 
> At the very least I would like to see e2e tests similar to https://github.com/solo-io/gloo/blob/master/test/e2e/zipkin_test.go

Yeah good call. I'm trying to better understand the e2e tests and I'll write some to cover this case.

2020-11-09 21:25 UTC, EItanya commented
> I thought I would add the config into the helm chart in a follow up. The goal was to have each PR introduce a single change: first to support config, second to implement it. Since the helm change will be small enough, I'm happy to do it as part of this PR. What do you think is best?

That sounds good to me, if that's the case then we should set `resolvesIssue: false` in the changelog

2020-11-11 16:05 UTC, EItanya commented on test/e2e/gateway_test.go
> +		Context("tracing", func() {
Can we move these tests into `tracing_test.go`?

2020-11-11 16:07 UTC, EItanya commented on test/e2e/gateway_test.go
> +		Context("tracing", func() {
Also, similar to how it's done in `zipkin_test.go` can we test that the traces are actually making it into zipkin

2020-11-12 16:10 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +	typedConfig, err := protoutils.AnyGogoToPb(tracingSettings.Provider.GetTypedConfig())
I think we can change the impl of this function. Right now it does a double marshal, but we can actually just do a simple conversion, something like:
```
	typedGogoMsg := utils.MustMessageToAny(msg)
        newGolangAny := &any.Any{
            TypeUrl: typedGogoMsg.GetTypedUrl(),
            Value: typedGogoMsg.GetValue()
        }
```

2020-11-12 16:10 UTC, EItanya commented on projects/gloo/pkg/plugins/hcm/plugin_test.go
> +				Provider: &tracingv1.Provider{
I think it's also important here to test that we can properly `unmarshal` the yaml. This is our first instance of using `Any` like envoy in this way, and the `gogo` vs `golang` proto differences have me a bit worried.

2020-11-12 17:38 UTC, sam-heilbron commented on projects/gloo/api/v1/options/tracing/tracing.proto
> +    Provider provider = 4;
I opted for just provider since it was in the tracing.proto file, I figured it was already tracing namespaced. I'd happily change it to tracing_provider though, I like the clarity. Would you expect the type to change to TracingProvider as well?

2020-11-12 17:39 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +	typedConfig, err := protoutils.AnyGogoToPb(tracingSettings.Provider.GetTypedConfig())
Awesome! Thanks for the tip. Yeah what I was doing felt a little smelly. This alternative feels better.

2020-11-12 22:50 UTC, sam-heilbron commented
Eitan helped me out and it's clear that our current dependence on `gogo` is going to cause an issue with this implementation. When unmarshalling, the Enum isn't found. I'm converting this back into a draft and going to move forward with the following:
- Supporting specific types (as opposed to any). I'll start with Zipkin first
- Writing a translation function to support these types
- Tests for the translation functions

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +func (p *Plugin) ProcessEnvoyTracingProvider(snapshot *v1.ApiSnapshot, tracingSettings *tracing.ListenerTracingSettings) (*envoy_config_trace_v3.Tracing_Http, error) {
nit: private function
```suggestion
func (p *Plugin) processEnvoyTracingProvider(snapshot *v1.ApiSnapshot, tracingSettings *tracing.ListenerTracingSettings) (*envoy_config_trace_v3.Tracing_Http, error) {
```

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +	if tracingSettings == nil || tracingSettings.ProviderConfig == nil {
```suggestion
	if tracingSettings.GetProviderConfig() == nil {
```

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +	switch typed := tracingSettings.ProviderConfig.(type) {
```suggestion
	switch typed := tracingSettings.GetProviderConfig().(type) {
```

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +		marshalledZipkinConfig, err := proto.Marshal(envoyZipkinConfig)
You can do `MarshalAny` here which will also fill in the `TypeUrl`

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +		return "", errors.Errorf("Invalid CollectorUpstreamRef (no upstream found for ref provided)")
Can you add which ref that is

2020-11-17 02:58 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +		marshalledDatadogConfig, err := proto.Marshal(envoyDatadogConfig)
`MarshalAny`

2020-11-17 15:30 UTC, sam-heilbron commented on docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/trace/v3/zipkin.proto.sk.md
> +| `DEPRECATED_AND_UNAVAILABLE_DO_NOT_USE` | Zipkin API v1, JSON over HTTP. [#comment: The default implementation of Zipkin client before this field is added was only v1 and the way user configure thi
I should probably just remove this

2020-11-17 15:56 UTC, EItanya requested changes

2020-11-17 15:56 UTC, EItanya commented on pkg/utils/gogoutils/trace.go
> +		ServiceName:      glooDatadogConfig.ServiceName,
nit: in general all gets from a proto message should be done with the `Get<Field>` function as they are nil saf

2020-11-17 16:03 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin.go
> +	return nil, errors.Errorf("Unsupported Tracing.ProviderConfiguration")
Can we move this into the default case, and add the type to the error string

2020-11-17 16:04 UTC, EItanya commented on projects/gloo/pkg/plugins/hcm/plugin_test.go
> +				ProviderConfig:        nil,
Can we add a test here that the `HcmPlugins` get called properly?

2020-11-17 16:05 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin_test.go
> +			// TODO (sam) - Fix this
TODO?

2020-11-17 16:06 UTC, EItanya commented on projects/gloo/pkg/plugins/tracing/plugin_test.go
> +			envoyTracingProvider, err := p.processEnvoyTracingProvider(pluginParams.Snapshot, hcmTracingSettings)
In general non-interface functions shouldn't be called like this in tests, better to test the component as it is used by the parent

2020-11-17 16:09 UTC, EItanya commented on test/e2e/zipkin_test.go
> +		startZipkinServer(":9411", nil)
How does this work if the handle func isn't passed in here?

2020-11-17 16:10 UTC, EItanya commented on test/e2e/zipkin_test.go
> +			}
Are you testing both http and https gateways?

2020-11-17 16:10 UTC, EItanya commented on test/e2e/zipkin_test.go
> +				}, "5s", "0.1s").ShouldNot(BeNil())
Weird formatting

2020-11-17 17:43 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tracing/plugin_test.go
> +			envoyTracingProvider, err := p.processEnvoyTracingProvider(pluginParams.Snapshot, hcmTracingSettings)
Yeah good call. I was attempting to make sure I was isolating the test to the tracing provider methods. But you're right, I'm better off just using the interface functions, and setting up the tests properly to ensure it reaches my desired methods

2020-11-17 17:46 UTC, sam-heilbron commented on test/e2e/zipkin_test.go
> +		startZipkinServer(":9411", nil)
http.DefaultServeMux is the default, if the handler is nil. However, you're right, passing in nil makes it harder to understand the intention. Passing in the default handler to make it clearer

2020-11-17 17:46 UTC, sam-heilbron commented on test/e2e/zipkin_test.go
> +			}
I wasn't! I'll add a similar passing test where I use the https gateway

2020-11-17 18:01 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/hcm/plugin_test.go
> +				ProviderConfig:        nil,
There are some checks here which do validate that the HcmPlugins get called properly. We wouldn't have any of the Tracing properties (RequestHeaderForTags, Verbose...etc) if the plugin wasn't called. My goal was to keep all Provider tests isolated to the tracing plugin tests. However, I can certainly make the ProviderConfig look a little more robust/realistic for this test

2020-11-17 18:32 UTC, EItanya commented on projects/gloo/pkg/plugins/hcm/plugin_test.go
> +				ProviderConfig:        nil,
Ok I see that now. However, this would be a perfect spot for a mock rather than the actual function. Since we don't also want to test the tracing plugin here.

2020-11-17 19:20 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/hcm/plugin_test.go
> +				ProviderConfig:        nil,
Agreed! I can look into that. FOr now, I just followed the existing pattern of using some defaults for the Tracing object

2020-11-18 19:14 UTC, EItanya approved these changes

2020-11-18 19:14 UTC, merged