Expose cluster header as a Route Action destination
solo-io/gloo pull request #3845
Opened 2020-11-10 20:52 UTC by saiskee

# Description

The `cluster_header` is the name of an HTTP header that contains the destination cluster name. This PR exposes this field to be used as a Route Action destination. 

# Context

User needed the `cluster_header` envoy route option to use a custom HTTP header to specify the destination cluster.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo [contribution guide](https://docs.solo.io/gloo/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-11-11 17:26 UTC, saiskee commented on projects/gloo/pkg/plugins/aws/plugin.go
> +		if spec == nil {
`MarkPerFilterConfig` will pass in `nil` for `spec *v1.Destination` if the destination type is a cluster header, so this handles that case.

2020-11-12 16:27 UTC, EItanya requested changes
Please add an e2e test verifying the cluster_header behavior

2020-11-12 16:27 UTC, EItanya commented on projects/gloo/pkg/plugins/consul/subsets.go
> +			ClusterHeader: dest.ClusterHeader,
```suggestion
			ClusterHeader: dest.GetClusterHeader(),
```

In general whenever accessing data from a proto msg always use the getters as they are nil safe

2020-11-12 16:27 UTC, EItanya commented on projects/gloo/pkg/plugins/pluginutils/headers.go
> +		return nil
Can you just leave a comment about why this one is nil unlike the rest

2020-11-12 16:27 UTC, EItanya commented on projects/gloo/pkg/translator/route_config.go
> +		return validateClusterHeader(dest.ClusterHeader)
```suggestion
		return validateClusterHeader(dest.GetClusterHeader())
```

2020-11-12 16:27 UTC, EItanya commented on projects/gloo/pkg/translator/route_config.go
> +			ClusterHeader: dest.ClusterHeader,
```suggestion
			ClusterHeader: dest.GetClusterHeader(),
```

2020-11-12 23:32 UTC, saiskee commented
/kick

2020-11-12 23:57 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +    bool sanitize_cluster_header = 14;
what is the default?

2020-11-13 00:00 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				{}},
what's this change?

2020-11-13 00:00 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				fmt.Printf("%+v\n", up.Metadata)
remove

2020-11-13 00:04 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +    bool sanitize_cluster_header = 14;
looks like it defaults to false. we should list that in the comment, as well as more clearly describe what sanitizing the header means and why a user might want to do this

2020-11-16 15:14 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				upstreamName := fmt.Sprintf("%s_%s", us.Metadata.Name, us.Metadata.Namespace)
we should be using https://github.com/solo-io/gloo/blob/b30c3e65bbef4a01a09443a23b139e2ebad966ef/projects/gloo/pkg/translator/utils.go#L18

2020-11-16 15:14 UTC, kdorosh requested changes
couple nits/questions

2020-11-16 15:15 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +    // Enterprise-only: If using the HTTP header specified by cluster_header to direct traffic to a cluster,
why is the plugin logic to honor the API here if this filter is enterprise only?

if someone were to provide this, appears gloo would configure envoy and break it

2020-11-16 15:16 UTC, kdorosh commented on test/e2e/gateway_test.go
> +			defaults.HttpsPort = 8081
let's keep it the original way, since the other tests use `defaults.HttpPort(s)`

2020-11-17 14:53 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				upstreamName := translator.UpstreamToClusterName(core.ResourceRef{Namespace: us.Metadata.Namespace, Name: us.Metadata.Name})
nit, just a bit shorter
```suggestion
				upstreamName := translator.UpstreamToClusterName(us.Metadata.Ref())
```

2020-11-17 15:00 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				}, 10*time.Second, 500*time.Millisecond).Should(Equal(200))
i think we need a stronger assertion here, to ensure this test would fail in the case of test pollution (a buggy test that doesn't clean up)

for example, we could:
- assert that the upstream service we hit is the right one
or
- assert before applying the virtual service that these requests would fail with 404 error code consistently

2020-11-17 15:16 UTC, kdorosh approved these changes

2020-11-17 15:41 UTC, merged