Fix syncers competing to write proxy status
solo-io/gloo pull request #3885
Opened 2020-11-17 23:48 UTC by Sodman

# Description

There is a bug which can occur when extensions try to write proxy statuses which compete with the status Gloo writes. Eg gloo may add a warning to a proxy for an invalid upstream, but rateLimit may find no problems in it's scope and over-write that status with an "accepted", which would hide the error from anyone looking at the proxy resource.

To fix this, this PR consolidates all of the extra instances of `WriteReports` into one, at the end of the `Sync`. Instead of passing a reporter around, we pass the reports map itself. The syncers are called serially, so we don't need to worry about locking the map.

# Context

Users ran into this bug originally when artificial resource constraints were placed on the control-plane pods, but we were able to reproduce it in a simpler setup. The simplest reproduction involves installing vanilla GlooEE and adding a route to an invalid upstream. Note that the proxy can settle as "accepted", even though we'd expect it to have a "Warning" status because of the invalid upstream.

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-11-19 21:53 UTC, Sodman commented
/kick zipkin test fail? https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=43db43d2-68fd-4b6d-9991-492967df0b7f

2020-11-23 20:28 UTC, Sodman commented
/kick aws key mismatch err - https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=c09b2f74-74f1-47d6-a354-ee70439af7a0&authuser=1

2020-11-25 15:03 UTC, kdorosh requested changes

2020-11-25 15:03 UTC, kdorosh commented on projects/gloo/pkg/syncer/envoy_translator_syncer.go
> +func (s *translatorSyncer) syncEnvoy(ctx context.Context, snap *v1.ApiSnapshot) (reporter.ResourceReports, error) {
this function still creates and returns its own `reports`:  https://github.com/solo-io/gloo/blob/d3df60f91f227e0c6c1c3d7423793b78e49160eb/projects/gloo/pkg/syncer/envoy_translator_syncer.go#L87

shouldn't this be sharing the one that's getting shared by the extensions? https://github.com/solo-io/gloo/blob/d3df60f91f227e0c6c1c3d7423793b78e49160eb/projects/gloo/pkg/syncer/setup_syncer.go#L501

2020-11-25 15:42 UTC, Sodman commented on changelog/v1.6.0-beta12/proxy-mulit-write-fix.yaml
> +    description: Fixed a bug where syncers were writing competing statuses to the proxy resource.
I'm good with making this one non-user facing, I'm thinking we keep the enterprise changelog user-facing though since this bug only affects enterprise.

2020-11-25 15:44 UTC, kdorosh commented on changelog/v1.6.0-beta12/proxy-mulit-write-fix.yaml
> +    description: Fixed a bug where syncers were writing competing statuses to the proxy resource.
agree 👍

2020-12-01 03:19 UTC, Sodman commented on projects/gloo/pkg/syncer/envoy_translator_syncer.go
> +func (s *translatorSyncer) syncEnvoy(ctx context.Context, snap *v1.ApiSnapshot) (reporter.ResourceReports, error) {
We discussed on slack, the `allReports.Merge()` call below will merge all of these Translator reports together, although the current merge function needs to be updated. The current merge just replaces any resources if they already exist in the report, needs to be updated to a deep merge. [This PR](https://github.com/solo-io/solo-kit/pull/393) in solo-kit has those changes.

2020-12-11 20:17 UTC, kdorosh reviewed
lgtm 👍

2020-12-14 17:05 UTC, kdorosh approved these changes

2020-12-14 17:05 UTC, merged