Aggregate changelogs
solo-io/gloo pull request #3907
Opened 2020-11-20 19:02 UTC by saiskee

# Description

This PR adds links to the appropriate gloo OSS version from the enterprise changelog docs.

# Context

When looking at enterprise changelogs, it is useful for customers and field engineers to have reference to which gloo OSS version the enterprise version relies on. This adds a link to the enterprise changelog docs next to each version.

# Screenshots
![image](https://user-images.githubusercontent.com/1731122/99839621-06ac0880-2b39-11eb-9c9f-7c838e8744a6.png)

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-11-24 16:09 UTC, kdorosh requested changes
it appears the open source chronological ordering is now broken

also the enterprise chronologic order is also broken, and doesn't have the aggregate changelog

2020-11-24 16:48 UTC, saiskee commented
/kick building again

2020-11-24 19:29 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +			return Version(*versionA).LessThan(Version(*versionB))
why not,
```suggestion
			return versionB.MustIsGreaterThan(*versionA)
```
and avoid re-declaring types for `Version` and `Versions` at the bottom of the file?

2020-11-24 19:30 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +			previousVersion, err = versionutils.ParseVersion(previousRelease.GetTagName())
missing error check here

2020-11-24 19:36 UTC, kdorosh reviewed
some of this parsing code is getting pretty complex, we should write some unit tests for it

2020-11-24 19:46 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +		// Get the Gloo OSS version that the Gloo enterprise version relied on
```suggestion
		// Get the Gloo Edge OSS version that the previous Gloo Edge Enterprise version relied on
```

2020-11-24 19:48 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +		var previousVersion *versionutils.Version
rename this to `lastGlooOSSDependency`? i want the name to indicate that the version is for open source gloo, the dependency for the last enterprise version we parsed

2020-11-24 19:54 UTC, saiskee commented on docs/cmd/generate_changelog_doc.go
> +			return Version(*versionA).LessThan(Version(*versionB))
The change is valid. However, I'm using the `sort` library to sort versions, and to sort on a type requires that the type have a `LessThan` function.

2020-11-24 20:04 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +	// Releaes notes are not nested under the headers in the AST, hence we must keep track of the currentHeader
typo, 
```suggestion
	// Release notes are not nested under the headers in the AST, hence we must keep track of the currentHeader
```

2020-11-24 20:11 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +	headersParsed := make(map[string]int)
we should make this an "enum" for values 1 and 2, so it's more readable. e.g. https://github.com/solo-io/solo-projects/blob/cf2e4e3a9c33b0189adb9a0cfae154e1980c1e77/projects/gloo/pkg/plugins/extauth/process_plugins_test.go#L32-L36

2020-11-24 20:13 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +							osRefLink := fmt.Sprintf("(From [OSS %s](/reference/changelog/open_source/#%s)) ", depVersion.String(), osReleaseId)
this logic is repeated a couple times, thinking we should pull into a shared function

2020-11-24 20:17 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +func parseEnterpriseNotes(enterpriseReleaseNotes string, openSourceReleases map[Version]string, depVersions []Version) (string, error) {
i had a tough time grokking this, would like to see some more comments. perhaps we talk about this function on a call after the other comments are resolved?

2020-11-24 20:20 UTC, kdorosh commented on docs/cmd/generate_changelog_doc.go
> +func parseEnterpriseNotes(enterpriseReleaseNotes string, openSourceReleases map[Version]string, depVersions []Version) (string, error) {
this is also a case where i think tests would have helped a lot. then i could step through the code easily too.

i think tests are going to be very important with this dense code as i am a bit afraid of brittle code in our changelog generation breaking future docs updates (particularly if the release notes get modified by hand)

2020-11-25 22:13 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +// Parses OSS Gloo Edge releases into correct format for printing
we also call this function in the enterprise case, can make the comment more generic

2020-11-25 22:13 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +// Parses OSS Gloo Edge releases into correct format for printing
in fact, we could rename the function to remove "Gloo" from it's name altogether

2020-11-25 22:17 UTC, kdorosh reviewed
in the enterprise case, appears we are missing the version headers (after v1.6) for the other minor releases

2020-11-25 22:28 UTC, kdorosh commented on docs/cmd/test/generate_changelog_doc_test.go
> +			//fmt.Printf("%+v\n", dependencies)
remove

2020-11-30 15:19 UTC, kdorosh requested changes
going to http://localhost:1313/reference/changelog/ and clicking the link to changelogs on the page (rather than the menu on left) redirects to invalid pages with `nil` in them, e.g. http://localhost:1313/reference/changelog/%3cnil%3e/reference/changelog/open_source/

2020-11-30 15:25 UTC, kdorosh requested changes
the previous version logic for importing open source changes to enterprise doesn't work in the case of minor version upgrades.

e.g. 1.6.0-beta1 enterprise doesn't have any changes from 1.6.0-beta1 open source. we should fix and add a test for this

2020-11-30 15:27 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +		previousDepVersion, _ := GetOSSDependencyForEnterpriseVersion(previousEnterprisePatch)
add comment to explain why we are swallowing errors here?

2020-11-30 15:33 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +						//any extra text e.g. "This release build has failed", only used for enterprise release notes
this comment belongs in the else block?

2020-11-30 15:34 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +	currentVersion, _ := ParseVersion(enterpriseReleasesSorted[index].GetTagName())
why are we swallowing errors?

2020-11-30 15:36 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +		tag, _ := ParseVersion(release.GetTagName())
why swallow errors?

2020-11-30 15:37 UTC, kdorosh commented on docs/cmd/changelogutils/changelog_utils.go
> +		return isGreaterThanOrEqualTo
nit, is no easier to read in two lines, let's make one-liner

2020-11-30 16:33 UTC, saiskee commented
> the previous version logic for importing open source changes to enterprise doesn't work in the case of minor version upgrades.
> 
> e.g. 1.6.0-beta1 enterprise doesn't have any changes from 1.6.0-beta1 open source. we should fix and add a test for this

https://github.com/solo-io/gloo/blob/d4fea10aee2053e0e8cd2fb7803c608a9bb5fcae/docs/content/reference/changelog/_index.md#L9
Haven't changed any of the logic here. This may just be an effect of how hugo is rendering the links to the child sections. The same issue happens in master on localhost, but the live docs don't have this issue.

2020-11-30 16:59 UTC, saiskee commented
> the previous version logic for importing open source changes to enterprise doesn't work in the case of minor version upgrades.
> 
> e.g. 1.6.0-beta1 enterprise doesn't have any changes from 1.6.0-beta1 open source. we should fix and add a test for this

The release build for 1.6.0-beta1 failed and therefore the script can't fetch the OSS dependency for this verison. However, I noticed that "This release build failed" text wasn't rendering, so I fixed the bug and also accounted for that in the tests.

2020-11-30 19:06 UTC, kdorosh approved these changes
nice!

2020-11-30 19:24 UTC, merged