[WIP] Support static tracing cluster
solo-io/gloo pull request #3955
Opened 2020-12-04 21:13 UTC by sam-heilbron

# Description

Add support for statically defined tracing collector clusters.

# Context

When configuring tracing, you can specify a cluster where traces are collected. If the collector is an upstream, tracing works as expected. However, if the cluster is statically defined in the envoy bootstrap, traces do not get collected.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-12-04 22:16 UTC, EItanya requested changes
Looks good, last thing through, can we add an e2e to test this as well

2020-12-06 22:11 UTC, sam-heilbron commented
/kick

2020-12-07 14:07 UTC, sam-heilbron commented on test/e2e/zipkin_test.go
> +			// verify that the gateway proxy is not reachable
If there's another way to verify this, I'm open to suggestions

2020-12-07 14:12 UTC, sam-heilbron commented on test/e2e/zipkin_test.go
> +			Eventually(apiHit, 5*time.Second).Should(Receive(&expectedZipkinApiHit))
Build bot is failing here

2020-12-07 15:20 UTC, EItanya commented on test/services/envoy.go
> +	ei.Role = "gloo-system~gateway-proxy"
Why this change?

2020-12-07 15:22 UTC, EItanya commented on test/services/envoy.go
> +	config = strings.ReplaceAll(config, "30400", strconv.Itoa(int(ei.Port)))
Can we use templating here instead?

2020-12-07 15:35 UTC, sam-heilbron commented on test/services/envoy.go
> +	config = strings.ReplaceAll(config, "30400", strconv.Itoa(int(ei.Port)))
Yeah that's what I would prefer. With the existing way that running envoy with a custom bootstrap config works, when I tried to add templating, I was getting errors with the downward api. I figured it would be more straightforward to use the existing mechanism to replace addr/ports, but given that it still isn't working, it's likely necessary/preferable to use templating

2020-12-07 15:37 UTC, sam-heilbron commented on test/services/envoy.go
> +	ei.Role = "gloo-system~gateway-proxy"
I noticed that all e2e tests that run envoy, using the `runWithRole` option, and set the role to this value. I was trying to better understand what change this would have (and then was surprised when there wasn't a noticeable effect).

2020-12-07 22:00 UTC, sam-heilbron commented on test/services/envoy.go
> +	eic := &envoyInstanceConfig{
A while back Yuval had built out this EnvoyInstanceConfig interface. The goal of my changes here was to move more of our internal logic to respect this interface. Instead of supporting lots of combinations of configuration (port, role, configFile...etc) we can support an interface that tests have to follow.

2020-12-08 00:30 UTC, EItanya commented on test/e2e/envoyconfigs/zipkin-static-cluster.yaml
> +      type: STATIC
Do we ned these for this test?

2020-12-08 00:30 UTC, EItanya commented on test/e2e/envoyconfigs/zipkin-static-cluster.yaml
> +        envoy_grpc: {cluster_name: metrics_cluster}
Do we need this for this test?

2020-12-08 02:01 UTC, sam-heilbron commented on test/e2e/envoyconfigs/zipkin-static-cluster.yaml
> +      type: STATIC
No good call, I'll remove

2020-12-08 02:01 UTC, sam-heilbron commented on test/e2e/envoyconfigs/zipkin-static-cluster.yaml
> +        envoy_grpc: {cluster_name: metrics_cluster}
Right again, I'll slim down this config

2020-12-08 15:36 UTC, EItanya approved these changes

2020-12-08 15:48 UTC, merged