feat: configuration of settings.extauth via helm values
solo-io/gloo pull request #3956
Opened 2020-12-07 13:47 UTC by eshepelyuk

# Description

Resolves #1892

# Context

Users needed this feature to .configure custom extauth server ref withoun need to post-render or kubectl patch steps.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2020-12-07 13:48 UTC, eshepelyuk commented
@mveitas plz check

2020-12-08 15:43 UTC, Sodman commented
/test

2020-12-08 16:22 UTC, Sodman commented
Hi @eshepelyuk , thanks for the PR!

For these helm changes, the primary tests you are going to care about is the `build-bot` check, which runs in our google cloudbuild environment (The logs for this test are publicly accessible, though).

To pass the `changelog-bot` check, you'll need to add a changelog file describing the changes and linking it to the GitHub Issue. The next release will be v1.6.0-beta18  (you can create that folder in the `changelog` directory if it doesn't exist). You can see an example changelog for another helm change here - https://github.com/solo-io/gloo/blob/master/changelog/v1.6.0-beta4/helm-value-for-stats-prefix-rewrite.yaml#L6

The `codegen check` appears to be failing on a docs generation issue which is unrelated to your PR, I am looking into it so don't worry about that one for now.

2020-12-08 16:39 UTC, eshepelyuk commented
@Sodman done, thanks for advices.

2020-12-08 16:48 UTC, eshepelyuk commented
@Sodman also I've added helm value documentation.

2020-12-08 19:05 UTC, Sodman requested changes
Looking good, just need you to change the path for the extauth values to be consistent with the value used in Gloo Edge Enterprise. Also need you to remove the reference doc, as this is something we'll address internally in a broader PR to consolidate enterprise and open source helm chart docs. See comments for more details. Thanks!

2020-12-08 19:05 UTC, Sodman commented on docs/content/reference/values.txt
> +for details.|
These docs are automatically generated based on the values in `values.go`. As extauth is a value defined in the enterprise helm chart, it should be getting generated as part of a different process which doesn't need to be address in this PR. The codegen check will fail because it counts this as a "diff" from what go generate will create.

So you can remove these changes for this PR, we'll address merging the docs from the Enterprise chart internally.

2020-12-09 11:04 UTC, eshepelyuk commented on docs/content/reference/values.txt
> +for details.|
Updated

2020-12-09 11:11 UTC, eshepelyuk commented on install/helm/gloo/templates/18-settings.yaml
> +{{- if .Values.settings.extauth }}
I have to say that, I absolutely don't understand this approach and how it's gonna work at all, because `settings.extensions` are not related to `settings.extauth` according to [API reference](https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/settings.proto.sk/#settings)

But anyway, I've update the PR according to your comment.

2020-12-09 23:33 UTC, Sodman commented
The code's looking good to me, just need a helm test to confirm everything's working as expected and to prevent any future regressions. You can check out this existing test (for [sds resources](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L295-L299)) as an example of another helm test which tests values that are added using a `toYaml` template - https://github.com/solo-io/gloo/blob/master/install/test/helm_test.go#L1804-L1821

2020-12-10 13:54 UTC, eshepelyuk commented
> The code's looking good to me, just need a helm test to confirm everything's working as expected and to prevent any future regressions. You can check out this existing test (for [sds resources](https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L295-L299)) as an example of another helm test which tests values that are added using a `toYaml` template - https://github.com/solo-io/gloo/blob/master/install/test/helm_test.go#L1804-L1821 We'll also need to update this branch with latest master once you're ready to merge.

Unfortunately, I'm currently unable to create any tests for helm chart. 
The reasons were described in [this slack thread](https://solo-io.slack.com/archives/C9L6VPAUW/p1607105509002000)

I have a feeling that efforts required to contribute this feature went far beyond my abilities, so I'd rather close this PR, leaving a place for more experienced volunteers to complete the issue #1892

Please feel free to use all this code according to your needs.
Sorry, for the time spent helping me, I do appreaciate these efforts.

2020-12-10 13:54 UTC, closed without merging

2020-12-10 13:58 UTC, mveitas commented
I will pick up on this after I get some things addressed at work that are taking priority

2020-12-11 15:58 UTC, Sodman commented
Thanks @eshepelyuk for getting us this far! It looks like the tests are all that's left so I'll try to see if I can pick it up and get it over the finish line!

2020-12-11 16:33 UTC, eshepelyuk commented
Thank you

2020-12-11 17:36 UTC, Sodman commented
Opened https://github.com/solo-io/gloo/pull/3978 for this