Csrf filter
solo-io/gloo pull request #3977
Opened 2020-12-11 14:53 UTC by npolshakova

# Description
Adds support for upstream envoy CSRF filter

# Context

CSRF rulesets are already available for modsec. This adds Envoy-based alternative to support upstream CSRF filters.

https://github.com/solo-io/gloo/issues/3898

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2020-12-11 15:17 UTC, EItanya requested changes

2020-12-11 15:17 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +type Plugin struct {
can we make this struct private?

2020-12-11 15:17 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +var _ plugins.HttpFilterPlugin = new(Plugin)
Can we also verify the other plugins:

- `WeightedDestination`
- `VirtualHost`
- `Route`

2020-12-11 15:17 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +	shadowEnabled := csrfPolicy.GetShadowEnabled()
Why create these vars if you're just checking for nils, that can be done inline in the `if`

2020-12-11 15:17 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +	return &envoycsrf.CsrfPolicy{
Can we also return an error from the function which calls the `Validate` function on the csrf config. The envoy protos have generated `Validate` functions which we can take advantage of to make sure our protos won't get rejected by envoy.

2020-12-11 15:17 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +package csrf_test
We should also add an e2e test

2020-12-11 18:44 UTC, npolshakova commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +type Plugin struct {
It looks like most of the other plugins (buffer, wasm, etc) have the struct as public, but I think it's fine making this one private.

2020-12-11 19:12 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +type Plugin struct {
In general they should be private. Components like this are better tested by their public functions. The public ones are mostly remnants.

2020-12-11 22:10 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
> +option (gogoproto.equal_all) = true;
@EItanya will this conflict with your attempts to rip out gogo?

2020-12-11 22:10 UTC, kdorosh commented on test/e2e/csrf_test.go
> +	//envoytype "github.com/envoyproxy/go-control-plane/envoy/type/v3"
remove?

2020-12-11 22:23 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +					ShadowEnabled:     nil,
No need to explicitly include nils in struct definitions. It is clear by it's omission that it will use the default value.

2020-12-11 22:23 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +		envoyFilter.DefaultValue.XXX_sizecache = 0
As mentioned above, these fields should not be accessed, why did we need to do it in this case?

2020-12-11 22:24 UTC, EItanya commented on projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
> +option (gogoproto.equal_all) = true;
Yea, but if it goes in beforehand I can handle it

2020-12-11 22:37 UTC, saiskee commented on test/e2e/csrf_test.go
> +	FContext("with envoy", func() {
Unfocus the context so that all the tests run

2020-12-11 22:40 UTC, kdorosh commented on test/e2e/csrf_test.go
> +	FContext("with envoy", func() {
fortunately this will never pass ci because we run ginkgo with the `-failOnPending` flag: https://github.com/solo-io/gloo/blob/32160b73c509a84eef47cfe87164e58ccc698160/cloudbuild.yaml#L94

2020-12-11 22:45 UTC, saiskee commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +		err = ptypes.UnmarshalAny(out.GetTypedPerFilterConfig()["envoy.filters.http.csrf"], &cfg)
Can you make `envoy.filters.http.csrf` a `const` in the plugin.go file and use that?

2020-12-11 22:48 UTC, kdorosh commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +		err = ptypes.UnmarshalAny(out.GetTypedPerFilterConfig()["envoy.filters.http.csrf"], &cfg)
even better than that, use the const that envoy itself exposes? e.g. https://github.com/solo-io/gloo/blob/30131e794c8b6de401dccb4fd67175ecab8a798f/projects/gloo/pkg/plugins/buffer/plugin_test.go#L35

the sanitize filter is our filter not upstream envoy's thus we don't use `wellknown`

2020-12-14 14:33 UTC, npolshakova commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +	if csrfPolicy.GetAdditionalOrigins() != nil || csrfPolicy.GetFilterEnabled() != nil || csrfPolicy.GetShadowEnabled() != nil {
I thought `filter_enabled` needed to be off for `shadow_enabled` to be used? Otherwise `shadow_enabled` is ignored.

2020-12-14 14:52 UTC, npolshakova commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +			XXX_sizecache: 8,
`XXX_sizecache: 8` gets added to the envoyAdditionalOrigins in the HttpFilters tests so they're failing because the sizecache aren't equal

2020-12-14 15:18 UTC, npolshakova commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +		err = ptypes.UnmarshalAny(out.GetTypedPerFilterConfig()["envoy.filters.http.csrf"], &cfg)
It didn't look like wellknown from the go-control-plane had the csrf filter name, but it looks like envoy has it in well_known_names (https://github.com/envoyproxy/envoy/blob/master/source/extensions/filters/http/well_known_names.h).

2020-12-14 15:21 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
> +option (gogoproto.equal_all) = true;
Now that gogo has been ripped out, this proto should be updated

2020-12-14 17:23 UTC, EItanya commented on projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
> +package envoy.extensions.filters.http.csrf.v3;
Please add the solo.io. prefix to this package name

2020-12-14 19:19 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin_test.go
> +		err = ptypes.UnmarshalAny(out.GetTypedPerFilterConfig()["envoy.filters.http.csrf"], &cfg)
unfortunately this is an example of a filter name which isn't in the go-control-plane code. They decided to stop trying to keep up with all of the names, since afaik they are not technically necessary anymore. However, for the time being, having a const in the file should be fine.

2020-12-16 19:06 UTC, EItanya commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +	}
Didn't we figure out that envoy doesn't like this?

2020-12-17 15:42 UTC, saiskee commented on projects/gloo/api/external/envoy/extensions/filters/http/csrf/v3/csrf.proto
> +//  option (udpa.annotations.versioning).previous_message_type =
Do we still need this? If so can we add a comment as to what this commented out option means

2020-12-18 00:09 UTC, sam-heilbron reviewed
This is looking good overall! 

I think https://github.com/solo-io/gloo/issues/4000 helped add some more challenges around writing e2e tests for this plugin.

I pushed up some proposed changes to a branch that we can talk about tomorrow: https://github.com/solo-io/gloo/tree/csrf-filter-sam

There are 2 notable changes:
(1) I simplified some of the plugin logic to remove the `present` property and simplify the logic. The CSRF filter has some built in relationship between the shadow_enabled and filter_enabled (shadow happens when filter is off). But I think we can let envoy handle this, and keep our plugin as a simple adapter between the gloo api and envoy api.

(2) I found some of the classes (I know you were just using the cors plugin test, so it's not on you) in the e2e tests to add more confusion and indirection. I tried to simplify the test and instead of checking stats, just check that a request is accepted or rejected.

Notably, we need to test unsafe http methods (ones that change the server state) since these are the only methods that the filter will operate on. 

All in all, good stuff though! We can chat tomorrow in person

2020-12-18 20:03 UTC, EItanya commented
> (1) I simplified some of the plugin logic to remove the `present` property and simplify the logic (https://github.com/solo-io/gloo/blob/csrf-filter-sam/projects/gloo/pkg/plugins/csrf/plugin.go). The CSRF filter has some built in relationship between the shadow_enabled and filter_enabled (shadow happens when filter is off). But I think we can let envoy handle this, and keep our plugin as a simple adapter between the gloo api and envoy api.

I agree with this in theory. However, since the relationship between gloo and envoy filters in this case is asynchronous, we want to do as much up front checking as possible. The errors from the plugins will wind up on the resource status whereas envoy rejections will not.

2020-12-18 22:21 UTC, kdorosh commented on test/kube2e/csrf/csrf_suite_test.go
> +package csrf
do we really need a kube e2e test if we already wrote local e2e? this feels like overkill to me

2020-12-18 22:29 UTC, sam-heilbron commented
> I agree with this in theory. However, since the relationship between gloo and envoy filters in this case is asynchronous, we want to do as much up front checking as possible. The errors from the plugins will wind up on the resource status whereas envoy rejections will not.

Yeah im good with that. I was concerned that instead of returning an error, we were choosing to copy a piece of the configuration to envoy and proceeding. If there's any up front config validation we can do in the plugin, Im game.

2020-12-18 23:13 UTC, npolshakova commented on projects/gloo/pkg/plugins/csrf/plugin.go
> +	}
Yep, you need to have a non null EnabledFilter value :(

2020-12-18 23:14 UTC, npolshakova commented on test/kube2e/csrf/csrf_suite_test.go
> +package csrf
Yep, I think the local e2e is extensive enough. We don't need kube e2e test anymore

2020-12-21 14:47 UTC, npolshakova commented
/kick

2020-12-21 23:21 UTC, EItanya commented on changelog/v1.6.0-beta23/support-csrf-filter.yaml
> +      and on weighted destinations. See [envoy csrf](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/csrf/v2/csrf.proto)
Link to V3 instead

2020-12-21 23:21 UTC, EItanya commented on test/e2e/csrf_test.go
> +		Eventually(func() error {
When using `gomaga` functions like this in multiple tests, it's important to use the `WithOffset` variant of the functions, so that the breaking test is properly listed. For instance `EventuallyWithOffset(1,...`

2020-12-21 23:21 UTC, EItanya commented on test/e2e/csrf_test.go
> +	Context("defined on listener with shadow mode config", func() {
Can this and the above be in a combine `Context("listener")`

2020-12-22 14:43 UTC, npolshakova commented on test/e2e/csrf_test.go
> +	Context("defined on listener with shadow mode config", func() {
It could, but then the test would have to update the csrf policy. Shadow mode needs to be set in the csrf policy and the filter enabled has to be cleared for shadow mode to get applied.

2020-12-22 15:34 UTC, EItanya approved these changes

2020-12-22 15:34 UTC, merged