Path case sensitivity opt
solo-io/gloo pull request #3982
Opened 2020-12-11 21:34 UTC by asayah

# Description

Adding path case sensitivity option. 

# Context

Users need to enforce/disable case sensitivity when adding a path matcher 
# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2020-12-11 22:29 UTC, kdorosh requested changes
did we think about how the semantics work with route delegation? i think the better UX (thoughts?) is better if we error in the following case:
- route tables where the parent route table/vs doesn't have the same value for `case_sensitive` as its children (should be an error case?)

to implement this we need a new check in route table/vs -> route conversion that ensures we properly error on route tables using this new matcher option improperly.

where this additional check would go: https://github.com/solo-io/gloo/blob/1717f9f01269abe319f1b07b7469b4156ad8bd37/projects/gateway/pkg/translator/converter.go#L444

2020-12-12 01:34 UTC, asayah commented
@kdorosh thanks, I added a quick validation

2020-12-12 03:19 UTC, kdorosh commented
/kick test flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=07aaedc5-33c7-4a82-a3e7-c5071f6e3484

2020-12-14 20:40 UTC, kdorosh approved these changes

2020-12-14 20:40 UTC, merged