Staged JWT Api
solo-io/gloo pull request #4034
Opened 2020-12-29 19:18 UTC by saiskee

# Description

Adds API for staged JWT config for before and extauth stages.

# Context

This is part of a longer task to allow JWT to be used with the boolean expression api in the extauth service to allow JWT to be used as an external authentication method in conjunction with other methods.

2020-12-29 19:53 UTC, saiskee commented on projects/gloo/api/v1/options.proto
>      // headers to make routing decisions or combine with RBAC for fine-grained access control.
Wondering if I should include a comment about how this, by default, configures JWT only after extauth. Don't want to confuse readers though.

2020-12-29 20:12 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +        // JWT configuration has stages "BeforExtAuth" and "AfterExtAuth". BeforeExtAuth JWT
typo, "BeforExtAuth"

2020-12-29 20:13 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +        jwt.options.gloo.solo.io.JwtStagedVhostExtension jwt_staged_vhost_config = 19;
slightly prefer the name `jwt_staged` to `jwt_staged_vhost_config`, since it's implicit that this config lives on the virtual host since it lives on `VirtualHostOptions`

2020-12-29 20:14 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +        jwt.options.gloo.solo.io.JwtStagedRouteExtension jwt_staged_route_config = 25;
same typo and naming nits as above

2021-01-11 23:24 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +        // JWT configuration has stages "BeforeExtAuth" and "AfterExtAuth". BeforeExtAuth JWT
perhaps mention that after auth is useful for verifying jwts obtained during extauth (e.g., oauth / oidc)

2021-01-11 23:24 UTC, kdorosh commented on projects/gloo/api/v1/options.proto
> +        // headers to make routing decisions or combine with RBAC for fine-grained access control.
explicitly mention that this is deprecated in favor of staged jwt?

2021-01-11 23:24 UTC, kdorosh commented on projects/gloo/pkg/syncer/envoy_translator_syncer.go
> +		logger.Debugf("Full snapshot for proxy %v: %+v", proxy.Metadata.Name, xdsSnapshot)
👏

2021-01-12 17:20 UTC, kdorosh approved these changes

2021-01-12 17:23 UTC, kdorosh requested changes
needs changes to handle disable jwt on routes

2021-01-12 23:10 UTC, saiskee commented
/kick

2021-01-12 23:24 UTC, kdorosh approved these changes
Those changes are internal not in the API

2021-01-12 23:47 UTC, merged