Add enterprise-only feature warning
solo-io/gloo pull request #4052
Opened 2021-01-04 15:53 UTC by npolshakova

# Description

Adds warnings for enterprise-only features

# Context

https://github.com/solo-io/gloo/issues/4020

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-01-08 21:40 UTC, Sodman reviewed
Code looks good overall 👍 

Just a few small nits about messaging and error outputs!

2021-01-08 21:40 UTC, Sodman commented on projects/gloo/pkg/plugins/ratelimit/plugin.go
> +	ErrEnterpriseOnly = "Could not apply ratelimit plugin - this is an Enterprise feature"
Same comment as above for extauth - might want to clarify what exactly is enterprise here, as there are parts of the plugin which are _not_ exclusive to enterprise. Looking at our [rate-limit docs](https://docs.solo.io/gloo-edge/latest/guides/security/rate_limiting/) I'm thinking something like 

`The Gloo Advanced Rate limit API is an enterprise-only feature, please upgrade or use the Envoy rate-limit API instead`.

I'm still not sure if that's clear enough, thoughts? I don't think we've set a precedent of putting a URL into our errors anywhere else, but it's hard to succinctly describe the different APIs here in a short error message...

2021-01-08 21:40 UTC, Sodman commented on test/e2e/enterprise_warnings_test.go
> +var _ = FDescribe("warning when using enterprise features", func() {
Unfocus
```suggestion
var _ = Describe("warning when using enterprise features", func() {
```

2021-01-08 21:44 UTC, Sodman requested changes
Just came back from the GlooEE review - We'll need to change the extauth & ratelimit plugins.

The EE ones currently run in parallel to the OS ones, so we don't want to do a full replace for those two. I suggest instead we create two new OS plugins to handle the EE-only config & warnings, and then replace _those_ with the EE ones on upgrade instead. Happy to hop on a call to discuss!

2021-01-11 20:20 UTC, npolshakova commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +package setup
Needed to move setup_syncer.go into new package. setup_syncer imports extauthExt and ratelimitExt, but extauthExt and ratelimitExt also import definitions from setup_syncer

2021-01-12 15:55 UTC, Sodman reviewed
Looks good over all, couple minor nits. See also comments on the GlooEE PR.

2021-01-12 15:55 UTC, Sodman commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +	return fmt.Sprintf("The Gloo Advanced Rate limit API '%s' resource is an enterprise-only feature, please upgrade or use the Envoy rate-limit API instead", feature)
This wording works for `RateLimitConfig`s which are a k8s resource, but I think everything else is more accurately described as a "field". I'm worried that "setAction resource" might be confusing to people, thoughts?

2021-01-12 16:01 UTC, kdorosh commented on projects/gloo/pkg/plugins/proxylatency/plugin.go
> +	FilterStage = plugins.AfterStage(plugins.RouteStage)
are these filter stage variables used anywhere?

2021-01-12 16:03 UTC, kdorosh commented on projects/gloo/pkg/plugins/proxylatency/plugin_test.go
> +package proxylatency
ideally our tests go in a package called `<packagename>_test`, which ensures that we test the behavior/exposed API rather than internals to the package

2021-01-12 16:03 UTC, kdorosh commented on projects/gloo/pkg/plugins/proxylatency/plugin_test.go
> +		Expect(err.Error()).To(Equal(errEnterpriseOnly))
this error will need to be exported once we change the package name

2021-01-12 16:05 UTC, kdorosh commented on projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go
> +	}
this doesn't mean anything in this shell of extauth, can remove

2021-01-12 16:06 UTC, kdorosh commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +)
likewise we can remove

2021-01-12 16:06 UTC, kdorosh commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +}
can remove

2021-01-12 16:08 UTC, kdorosh commented on projects/gloo/pkg/syncer/setup/setup_syncer_test.go
> +package setup
why this change? our tests should end in `_test`

2021-01-12 16:09 UTC, kdorosh commented on projects/gloo/pkg/syncer/extauth/extauth_translator_syncer.go
> +
we should add compile time assertions for `UpgradeableTranslatorSyncerExtension`

2021-01-12 16:09 UTC, kdorosh commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +
we should add compile time assertions for `UpgradeableTranslatorSyncerExtension`

2021-01-12 16:41 UTC, npolshakova commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer_test.go
> +	// Dummy method
Good point! It turns out the translator_syncer_test defines a MockXdsCache, so I might just refactor the ratelimit and extauth tests to use that instead.

2021-01-12 16:44 UTC, npolshakova commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +	return fmt.Sprintf("The Gloo Advanced Rate limit API '%s' resource is an enterprise-only feature, please upgrade or use the Envoy rate-limit API instead", feature)
How about "The Gloo Advanced Rate limit API feature 'RateLimitConfig/setActions/ratelimitBasic' is enterprise-only, please upgrade or use the Envoy rate-limit API instead" ?

2021-01-12 16:45 UTC, npolshakova commented on projects/gloo/pkg/plugins/proxylatency/plugin.go
> +	FilterStage = plugins.AfterStage(plugins.RouteStage)
No, not anymore. I'll remove it, nice catch!

2021-01-12 16:54 UTC, Sodman commented on projects/gloo/pkg/syncer/ratelimit/ratelimit_translator_syncer.go
> +	return fmt.Sprintf("The Gloo Advanced Rate limit API '%s' resource is an enterprise-only feature, please upgrade or use the Envoy rate-limit API instead", feature)
Sounds good to me!

2021-01-12 17:07 UTC, npolshakova commented on projects/gloo/pkg/syncer/setup/setup_syncer_test.go
> +package setup
It must have gotten refactored incorrectly when I moved into the package. It should be `setup_test`

2021-01-12 19:13 UTC, kdorosh commented on projects/gloo/pkg/plugins/dlp/plugin.go
> +)
upgradeable plugin assertion?

2021-01-12 19:14 UTC, kdorosh commented on projects/gloo/pkg/plugins/failover/plugin.go
> +)
upgradeable plugin?

2021-01-12 19:15 UTC, kdorosh commented on projects/gloo/pkg/plugins/http_path/plugin.go
> +)
upgradeable

2021-01-12 19:15 UTC, kdorosh commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +)
going to stop marking upgradeable here

2021-01-12 19:16 UTC, kdorosh commented on projects/gloo/pkg/plugins/rbac/plugin.go
> +	filterStage                           = plugins.DuringStage(plugins.AuthZStage)
remove?

2021-01-12 19:16 UTC, kdorosh commented on projects/gloo/pkg/plugins/sanitize_cluster_header/plugin.go
> +	sanitizeFilterStage = plugins.BeforeStage(plugins.AuthNStage)
remove?

2021-01-12 19:17 UTC, kdorosh commented on projects/gloo/pkg/plugins/waf/plugin.go
> +	filterStage = plugins.DuringStage(plugins.WafStage)
remove?

2021-01-13 16:35 UTC, Sodman reviewed
LGTM, all my comments are addressed, awesome work! I'll leave the final approval for @kdorosh

2021-01-13 18:54 UTC, saiskee reviewed
This work is great and much needed! Just found a nit with the jwt plugin.

2021-01-13 18:54 UTC, saiskee commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +	if in.GetOptions().GetJwt() != nil {
To support the new api, change this to `in.GetOptions().GetJwtConfig() != nil`

2021-01-13 18:54 UTC, saiskee commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +
```suggestion
func (p *plugin) ProcessRoute(plugins.RouteParams, in*v1.Route, out *envoy_config_route.Route) error {
  if in.GetOptions().GetJwtConfig() != nil {
    return eris.New(ErrEnterpriseOnly)
  }
  return nil
}
```

2021-01-13 18:56 UTC, saiskee commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +
Actually, I'm not sure if this one is needed. Will `ProcessVirtualHost` failing automatically block `ProcessRoute` from running?

2021-01-13 20:18 UTC, npolshakova commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +
Wouldn't the configuration be set on the vhost or the route? So checking `in.GetOptions().GetJwtConfig()` on the Route is different from the virtual host?

2021-01-13 20:18 UTC, npolshakova commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +	if in.GetOptions().GetJwt() != nil {
Nice catch! I think I'll need to change the plugin test to reflect that too

2021-01-13 20:19 UTC, npolshakova commented on projects/gloo/pkg/plugins/jwt/plugin.go
> +
Oh I see what you mean- yes, I'll add a check for the route!

2021-01-13 22:30 UTC, npolshakova commented
/kick

2021-01-14 22:56 UTC, kdorosh approved these changes

2021-01-14 22:57 UTC, merged