Re-enable REST EDS
solo-io/gloo pull request #4155
Opened 2021-01-19 20:14 UTC by ashleywang1

# Description

Re-enable REST EDS

This fixes some behavior where envoy sometimes does not list clusters with their proper endpoints.

# Context

I ran into this with the gloo-fed e2e test due to failover modifying the upstream.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-01-19 20:23 UTC, kdorosh requested changes
let's also change it here for the non-k8s deployments defaults: https://github.com/solo-io/gloo/blob/d313a43c70b33cdaecfc803a8dbf09ee8ddef7de/projects/gloo/pkg/xds/utils.go#L19

2021-01-20 14:45 UTC, npolshakova commented on docs/content/reference/values.txt
> +|settings.enableRestEds|bool|true|Whether or not to use rest xds for all EDS by default. Set to true by default in versions > v1.6.0.|
Was this just a typo in the docs? That it was set to true by default in versions > v1.6?

2021-01-20 14:49 UTC, kdorosh commented on docs/content/reference/values.txt
> +|settings.enableRestEds|bool|true|Whether or not to use rest xds for all EDS by default. Set to true by default in versions > v1.6.0.|
These are generated docs, generated from our helm chart. since we changed the default there, the docs got updated as well

2021-01-20 14:50 UTC, kdorosh commented on docs/content/reference/values.txt
> +|settings.enableRestEds|bool|true|Whether or not to use rest xds for all EDS by default. Set to true by default in versions > v1.6.0.|
this file is used for https://docs.solo.io/gloo-edge/latest/reference/helm_chart_values/

2021-01-20 21:25 UTC, kdorosh requested changes
still need to fix https://github.com/solo-io/gloo/pull/4155#pullrequestreview-571628990

2021-01-20 21:48 UTC, ashleywang1 commented
> still need to fix [#4155 (review)](https://github.com/solo-io/gloo/pull/4155#pullrequestreview-571628990)

I'm not too clear on what should be changed. `settings.GetGloo().GetEnableRestEds().GetValue()` should now return 'true' now that the helm defaults have been updated.

2021-01-20 22:08 UTC, kdorosh submitted a review, later dismissed

2021-01-21 04:04 UTC, ashleywang1 commented
/kick

2021-01-21 20:57 UTC, kdorosh approved these changes

2021-01-21 21:31 UTC, merged