Tls inspector filter
solo-io/gloo pull request #4188
Opened 2021-01-26 14:39 UTC by npolshakova

# Description

WIP

# Context

https://github.com/solo-io/gloo/issues/4044

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-01-26 15:49 UTC, yuval-k commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +	if in.GetOptions().TlsInspector != nil {
i think we should abstract the user from this, and not add additional API.
i.e. add this automatically when ssl is enabled.

requiring configuration to add this listener filter will break backwards compatability

2021-01-26 17:18 UTC, kdorosh commented on changelog/v1.7.0-beta11/tls_inspector_filter.yaml
> +  - type: NEW_FEATURE
if we do this right, this will be a `NON_USER_FACING` change (no change in functionality, no new features or toggles)

2021-01-27 14:36 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +	// Only focused on Http listeners, tcp plugin will handle tcp case
Is this the only case we care about when injecting the TLS Inspector for tcp listeners? https://github.com/solo-io/gloo/blob/01d04751f72c168e304977c4f67fdbcbf30232a9/projects/gloo/pkg/plugins/tcp/plugin.go#L71

2021-01-27 15:58 UTC, saiskee commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +	pluginStage          = plugins.DuringStage(plugins.RouteStage)
Why `DuringStage` rather than `AfterStage`? I'm not too familiar with how the actual relative stages work, but was this on purpose?

2021-01-27 16:02 UTC, saiskee commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +		return nil
return `err` here, not `nil`.

2021-01-27 16:06 UTC, saiskee reviewed
Found a small change and am curious about the `DuringStage` vs `AfterStage`.

2021-01-27 17:26 UTC, kdorosh commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +		}
this logic too closely mirrors the logic in tcp plugin. I think we should either:
- move the TLS inspector logic from tcp plugin to here (my favorite)
- make the case statement here empty and handle in TCP plugin

2021-01-27 17:55 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +		}
Yeah the gateway regression test that was failing this morning was because the tls inspector wasn't getting injected correctly for the tcp listener. I think removing the tcp inspector logic from the tcp plugin would be best. Would the tcp plugin even need to be a ListenerPlugin then though?

2021-01-27 18:25 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +	pluginStage          = plugins.DuringStage(plugins.RouteStage)
Actually I think this is wrong. It shouldn't be in the routing stage. Some of the http filters like gzip/buffer need to be called after the routing is determined, but the tls inspector is a listener filter so this should be removed.

2021-01-27 21:15 UTC, kdorosh commented on projects/gloo/pkg/plugins/tcp/plugin_test.go
> -		})
did this test get dropped when it got moved?

2021-01-27 21:28 UTC, kdorosh reviewed
last we spoke you were planning on adding an e2e test but otherwise lgtm

2021-01-28 15:09 UTC, npolshakova commented on projects/gloo/pkg/plugins/tcp/plugin_test.go
> -		})
Yep, this should be added back- now in the tls inspector plugin tests.

2021-01-28 18:56 UTC, npolshakova commented on projects/gloo/pkg/plugins/tcp/plugin_test.go
> -		})
Now that we're not injecting the TLS Inspector at runtime, we do want the plugin to prepend the TLS Inspector whenever `SslConfig` is set. The tcp plugin used to be only responsible for prepending the TLS inspector when there is a forward SNI cluster, and no SNI matches. This test was supposed to check that the TLS inspector wasn't added twice.

2021-01-28 19:20 UTC, npolshakova commented on install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
>            envoy.reloadable_features.enable_deprecated_v2_api: true
v2 refs be removed in separate PR: https://github.com/solo-io/gloo/pull/4193

2021-01-28 20:42 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				cancel()
cancel should always be last in all of our `AfterEach`s.

cancelling it early ends the `ctx`, which if used after cancel can lead to failures/test flakes

2021-01-28 20:44 UTC, kdorosh commented on test/e2e/gateway_test.go
> +				createdSecret, err := testClients.SecretClient.Write(secret, clients.WriteOpts{})
```suggestion
				createdSecret, err := testClients.SecretClient.Write(secret, clients.WriteOpts{ctx: ctx})
```

2021-01-28 21:03 UTC, npolshakova commented on test/e2e/gateway_test.go
> +				cancel()
Okay that makes sense. I'll refactor the ctx to the top level of the test and move the afterEach there.

2021-01-29 00:15 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +			out.ListenerFilters = append([]*envoy_config_listener_v3.ListenerFilter{tlsInspector}, out.ListenerFilters...)
```suggestion
			out.ListenerFilters = append(out.ListenerFilters, tlsInspector)
```

2021-01-29 00:15 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +				out.ListenerFilters...,
```suggestion
			out.ListenerFilters = append(out.ListenerFilters, &envoy_config_listener_v3.ListenerFilter{Name: wellknown.TlsInspector},
```

2021-01-29 00:15 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +			out.ListenerFilters = append([]*envoy_config_listener_v3.ListenerFilter{tlsInspector}, out.ListenerFilters...)
```suggestion
			out.ListenerFilters = append(out.ListenerFilters, tlsInspector)
```

2021-01-29 00:15 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +				[]*envoy_config_listener_v3.ListenerFilter{{Name: wellknown.TlsInspector}},
Why do we only apply the ListenerFilter with a name, when we use an empty config for the others. Is there a difference in behavior?

2021-01-29 12:53 UTC, EItanya commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +			out.ListenerFilters = append([]*envoy_config_listener_v3.ListenerFilter{tlsInspector}, out.ListenerFilters...)
I think the prepend makes sense here, in general this filter should run before most others

2021-01-29 13:12 UTC, EItanya requested changes

2021-01-29 13:12 UTC, EItanya commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +				[]*envoy_config_listener_v3.ListenerFilter{{Name: wellknown.TlsInspector}},
Agreed, this is most likely copy pasted from the TCP plugin. Either way should work fine, but we should be consistent

2021-01-29 13:12 UTC, EItanya commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +	case *v1.Listener_TcpListener:
I think we can clean up this block a bit, I tried to be smart when I originally wrote it to make sure we didn't have 2 TlsInspector filters, but now since we control it we can be a bit more heavy handed. For instance we can do something like this:
```
		tcpListener := in.GetTcpListener()
		for _, host := range tcpListener.GetTcpHosts() {
			if host.GetSslConfig() != nil || host.GetDestination().GetForwardSniClusterName() != nil {
				out.ListenerFilters = append([]*envoy_config_listener_v3.ListenerFilter{tlsInspector}, out.ListenerFilters...)
				break
			}
		}

```

2021-01-29 13:12 UTC, EItanya commented on test/e2e/gateway_test.go
> +		Context("ssl", func() {
Also, why are we creating an entirely new `Describe` here. All of this setup already happens in the above `memory` `Describe`, we should be able to piggy back off of all that.

2021-01-29 13:12 UTC, EItanya commented on test/e2e/gateway_test.go
> +			It("should work with ssl", func() {
I understand what this test is doing but I don't think it is really an `e2e` test. Can we instead test some traffic and ensure that it works. In my opinion testing real use cases of a particular feature is more useful, and regression proof.

2021-01-29 14:17 UTC, npolshakova commented on test/e2e/gateway_test.go
> +					adminUrl := fmt.Sprintf("http://%s:%d/config_dump",
That's a good idea!

2021-01-29 14:19 UTC, npolshakova commented on test/e2e/gateway_test.go
> +				// Check that the new instance of envoy is running
I haven't noticed to fail after the startup checks, but the other ssl test had same check. I'll test it to see if I run to any issues and if works, it makes sense to remove it here and in the http gateway version.

2021-01-29 14:23 UTC, npolshakova commented on test/e2e/gateway_test.go
> +		Context("ssl", func() {
I can clean it up a little for the runOptions and testClient stuff. Creating the tcp gateway needs to be in it's own layer because the memory Describe is using `WriteDefaultGateways`.

2021-01-29 14:25 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +			out.ListenerFilters = append([]*envoy_config_listener_v3.ListenerFilter{tlsInspector}, out.ListenerFilters...)
I don't think we're explicitly adding any listener filter other than the tls inspector, but later on if we have more listener filters it should be prepended.

2021-01-29 14:26 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +				out.ListenerFilters...,
I think we want to prepend the tls listener filter to the other listener filter list so it gets run before. Idk if there's another way to specify it getting run before the other filters in the list other than prepending it?

2021-01-29 14:28 UTC, npolshakova commented on projects/gloo/pkg/plugins/tls_inspector/plugin.go
> +				[]*envoy_config_listener_v3.ListenerFilter{{Name: wellknown.TlsInspector}},
Yep, I just copied the SNI forward cluster and no SNI matchers from the tcp plugin. I'll make it consistent with the other case when we're prepending the listener filter.

2021-01-29 15:05 UTC, npolshakova commented on test/e2e/gateway_test.go
> +				// Wait till envoy is completely cleaned up
When I was debugging the test, this was one thing I had to add to get it working. But I should be able to remove it- it seems to work fine when not in debug mode.

2021-01-29 15:09 UTC, npolshakova commented on test/e2e/gateway_test.go
> +				adminUrl := fmt.Sprintf("http://%s:%d/config_dump",
Yeah that's a good idea. I realized some of other tests that are checking the envoy test/config aren't wrapped in an eventually but they probably should be...

2021-02-01 19:15 UTC, sam-heilbron requested changes

2021-02-01 19:15 UTC, sam-heilbron commented on test/services/envoy.go
> +	Eventually(func() error {
nit: I think we can/should just return the result of the GET request to the adminUrl. Any tests that consume this, can wrap the call in an eventually

2021-02-01 19:15 UTC, sam-heilbron commented on test/e2e/gateway_test.go
> +		Context("tcp gateway", func() {
When I set the tls_inspector plugin to just return nil (and not modify the listener), all of these tests still pass for me. I'm not familiar with the plugin enough to figure out what the e2e setup should be / how to verify the effectiveness.

It also makes me nervous that the regex test against the admin endpoint (to verify the tls_inspector filter) is actually doing what we want/expect

2021-02-01 21:17 UTC, npolshakova commented on test/e2e/gateway_test.go
> +		Context("tcp gateway", func() {
I think this may be because tls_inspector automatic injection is only removed in 1.17 so it should still be getting included if you are running an earlier version of envoy. (https://www.envoyproxy.io/docs/envoy/v1.17.0/version_history/current)

2021-02-01 21:50 UTC, npolshakova commented
/kick

2021-02-02 00:13 UTC, sam-heilbron commented on test/e2e/gateway_test.go
> +		Context("tcp gateway", func() {
Gloo's envoy image (https://github.com/solo-io/gloo/blob/master/Makefile#L24) is based off of 1.17 and I ran the tests locally using that build.

2021-02-02 20:08 UTC, npolshakova commented on test/e2e/gateway_test.go
> +		Context("tcp gateway", func() {
This was a test bug. It should have been checking the listener filters for:

```
{
         "name": "envoy.filters.listener.tls_inspector",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector"
         }
        }
```

Instead of `tls_inspector` which will always be on the envoy config extensions.

2021-02-03 14:35 UTC, sam-heilbron approved these changes

2021-02-03 15:18 UTC, sam-heilbron approved these changes

2021-02-03 18:04 UTC, EItanya approved these changes

2021-02-03 18:40 UTC, npolshakova commented
/kick

2021-02-03 19:15 UTC, merged