[WIP] add extra volumes and volume mounts on gateway proxy for helm
solo-io/gloo pull request #4230
Opened 2021-01-29 23:17 UTC by kevin-shelaga

# Description
Add helm values and tests for extra volume and volume mounts on the gateway proxy

Please include a summary of the changes.

Add helm values to address https://github.com/solo-io/gloo/issues/4198, including values, tests and a changelog

# Context

This will allow users to more easily mount sslFiles without the use of Kustomize

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-01-29 23:48 UTC, kevin-shelaga commented
I am not a big fan of how the docs were generated for the new helm values, open to suggestions

2021-02-01 14:05 UTC, kdorosh commented on install/helm/gloo/generate/values.go
> +	ExtraVolumes                   []*appsv1.Volume             `json:"extraVolumes,omitempty"`
if we used a `map[string]interface{}` as a type here, there would be much fewer auto-generated docs for the helm value

2021-02-01 14:07 UTC, kdorosh commented on install/test/helm_test.go
> +
when do we assert that these changes are present in the rendered chart? I don't see any changes to the chart in this PR

2021-02-01 15:37 UTC, kdorosh requested changes
no changes to chart templates were made

2021-02-01 15:55 UTC, kevin-shelaga commented on install/helm/gloo/generate/values.go
> +	ExtraVolumes                   []*appsv1.Volume             `json:"extraVolumes,omitempty"`
agreed, will make this change

2021-02-01 15:58 UTC, kevin-shelaga commented on install/test/helm_test.go
> +
hmm, for some reason my changes to 7-gateway-proxy-deployment.yaml didnt get pushed. Will push again with the values mapping for docs change

2021-02-01 17:19 UTC, kdorosh commented on install/test/helm_test.go
> +
where in the tests do we assert that these values were picked up? i don't see any new assertions here on the PR

2021-02-01 17:48 UTC, kevin-shelaga commented
@kdorosh Pr updated

2021-02-01 20:39 UTC, kdorosh commented
/test

2021-02-01 20:54 UTC, kdorosh commented
/test (very bizarre flake) https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=46b97112-0c44-440f-9bcf-03c1f0f18b6b

2021-02-01 20:59 UTC, kdorosh commented on install/test/helm_test.go
> +
bump (still don't see any new assertions in the test code)

2021-02-01 21:01 UTC, kevin-shelaga commented
@kdorosh I was sort of following along with how "gatewayProxies.gatewayProxy.extraVolumeHelper" was implemented. It seems like testManifest.ExpectDeploymentAppsV1(gatewayProxyDeployment) is just testing the whole deployment spec. Separate Volume and VolumeMount tests are probably best. 

https://github.com/solo-io/gloo/blob/e856fd99befe67925bd7840b14ce2a1551c5ca60/install/test/helm_test.go#L1678

2021-02-02 17:13 UTC, kdorosh commented
/test

2021-02-02 17:15 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +          {{- if $spec.podTemplate.resources }}
why change this?

2021-02-02 17:19 UTC, kevin-shelaga commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +          {{- if $spec.podTemplate.resources }}
@kdorosh I found the "{{toYaml" to be inconsistent with other "{{ toYaml" with the space, indentation must of been a local linting thing. Should i change it back?

2021-02-02 18:08 UTC, kdorosh commented
/test

2021-02-02 18:09 UTC, kdorosh submitted a review, later dismissed

2021-02-02 19:17 UTC, kdorosh commented
/test flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=4c204ff8-50df-4624-ab1e-a8f81fcc8421

2021-02-02 21:14 UTC, kdorosh commented
Unfortunately given the latest release, we now need to update the changelog here

2021-02-02 23:38 UTC, kevin-shelaga commented
added v1.7.0-beta14 folder and moved changelog there

2021-02-03 00:47 UTC, kdorosh commented
/test

2021-02-03 01:44 UTC, kdorosh approved these changes
thanks for the contribution! 🚀

2021-02-03 01:44 UTC, merged

2021-02-03 01:51 UTC, kevin-shelaga commented
Thank you for your help @kdorosh