Setup trivy security scanner
solo-io/gloo pull request #4273
Opened 2021-02-09 15:02 UTC by npolshakova

# Description

WIP: testing the github workflow

Adds Trivy to perform security scan on container images in Gloo. Reports the HIGH and CRITICAL CVEs found as a markdown table in the Docs and a SARIF file to the Github security tab.

# Context

# Checklist:

- [] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-02-10 22:30 UTC, npolshakova commented on .github/workflows/trivy-analysis-access-logger.yaml
> +          sarif_file: 'trivy-results-access-logger.sarif'
Onlu one sarif scan can be uploaded to the Github security tab per workflow so the image scans were separated out into separate yaml files.

2021-02-11 14:32 UTC, npolshakova commented on .github/workflows/trivy-analysis-access-logger.yaml
> +          severity: 'CRITICAL,HIGH'
Currently only interested in CRITICAL/HIGH cves

2021-02-11 14:35 UTC, npolshakova commented on Makefile
> +	./trivy --exit-code 0 --severity HIGH,CRITICAL --no-progress --format template --template "@hack/utils/security_scan_report/markdown.tpl" -o $(SCAN_DIR)/gateway_cve_report.docgen $(IMAGE_REPO)/gatew
Allows you to run scan locally

2021-02-11 14:49 UTC, kdorosh commented on .github/workflows/trivy-analysis-access-logger.yaml
> +name: release
we should be able to DRY up these GH actions using a matrix: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

similar to https://github.com/solo-io/gloo/blob/ce440337240a708db686a808694063009caa844a/.github/workflows/regression-tests-and-codegen.yaml#L55

2021-02-11 14:49 UTC, kdorosh requested changes
lets DRY up the GH actions

2021-02-11 14:52 UTC, kdorosh commented on Makefile
> +	gsutil cp -r $(SCAN_DIR)/$(SCAN_FILE) gs://$(SCAN_BUCKET)
wrap in an if statement that ensures we only do on release

2021-02-11 14:52 UTC, kdorosh commented on Makefile
> +SCAN_BUCKET := solo-gloo-security-scans
slightly prefer `?=` syntax in case a user wants to override

2021-02-11 15:53 UTC, npolshakova commented on .github/workflows/trivy-analysis-access-logger.yaml
> +          sarif_file: 'trivy-results-access-logger.sarif'
Now using matrix job config

2021-02-11 17:40 UTC, saiskee submitted a review, later dismissed
Looks good to me!

2021-02-11 20:20 UTC, npolshakova commented on .github/workflows/publish-docs.yaml
> +  workflow_run:
Need to rebuild the docs after the trivy scan publishes the new scan results to the bucket

2021-02-11 20:41 UTC, kdorosh commented on .github/workflows/publish-docs.yaml
> +  workflow_run:
This is neat. I like this. Nice side affect is that this will trigger docs rebuild on every release for Gloo

Gloo release -> trivy -> docs update

2021-02-11 20:46 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +		if !strings.Contains(release.GetTagName(), "beta") {
we also have done "rc" releases in the past -- we should do a strict semver parse and fail anything that doesn't parse

2021-02-11 20:46 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +		if !strings.Contains(release.GetTagName(), "beta") {
also log warning when we skip releases

2021-02-11 20:48 UTC, kdorosh commented on docs/cmd/securityscanutils/securityscan_utils.go
> +		// Older releases may be missing scan results
which error code do we get for missing scan results? let's check against that?

2021-02-11 20:49 UTC, kdorosh commented on Makefile
> +endif
why not just do `machine =`?

2021-02-11 20:50 UTC, kdorosh commented on .github/workflows/trivy-analysis.yaml
> +          mkdir -p ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}
should this be part of the make target instead?

2021-02-11 22:29 UTC, npolshakova commented on .github/workflows/trivy-analysis.yaml
> +          mkdir -p ${{ env.SCAN_DIR }}/${{ steps.build-docker-image.outputs.VERSION }}
The ouput scans directory has to be created before the trivy scan is run. So I could create it the same way we're making the _output directory in the makefile (z := $(shell mkdir -p $(OUTPUT_DIR))) or have a setup-scans-directory make target that just only builds the directory.

2021-02-12 16:33 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +		isMatch, _ := regexp.MatchString("^v(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$", release.GetTagName())
fyi, we could use the `semver` library here with strict versioning: https://github.com/solo-io/gloo/blob/104297b30d69b916a67294cbda5b7cb77fd21a87/pkg/version/enterprise.go#L67

2021-02-12 17:43 UTC, kdorosh approved these changes

2021-02-12 18:20 UTC, merged