fix regex parsing
solo-io/gloo pull request #4309
Opened 2021-02-18 15:11 UTC by npolshakova

# Description

Fixes regex parsing for homebrew-core formula.

# Context

Empty commits were getting generated in homebrew-core by Solo-io Bot because of incorrect regex parsing.

https://github.com/solo-io/gloo/issues/4217

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-02-18 17:01 UTC, sam-heilbron requested changes

2021-02-18 17:03 UTC, npolshakova commented on changelog/v1.7.0-beta21/fix-homebrew-ci.yaml
> +    issueLink: https://github.com/solo-io/gloo/issues/4217
Thanks!

2021-02-18 19:09 UTC, kdorosh commented on changelog/v1.7.0-beta21/fix-homebrew-ci.yaml
> +  - type: FIX
non user facing?

2021-02-18 19:13 UTC, kdorosh approved these changes

2021-02-18 20:23 UTC, kdorosh approved these changes

2021-02-19 13:40 UTC, sam-heilbron approved these changes

2021-02-19 14:05 UTC, merged