bug fix for settings invalidConfigPolicy helm value
solo-io/gloo pull request #4323
Opened 2021-02-20 13:36 UTC by kevin-shelaga

# Description

InvalidConfigPolicy was incorrectly mapped in the settings template. Updated mapping and test.

# Context

Users ran into this bug: https://github.com/solo-io/gloo/issues/4321

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-02-20 19:18 UTC, saiskee requested changes
Looks good, a few changes/comments. Thank you for picking up on this task!

2021-02-20 19:18 UTC, saiskee commented on install/helm/gloo/templates/18-settings.yaml
> +{{- if or (.Values.settings.InvalidConfigPolicy) (.Values.settings.replaceInvalidRoutes) }}
```suggestion
{{- if or (.Values.settings.invalidConfigPolicy) (.Values.settings.replaceInvalidRoutes) }}
```

2021-02-20 19:18 UTC, saiskee commented on install/test/helm_test.go
> +								"settings.InvalidConfigPolicy.replaceInvalidRoutes=true",
```suggestion
								"settings.invalidConfigPolicy.replaceInvalidRoutes=true",
```

2021-02-20 19:18 UTC, saiskee commented on install/test/helm_test.go
> +
Can you write a test that whether `invalidPolicy` is rendered based on a non-null value of `settings.InvalidConfigPolicy` and not just `invalidConfigPolicy.replaceInvalidRoutes`?

2021-02-20 23:30 UTC, kevin-shelaga commented on install/test/helm_test.go
> +
@saiskee I had to update all the settings test because invalidConfigPolicy is in the default values. I updated the tests to to more complete. Please take a look at let me know if this is not what you had in mind.

2021-02-22 15:14 UTC, kdorosh commented
/test

2021-02-22 16:49 UTC, saiskee approved these changes
Looks good to me! Thanks @kevin-shelaga !

2021-02-22 16:49 UTC, merged