Backport disable transformation validation v1.5.x
solo-io/gloo pull request #4568
Opened 2021-04-07 16:07 UTC by EItanya

2021-04-07 16:35 UTC, saiskee requested changes

2021-04-07 16:35 UTC, saiskee commented on install/test/fixtures/settings/disable_transformation_validation.yaml
> +   enableRestEds: true
```suggestion
   enableRestEds: false
```

2021-04-20 15:17 UTC, saiskee commented
@EItanya is this backport still needed?

2021-04-20 18:55 UTC, kdorosh commented
closing as stale @EItanya

2021-04-20 18:55 UTC, closed without merging