Xslt transformer api
solo-io/gloo pull request #4585
Opened 2021-04-13 13:16 UTC by saiskee

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-04-13 13:25 UTC, saiskee commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +	TranslateTransformation     TranslateTransformationFn
I'm using this function as a point of extension for implementing the enterprise transformer (xslt) in solo-projects. Will definitely take design suggestions here.

2021-04-13 15:05 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
> +  // should be changed to `application/xml` to `application/json`
```suggestion
  // should be changed from `application/xml` to `application/json`
```

2021-04-13 15:05 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
> +  // should be changed to `application/xml` to `application/json`
what is the default if left empty?

2021-04-13 15:06 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
> +  bool non_xml_transform = 3;
this feels a bit clunky? what happens if i forget to set it? feels like we're exposing an implementation detail here

2021-04-13 15:07 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
> +    solo.io.envoy.config.core.v3.TypedExtensionConfig transformer_config = 3;
this is config for the filter itself, not user-facing correct? might be worth calling out this proto as internal or something in the comments

2021-04-13 15:08 UTC, kdorosh commented on projects/gloo/pkg/bootstrap/bootstrap_validation.go
> +	return nil
todo remove

2021-04-13 15:12 UTC, saiskee commented on projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
> +  bool non_xml_transform = 3;
The way XSLT works is that it can only take XML as an input. So if the body is a valid XML, nothing needs to happen. However, if the XSLT is a JSON to XML transform, the input is going to be JSON (not valid XML). In this case, we wrap the input in a xml CDATA tag, which will escape the input data. 

It would require quite a bit of processing overhead to detect whether something is valid XML or not, so I think that this can be specified by the user.

2021-04-13 15:20 UTC, kdorosh commented on projects/gloo/api/external/envoy/extensions/transformers/xslt/xslt_transformer.proto
> +  bool non_xml_transform = 3;
makes sense. I think this is context that could also live in the comments; as a user I'd definitely want to understand why this isn't automatically detected

2021-04-23 15:20 UTC, saiskee commented
/kick data race in consul endpoint test.

2021-04-23 15:51 UTC, kdorosh commented on projects/gloo/api/v1/options/transformation/transformation.proto
> +        envoy.config.transformer.xslt.v2.XsltTransformation xslt_transformation = 4;
add a comment for enterprise only?

2021-04-23 15:51 UTC, kdorosh commented on projects/gloo/api/v1/options/transformation/transformation.proto
> +        envoy.config.transformer.xslt.v2.XsltTransformation xslt_transformation = 4;
```suggestion
        envoy.config.transformer.xslt.v2.XsltTransformation xslt_transformation = 3;
```
?

2021-04-23 15:52 UTC, kdorosh commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +		return fmt.Errorf("transformation type %T is not supported in this version of Gloo Edge", transformation)
instead of saying "this version", perhaps call out that it's not supported in open source (i.e., don't imply that eventually it will be supported in open source)

2021-04-23 15:53 UTC, kdorosh commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +			break
no need for the breaks

2021-04-23 15:54 UTC, kdorosh commented on projects/gloo/pkg/plugins/transformation/plugin_test.go
> +			Expect(err).To(Equal(UnsupportedTransformationType(&transformation.Transformation_XsltTransformation{})))
nit, `MatchError` instead of `To(Equal())`

2021-04-23 15:58 UTC, kdorosh commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +	TranslateTransformation     TranslateTransformationFn
Looks reasonable to me 👍

2021-04-23 16:25 UTC, saiskee commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +		return fmt.Errorf("transformation type %T is not supported in this version of Gloo Edge", transformation)
This same logic will be run by the enterprise "upgraded" transformation plugin, so we can support Transformation Template and Header Body transform in enterprise and wouldn't have to dupe this logic. That's why I chose not to include an Open source warning. I could change this to `unknown transformation Type %T`?

2021-04-23 19:00 UTC, kdorosh requested changes
address https://github.com/solo-io/gloo/pull/4585/files#r612536229

2021-04-23 19:28 UTC, saiskee commented on projects/gloo/pkg/bootstrap/bootstrap_validation.go
> +	return nil
```suggestion
```

2021-04-23 19:38 UTC, kdorosh approved these changes

2021-04-24 14:20 UTC, merged