Add support for glooE Helm value documentation
solo-io/gloo pull request #4911
Opened 2021-06-21 17:09 UTC by ben-taussig-solo

# Description

- This PR partially addresses [issue 3679](https://github.com/solo-io/gloo/issues/3679).
- A new page in the documentation akin to the Reference/Helm Chart Values section documenting Gloo E Helm chart values has been created.
- The Gloo E Helm chart values are fetched from the solo-projects Github upon building the docs. A Github token for an account with access to this repository is required in order to accomplish this.

# Context

- Users needed this feature, because there are significant differences between the OSS Gloo and Enterprise Gloo Helm chart values.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2021-06-21 19:32 UTC, kdorosh commented on changelog/v1.8.0-beta22/glooe-helm-value-documentation.yaml
> +  - type: NEW_FEATURE
usually docs changes are `NON_USER_FACING`, preferring to leave the generated release notes and changelog full of changes that are actionable / more useful to users who are upgrading between versions

2021-06-21 19:47 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +	releaseTag, err := githubutils.FindLatestReleaseTag(ctx, client, "solo-io", "solo-projects")
prefer `FindLatestReleaseBySemver`? and add a comment that explains why we don't get pre-releases? (could break open source ci if latest enterprise release failed or is still in flight)

2021-06-21 19:48 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +	decodedContents, err := base64.StdEncoding.DecodeString(*files[0].Content)
assert length of `files` is 1 first?

2021-06-21 19:49 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +	fmt.Printf("%s", decodedContents)
do we still want this?

2021-06-21 19:49 UTC, kdorosh commented on docs/Makefile
> +	GO111MODULE=on go run cmd/generate_docs.go get-enterprise-helm-values 1.1 > content/static/content/glooe-values.docgen
why pass 1.1? is that unused?

2021-06-21 19:54 UTC, ben-taussig-solo commented on docs/Makefile
> +	GO111MODULE=on go run cmd/generate_docs.go get-enterprise-helm-values 1.1 > content/static/content/glooe-values.docgen
Yeah this is left over from testing 
```suggestion
	GO111MODULE=on go run cmd/generate_docs.go get-enterprise-helm-values > content/static/content/glooe-values.docgen
```

2021-06-21 19:57 UTC, ben-taussig-solo commented on docs/cmd/generate_docs.go
> +	fmt.Printf("%s", decodedContents)
Yes -- in the same pattern as changelog and security scan generation, we log the file content to stdout and pipe it into a file
https://github.com/solo-io/gloo/blob/b9174295923340b7028ea5259148ad7c7f71ff2e/docs/Makefile#L27

2021-06-21 20:09 UTC, ben-taussig-solo commented on docs/cmd/generate_docs.go
> +	decodedContents, err := base64.StdEncoding.DecodeString(*files[0].Content)
added the following block:
https://github.com/solo-io/gloo/blob/45d7268b971feabd301d42aaf712cccf041d76b5/docs/cmd/generate_docs.go#L293-L298

+ the accompanying error:
https://github.com/solo-io/gloo/blob/45d7268b971feabd301d42aaf712cccf041d76b5/docs/cmd/generate_docs.go#L129-L131

2021-06-22 14:18 UTC, saiskee commented on docs/cmd/generate_docs.go
> +	if os.Getenv("GITHUB_TOKEN") == "" {
Let's actually start using the tooling we have written for these lines: https://github.com/solo-io/go-utils/blob/659f83c28389f960ad8b3d2a337bb050fd229fce/githubutils/repo.go#L49


So this would just be 
```go
client := GetClient(ctx)
```

2021-06-23 16:28 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +	releaseTag, err := githubutils.FindLatestReleaseBySemver(ctx, client, "solo-io", "solo-projects")
we probably want to cap this by minor version. when this branch becomes the backport branch, we don't want the docs to grab the latest helm values, but rather the latest ones for 1.7, 1.8 etc.

2021-06-23 16:30 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +)
this constant is unused

2021-06-23 16:42 UTC, kdorosh requested changes
needs to be capped by minor version

2021-06-23 16:49 UTC, ben-taussig-solo commented on docs/cmd/generate_docs.go
> +)
```suggestion
```

2021-06-24 19:06 UTC, kdorosh commented on docs/cmd/generate_docs.go
> +	}
this still is going to grab versions that are too new on backport branches. we have solved this problem in the past using https://github.com/solo-io/gloo/blob/e64cc56064c35446256137d3671b7e59f398520b/hack/find_latest_enterprise_version.go#L23-L44

2021-06-24 19:06 UTC, kdorosh requested changes
still needs some version parsing fixes for backport branches

2021-06-28 21:08 UTC, kdorosh approved these changes
looks good!

2021-06-28 21:25 UTC, merged