Remove dependency on k8s.io/kubernetes
solo-io/gloo pull request #5042
Opened 2021-07-18 03:11 UTC by abursavich

# Description

This fixes #5041 and removes the dependency on `k8s.io/kubernetes`.

# Context

The dependency on `k8s.io/kubernetes` is preventing me from being able to import gloo's API, because of the pain that comes along with it.

2021-07-19 14:02 UTC, kdorosh commented
thanks for the contribution! /test

2021-07-19 15:55 UTC, abursavich commented
From the error message, it think the build-bot is using a pre-1.16 version of Go. Can we bump that up? The other test may fail similarly, depending on their Go versions.

2021-07-19 17:45 UTC, kdorosh commented
we should be able to bump that. if you update the code (https://github.com/solo-io/build-bot/blob/master/go.mod#L3) i can deploy the new bot in our environment

2021-07-19 17:54 UTC, sam-heilbron commented
Is it a build-bot issue, or because solo-apis requires client-go which is now excluded?
https://github.com/solo-io/solo-apis/blob/master/go.mod#L37

2021-07-20 21:35 UTC, abursavich commented
> Is it a build-bot issue, or because solo-apis requires client-go which is now excluded?

It's both. The way excludes work changed in Go 1.16. With Go 1.15, those excludes break builds in the way you're suggesting. With Go 1.16, those excludes make the build work without needing to require the wrong version and use replace hacks to fix it.

2021-07-21 01:20 UTC, saiskee commented
Hi @abursavich, could you link us to the go 1.16 docs for this change? This behavior checks out from local testing, but it would be good to have some official docs, which I'm unable to find currently.

2021-07-21 02:22 UTC, abursavich commented
From the [1.6 release notes](https://golang.org/doc/go1.16):

> The go command now ignores requirements on module versions excluded by exclude directives in the main module. Previously, the go command used the next version higher than an excluded version, but that version could change over time, resulting in non-reproducible builds.

2021-07-23 21:29 UTC, sam-heilbron commented
Hi @abursavich, I'm going to do some reading to better understand the scope of this change. This type of change to build-bot could/would affect others teams within the organization.

2021-07-23 22:27 UTC, abursavich commented
No worries. I'm not in any rush.

2021-09-15 21:49 UTC, abursavich commented
It's been about 2 months. Please let me know if anyone's gonna take a look at this. I'll probably wait until then to resolve any conflicts.

2021-09-15 22:30 UTC, abursavich commented
Alright... I rebased it once.

2021-09-16 00:17 UTC, sam-heilbron commented
Apologies for the delay. I'm doing some tangential work that I hope to resolve this. It's taken a little longer than expected. I will update this issue when the work is completed

2021-09-24 01:19 UTC, sam-heilbron commented
/test

2021-09-24 01:51 UTC, sam-heilbron commented
build-bot failing with: `go: github.com/solo-io/solo-apis@v0.0.0-20210922150112-505473b2e66c: github.com/solo-io/solo-apis(v0.0.0-20210922150112-505473b2e66c) depends on excluded k8s.io/client-go(v11.0.0+incompatible) with no newer version available`

2021-09-24 07:05 UTC, abursavich commented
@sam-heilbron, is the build bot still using a pre-1.16 version of go?

We did this same thing ~2 months ago: https://github.com/solo-io/gloo/pull/5042#issuecomment-882661911

2021-09-24 07:13 UTC, abursavich commented
I'm not sure if I'm reading the logs correctly, but it _looks_ like it's using v1.13.5.

```
$ docker run --entrypoint go gcr.io/solo-public/prepare-go-workspace:0.3.0 version
go version go1.13.5 linux/amd64
```

2021-09-24 21:41 UTC, sam-heilbron commented
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=887a7d82-54b1-42e2-8722-eb55720f13d7

2021-09-30 21:43 UTC, bewebi commented
/kick

2021-09-30 22:10 UTC, bewebi commented
/kick

2021-10-01 16:32 UTC, bewebi commented
/kick

2021-10-01 20:10 UTC, sam-heilbron requested changes
Discussed offline that this will go into our 1.10.0-beta1 release, since we're too close to the 1.9 release. Requesting changes to ensure it doesn't get merged accidentally before we cut a new branch

2021-10-04 17:48 UTC, sam-heilbron commented on go.mod
> +	google.golang.org/grpc => google.golang.org/grpc v1.36.0
this upgrade is being handled in a separate PR: https://github.com/solo-io/gloo/pull/5429

2021-10-05 18:22 UTC, bewebi commented
/kick

2021-10-05 19:00 UTC, bewebi commented
/kick

2021-10-06 12:47 UTC, MitchAman reviewed
LGTM

2021-10-06 13:06 UTC, sam-heilbron approved these changes

2021-10-06 13:06 UTC, merged