Add docs for nested claims in JWT RBAC
solo-io/gloo pull request #5190
Opened 2021-08-19 12:44 UTC by MitchAman

# Description

Doc changes to reflect new nested claims feature added in https://github.com/solo-io/solo-projects/pull/2675

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-08-20 15:02 UTC, MitchAman commented
/kick data race flake: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=105e1ffe-3078-46a3-a82a-dc0838b20997

2021-08-20 16:56 UTC, Rachael-Graham requested changes
Let me know if any of this doesnt quite work or make sense - still learning the product! :)

2021-08-20 16:56 UTC, Rachael-Graham commented on docs/content/guides/security/auth/jwt/access_control.md
> +    and specifying the claim name as a path (i.e. `parent.child.foo`) in the [JWTPrincipal]({{% versioned_link_path fromRoot="/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/op
```suggestion
  - **Note**: Matching is supported for top-level claims of the JWT and for nested claims, or claims that are children of top-level claims.
    To enable matching against nested claims, you must first specify a `nestedClaimsDelimiter`, such as `.`, in a [Policy]({{% versioned_link_path fromRoot="/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/rbac/rbac.proto.sk/#policy" %}})
    and specify the claim name as a path, such as `parent.child.foo`, in the `claims` field of the [JWTPrincipal]({{% versioned_link_path fromRoot="/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/rbac/rbac.proto.sk/#jwtprincipal" %}}).
```

2021-08-20 16:56 UTC, Rachael-Graham commented on docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/rbac/rbac.proto.sk.md
> +| `claims` | `map<string, string>` | Set of claims that make up this principal. Commonly, the 'iss' and 'sub' or 'email' claims are used. All claims must be present on the JWT. Nested claims, such as
```suggestion
| `claims` | `map<string, string>` | A set of claims for this principal. Commonly, this list includes the `iss` claim and the `sub` or `email` claims. All claims in this list must be present on the JWT.  If you specify the path for a nested claim, such as 'parent.child.foo', you must also specify a non-empty string value for the `nested_claim_delimiter` field in the [Policy]({{% versioned_link_path fromRoot="/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/enterprise/options/rbac/rbac.proto.sk/#policy" %}}).
```

2021-08-20 16:56 UTC, Rachael-Graham commented on projects/gloo/api/v1/enterprise/options/rbac/rbac.proto
> +    // the Policy must have a non-empty string value set for `nested_claim_delimiter`.
I am not sure if these are generated here or from another file location, but adding a review here just in case
```suggestion
    // If you specify the path for a nested claim, such as 'parent.child.foo', you must also specify
    // a non-empty string value for the `nested_claim_delimiter` field in the Policy.
```

2021-08-20 16:56 UTC, Rachael-Graham commented on projects/gloo/pkg/api/v1/enterprise/options/rbac/rbac.pb.go
> +	// the Policy must have a non-empty string value set for `nested_claim_delimiter`.
same as above
I am not sure if these are generated here or from another file location, but adding a review here just in case
```suggestion
    // If you specify the path for a nested claim, such as 'parent.child.foo', you must also specify
    // a non-empty string value for the `nested_claim_delimiter` field in the Policy.
```

2021-08-20 16:56 UTC, Rachael-Graham commented on changelog/v1.9.0-beta14/nested-claims-docs.yaml
> +    description: Add documentation for nested claims (rather than just top-level claims) in JWT RBAC.
```suggestion
    description: Adds documentation for nested claim support in RBAC policies for JSON Web Tokens (JWT).
```

Do you typically add links from the changelog to the topic as well? Such as `... [JSON Web Tokens (JWT) RBAC policies]({{% versioned_link_path fromRoot="/docs/content/guides/security/auth/jwt/access_control/" %}})` , or nah?

2021-08-23 14:46 UTC, MitchAman commented on changelog/v1.9.0-beta14/nested-claims-docs.yaml
> +    description: Add documentation for nested claims (rather than just top-level claims) in JWT RBAC.
I don't typically, but that doesn't mean we can't do that going forward.  The bigger question would be: what version of the topic should we link to, and what happens when topics move or get removed?

We could just use whichever version they're currently viewing with, so that's fine. But what happens if a topic is removed or moved to a different url? We would have to either make sure it redirects to correct location, or go back and update links in changelog files.  I don't have a strong opinion here, I feel like a link could be very helpful in figuring out how to use newly released features.  If this is something the tech. writing team would like to see happen moving forward, we should add some information about it to https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog. Perhaps we could add an (optional) `additionalLinks` field to the changelog?

2021-08-23 14:48 UTC, MitchAman commented on projects/gloo/pkg/api/v1/enterprise/options/rbac/rbac.pb.go
> +	// the Policy must have a non-empty string value set for `nested_claim_delimiter`.
It is indeed generated from `rbac.proto`, so I'll just re-run the codegen and push the changes, just to make sure there are no little differences

2021-08-23 14:55 UTC, Rachael-Graham approved these changes

2021-08-23 15:06 UTC, MitchAman commented
/skip-ci as this is docs-only.

2021-08-23 15:24 UTC, MitchAman commented
/skip-ci

2021-08-23 17:11 UTC, merged