[WIP] Support Namespaced Statuses
solo-io/gloo pull request #5191
Opened 2021-08-19 13:40 UTC by sam-heilbron

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-08-30 22:10 UTC, sam-heilbron commented
/kick consul data race: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=ecfb9f62-6fc9-447f-b01a-4df0e91dd555

2021-08-31 15:41 UTC, MitchAman commented on go.mod
> +	github.com/solo-io/solo-kit v0.21.4-0.20210827165033-6f30192f1b58
TODO: reference actual solo-kit PR when it's available

2021-08-31 15:41 UTC, MitchAman commented on projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
> ++-----------------+--------------+---------+------+--------+-----------------+--------------------------------+`))
Is there a good way to prevent this behavior change? I was beginning to look into this before the task switched hands

2021-08-31 19:38 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/get/virtualservice_test.go
> ++-----------------+--------------+---------+------+--------+-----------------+--------------------------------+`))
updated PR. I decide to do 2 things:
1. When there is just a single status, only dispaly that status. Most clients will interact with the UI this way so I figured it reduced the change exposed to users 
2. If there is no status , which happens before a resource has been synced, default to pending.

2021-09-01 15:31 UTC, kdorosh commented
supersedes https://github.com/solo-io/gloo/pull/5020

2021-09-01 15:34 UTC, kdorosh commented on projects/gateway/api/v1/external_options.proto
> +  // NamespacedStatuses is read-only by clients, and set by gloo during validation
in this case, the status is set by gateway during validation

2021-09-01 15:35 UTC, kdorosh commented on projects/gateway/api/v1/external_options.proto
> +  // NamespacedStatuses is read-only by clients, and set by gloo during validation
since this is the gateway api `projects/gateway/api/...`

2021-09-01 15:36 UTC, kdorosh commented on projects/gateway/api/v1/gateway.proto
> +    // NamespacedStatuses is read-only by clients, and set by gloo during validation
set by gateway during validation

2021-09-01 15:36 UTC, kdorosh commented on projects/gateway/api/v1/route_table.proto
> +    // NamespacedStatuses is read-only by clients, and set by gloo during validation
set by gateway

2021-09-01 15:37 UTC, kdorosh commented on projects/gateway/pkg/syncer/translator_syncer.go
> +			contextutils.LoggerFrom(ctx).Errorf("Error getting NamespacedStatus: %v", err)
super nit, golang errors should begin with lower-case

2021-09-01 15:40 UTC, kdorosh commented on test/kube2e/util.go
> +func GetRandomNamespace(prefix string) string {
do we really want/need this anymore? this was left over from when ci used to run in parallel all on the same GKE cluster, in the hopes we wouldn't get any collisions across namespaces.

since ci runs sequentially now, no reason to make tests harder to reproduce with randomness (or have the extra code)

2021-09-14 16:16 UTC, kdorosh commented on docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/api/v2/cluster/outlier_detection.proto.sk.md
> +"consecutive5Xx": .google.protobuf.UInt32Value
any idea why this change is coming out of codegen?

2021-09-14 16:19 UTC, kdorosh commented on projects/gateway/pkg/utils/proxy_transition_function.go
> -		desired.Status = original.GetStatus()
should we bubble up the error here?

2021-09-14 21:01 UTC, sam-heilbron commented on docs/content/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/api/v2/cluster/outlier_detection.proto.sk.md
> +"consecutive5Xx": .google.protobuf.UInt32Value
I'm not sure, though I can investigate. There are a number of dep bumps as a result of the solo-kit upgrade

2021-09-14 21:59 UTC, sam-heilbron commented on projects/gateway/pkg/utils/proxy_transition_function.go
> -		desired.Status = original.GetStatus()
yeah good call

2021-09-15 14:02 UTC, kdorosh requested changes
this needs some changes to work with our non-k8s install flows where the downward k8s api doesn't populate the namespace env var for us

2021-09-20 13:11 UTC, sam-heilbron commented
Replaced by: https://github.com/solo-io/gloo/pull/5352

2021-09-20 13:11 UTC, closed without merging