[WIP] Glooctl check printers - TABLE, JSON
solo-io/gloo pull request #5282
Opened 2021-09-01 14:10 UTC by kevin-shelaga

# Description

Add a printer/output option for glooctl check - TABLE, JSON

# Context

Resolves: https://github.com/solo-io/gloo/issues/4807

Initial design: After discussion with @sam-heilbron I have opted for a centralized AppendResponse

Issues:

    glooctl check looks at structs and checks for values to see if they are "OK". There is no struct to output.
    default output is "TABLE", but glooctl check just printlns

decisions:

    create a struct to represent checks
    build object regardless of output type?
    glooctl check should work the same by default
    anything other than -o json should return "invalid output type"

TABLE:
```sh
Checking deployments... OK
Checking pods... OK
Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
No problems detected.
I0901 09:53:44.423450   51570 request.go:645] Throttling request took 1.008756891s, request: GET:https://1.1.1.1/apis/cilium.io/v2alpha1?timeout=32s

Detected Gloo Federation!

Checking upstreams... OK
Checking upstream groups... OK
Checking auth configs... OK
Checking rate limit configs... OK
Checking VirtualHostOptions... OK
Checking RouteOptions... OK
Checking secrets... OK
Checking virtual services... OK
Checking gateways... OK
Checking proxies... OK
Checking rate limit server... OK
Error: 8 errors occurred:
	* Pod gloo-58f6b98cc8-2kl55 in namespace gloo-system is not ready! Message: containers with unready status: [gloo]
	* Not all containers in pod gloo-58f6b98cc8-2kl55 in namespace gloo-system are ready! Message: containers with unready status: [gloo]
	* Pod gloo-645ff777c6-tnfj6 in namespace gloo-system is not ready! Message: containers with unready status: [gloo]
	* Not all containers in pod gloo-645ff777c6-tnfj6 in namespace gloo-system are ready! Message: containers with unready status: [gloo]
	* Pod gloo-9d8888d8c-lrjhp in namespace gloo-system is not ready! Message: containers with unready status: [gloo]
	* Not all containers in pod gloo-9d8888d8c-lrjhp in namespace gloo-system are ready! Message: containers with unready status: [gloo]
	* Pod gloo-c96b6c677-4fv7d in namespace gloo-system is not ready! Message: containers with unready status: [gloo]
	* Not all containers in pod gloo-c96b6c677-4fv7d in namespace gloo-system are ready! Message: containers with unready status: [gloo]
```

JSON:
```json
{
  "resources": [
    { "name": "deployments", "status": "OK" },
    { "name": "pods", "status": "OK" },
    { "name": "upstreams", "status": "OK" },
    { "name": "upstream groups", "status": "" },
    { "name": "upstream groups", "status": "" },
    { "name": "auth configs", "status": "OK" },
    { "name": "rate limit configs", "status": "OK" },
    { "name": "VirtualHostOptions", "status": "OK" },
    { "name": "RouteOptions", "status": "OK" },
    { "name": "secrets", "status": "OK" },
    { "name": "virtual services", "status": "OK" },
    { "name": "gateways", "status": "OK" },
    { "name": "proxies", "status": "OK" },
    { "name": "rate limit server", "status": "OK" }
  ],
  "messages": ["No problems detected.", "Detected Gloo Federation!"],
  "errors": null
}

{
  "resources": [
    { "name": "deployments", "status": "OK" },
    { "name": "pods", "status": "8 Errors!" },
    { "name": "upstreams", "status": "OK" },
    { "name": "upstream groups", "status": "OK" },
    { "name": "auth configs", "status": "OK" },
    { "name": "rate limit configs", "status": "OK" },
    { "name": "VirtualHostOptions", "status": "OK" },
    { "name": "RouteOptions", "status": "OK" },
    { "name": "secrets", "status": "OK" },
    { "name": "virtual services", "status": "OK" },
    { "name": "gateways", "status": "OK" },
    { "name": "proxies", "status": "OK" },
    { "name": "rate limit server", "status": "OK" }
  ],
  "messages": ["Detected Gloo Federation!"],
  "errors": [
    "Pod gloo-54f4cb88cb-88crq in namespace gloo-system is not ready! Message: containers with unready status: [gloo]",
    "Not all containers in pod gloo-54f4cb88cb-88crq in namespace gloo-system are ready! Message: containers with unready status: [gloo]",
    "Pod gloo-5bf6cbbd6-rjcdw in namespace gloo-system is not ready! Message: containers with unready status: [gloo]",
    "Not all containers in pod gloo-5bf6cbbd6-rjcdw in namespace gloo-system are ready! Message: containers with unready status: [gloo]",
    "Pod gloo-6bf45bc8f7-phn2c in namespace gloo-system is not ready! Message: containers with unready status: [gloo]",
    "Not all containers in pod gloo-6bf45bc8f7-phn2c in namespace gloo-system are ready! Message: containers with unready status: [gloo]",
    "Pod gloo-776dd845bd-9px7j in namespace gloo-system is not ready! Message: containers with unready status: [gloo]",
    "Not all containers in pod gloo-776dd845bd-9px7j in namespace gloo-system are ready! Message: containers with unready status: [gloo]"
  ]
}
```
# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-09-01 14:35 UTC, kevin-shelaga commented
Will commit updated docs

2021-09-02 19:08 UTC, artberger reviewed
A couple doc comments, thanks!

2021-09-02 19:08 UTC, artberger commented on changelog/v1.9.0-beta16/glooctl-json-printer.yaml
> +    description: Add support for json output from `glooctl check -o json`. `glooctl check` continues to function as it did before.
Also just confirming, this change is only adding JSON support for output, and not just the entire output flag? 

(I noticed in my 1.8.7, the `glooctl check` command doesn't have the `-o` flag.)

If it's the entire --output flag, maybe:
```suggestion
    description: Adds the ability to set the output of the `glooctl check -o` command. The default output is a human-readable table, but you can change the output to another more programmatic format, such as for JSON or YAML.  No other functionality is added to the command.
```

2021-09-02 20:39 UTC, kevin-shelaga commented on projects/gloo/cli/pkg/cmd/check/root.go
> +				return errors.New("Invalid output type")
I updated this to `return errors.New("Invalid output type. Only table (default) and json are supported.")` because only table and json are supported right now

2021-09-02 22:05 UTC, artberger commented
LGTM for docs, thanks!

2021-09-08 12:52 UTC, sam-heilbron reviewed
This will be super useful! 

Have you take a look at https://github.com/solo-io/go-utils/blob/master/cliutils/printers.go to see what utility methods may exist already?

2021-09-08 12:52 UTC, sam-heilbron commented on projects/gloo/cli/pkg/printers/check.go
> +func AppendResponse(name string, status string, message string, err string, outputType OutputType) {
Since the outputType will be the same for each call to `glooctl check`, do you think it makes sense to initialize this somewhere once?

2021-09-08 12:52 UTC, sam-heilbron commented on projects/gloo/cli/pkg/printers/check.go
> +		} else if message != "" {
Does the table outputType not handle errors?

2021-09-08 12:52 UTC, sam-heilbron commented on projects/gloo/cli/pkg/printers/check.go
> +			checkResult.Errors = append(checkResult.Errors, strings.ReplaceAll(err, "\n", ""))
instead of checking messages and errors, perhaps it makes sense to expose an `AppendMessage` and `AppendError`

2021-09-08 12:52 UTC, sam-heilbron commented on projects/gloo/cli/pkg/printers/check.go
> +}
can we add a comment outlining what this is doing and why we need it?

2021-09-08 12:52 UTC, sam-heilbron commented on projects/gloo/cli/pkg/printers/check.go
> +func PrintChecks() error {
we could pass an io.Writer here, and Print/Flush passes that writer to fmt.Print

2021-09-08 21:26 UTC, kevin-shelaga commented on projects/gloo/cli/pkg/printers/check.go
> +}
done

2021-09-09 00:27 UTC, kevin-shelaga commented on projects/gloo/cli/pkg/printers/check.go
> +func PrintChecks() error {
Think i know what you meant

2021-09-09 00:28 UTC, kevin-shelaga commented
Ready for another review @sam-heilbron

2021-09-09 15:42 UTC, MitchAman requested changes
LGTM, other than one small nit

2021-09-09 15:42 UTC, MitchAman commented on docs/content/reference/cli/glooctl_check.md
> +  -o, --output OutputType   output format: (yaml, json, table, kube-yaml, wide) (default table)
Does this actually support yaml, kube-yaml, and wide, or should the description get updated?

2021-09-09 16:00 UTC, kevin-shelaga commented on docs/content/reference/cli/glooctl_check.md
> +  -o, --output OutputType   output format: (yaml, json, table, kube-yaml, wide) (default table)
Good catch, when adding in the output option it updated the description with unsupported types as well

2021-09-10 13:50 UTC, MitchAman approved these changes

2021-09-11 00:00 UTC, jenshu approved these changes

2021-09-11 00:00 UTC, merged