Docs - Updating to pull the Hugo theme dynamically
solo-io/gloo pull request #5300
Opened 2021-09-07 17:18 UTC by artberger

Related to https://github.com/solo-io/doctopus/issues/28

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-09-07 17:19 UTC, artberger commented
/skip-changelog

2021-09-07 17:41 UTC, artberger commented
Confirmed formatting changes from theme update are rendering in the preview, such as these H3s here: https://gloo-edge--pr5300-adb-hugo-up-dzbdc53w.web.app/gloo-edge/latest/introduction/observability/

![image](https://user-images.githubusercontent.com/20074219/132387862-5a75b633-ef29-4fa1-ac57-001e107ffe2b.png)

2021-09-07 18:56 UTC, saiskee commented on docs/Makefile
> +SOLO_HUGO_THEME_REVISION := $(curl --silent "https://api.github.com/repos/solo-io/hugo-theme-soloio/releases/latest" | jq -r .tag_name)
Let's change this to 
```
curl --silent “https://api.github.com/repos/solo-io/hugo-theme-soloio/releases/latest” | jq -esr ‘if . == [] then null else .[] | .tag_name end’
```

else if the `curl` fails, jq will swallow the error and silently fail here.

2021-09-08 16:07 UTC, sam-heilbron commented
What is the effect that has if breaking changes are introduced into the hugo theme?

2021-09-08 18:31 UTC, artberger commented
> What is the effect that has if breaking changes are introduced into the hugo theme?

@sam-heilbron I am not sure , and @saiskee can correct me if I'm misunderstanding the doc build process, but a couple thoughts are:
* Before publishing a latest Solo Hugo theme release that these docs would call, we should test changing the theme to the latest Solo Hugo commit in the Edge, Mesh, & Portal docs locally to make sure the release doesn't cause any issues.
* Whatever the breaking change is would get picked up only in the master branch, which isn't the default view of the doc and is for active development, before it would be backported to a previous branch, like 1.8/latest.

But maybe there are better ways to prevent?

2021-09-13 14:48 UTC, sam-heilbron requested changes
There are comments on PRs in other repos (https://github.com/solo-io/gloo-mesh-enterprise/pull/1219#discussion_r704789137) that this change will not work as expected.

2021-09-16 16:10 UTC, saiskee commented
/skip-changelog

2021-09-16 16:10 UTC, saiskee commented
/skip-ci

2021-09-16 18:47 UTC, artberger commented
@sam-heilbron Sai's update fixed that! In the logs, it's now checking out the latest version. https://github.com/solo-io/gloo/pull/5300/checks?check_run_id=3623994445#step:7:277

2021-09-17 17:57 UTC, sam-heilbron approved these changes

2021-09-17 17:57 UTC, merged