feat(proto): added `clone_all` interfaces to all proto objects (#5658)
solo-io/gloo pull request #5717
Opened 2021-12-16 15:31 UTC by gunnar-solo

* feat(proto): added clone_all interfaces to all proto objects
* excluded `health_check.proto` from generation process
* upgraded to solo-kit v0.24.2
* added test case to indicate difference in code generation (nil --> empty slice)

closes https://github.com/solo-io/gloo/issues/5620

* change test from FIt --> It

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2021-12-17 17:05 UTC, sam-heilbron requested changes
Let's remove the graphql.proto references

2021-12-20 19:29 UTC, gunnar-solo commented
/kick

2021-12-20 20:53 UTC, ben-taussig-solo approved these changes
LGTM!

2021-12-20 21:26 UTC, sam-heilbron commented
Not sure why codegen is still passing, but I see `graphql.proto.sk.md` is created. Can we remove that?

2021-12-20 21:30 UTC, gunnar-solo commented
it's probably the case that that particular autogenerated file type isn't removed explicitly when we do our cleaning operation.  Guessing it's leftover from when graphql _did_ have a proto file

it's since been deleted
...and the builds kicked again

2021-12-21 19:36 UTC, bewebi commented on Makefile
> -	go mod tidy
Why are we no longer tidying?

2021-12-21 19:45 UTC, bewebi reviewed
Looks good, just a couple of minor comments
Also, where does the extra `.` in the generated comments come from?

2021-12-21 19:45 UTC, bewebi commented on projects/gloo/api/external/envoy/api/v2/core/health_check.proto
> +// Who needs this anyway
Could we use a more specific justification comment?

2021-12-21 19:50 UTC, gunnar-solo commented on Makefile
> -	go mod tidy
largely because we no longer `tidy` on `master`

2021-12-21 19:51 UTC, gunnar-solo commented on Makefile
> -	go mod tidy
mmm.  looks like it was just [moved down](https://github.com/solo-io/gloo/commit/1ac616e99cdcf8f99c313d4703bfd5813edf89be#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R187)

2021-12-21 20:14 UTC, bewebi approved these changes

2021-12-21 20:50 UTC, bewebi approved these changes

2021-12-21 21:27 UTC, sam-heilbron approved these changes

2021-12-21 21:27 UTC, merged