add upgrade notice for graphql schema
solo-io/gloo pull request #5772
Opened 2022-01-11 14:36 UTC by saiskee

2022-01-11 14:38 UTC, sam-heilbron commented on docs/content/operations/upgrading/1.10.0.md
> +helm upgrade -n gloo-system gloo gloo/gloo --version=1.8.0
```suggestion
helm upgrade -n gloo-system gloo gloo/gloo --version=1.10.0
```

2022-01-11 14:38 UTC, saiskee commented
/skip-changelog /skip-ci

2022-01-11 14:38 UTC, sam-heilbron commented on docs/content/operations/upgrading/1.10.0.md
> +helm upgrade -n gloo-system glooe gloo/gloo-ee --version=1.8.0
```suggestion
helm upgrade -n gloo-system glooe gloo/gloo-ee --version=1.10.0
```

2022-01-11 14:40 UTC, bcollard commented on docs/content/operations/upgrading/1.10.0.md
> +kubectl apply -f gloo/crds/graphql_schema.yaml
kubectl apply -f gloo-ee/charts/gloo/crds/graphql_schema.yaml

2022-01-11 14:43 UTC, bcollard commented on docs/content/operations/upgrading/1.10.0.md
> +kubectl apply -f gloo/crds/graphql_schema.yaml
```suggestion
kubectl apply -f gloo-ee/charts/gloo/crds/graphql_schema.yaml
```

2022-01-11 14:45 UTC, artberger reviewed
Some doc comments. Thanks for adding this to the upgrade docs!

2022-01-11 14:45 UTC, artberger commented on docs/content/operations/upgrading/1.10.0.md
> +In v1.10.0, we introduced {{< protobuf name="graphql.gloo.solo.io.GraphQlSchema" display="The GraphQLSchema CRD">}}. This CRD will be automatically applied to your cluster when performing a `helm ins
```suggestion
Gloo Edge v1.10.0 introduces {{< protobuf name="graphql.gloo.solo.io.GraphQlSchema" display="The GraphQLSchema CRD">}}. This CRD is automatically applied to your cluster when performing a `helm install` operation.
```

2022-01-11 14:45 UTC, artberger commented on docs/content/operations/upgrading/1.10.0.md
> +However, these will not be applied when performing an upgrade. This is a [deliberate design choice](https://helm.sh/docs/topics/charts/#limitations-on-crds) on the part of the
```suggestion
However, the CRD is not be applied when performing an `helm upgrade` operation. This is a [deliberate design choice](https://helm.sh/docs/topics/charts/#limitations-on-crds) on the part of the
```

2022-01-11 14:45 UTC, artberger commented on docs/content/operations/upgrading/1.10.0.md
> +`helm upgrade`.
```suggestion
Helm maintainers, given the risk associated with changing CRDs. Given this limitation, you need to apply the new CRD to the cluster before upgrading.
```

2022-01-11 14:45 UTC, artberger commented on docs/content/operations/upgrading/1.10.0.md
> +[Gloo Edge GitHub repository](https://github.com/solo-io/gloo)
```suggestion
[Gloo Edge GitHub repository](https://github.com/solo-io/gloo).
```

2022-01-12 17:09 UTC, sam-heilbron commented
/kick (potential flake) https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=2ae522e9-cca1-4d87-9257-36deb08a1258. This flake exposed a bug that we are aware of and actively working to triage/resolve (cc @bewebi )

2022-01-12 17:10 UTC, sam-heilbron commented on docs/content/operations/upgrading/1.10.0.md
> +kubectl apply -f gloo/crds/graphql_schema.yaml
Since CRD validation was added, the name of the graphql CRD has changed. This needs to be updated to reflect that name

2022-01-12 17:11 UTC, sam-heilbron requested changes
CRD name has changed

2022-01-12 17:13 UTC, sam-heilbron commented on docs/content/operations/upgrading/1.10.0.md
> +kubectl apply -f gloo/crds/graphql_schema.yaml
Update: This CRD name change was not added to 1.10 so this is not a concern

2022-01-12 17:16 UTC, sam-heilbron commented
/skip-changelog docs only

2022-01-12 17:16 UTC, sam-heilbron approved these changes
LGTM

2022-01-12 17:17 UTC, saiskee commented
/skip-ci docs only

2022-01-12 17:17 UTC, merged