Doc fixes for week of 2/21/22
solo-io/gloo pull request #5982
Opened 2022-02-25 14:10 UTC by artberger

# Description

Doc fixes, version bumps, restoring gloo fed demo doc (https://github.com/solo-io/gloo/issues/4917)

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- N/A If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- N/A I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- N/A I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- N/A I have added tests that prove my fix is effective or that my feature works

2022-02-25 15:55 UTC, Rachael-Graham approved these changes

2022-02-25 19:36 UTC, saiskee commented
Hello docs team,
can you pull this fix into this PR?
https://github.com/solo-io/gloo/commit/77856fff159bf7ca2b9c571ac08959d1c73c76a8

2022-02-25 19:36 UTC, saiskee requested changes
pull this fix in? https://github.com/solo-io/gloo/commit/77856fff159bf7ca2b9c571ac08959d1c73c76a8

2022-02-28 22:09 UTC, kdorosh commented on docs/content/guides/traffic_management/request_processing/graphql/_index.md
> +   k apply -f - <<EOF
did we walk through this guide with the docs rendered and validate that this works with yaml whitespacing? I assume not, since `k` is not a valid command for most people, it should be `kubectl`

2022-02-28 22:10 UTC, kdorosh requested changes
we need to make sure the docs have been tested / validated when we have copy/pasteable content

2022-03-01 14:37 UTC, Rachael-Graham commented on docs/content/guides/traffic_management/request_processing/graphql/_index.md
> +   kubectl apply -f - <<EOF
@saiskee The previous image was for the bookinfo app, and all the subsequent steps in the section deal with using the Bookinfo app and its services - is there a specific reason we need to switch to petstore? If so the rest of this guide will need to be rewritten to use petstore instead

2022-03-01 16:40 UTC, saiskee commented on docs/content/guides/traffic_management/request_processing/graphql/_index.md
> +   kubectl apply -f - <<EOF
reverted in [e2a4bf2](https://github.com/solo-io/gloo/pull/5982/commits/e2a4bf204ee1fe8ab1dfcbc9715a4e1ce128c677). I meant to update the petstore application deployment, which I did in the same commit.

@kdorosh  Tested it locally.

2022-03-01 18:07 UTC, kdorosh submitted a review, later dismissed

2022-03-02 18:05 UTC, saiskee commented
/skip-ci

2022-03-02 18:05 UTC, merged