Fix discovery when multiple discoveries apply to a single upstream
solo-io/gloo pull request #5998
Opened 2022-03-01 21:09 UTC by saiskee

We recently introduced the fact that multiple discoveries could apply to a single upstream, for example grpc function discovery as well as grpc-graphql discovery. This exposed a bug where only the first function discovery will run for an upstream indefinitely.  

Solve this by creating a goroutine for each discovery that applies to an upstream.

2022-03-01 22:12 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +		}(discoveryForUpstream)
i think this will leak go-routines

see that this gets called by https://github.com/solo-io/gloo/blob/4043b34c5d780bba92860d0b3af61ac0ea556602/projects/discovery/pkg/fds/updater.go#L133-L138 , which runs when upstreams get added. we need to make sure we can cancel the old infinite loops and terminate those go-routines when new upstreams are added

2022-03-01 22:12 UTC, kdorosh requested changes
let's address potential go routine leak

2022-03-01 22:20 UTC, saiskee commented on projects/discovery/pkg/fds/updater.go
> +		}(discoveryForUpstream)
How is that goroutine you linked above being cleaned? Shouldn't it also leak given that `updater.Run()` runs indefinitely?

2022-03-01 22:21 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +		}(discoveryForUpstream)
I think it also leaks, but this makes it exponentially worse 😓

2022-03-01 22:44 UTC, saiskee commented on projects/discovery/pkg/fds/updater.go
> -		cancel()
Removed this cancel as now the go funcs / endless loops return when the context is cancelled.

2022-03-02 14:17 UTC, saiskee commented
/kick

2022-03-02 16:41 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +					return
let's debug/trace log when this happens

2022-03-02 16:45 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +			for {
let's add a comment to make it clearer that each discovery is responsible for sleeping itself so this isn't spammy (ideally in a configurable amount). a comment on the interface would be nice too

2022-03-02 16:49 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +			for {
also if none of the discoveries are valid then this is spammy and will run CPU hot (the original intent of 
```golang
go func() {
		updater.Run()
		cancel()
}
```
in `updater.go`.

let's make sure we sleep in the top-level loop at least a little if none of the discoveries were invoked

2022-03-02 16:50 UTC, kdorosh commented on projects/discovery/pkg/fds/discoveries/swagger/swagger.go
> +			return ctx.Err()
multierror here?

2022-03-02 16:50 UTC, kdorosh commented on projects/discovery/pkg/fds/discoveries/grpc/grpc.go
> +			return ctx.Err()
multierror?

2022-03-02 16:51 UTC, kdorosh commented on changelog/v1.11.0-beta15/fix-multiple-function-discoveries.yaml
> +      only one would run indefinitely.
can we add a unit test of some sort to ensure that this is now fixed?

2022-03-02 20:54 UTC, saiskee commented on projects/discovery/pkg/fds/updater.go
> +			for {
I'm settling for the design that top level loop sleeps, rather than delegating that to individual discoveries.

2022-03-02 21:18 UTC, saiskee commented
/kick

2022-03-02 21:30 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +			for {
@saiskee the old version still had configurable polling intervals per discovery. do we plan on removing that?

2022-03-02 21:34 UTC, saiskee commented on projects/discovery/pkg/fds/updater.go
> +			for {
those configurable polls are used in each discoveries exponential backoff, in the case where the discovery doesn't work due to network failure / pod blip. Those still exist.

2022-03-02 21:38 UTC, saiskee commented
added [test](https://github.com/solo-io/gloo/pull/5998/files?diff=split&w=0#diff-18bf42ff87b152088e791a3cfc56cd7cce902153a4e8c5b40289051272f829e1R174) to make sure that multiple discoveries run simultaneously and one doesn't block the other.

2022-03-02 21:50 UTC, kdorosh commented on projects/discovery/pkg/fds/updater.go
> +				time.Sleep(30 * time.Second)
looking over the code again, I was wrong, every implementer of `DetectFunctions` has a sleep so are fine to remove this (i think we should for responsiveness)

2022-03-02 21:53 UTC, kdorosh submitted a review, later dismissed

2022-03-03 14:52 UTC, kdorosh commented
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=a63c7bd8-ac38-4d2f-8756-ed34e08d360b

2022-03-03 14:52 UTC, kdorosh submitted a review, later dismissed

2022-03-03 18:23 UTC, kdorosh submitted a review, later dismissed

2022-03-03 20:42 UTC, saiskee commented
/kick

2022-03-04 16:14 UTC, saiskee commented
Looks like this is failing a legitamate test in build-bot

2022-03-08 18:55 UTC, saiskee commented
/kick

2022-03-09 16:28 UTC, kdorosh approved these changes

2022-03-09 16:28 UTC, merged