[wip] Rename GraphQLSchema CR to GraphQLApi
solo-io/gloo pull request #6083
Opened 2022-03-14 17:00 UTC by jenshu

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-03-14 23:54 UTC, jenshu commented on changelog/v1.11.0-beta21/graphql-rename.yaml
> +  - type: NON_USER_FACING
not sure of the type - non user facing? breaking?

2022-03-15 12:35 UTC, jenshu commented
/kick data race

2022-03-15 14:05 UTC, kdorosh reviewed
seems reasonable to me!

2022-03-15 14:05 UTC, kdorosh commented
/kick ssl e2e test flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=89162e79-f7b5-40d5-88e7-cfaf3b4ad3ae

perhaps @jenshu you can look into this flake while ci is running? I've seen a bunch of other PRs hit this as well

2022-03-15 14:06 UTC, kdorosh approved these changes

2022-03-15 14:23 UTC, saiskee requested changes

2022-03-15 14:23 UTC, saiskee commented on install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
> +    - ggqla
```suggestion
    - gql
    - gqls
```

2022-03-15 14:39 UTC, jenshu commented on install/helm/gloo/crds/graphql.gloo.solo.io_v1alpha1_GraphQLApi.yaml
> +    - ggqla
(spoke offline - changed to gql / ggql)

2022-03-15 16:44 UTC, jenshu commented
/kick

2022-03-15 17:46 UTC, merged