Add Custom PrecenseFilter to LDAP Auth
solo-io/gloo pull request #6208
Opened 2022-03-31 18:41 UTC by inFocus7

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-05 18:55 UTC, sam-heilbron requested changes
We'll need to add a changelog file to track this work. See https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog-files for examples, or previous PR for solutions.

2022-04-05 18:55 UTC, sam-heilbron commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    string searchFilter = 6;
can we make this proto field underscored_separated_named? (https://developers.google.com/protocol-buffers/docs/style#message_and_field_names)

2022-04-05 18:57 UTC, inFocus7 commented
> We'll need to add a changelog file to track this work. See https://github.com/solo-io/go-utils/tree/master/changelogutils#changelog-files for examples, or previous PR for solutions.
> 
> 
> 
> 

Yeah, was holding off since i wasn't sure which Gloo version this would/should be released for

2022-04-05 19:04 UTC, inFocus7 commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // Recommend using "(objectClass=*)"
I might just remove this recommendation since it could be confusing. This was originally a filter we used as a catch-all, but we were mistakenly(?) using _uid=*_ instead of _objectClass=*_ which LDAP recommends as a catch-all. 

I'll ask field eng. on their opinion as well, since _objectClass=*_ is recommended for this to act as a catch-all filter.

(Currently AFK but will provide docs when back)

2022-04-05 19:06 UTC, inFocus7 commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    string searchFilter = 6;
Good callout, will do 👍

2022-04-05 20:57 UTC, inFocus7 commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    string searchFilter = 6;
I just checked and remembered I was following the casing for the other LDAP fields. Would you know if there's a specific reason why the other fields are camelCased?

What's your opinion on using snake_case to follow protobuf conventions vs. camelCase to follow _this_ message's convention?
In my opinion, for _this_ specific case, camelCase would make more sense. It could cause confusion for users/customers if their LDAP config uses different conventions.

ex if using snake_case
```
  configs:
  - ldap:
      address: "ldap://ldap.default.svc.cluster.local:389" # Substitute your namespace for `default` here
      userDnTemplate: "uid=%s,ou=people,dc=solo,dc=io"
      allowedGroups:
      - "cn=managers,ou=groups,dc=solo,dc=io"
      search_filter: "(objectClass=*)"
```

2022-04-06 13:49 UTC, artberger commented on docs/content/guides/security/auth/extauth/ldap/_index.md
> +- `searchFilter`: The filter to use when searching for a member to, then, authorize.
I wasn't sure what the "then" meant; is there a next step? Is it a filter for a member or user entry (maybe they're the same thing?)
```suggestion
- `searchFilter`: The filter to use when searching for the user entry that you want to authorize.
```

2022-04-06 14:34 UTC, inFocus7 commented
/skip-changelog

2022-04-06 15:08 UTC, sam-heilbron commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    string searchFilter = 6;
Oh good point, and a fair question. I say we stick with the convention for this message to keep it consistent, and be on the lookout for future changes so that we can encourage best practices.

2022-04-06 15:09 UTC, sam-heilbron approved these changes

2022-04-06 17:45 UTC, inFocus7 commented
/skip-changelog

2022-04-06 18:02 UTC, inFocus7 commented
/kick flake #6237

2022-04-06 19:18 UTC, merged