Updated yaml with liveness config
solo-io/gloo pull request #6243
Opened 2022-04-05 17:43 UTC by Bslabe123

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-06 14:25 UTC, saiskee commented on .githooks/pre-commit
> +##if test -e /dev/tty ; then
I just `pip install python3` so this would work again

2022-04-06 18:59 UTC, Bslabe123 commented
/skip-changelog

2022-04-06 20:25 UTC, Bslabe123 commented
/kick

2022-04-07 13:25 UTC, Bslabe123 commented
/kick

2022-04-07 15:05 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            path: /readyz
Why this change? just curious.

2022-04-07 15:07 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            - {{ $spec.loopBackAddress }}:19000/live
I don't believe `/live` is a valid endpoint in the envoy admin endpoint, so I'm curious as to why we need to change this.

2022-04-07 15:08 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            path: /readyz
Unless we changed the readiness endpoint in envoy recently, I don't think this should change, and the liveness probe endpoint should be the same.

2022-04-07 15:09 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            path: /readyz
The old path was deprecated according to https://kubernetes.io/docs/reference/using-api/health-checks/

2022-04-07 15:19 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            - {{ $spec.loopBackAddress }}:19000/live
You were right about that one there's no `live` endpoint `server_info` would do just fine. Rolling this back

2022-04-07 15:46 UTC, kdorosh requested changes
looking for answer to question before merge

2022-04-07 15:46 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /readyz
what does this endpoint do? based on the name it seems wrong / dangerous to make this the liveness probe rather than a readiness probe

liveness probe should only detect stuck processes, nothing about readiness (e.g. valid configuration to serve traffic)

2022-04-07 15:49 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /readyz
Yep just fixed that one in the next commit it should be `/livez`

2022-04-07 15:55 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            path: /readyz
That doc is referring to the kubernetes apiserver. I believe here we are checking the readiness of the istio sidecar, so we shouldn't be changing this value unless istio says to.

2022-04-07 16:00 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /livez
Does istio sidecar expose a specific liveness endpoint? Where did we get this value from?

2022-04-07 16:01 UTC, saiskee commented on install/test/values/val_custom_istio_sidecar.yaml
> +            path: /readyz
We should not be changing this value unless explicitly stated as a change in the istio docs.

2022-04-07 16:10 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            path: /readyz
Ahh that makes sense. In that caseIm not aware of any changes to the api so ill roll it back.

2022-04-07 16:11 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /livez
Mistakenly from kubernetes apiserver docs, fixing now.

2022-04-07 16:15 UTC, Bslabe123 commented on install/test/values/val_custom_istio_sidecar.yaml
> +            path: /readyz
Correct, same reasons as above, rolling back

2022-04-07 16:54 UTC, kdorosh commented on install/test/helm_test.go
> +									Path:   "/gloo/health",
i think it's a bit misleading in the test here to have a gloo health check configured on the gateway proxy (envoy)

2022-04-07 17:08 UTC, Bslabe123 commented on install/test/helm_test.go
> +									Path:   "/gloo/health",
Both the /ready and /live endpoints would live in gloo/health/ though right? I moified the liveness probe check so that it matches with the readiness probe check right above this

2022-04-07 18:29 UTC, Bslabe123 commented
/kick

2022-04-07 23:50 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            failureThreshold: 30
this failure threshold default is too high; perhaps 3?

2022-04-07 23:51 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          failureThreshold: 10
across the board we should lower the failure threshold to 3 imo

2022-04-08 14:35 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            failureThreshold: 30
fixed

2022-04-08 14:35 UTC, Bslabe123 commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          failureThreshold: 10
fixed

2022-04-11 15:10 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /readyz
The doc you've referenced above is a kubernetes apiserver doc, and so I believe those endpoints are the health check endpoints for the the kubernetes apiserver, not our gateway-proxy deployment. I'm trying to look for documentation for envoy readiness / liveness endpoints / figure out where the previous contributor got this value from.

2022-04-11 15:23 UTC, nfuden commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +              path: /readyz
https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--ready
?

2022-04-11 15:28 UTC, saiskee requested changes

2022-04-11 15:28 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        livenessProbe:
Given this conversation: https://solo-io-corp.slack.com/archives/CHAC8587L/p1649690434388929?thread_ts=1649689450.078819&cid=CHAC8587L

I believe we should follow istio's practices and not configure a liveness probe on the sidecar. We can remove this config.

cc @nrjpoddar

2022-04-11 15:32 UTC, saiskee commented on install/test/helm_test.go
> +									Path:   "/gloo/health",
I believe this was correct previously. We can change the path here to `/server_info` and the port to `19000` for the admin port. For envoy docs for the liveness probe endpoint, see https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--server_info

2022-04-11 16:12 UTC, Bslabe123 commented on install/test/helm_test.go
> +									Path:   "/gloo/health",
Fixed these in the latest commit

2022-04-11 16:39 UTC, Bslabe123 commented
/kick

2022-04-12 18:54 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          failureThreshold: 3
let's make the liveness probe less trigger happy than the readiness probe by switching the failure threshold on both probes in this PR

2022-04-12 18:58 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          failureThreshold: 3
also, let's gate these default liveness probe with a helm value like `enabled` that defaults to false.

some users/customers will require the liveness probe for compliance, but a default liveness probe can also be bad form:

> liveness is generally considered bad form for bunch of reasons as it's really hard to signal that you're in a deadlock situtaion. In most other cases if you have a catastrophic failure you should exit and kubelet will restart irrrespective of liveness probe

2022-04-12 19:00 UTC, kdorosh commented on install/helm/gloo/templates/5-gateway-deployment.yaml
> +        livenessProbe:
same comment on gating with an enabled set to false, and switching the failure threshold with readiness probe

2022-04-12 19:01 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
>          livenessProbe:
let's gate the pre-existing liveness probe in the `enabled` field

2022-04-12 19:02 UTC, kdorosh reviewed
looks good overall, couple nits!

2022-04-13 15:33 UTC, Bslabe123 commented
/kick

2022-04-13 19:16 UTC, kdorosh commented on changelog/v1.12.0-beta4/liveness.yaml
> +    issueLink: https://github.com/solo-io/gloo/issues/5431
do we have the right issue linked here? this issue is only for the gloo pod

2022-04-13 19:18 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
>            failureThreshold: 10
let's make failure threshold on the readiness probes 3

2022-04-13 19:53 UTC, Bslabe123 commented on changelog/v1.12.0-beta4/liveness.yaml
> +    issueLink: https://github.com/solo-io/gloo/issues/5431
Just checked I dont think we have an open issue for putting liveness probes on anything other than gloo pods

2022-04-13 19:57 UTC, Bslabe123 commented on install/helm/gloo/templates/1-gloo-deployment.yaml
>            failureThreshold: 10
On it!

2022-04-14 15:58 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            port: {{ $spec.podTemplate.httpPort }}p
this looks like a typo at the end; also this looks duplicated from https://github.com/solo-io/gloo/pull/6291

i'm surprised this passed ci with the extra "p" at the end; we should probably consider adding an e2e test for sds

also this change should go outside the `{{- if $global.glooMtls.sdsResources }}` check (perhaps why it passed ci, since this likely never rendered)

2022-04-14 15:58 UTC, kdorosh requested changes
found some bugs in yaml rendering

2022-04-15 14:31 UTC, saiskee commented on projects/sds/cmd/main.go
> +	SdsServerAddress string `split_words:"true" default:"0.0.0.0:8234"` //sds_config target_uri in the envoy instance that it provides secrets to
This is necessary for the readiness probe to work. Kubernetes uses the pod IP for the readiness probe. We need to make sure that this accepts all IPs.

2022-04-15 16:38 UTC, kdorosh reviewed
lgtm, leaving last review to @saiskee

2022-04-15 16:38 UTC, kdorosh commented
very nice! 🚀

2022-04-15 16:44 UTC, saiskee commented on install/test/values/val_custom_istio_sidecar.yaml
> -          failureThreshold: 30
can we revert this change? I don't think it's necessary

2022-04-15 16:45 UTC, saiskee commented on install/test/helm_test.go
> -							InitialDelaySeconds: 1,
We can also revert these changes right?

2022-04-15 16:45 UTC, saiskee commented on install/test/helm_test.go
> -							PeriodSeconds:       10,
revert?

2022-04-15 16:45 UTC, saiskee commented on install/test/helm_test.go
> -							InitialDelaySeconds: 5,
revert?

2022-04-15 16:45 UTC, saiskee commented on install/test/helm_test.go
> -							PeriodSeconds:       10,
revert?

2022-04-15 16:46 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> -          periodSeconds: 10
revert?

2022-04-15 16:46 UTC, Bslabe123 commented on install/test/helm_test.go
> -							InitialDelaySeconds: 1,
This one I bumped to give the SDS a bit more time to startup and pass CI but I can revert if that works.

2022-04-15 18:09 UTC, Bslabe123 commented on install/test/helm_test.go
> -							InitialDelaySeconds: 1,
nvm fixed

2022-04-15 18:43 UTC, saiskee commented on install/helm/gloo/templates/5-gateway-deployment.yaml
> -          periodSeconds: 2
revert period seconds here?

2022-04-15 18:43 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +          failureThreshold: 3
revert?

2022-04-15 18:43 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +          failureThreshold: 3
revert

2022-04-15 18:43 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +          periodSeconds: 10
revert

2022-04-15 18:43 UTC, saiskee commented on install/test/helm_test.go
> +							FailureThreshold:    3,
revert this value

2022-04-15 18:44 UTC, saiskee commented on install/test/helm_test.go
> -          periodSeconds: 2
revert periodSeconds here

2022-04-15 18:44 UTC, saiskee commented on install/test/helm_test.go
> -							PeriodSeconds:       2,
revert the values here

2022-04-15 18:44 UTC, saiskee commented on install/test/helm_test.go
> -							PeriodSeconds:       2,
revert these values

2022-04-15 18:44 UTC, saiskee commented on projects/gloo/cli/pkg/cmd/install/knative_test_yaml.yaml
> -          failureThreshold: 10
revert this failureThreshold and the one below

2022-04-15 19:04 UTC, kdorosh commented
i think it does make sense to standardize on some reasonable values here @saiskee

2022-04-18 17:15 UTC, artberger reviewed
I left a couple questions and suggestions from a docs perspective (we're trying to move towards more of a sentence-style in the descriptions). Thanks!

2022-04-18 17:15 UTC, artberger commented on install/helm/gloo/generate/values.go
> +	LivenessProbeEnabled  *bool             `json:"livenessProbeEnabled,omitempty" desc:"Does gloo have a liveness probe (default false)"`
```suggestion
	LivenessProbeEnabled  *bool             `json:"livenessProbeEnabled,omitempty" desc:"Set to true to enable a liveness probe for Gloo Edge (default is false)."`
```

2022-04-18 17:15 UTC, artberger commented on install/helm/gloo/generate/values.go
> +	Probes                        *bool                 `json:"probes,omitempty" desc:"enable readiness probe and allow liveness probe to be enabled"`
```suggestion
	Probes                        *bool                 `json:"probes,omitempty" desc:"Set to true to enable a readiness probe (default is false). Then, you can also enable a liveness probe."`
```

2022-04-18 17:15 UTC, artberger commented on install/helm/gloo/generate/values.go
> +	LivenessProbeEnabled             *bool    `json:"livenessProbeEnabled,omitempty" desc:"Is liveness probe enabled on gateway (default false)"`
Does the Probes field also need to be set? If so, maybe include that.
```suggestion
	LivenessProbeEnabled             *bool    `json:"livenessProbeEnabled,omitempty" desc:"Set to true to enable a liveness probe for the gateway (default is false). You must also set the 'Probes' value to true."`
```

2022-04-18 17:15 UTC, artberger commented on install/helm/gloo/generate/values.go
> +	LivenessProbeEnabled          *bool                 `json:"livenessProbeEnabled,omitempty" desc:"enable liveness probe, Default is false"`
Is this for a different component than `gloo` or the gateway? If so, we might want to put that.
```suggestion
	LivenessProbeEnabled          *bool                 `json:"livenessProbeEnabled,omitempty" desc:"Set to true to enable a liveness probe (default is false)."`
```

2022-04-19 13:25 UTC, Bslabe123 commented
/kick

2022-04-19 14:33 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          initialDelaySeconds: 0
I think initial delay seconds should always be nonzero, probably 3 is preferable

2022-04-19 14:36 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
>  {{- end}}
nit; can we label these with comments as to what they end? the chart is starting to get confusing to reason about e.g. https://github.com/solo-io/gloo/blob/47bfe6a6fb46b9e7809c6b1405fc7ac6d171b62b/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L508

2022-04-19 14:44 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
>  {{- end}}
Yep! Added

2022-04-19 14:45 UTC, kdorosh commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +          name: probe
i know we use it for the probe but the port name should probably be a bit more descriptive about the service behind it
```suggestion
          name: validation
```

2022-04-19 14:47 UTC, kdorosh approved these changes
lgtm!

2022-04-19 14:48 UTC, saiskee approved these changes

2022-04-19 15:10 UTC, Bslabe123 commented
/kick

2022-04-19 15:24 UTC, Bslabe123 commented
/kick

2022-04-19 16:54 UTC, Bslabe123 commented
/kick

2022-04-19 17:07 UTC, Bslabe123 commented
/kick

2022-04-19 17:54 UTC, kdorosh approved these changes

2022-04-19 19:13 UTC, merged