Adding enableAddDatadogRoute parameter
solo-io/gloo pull request #6273
Opened 2022-04-07 21:43 UTC by DiegoLelis

# Description

Adds a new parameter on the helm chart that it will allow to enable/disable the datadog metrics endpoint, without disabling the Prometheus endpoint, this way will be possible to manage exposing both endpoints using the helm chart.

# Context

Users needed this feature to be able to use Datadog and Grafana + Prometheus at the same time without any manual step.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-07 22:07 UTC, DiegoLelis commented
Tested this and I'm currently using it on my installation of Gloo Enterprise + Gloo OSS

2022-04-07 23:11 UTC, jenshu reviewed
can you also run codegen:
```
make install-go-tools generated-code -B
```

2022-04-07 23:11 UTC, jenshu commented on install/helm/gloo/generate/values.go
> +	datadogPrefixRewrite    *string `json:"datadogPrefixRewrite,omitempty" desc:"The envoy stats endpoint to which the datadog metrics are written"`
```suggestion
	EnableAddDatadogRoute   *bool `json:"enableAddDatadogRoute,omitempty" desc:"Enables datadog (without disabling Prometheus) envoy stats endpoint to which the metrics are written|"`
	DatadogPrefixRewrite    *string `json:"datadogPrefixRewrite,omitempty" desc:"The envoy stats endpoint to which the datadog metrics are written"`
```
(capitalized the struct fields)

2022-04-12 19:07 UTC, kdorosh commented
/test

2022-04-12 19:20 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- end }}
I don't think we need to add these given that this is already supported via `$spec.podTemplate.extraAnnotations` and datadog is a very specific integration here. trying to avoid chart bloat

2022-04-12 19:21 UTC, kdorosh commented on install/helm/gloo/templates/9-gateway-proxy-configmap.yaml
> +                            {{ end }}
instead of these blocks, i think we can just update the previous admin port blocks to have this line be configurable: https://github.com/solo-io/gloo/blob/fc9ee65159baf0e1e601882c9637b2073ad0b86e/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml#L81

2022-04-12 19:21 UTC, kdorosh requested changes
i think we can make this more generic and the changeset smaller to support datadog

2022-04-12 21:02 UTC, nfuden commented
How do people feel about this version of it?: https://github.com/solo-io/gloo/pull/6306/files

2022-04-14 20:15 UTC, nfuden commented
Took the commits here and it merged as https://github.com/solo-io/gloo/pull/6306 
Functionality now exists.

Thanks so much for the issue and for the contributions.
Sorry that it took us so long to get a final version through!

2022-04-14 20:15 UTC, closed without merging