Added probe to SDS
solo-io/gloo pull request #6291
Opened 2022-04-11 14:39 UTC by Bslabe123

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-04-11 17:17 UTC, saiskee commented on changelog/v1.12.0-beta3/sds-readiness-probe.yaml
> +  - type: FIX
`NEW_FEATURE`?

2022-04-11 17:20 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            port: {{ .Values.gatewayProxies.gatewayProxy.XdsServicePort }}
```suggestion
            port: {{ $spec.xdsServicePort }}
```

2022-04-11 18:49 UTC, saiskee commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            port: {{ $spec.xdsServicePort }}
let's hardcode this to `8234` based on the port value [here](https://github.com/solo-io/gloo/blob/46aaa649da717f88c878742e21d7a7d2611c8e9d/projects/sds/cmd/main.go#L25)

2022-04-14 15:53 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            port: {{ $spec.podTemplate.httpPort }}
i think the http port here is for the envoy container https://github.com/solo-io/gloo/blob/e540ed56fa5481da47740d3e1b900a12ef812c83/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L196 not the sds container https://github.com/solo-io/gloo/blob/e540ed56fa5481da47740d3e1b900a12ef812c83/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L287

we should probably be using readiness on the sds container port instead: https://github.com/solo-io/gloo/blob/e540ed56fa5481da47740d3e1b900a12ef812c83/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L330-L332

2022-04-14 15:54 UTC, kdorosh requested changes
overall looks good, great job sorting out our complex helm charts!

just looking for one change to a probe; also lets update our helm tests to ensure these render correctly

2022-04-14 15:59 UTC, kdorosh commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            port: {{ $spec.podTemplate.httpPort }}
I think this isn't rendering, it should be moved out of the `{{ toYaml $global.glooMtls.sdsResources | indent 10}}` check

2022-04-15 16:43 UTC, closed without merging