Consul consistency mode: Allow for Stale Queries
solo-io/gloo pull request #6332
Opened 2022-04-18 04:30 UTC by jackstine

# Description

Added the consistency modes to both the Plugin Settings and to the Consul Api Options.

# Context

Users want to be able to have Stale Queries.  Right now they can only be consistent.

# Checklist:

- [X] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [X] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [X] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

2022-04-20 23:39 UTC, nfuden commented
needs code gen (namely doc gen and format portions of it)
 The build bot failure may be a flake but it is in the consul portion with a nil dereference so once codegenned version is pushed it will be interesting to see if build bot still fails.

2022-04-21 15:42 UTC, jackstine commented
LGTM, once it passes I will approve.

2022-04-21 18:45 UTC, nfuden requested changes
I think in general the idea here is solid. 
A few nits and questions that I think should be answered but otherwise nice.

2022-04-21 18:45 UTC, nfuden commented on projects/gloo/pkg/plugins/consul/eds.go
> +func GenerateConsulOptions(dataCenter string, cm glooConsul.UpstreamSpec_ConsulConsistencyModes) *consulapi.QueryOptions {
nit: since we are adding a new function can we put a comment that follows go paradigms? : https://go.dev/doc/effective_go#commentary

Also a nit but how would you feel about NewConsulOptions

2022-04-21 18:45 UTC, nfuden commented on projects/gloo/pkg/plugins/consul/plugin.go
> +	options := GenerateConsulOptions(dc, consulSpec.Consul.GetConsistencyMode())
what if consul is nil?

2022-04-21 18:45 UTC, nfuden commented on projects/gloo/pkg/upstreams/consul/consul_client.go
> +func GenerateConsulOptions(dataCenter string, cm v1.Settings_ConsulUpstreamDiscoveryConfiguration_ConsulConsistencyModes) *consulapi.QueryOptions {
how is this exported function different from the one in eds?
Is there a valid reason for this to be duplicated here? Go is happier to repeat things to keep them closer in general so I am not entirely against this but did we at least consider if there was a better location for this?

2022-04-21 18:45 UTC, nfuden commented on projects/gloo/pkg/bootstrap/utils.go
> +var DefaultQueryOptions = &consulapi.QueryOptions{RequireConsistent: true, AllowStale: false}
Might as well comment this exported function

2022-04-21 18:45 UTC, nfuden commented on projects/gloo/pkg/plugins/consul/eds.go
> +				consulUpstream := arrayOfConsulUpstreams[0]
why do we only respect the consistency mode for the first upstream? Add a comment to disambiguate?

2022-04-21 18:53 UTC, jackstine commented on projects/gloo/pkg/plugins/consul/eds.go
> +				consulUpstream := arrayOfConsulUpstreams[0]
Read line 48

2022-04-21 18:54 UTC, jackstine commented on projects/gloo/pkg/plugins/consul/eds.go
> +				consulUpstream := arrayOfConsulUpstreams[0]
I suppose an added comment can be added here as well

2022-04-21 18:59 UTC, jackstine commented on projects/gloo/pkg/upstreams/consul/consul_client.go
> +func GenerateConsulOptions(dataCenter string, cm v1.Settings_ConsulUpstreamDiscoveryConfiguration_ConsulConsistencyModes) *consulapi.QueryOptions {
I tried to import GenerateConsulOptions but ran into a conflict.  But I do agree.  Also is there a way to resolve the issue of duplicity within the protocs?  Here projects/gloo/api/v1/settings.proto and projects/gloo/api/v1/options/consul/consul.proto.  I'd be interested in knowing what the syntax for this is.

2022-04-21 19:43 UTC, inFocus7 commented on projects/gloo/pkg/plugins/consul/eds.go
> +				consulUpstream := arrayOfConsulUpstreams[0]
@jackstine provided me with insight on this and I updated the ticket with a comment (pushing PR soon). There's comments from Marco above where he states there should be only one upstream per consul service name.

2022-04-21 19:43 UTC, inFocus7 commented on projects/gloo/pkg/plugins/consul/eds.go
> +func GenerateConsulOptions(dataCenter string, cm glooConsul.UpstreamSpec_ConsulConsistencyModes) *consulapi.QueryOptions {
Sounds good! I changed it to `NewConsulQueryOptions`, since Consul Options is vague. (pushing PR soon)

2022-04-21 19:46 UTC, jackstine commented on projects/gloo/pkg/plugins/consul/eds.go
>  				services, _, err := client.Service(svc.Name, "", queryOpts.WithContext(ctx))
if `serviceToUpstream[serviceName]`is of `length > 0`.  Then you would need to have a go routine for each upstream in `arrayOfConsulUpstreams`.

2022-04-21 19:47 UTC, jackstine commented on projects/gloo/pkg/plugins/consul/eds.go
>  				services, _, err := client.Service(svc.Name, "", queryOpts.WithContext(ctx))
that is not the case though, from Marco's comment on line 38.

2022-04-21 20:14 UTC, inFocus7 commented on projects/gloo/pkg/plugins/consul/plugin.go
> +	options := GenerateConsulOptions(dc, consulSpec.Consul.GetConsistencyMode())
In previous lines there's
```
	if len(spec.GetDataCenters()) > 0 {
		dc = spec.GetDataCenters()[0]
	}
```
where spec == Consul. It looks like this hasn't been an issue before, (it _might_ be impossible for this function to have a nil Consul).

I changed the code to be `spec.GetConsistencyMode()` and match the other code.

2022-04-21 20:27 UTC, nfuden commented on projects/gloo/pkg/plugins/consul/eds.go
>  				services, _, err := client.Service(svc.Name, "", queryOpts.WithContext(ctx))
👍

2022-04-21 20:27 UTC, nfuden commented on projects/gloo/pkg/plugins/consul/eds.go
> +				consulUpstream := arrayOfConsulUpstreams[0]
👍 I like it. I coulda dug farther. The file def has the right answers! Thanks!

2022-04-21 21:09 UTC, nfuden commented on projects/gloo/pkg/upstreams/consul/consul_client.go
> +func GenerateConsulOptions(dataCenter string, cm v1.Settings_ConsulUpstreamDiscoveryConfiguration_ConsulConsistencyModes) *consulapi.QueryOptions {
Ah gotcha so the difference here is the subcalls which have specific proto things.
Makes sense to me now.

2022-04-21 21:10 UTC, nfuden approved these changes

2022-04-21 21:10 UTC, merged