[wip] helm custom resources
solo-io/gloo pull request #6548
Opened 2022-06-09 18:08 UTC by jenshu

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-06-27 14:25 UTC, jenshu commented
/kick csrf

2022-06-29 10:24 UTC, jenshu commented
/kick csrf

2022-06-30 16:06 UTC, gunnar-solo requested changes

2022-06-30 16:29 UTC, jenshu commented on install/helm/gloo/templates/5-resource-cleanup-job.yaml
> +            kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io gloo-gateway-validation-webhook-{{ .Release.Namespace }} || exit $?
without it, the job was silently failing and not retrying. but let me double check this with the latest changes and make sure that's still the case

2022-06-30 16:36 UTC, jenshu commented on install/test/helm_test.go
> -          - name: client-ip-reject
before, the Gateways were included as a helm template and this test would unmarshal the rendered helm template into a Gateway and check that the Gateway was equivalent to the expected value. Now the Gateway yaml is only included as part of the command of the gloo-resource-rollout job (where it calls kubectl apply) so I'm just checking if this Gateway yaml appears as a substring anywhere in the job command text...so the spacing has to match exactly. Let me look into whether it's feasible to parse the text of the job command and unmarshal those into gateways

2022-06-30 20:03 UTC, jenshu commented on test/kube2e/helm/helm_test.go
> +	time.Sleep(time.Second * 5)
the problem this is trying to solve is that that the newly applied CRDs are not ready before we do 'helm upgrade'. i preferred not to use Sleep, but this went through a few iterations that each had issues. 
1. at first we passed in `--disable-openapi-validation` to helm upgrade as a workaround to just ignore the errors with the new CRDs not being ready
2. next after applying the CRDs, tried `kubectl wait --for condition=established` for each CRD to become ready, but this didn't work because the previously existing CRDs were still there and would show as ready
3. tried deleting the CRDs first, and then applying them. this seemed to be working and was what was being done prior to this current PR
4. as part of this PR's changes, we are ensuring that custom resources (Gateways, Upstreams) don't get deleted during the helm upgrade. Since deleting CRDs causes the CRs to be deleted too, we can no longer use this workaround in the tests. For now the best I can do is just Sleep for a bit to wait for the CRDs to become ready.

any other options I may be missing?

2022-06-30 20:11 UTC, jenshu commented on install/test/helm_test.go
> -          - name: client-ip-reject
> Let me look into whether it's feasible to parse the text of the job command and unmarshal those into gateways

i think it will be too much of a refactor, mind if we punt on this?

2022-06-30 23:58 UTC, jenshu commented on install/helm/gloo/templates/5-resource-cleanup-job.yaml
> +            kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io gloo-gateway-validation-webhook-{{ .Release.Namespace }} || exit $?
yeah, without the `|| exit $?`, the job runs through to the end even if there are errors. looks like it retries if the last command happens to fail. but if a command further up fails, it gets swallowed

2022-07-01 02:16 UTC, jenshu commented on test/kube2e/helm/helm_test.go
> +					// we can successfully upgrade from the helm hook release to the current release.
added in cf87e35

2022-07-01 02:16 UTC, jenshu commented on install/test/helm_test.go
> +						Expect(job.Spec.Template.Spec.Containers[0].Command[2]).NotTo(ContainSubstring("name: " + defaults.GatewayProxyName))
added in cf87e35

2022-07-01 11:19 UTC, gunnar-solo commented on test/kube2e/helm/helm_test.go
> +	time.Sleep(time.Second * 5)
nothing springs to mind, immediately.  Let's watch tests (over the next few weeks) as this goes is

2022-07-01 11:19 UTC, gunnar-solo commented on install/test/helm_test.go
> -          - name: client-ip-reject
no worries!

2022-07-01 11:20 UTC, gunnar-solo approved these changes

2022-07-01 11:23 UTC, merged