Parametrize the gateway proxy sidecar image
solo-io/gloo pull request #6651
Opened 2022-06-28 12:07 UTC by rinormaloku

# Description

Currently, installing Gloo Edge with Istio doesn't work as the istio-proxy is a very old image. 1.9.5.

This parametrizes the image so that users can self-define the version of istio when deploying with helm.

Fixes https://github.com/solo-io/gloo/issues/4152

2022-06-28 14:35 UTC, jenshu requested changes

2022-06-28 14:42 UTC, nfuden commented on install/helm/gloo/generate/values.go
> +	EnvoySidecarImage     *string               `json:"envoySidecarImage,omitempty" desc:"Sets the Istio-proxy container image to use for mTLS"`
Oof that's is a good point given the scope where this is placed

2022-06-28 15:54 UTC, rinormaloku commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        image: {{ $global.glooMtls.envoySidecarImage }}
What is the idea of the global image? If it is about gloo edge, then there is no correlation with the global image.

2022-06-28 22:03 UTC, jenshu commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        image: {{ $global.glooMtls.envoySidecarImage }}
it has defaults for some fields in case you don't provide them here. probably the only relevant one for defaulting is the `pullPolicy` since you will be overriding the registry

2022-06-30 15:27 UTC, rinormaloku commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        image: {{ $global.glooMtls.envoySidecarImage }}
I updated the code according to your suggestion. Thanks for the information, Jen!

2022-07-01 01:45 UTC, jenshu commented on install/helm/gloo/generate/values.go
> +	EnvoySidecarImage     *Image                `json:"envoySidecarImage,omitempty" desc:"Istio-proxy image to use for mTLS"`
for the existing `EnvoySidecarContainer` above, it's used in the gloo deployment in the `envoy-sidecar` container.

how about to mirror that, we can name this new field IstioProxy
```suggestion
	IstioProxy     IstioProxyContainer               `json:"istioProxy,omitempty" desc:"Istio-proxy container"`
```
and define container:
```
type IstioProxyContainer struct {
	Image *Image `json:"image,omitempty" desc:"Istio-proxy image to use for mTLS"`
}
```

2022-07-01 01:51 UTC, jenshu commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        image: {{ template "gloo.image" $istioProxyImage }}
on line 434 there's a hardcoded `imagePullPolicy`. we should use the `$istioProxyImage.pullPolicy`. can you also move the field up here to be right after `image`?

2022-07-01 08:05 UTC, rinormaloku commented on install/helm/gloo/generate/values.go
> +	EnvoySidecarImage     *Image                `json:"envoySidecarImage,omitempty" desc:"Istio-proxy image to use for mTLS"`
@jenshu I updated the code according to your suggestion. However, I am not sure if you have seen my comment about the previous naming:

> it was dictated to me by the existing property https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L354-L356

With this update for someone to configure the istio-proxy container resources he would have to use the property: `envoySidecarResources` and to configure the image he'd have to use the `istioProxy.image`. Which are two different names envoy and istio proxy, while we mean istio-proxy in both cases.

2022-07-01 11:43 UTC, jenshu commented on install/helm/gloo/generate/values.go
> +	EnvoySidecarImage     *Image                `json:"envoySidecarImage,omitempty" desc:"Istio-proxy image to use for mTLS"`
hmm, i think it's ok to keep the naming we have. in the gloo deployment, the envoySidecarResources is used under the `envoy-sidecar` container and the image uses `global.glooMtls.envoy.image`.
for this new one, i think `istioProxy.image` works because it matches the container name. it happens to reuse the envoySidecarResources value but i think that's ok. if we rename the envoySidecarResources in gateway-proxy-deployment, the user will have to define the resources in 2 places

2022-07-01 11:55 UTC, rinormaloku commented on install/helm/gloo/generate/values.go
> +	EnvoySidecarImage     *Image                `json:"envoySidecarImage,omitempty" desc:"Istio-proxy image to use for mTLS"`
Sounds good to me!

2022-07-01 15:59 UTC, jenshu commented
/kick

2022-07-01 16:20 UTC, jenshu approved these changes

2022-07-01 16:37 UTC, merged