Fix/cache max sizes
solo-io/gloo pull request #6794
Opened 2022-07-24 12:54 UTC by nfuden

Allow for max sizing to be applied to the cleaner portion of the filter.

2022-07-24 15:12 UTC, sam-heilbron requested changes
The key used in the settings need to be cachingServer to match the API. Can we add a test to verify that passing in the appropriate value would result in yaml that fits the Settings API?

2022-07-24 15:12 UTC, sam-heilbron commented on changelog/v1.12.0-rc3/fix-caching-custom-layer-bytes.yaml
> +    description: Cache max size configurable on custom layer in addition to top layer
nit: When you say "custom layer as opposed to top layer", are you referring to being configured at the listener level as opposed to the global level?

2022-07-24 15:12 UTC, sam-heilbron commented on projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto
> +  // Max payload size to cache. This may be set to protect against large
Is this the internal API for the Envoy filter? What does this value default to if no size is provided?

2022-07-24 15:12 UTC, sam-heilbron commented on install/helm/gloo/templates/18-settings.yaml
> +  caching:
The settings proto uses a different key `caching_server`: https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/settings.proto#L379

2022-07-24 15:18 UTC, nfuden commented on projects/gloo/api/external/envoy/extensions/cache/grpc/config.proto
> +  // Max payload size to cache. This may be set to protect against large
This is the internal api for our custom filter. Sets to 0 if not set but we handle that in our enterprise code.

2022-07-24 15:21 UTC, nfuden commented on changelog/v1.12.0-rc3/fix-caching-custom-layer-bytes.yaml
> +    description: Cache max size configurable on custom layer in addition to top layer
Nope upstream introduced a custom maxbytes setup in their filter which we were previously applying our custom maxbytes to but we have a cleaner implementation at the grpc filter level that we would like to use.

2022-07-24 15:22 UTC, nfuden commented on install/helm/gloo/templates/18-settings.yaml
> +  caching:
Good point, was testing it with the replace in helm rather than testing the boot post. Changing

2022-07-24 15:31 UTC, sam-heilbron commented on changelog/v1.12.0-rc3/fix-caching-custom-layer-bytes.yaml
> +    description: Cache max size configurable on custom layer in addition to top layer
Makes sense! I think I read that as a user and am slightly confused about the user facing implications. It seems this is a non user facing change though?

2022-07-25 17:23 UTC, nfuden commented on changelog/v1.12.0-rc3/fix-caching-custom-layer-bytes.yaml
> +    description: Cache max size configurable on custom layer in addition to top layer
Good call ou!

2022-07-25 18:29 UTC, sam-heilbron approved these changes
LGTM

2022-07-25 18:59 UTC, merged