LDAP Proto
solo-io/gloo pull request #6800
Opened 2022-07-25 19:19 UTC by Bslabe123

# Description

Added a flag to allow LDAP auth without group checking

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-07-25 19:24 UTC, Bslabe123 commented
/kick

2022-07-25 19:41 UTC, Bslabe123 commented
/kick

2022-07-29 16:07 UTC, sam-heilbron requested changes

2022-07-29 16:07 UTC, sam-heilbron commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    bool DisableGroupChecking = 7;
Can you check out the recommended style guide for protocol buffers: https://developers.google.com/protocol-buffers/docs/style#message_and_field_names and update accordingly?

2022-07-29 16:07 UTC, sam-heilbron commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    //Sometimes, it's enough to check for the user credentials so this flag disables group checking
How does this field work in conjunction with allowedGroups? (which one will win if both are defined)?

if you disable group checking, what is the reason for it? 

nit: Instead of saying "sometimes it's enough to check for user credentials",I think we can be explicit and say something along the lines of "disables group checking...the membership attribute of the user entry is not validated" or something to that affect for consistent terminology across the API.

2022-07-29 16:07 UTC, sam-heilbron commented on changelog/v1.12.0-rc6/ldap.yaml
> +  - type: NEW_FEATURE
This is an enterprise only feature. Since this is just the API change, I tend to make it non-user-facing and then the enteprirse changelog outlines the change and the exact field that is being added. That way we don't have "new features" listed in the open source repo that aren't available to open source users.

2022-08-01 13:22 UTC, Rachael-Graham commented on projects/gloo/pkg/api/v1/enterprise/options/extauth/v1/extauth.pb.go
> +	// Group checking is enabled by default
```suggestion
	// Disables group checking, regardless of the value for allowedGroups,
	// and disables validation for the membership attribute of the user entry.
	// Group checking is enabled by default.
```

2022-08-02 19:04 UTC, Bslabe123 commented
/kick

2022-08-03 14:58 UTC, Bslabe123 commented
/kick

2022-08-03 16:36 UTC, merged