Trivy scan gateway images fix
solo-io/gloo pull request #7015
Opened 2022-08-23 17:13 UTC by Bslabe123

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-08-23 18:32 UTC, sam-heilbron commented on docs/cmd/generate_docs.go
> +					"<v1.12.0, >=v1.6.0": OpenSourceImages(true),
Since we only scan images for versions 1.8 and above, I think we can get rid of the ">=1.6.0" constraint

2022-08-23 18:32 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func OpenSourceImages(before11 bool) []string {
should this be before 1.12? Was it 1.12 where the gateway was removed?

2022-08-23 18:32 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
>  	return append([]string{"rate-limit-ee", "gloo-ee", "gloo-ee-envoy-wrapper", "observability-ee", "extauth-ee"}, extraImages...)
I think recently, we added a `discovery-ee` and `caching-ee` image. Can we add those (and any others I may have missed) to the set of images we scan and include in our docs?

2022-08-23 18:40 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func OpenSourceImages(before11 bool) []string {
Yep was using before inclusively, before12 would be better, fixing

2022-08-23 18:43 UTC, Bslabe123 commented on docs/cmd/generate_docs.go
> +					"<v1.12.0, >=v1.6.0": OpenSourceImages(true),
Figured we were keeping it for a customer but fixed!

2022-08-23 18:47 UTC, Bslabe123 commented
/kick

2022-08-23 20:23 UTC, sam-heilbron requested changes
I think we need to only scan discovery-ee and caching-ee for certain versions of GlooEE.

Can we add steps in the PR that outline how you tested these changes and how a reviewer could do the same?

2022-08-23 20:23 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	return append([]string{"rate-limit-ee", "gloo-ee", "gloo-ee-envoy-wrapper", "observability-ee", "extauth-ee", "discovery-ee", "caching-ee"}, extraImages...)
This list is the set of images that are present in glooEE after 1.7. I think we need more logic to gate certain images which were introduced in later versions

2022-08-23 20:23 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	hasFedVersion, _ := semver.Compare("1.12.0")
Why is this necessary? Were there Fed changes around 1.12?

2022-08-23 21:12 UTC, jenshu commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	return []string{"access-logger", "certgen", "discovery", "gloo", "gloo-envoy-wrapper", "ingress", "sds"}
can we also add `kubectl` to both of these lists (kubectl is only 1.11.x and later)

2022-08-23 21:13 UTC, jenshu commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	return []string{"access-logger", "certgen", "discovery", "gloo", "gloo-envoy-wrapper", "ingress", "sds"}
is there also perhaps a dynamic way we can find the list of images for a certain release?

2022-08-24 13:12 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	hasFedVersion, _ := semver.Compare("1.12.0")
Misread what this function was doing, reverted

2022-08-24 14:26 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	return append([]string{"rate-limit-ee", "gloo-ee", "gloo-ee-envoy-wrapper", "observability-ee", "extauth-ee", "discovery-ee", "caching-ee"}, extraImages...)
Finishing up a bit of retyping these headers to be a bit more futureproof

2022-08-24 15:07 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	return []string{"access-logger", "certgen", "discovery", "gloo", "gloo-envoy-wrapper", "ingress", "sds"}
Might be an option! Where are we pulling the images from?

2022-08-24 17:21 UTC, Bslabe123 commented
/kick

2022-08-24 19:02 UTC, Bslabe123 commented
/kick

2022-08-25 18:15 UTC, Bslabe123 commented
/kick

2022-08-25 18:20 UTC, Bslabe123 commented
/kick

2022-08-25 18:28 UTC, Bslabe123 commented
/kick Step #12 - "docker-push-extended": cp projects/discovery/cmd/Dockerfile /workspace/gloo/_output/projects/discovery/Dockerfile.discovery
Step #12 - "docker-push-extended": docker build /workspace/gloo/_output/projects/discovery -f /workspace/gloo/_output/projects/discovery/Dockerfile.discovery \
Step #12 - "docker-push-extended": 	--build-arg GOARCH=amd64 \
Step #12 - "docker-push-extended": 	-t quay.io/solo-io/discovery:.1.13.0-beta8-7015 
Step #12 - "docker-push-extended": invalid argument "quay.io/solo-io/discovery:.1.13.0-beta8-7015" for "-t, --tag" flag: invalid reference format
Step #12 - "docker-push-extended": See 'docker build --help'.
Step #12 - "docker-push-extended": make[1]: *** [Makefile:362: discovery-docker] Error 125
Step #12 - "docker-push-extended": make[1]: Leaving directory '/workspace/gloo'
Step #12 - "docker-push-extended": >> Temporary output file /tmp/tmp.Eh0hvrqpgG
Step #12 - "docker-push-extended": >> Removing /tmp/tmp.Eh0hvrqpgG
Step #12 - "docker-push-extended": make: *** [Makefile:678: docker-push-extended] Error 2
Finished Step #12 - "docker-push-extended"

2022-08-25 19:45 UTC, jackstine commented on docs/cmd/generate_docs.go
> +					"<v1.11.28, >=v1.8.0":  OpenSourceImages(version.MustParseSemantic("1.8.0")),   //extra images: [gateway]
how often do we intend to change this file, should we consider using a config file that manages all the semver values for each image?

2022-08-25 19:48 UTC, Bslabe123 commented on docs/cmd/generate_docs.go
> +					"<v1.11.28, >=v1.8.0":  OpenSourceImages(version.MustParseSemantic("1.8.0")),   //extra images: [gateway]
I haven't heard of anyone needing to change it but how often do we add new images to backports?

2022-08-25 20:35 UTC, jenshu commented on docs/cmd/generate_docs.go
> +					"<v1.11.28, >=v1.8.0":  OpenSourceImages(version.MustParseSemantic("1.8.0")),   //extra images: [gateway]
spoke offline - @Bslabe123 is going to see if it's feasible to dynamically get the images for a version using the helm chart

2022-08-26 15:03 UTC, Bslabe123 commented on docs/cmd/generate_docs.go
> +					"<v1.11.28, >=v1.8.0":  OpenSourceImages(version.MustParseSemantic("1.8.0")),   //extra images: [gateway]
Moved to separate issue as per parking lot

2022-08-26 15:16 UTC, nfuden commented on changelog/v1.13.0-beta10/gateway-trivy-scan.yaml
> +    issueLink: https://github.com/solo-io/gloo/issues/4006
Lets link this to the salient issue

2022-08-26 15:19 UTC, nfuden commented on docs/cmd/securityscanutils/securityscan_utils.go
> +	if kubectlTwelve || kubectlEleven {
what about our beta images?

2022-08-26 16:07 UTC, Bslabe123 commented
/kick

2022-08-26 19:13 UTC, sam-heilbron reviewed
There are a few missing pieces to ensure that we are running scans for the appropriate versions. Can you include in the PR description and outline of how you ran the job locally to verify that we are scanning the appropriate images now and how a reviewer could confirm that?

2022-08-26 19:13 UTC, sam-heilbron commented on docs/cmd/generate_docs.go
> +					">=v1.12.3":            OpenSourceImages(version.MustParseSemantic("1.12.3")),  //extra images: [kubectl]
nit: Having image names in the list that we don't actually have released images for (ie gateway) isn't the worst, because we have logic to say if we kind find the image in quay, just ignore and continue the job. We could simplify this logic to just say :
prep 1.12 include gateway
1.12 and later, exclude gateway and include kubectl

I think that would simplify this logic alot

2022-08-26 19:13 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +
Listed a comment above, but I think we can simplify this to say: exclude gateway after 1.12 and include kubectl after 1.12.

2022-08-26 19:13 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func EnterpriseImages(semver *version.Version) []string {
This function is used in the configuration we send to the trivy scan job. Don't we need to add more configuration to support the ImagesPerVersion config which right now only defines 1.7 and up?

2022-08-26 19:13 UTC, sam-heilbron commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func printImageReportGloo(semver *version.Version) error {
These functions are used to output the results of the scans to our docs. We increased the minimum version of our scans to 1.9. Can we also update the minimum version that we write to our docs to 1.9?

2022-08-26 19:23 UTC, Bslabe123 commented on changelog/v1.13.0-beta9/gateway-trivy-scan.yaml
> +    issueLink: https://github.com/solo-io/gloo/issues/4006
Yep thats the old issue, fixed

2022-08-26 19:30 UTC, Bslabe123 commented on docs/cmd/generate_docs.go
> +					">=v1.12.3":            OpenSourceImages(version.MustParseSemantic("1.12.3")),  //extra images: [kubectl]
I sort of have that here, the issue is that kubectl exists on certain patch versions of 1.11 and 1.12 so thats what the extra logic here is for 
```
	images := []string{"access-logger", "certgen", "discovery", "gloo", "gloo-envoy-wrapper", "ingress", "sds"}

	kubectlThirteen := semver.Minor() == 13
	kubectlTwelve := semver.Minor() == 12 && semver.AtLeast(version.MustParseSemantic("1.12.3"))
	kubectlEleven := semver.Minor() == 11 && semver.AtLeast(version.MustParseSemantic("1.11.28"))
	if kubectlThirteen || kubectlTwelve || kubectlEleven {
		images = append(images, "kubectl")
	}
	if semver.LessThan(version.MustParseSemantic("1.12.0")) {
		images = append(images, "gateway")
	}
	return images
```

2022-08-26 19:40 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func printImageReportGloo(semver *version.Version) error {
Added!

2022-08-26 19:41 UTC, Bslabe123 commented on docs/cmd/securityscanutils/securityscan_utils.go
> +func EnterpriseImages(semver *version.Version) []string {
But do we scan any enterprise images below 1.7? Also this function is relatively unchanged minus the types

2022-08-29 15:15 UTC, Bslabe123 commented
/kick

2022-08-30 13:14 UTC, Bslabe123 commented
/kick

2022-08-30 14:24 UTC, sam-heilbron approved these changes

2022-08-30 14:25 UTC, merged