fixes #5961 disable strict response headers to allow websocket connections
solo-io/gloo pull request #7028
Opened 2022-08-25 10:01 UTC by Paschi28

# Description

This pr fixes #5961 by adding the config line to disable require_strict_1xx_and_204_response_headers by default. 
The disabling is necessary to connect websocket connections through the gateway .

# Context

Users ran into this bug doing websocket connections e.g. SignalR.

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-08-25 10:02 UTC, Paschi28 commented
Hi @rinormaloku,
could you please have a look.

2022-08-25 10:53 UTC, rinormaloku commented
The change is correct.
@kdorosh can you please review this change

2022-08-25 20:42 UTC, kdorosh commented on install/helm/gloo/templates/12-ingress-proxy-configmap.yaml
> +          envoy.reloadable_features.require_strict_1xx_and_204_response_headers: false
this is not compliant with the HTTP spec and has been disabled since envoy 1.22 https://github.com/projectcontour/contour/issues/4458#issuecomment-1111217672

i think we should add something like this to the other configmaps as an escape hatch for clients that aren't spec compliant https://github.com/solo-io/gloo/blob/df2dc06df85dd5e030ba6f5d53c1d666926ce6d1/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml#L30-L32

but we should not allow all clients to make spec non-compliant requests

2022-08-25 20:43 UTC, kdorosh requested changes
let's do a simpler helm change as an escape hatch rather than allow non spec-compliant clients (including istio) by default

2022-08-26 12:18 UTC, Paschi28 commented
I figured out, that the needed change is possible using the helm spec `gloo.gatewayProxies.gatewayProxy.customStaticLayer`

2022-08-26 12:18 UTC, closed without merging