Consul EDS Blocking Queries
solo-io/gloo pull request #7033
Opened 2022-08-25 18:16 UTC by kdorosh

# Description

Consul EDS discovery query mode is now configurable (blocking vs non-blocking consul queries) via `eds_blocking_queries` on the Gloo `Settings`. The default remains the same (non-blocking queries) becuase this is more performant with cache hits on the consul agent (caching also enabled by default) but can be more performant when caching is disabled since blocking queries should result in fewer network calls.

# Context

Adding features to improve performance with consul at scale.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-08-25 18:20 UTC, kdorosh commented on test/e2e/consul_test.go
> +	Context("with envoy and gloo", func() {
note for reviewer; this PR adds one more e2e test at the end of the file, the rest of the diff is caused by moving the existing tests into this new `Context` for "with envoy and gloo"

2022-08-25 20:16 UTC, kdorosh commented
/kick should work with ssl flake https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=ac256f82-c2fe-4cce-b789-4ea7c42f6aa3

2022-08-25 20:25 UTC, kdorosh commented on test/e2e/consul_test.go
> +	Context("with envoy and gloo", func() {
also the EDS e2e test was rewritten to run both with blocking and non-blocking eds queries

2022-08-25 20:52 UTC, kdorosh commented
/kick flake? https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=3f6f857f-170a-48f3-b317-bcc2eceff8f3

2022-08-26 16:37 UTC, ianmacclancy requested changes

2022-08-26 16:37 UTC, ianmacclancy commented on projects/gloo/pkg/plugins/aws/ec2/eds.go
> +func (p *plugin) WatchEndpoints(writeNamespace string, unfilteredUpstreams v1.UpstreamList, opts clients.WatchOpts, settings *v1.Settings) (<-chan v1.EndpointList, <-chan error, error) {
Settings is taken as a parameter but not used, there is also no need to take in settings as a parameter as the plugin has the settings if init is correctly run. you can access them through p.settings

2022-08-26 16:37 UTC, ianmacclancy commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +func (p *plugin) WatchEndpoints(writeNamespace string, upstreamsToTrack v1.UpstreamList, opts clients.WatchOpts, settings *v1.Settings) (<-chan v1.EndpointList, <-chan error, error) {
Same comment as above - 

Settings is taken as a parameter but not used, there is also no need to take in settings as a parameter as the plugin has the settings if init is correctly run. you can access them through p.settings

2022-08-26 16:58 UTC, kdorosh commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +func (p *plugin) WatchEndpoints(writeNamespace string, upstreamsToTrack v1.UpstreamList, opts clients.WatchOpts, settings *v1.Settings) (<-chan v1.EndpointList, <-chan error, error) {
good call, updated

2022-08-26 16:58 UTC, kdorosh commented on projects/gloo/pkg/plugins/aws/ec2/eds.go
> +func (p *plugin) WatchEndpoints(writeNamespace string, unfilteredUpstreams v1.UpstreamList, opts clients.WatchOpts, settings *v1.Settings) (<-chan v1.EndpointList, <-chan error, error) {
good call, updated

2022-08-26 17:37 UTC, kdorosh commented
/kick flake? passes locally reliably https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=b5ef9f1f-37eb-4a2a-8c14-7b5a52988d8b

2022-08-26 17:46 UTC, ianmacclancy commented on projects/gloo/api/v1/settings.proto
> +        google.protobuf.BoolValue eds_blocking_queries = 23;
Where is this setting value used?

2022-08-26 17:47 UTC, kdorosh commented on projects/gloo/api/v1/settings.proto
> +        google.protobuf.BoolValue eds_blocking_queries = 23;
gets used here https://github.com/solo-io/gloo/blob/cba7ba77165c8927a56517093cd851f25fee79d6/projects/gloo/pkg/plugins/consul/eds.go#L121

2022-08-26 17:51 UTC, ianmacclancy submitted a review, later dismissed

2022-08-26 22:30 UTC, elcasteel submitted a review, later dismissed

2022-08-29 20:33 UTC, elcasteel commented on projects/gloo/pkg/plugins/consul/eds.go
> +				dcToCurrentSvcs := map[string]sets.String{}
This makes more sense.

2022-08-29 20:33 UTC, elcasteel approved these changes

2022-08-29 23:05 UTC, merged