RouteOptions.grpc_timeout_header_max
solo-io/gloo pull request #7140
Opened 2022-09-13 18:08 UTC by Bslabe123

# Description

Added the grpc_timeout_header_max to the RouteOptions proto.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-09-14 16:18 UTC, Bslabe123 commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	routeAction.Route.Timeout = in.GetOptions().GetTimeout()
Accidentally rolled this back thanks for catching

2022-09-14 16:25 UTC, Bslabe123 commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +		Expect(routeAction.MaxStreamDuration.GrpcTimeoutHeaderMax).NotTo(BeNil())
Found a nil pointer and fixed it

2022-09-14 18:34 UTC, sam-heilbron requested changes

2022-09-14 18:34 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +var _ = FDescribe("MaxGrpcTimeout", func() {
Focused tests will cause CI to fail

2022-09-14 18:34 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +		Expect(routeAction.MaxStreamDuration.GrpcTimeoutHeaderMax).NotTo(BeNil())
we can probably conslidate these two checks (non nil and equal to a value) since the second check does both

2022-09-14 18:34 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	}
nit: I see a lot of these utility functions perform similar logic. Is it possible to simplify these? It seems like we use this in ProcessRoute, and at the beginning of processRoute we perform:
```
// This plugin is only available for routeActions. return early if a different action is specified.
	if _, ok := in.GetAction().(*v1.Route_RouteAction); !ok {
		return nil
	}
```

2022-09-14 18:34 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +    // Default value is infinity, Please refer to the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v
In the timeout comment I see: 
```
/ Specifies the upstream timeout for the route. If not specified, the default is 15s. This spans between the point
    // at which the entire downstream request (i.e. end-of-stream) has been processed and when the upstream response has
    // been completely processed. A value of 0 will disable the route’s timeout.
```

I think it provides nice context around potential values (none, 0) and how they will be handled. Can we clarify this behavior for this field?

2022-09-14 18:34 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +    // Default value is infinity, Please refer to the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v
This field (in the envoy docs) talks about how you can configure this to override the max_stream_duration: 
```
If present, and the request contains a [grpc-timeout header](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md), use that value as the max_stream_duration, but limit the applied timeout to the maximum value specified here. If set to 0, the grpc-timeout header is used without modification.
```

Do we expose the MaxStreamDuration config in our API currently? If not, should we?

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-routeaction-maxstreamduration

Also, have we confirmed from the issue author why this field is needed?

2022-09-15 15:06 UTC, sam-heilbron requested changes

2022-09-15 15:06 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +    // Default value is infinity and setting to 0 will disable timeout, Please refer to the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.p
I don't think this comment is accurate anymore. It refers to a default value of infinity, but the type has changed

2022-09-15 15:06 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	}
Perhaps I'm misreading this, but is this doing what we expect it to?
We're assigninig inMaxStreamDuration to routeAction.Route.GetMaxStreamDuration, but routeAction is pulled from the out.GetAction. I don't see how we're reading the options from the in Route.

2022-09-15 15:06 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +var _ = FDescribe("MaxGrpcTimeout", func() {
This is still focused and will fail CI

2022-09-15 15:06 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +		Expect(routeAction.MaxStreamDuration.GrpcTimeoutHeaderMax).To(Equal(t))
We have introduced 3 fields in MaxStreamDuration, can we test that all have been translated correctly?

2022-09-15 15:11 UTC, Bslabe123 commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	}
Yep thats a mistake, Fixed

2022-09-15 15:55 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	inMaxStreamDuration := in.GetOptions().MaxStreamDuration
I assuem codegen will fail, since this is not a Getter. 
During our codegen check, we call out to https://github.com/solo-io/gloo/blob/master/Makefile#L227

2022-09-15 16:02 UTC, sam-heilbron reviewed
Can you update the PR description/context to handle the updated changes (ie now we're doing the whole message instead of a single field)

2022-09-15 16:02 UTC, sam-heilbron commented on changelog/v1.13.0-beta15/grpc-header-timeout.yaml
> +  - type: FIX
nit: NEW_FEATURE perhaps?

2022-09-15 16:02 UTC, sam-heilbron commented on changelog/v1.13.0-beta15/grpc-header-timeout.yaml
> +    description: Adds the new grpc_timeout_header_max field to RouteOptions
Let's update this to reflect that change in the API

2022-09-15 16:02 UTC, sam-heilbron commented on changelog/v1.13.0-beta15/grpc-header-timeout.yaml
> +    resolvesIssue: true
This will close the issue, should this be false until we get this onto an enterprise release?

2022-09-15 17:44 UTC, Bslabe123 commented
/kick
```
starting build "b3f90266-0954-4212-980b-6671d2163630"

FETCHSOURCE
Fetching storage object: gs://solo-public_cloudbuild/source/gloo/cd1a62016fa4ffb621307017653f60669e87385f_1663263098.tgz#1663263099668756
Copying gs://solo-public_cloudbuild/source/gloo/cd1a62016fa4ffb621307017653f60669e87385f_1663263098.tgz#1663263099668756...
/ [0 files][    0.0 B/ 38.5 MiB]                                                
/ [1 files][ 38.5 MiB/ 38.5 MiB]                                                
Operation completed over 1 objects/38.5 MiB.                                     
tar: Substituting `.' for empty member name
BUILD
Starting Step #6 - "grab-ginkgo-container"
Starting Step #0 - "prepare-workspace"
Step #6 - "grab-ginkgo-container": Pulling image: gcr.io/solo-public/e2e-go-mod-ginkgo:0.4.24
Step #0 - "prepare-workspace": Pulling image: gcr.io/solo-public/prepare-go-workspace:0.4.24
Step #0 - "prepare-workspace": 0.4.24: Pulling from solo-public/prepare-go-workspace
Step #0 - "prepare-workspace": df9b9388f04a: Already exists
Step #0 - "prepare-workspace": 52dc419b0ee2: Pulling fs layer
Step #0 - "prepare-workspace": 25bc292e5bac: Pulling fs layer
Step #0 - "prepare-workspace": 6858aa20941b: Pulling fs layer
Step #0 - "prepare-workspace": 9a8029b02d49: Pulling fs layer
Step #0 - "prepare-workspace": 5125caa14fe6: Pulling fs layer
Step #0 - "prepare-workspace": cb6db9c6cbe2: Pulling fs layer
Step #0 - "prepare-workspace": 229310b9c70f: Pulling fs layer
Step #0 - "prepare-workspace": 5125caa14fe6: Waiting
Step #0 - "prepare-workspace": cb6db9c6cbe2: Waiting
Step #0 - "prepare-workspace": 229310b9c70f: Waiting
Step #0 - "prepare-workspace": 9a8029b02d49: Waiting
Step #6 - "grab-ginkgo-container": 0.4.24: Pulling from solo-public/e2e-go-mod-ginkgo
Step #6 - "grab-ginkgo-container": dbba69284b27: Pulling fs layer
Step #6 - "grab-ginkgo-container": 9baf437a1bad: Pulling fs layer
Step #6 - "grab-ginkgo-container": 6ade5c59e324: Pulling fs layer
Step #6 - "grab-ginkgo-container": b19a994f6d4c: Pulling fs layer
Step #6 - "grab-ginkgo-container": e3c59fd148be: Pulling fs layer
Step #6 - "grab-ginkgo-container": 4fe55ee977f1: Pulling fs layer
Step #6 - "grab-ginkgo-container": 09c5fd124f19: Pulling fs layer
Step #6 - "grab-ginkgo-container": 4e13f7353c01: Pulling fs layer
Step #6 - "grab-ginkgo-container": 98b14ab502c9: Pulling fs layer
Step #6 - "grab-ginkgo-container": d2cbf6d9abb9: Pulling fs layer
Step #6 - "grab-ginkgo-container": 7876efb4d532: Pulling fs layer
Step #6 - "grab-ginkgo-container": dbba69284b27: Waiting
Step #6 - "grab-ginkgo-container": 62e6f4e6f752: Pulling fs layer
Step #6 - "grab-ginkgo-container": d7bdd1784d68: Pulling fs layer
Step #6 - "grab-ginkgo-container": 703494661407: Pulling fs layer
Step #6 - "grab-ginkgo-container": 6ade5c59e324: Waiting
Step #6 - "grab-ginkgo-container": d232f850f53f: Pulling fs layer
Step #6 - "grab-ginkgo-container": 3926b61b7194: Pulling fs layer
Step #6 - "grab-ginkgo-container": b19a994f6d4c: Waiting
Step #6 - "grab-ginkgo-container": 4fe55ee977f1: Waiting
Step #6 - "grab-ginkgo-container": e2ad26c557fe: Pulling fs layer
Step #6 - "grab-ginkgo-container": 9baf437a1bad: Waiting
Step #6 - "grab-ginkgo-container": dda2602f35f2: Pulling fs layer
Step #6 - "grab-ginkgo-container": 12e71d655e7c: Pulling fs layer
Step #6 - "grab-ginkgo-container": d2cbf6d9abb9: Waiting
Step #6 - "grab-ginkgo-container": 62e6f4e6f752: Waiting
Step #6 - "grab-ginkgo-container": 3926b61b7194: Waiting
Step #6 - "grab-ginkgo-container": e2ad26c557fe: Waiting
Step #6 - "grab-ginkgo-container": 09c5fd124f19: Waiting
Step #6 - "grab-ginkgo-container": 4e13f7353c01: Waiting
Step #6 - "grab-ginkgo-container": 98b14ab502c9: Waiting
Step #6 - "grab-ginkgo-container": dda2602f35f2: Waiting
Step #6 - "grab-ginkgo-container": d7bdd1784d68: Waiting
Step #6 - "grab-ginkgo-container": d232f850f53f: Waiting
Step #6 - "grab-ginkgo-container": 703494661407: Waiting
Step #0 - "prepare-workspace": 25bc292e5bac: Verifying Checksum
Step #0 - "prepare-workspace": 25bc292e5bac: Download complete
Step #0 - "prepare-workspace": 52dc419b0ee2: Verifying Checksum
Step #0 - "prepare-workspace": 52dc419b0ee2: Download complete
Step #0 - "prepare-workspace": 9a8029b02d49: Download complete
Step #0 - "prepare-workspace": cb6db9c6cbe2: Verifying Checksum
Step #0 - "prepare-workspace": cb6db9c6cbe2: Download complete
Step #0 - "prepare-workspace": 52dc419b0ee2: Pull complete
Step #0 - "prepare-workspace": 5125caa14fe6: Verifying Checksum
Step #0 - "prepare-workspace": 5125caa14fe6: Download complete
Step #0 - "prepare-workspace": 229310b9c70f: Verifying Checksum
Step #0 - "prepare-workspace": 229310b9c70f: Download complete
Step #0 - "prepare-workspace": 25bc292e5bac: Pull complete
Step #6 - "grab-ginkgo-container": 9baf437a1bad: Verifying Checksum
Step #6 - "grab-ginkgo-container": 9baf437a1bad: Download complete
Step #6 - "grab-ginkgo-container": 6ade5c59e324: Verifying Checksum
Step #6 - "grab-ginkgo-container": 6ade5c59e324: Download complete
Step #6 - "grab-ginkgo-container": dbba69284b27: Verifying Checksum
Step #6 - "grab-ginkgo-container": dbba69284b27: Download complete
Step #0 - "prepare-workspace": 6858aa20941b: Verifying Checksum
Step #0 - "prepare-workspace": 6858aa20941b: Download complete
Step #6 - "grab-ginkgo-container": b19a994f6d4c: Verifying Checksum
Step #6 - "grab-ginkgo-container": b19a994f6d4c: Download complete
Step #6 - "grab-ginkgo-container": 09c5fd124f19: Verifying Checksum
Step #6 - "grab-ginkgo-container": 09c5fd124f19: Download complete
Step #6 - "grab-ginkgo-container": 4e13f7353c01: Verifying Checksum
Step #6 - "grab-ginkgo-container": 4e13f7353c01: Download complete
Step #6 - "grab-ginkgo-container": e3c59fd148be: Verifying Checksum
Step #6 - "grab-ginkgo-container": e3c59fd148be: Download complete
Step #6 - "grab-ginkgo-container": d2cbf6d9abb9: Download complete
Step #6 - "grab-ginkgo-container": 7876efb4d532: Verifying Checksum
Step #6 - "grab-ginkgo-container": 7876efb4d532: Download complete
Step #6 - "grab-ginkgo-container": 62e6f4e6f752: Download complete
Step #6 - "grab-ginkgo-container": dbba69284b27: Pull complete
Step #6 - "grab-ginkgo-container": 4fe55ee977f1: Verifying Checksum
Step #6 - "grab-ginkgo-container": 4fe55ee977f1: Download complete
Step #6 - "grab-ginkgo-container": d7bdd1784d68: Download complete
Step #6 - "grab-ginkgo-container": d232f850f53f: Verifying Checksum
Step #6 - "grab-ginkgo-container": d232f850f53f: Download complete
Step #6 - "grab-ginkgo-container": 9baf437a1bad: Pull complete
Step #6 - "grab-ginkgo-container": 703494661407: Verifying Checksum
Step #6 - "grab-ginkgo-container": 703494661407: Download complete
Step #6 - "grab-ginkgo-container": 6ade5c59e324: Pull complete
Step #6 - "grab-ginkgo-container": 3926b61b7194: Verifying Checksum
Step #6 - "grab-ginkgo-container": 3926b61b7194: Download complete
Step #6 - "grab-ginkgo-container": e2ad26c557fe: Verifying Checksum
Step #6 - "grab-ginkgo-container": e2ad26c557fe: Download complete
Step #6 - "grab-ginkgo-container": dda2602f35f2: Verifying Checksum
Step #6 - "grab-ginkgo-container": dda2602f35f2: Download complete
Step #6 - "grab-ginkgo-container": b19a994f6d4c: Pull complete
Step #0 - "prepare-workspace": 6858aa20941b: Pull complete
Step #0 - "prepare-workspace": 9a8029b02d49: Pull complete
Step #6 - "grab-ginkgo-container": 98b14ab502c9: Verifying Checksum
Step #6 - "grab-ginkgo-container": 98b14ab502c9: Download complete
Step #0 - "prepare-workspace": 5125caa14fe6: Pull complete
Step #0 - "prepare-workspace": cb6db9c6cbe2: Pull complete
Step #0 - "prepare-workspace": 229310b9c70f: Pull complete
Step #0 - "prepare-workspace": Digest: sha256:f3ae6d672d61ac7a41393119c6bfe9bbbeca74e0ca3aeb24fe09bf6631ef4363
Step #0 - "prepare-workspace": Status: Downloaded newer image for gcr.io/solo-public/prepare-go-workspace:0.4.24
Step #0 - "prepare-workspace": gcr.io/solo-public/prepare-go-workspace:0.4.24
Step #6 - "grab-ginkgo-container": e3 [...]

2022-09-15 21:30 UTC, sam-heilbron commented
/kick
https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d4b1578f-df75-4b20-afce-a399a6c1b9d7

```
Step #10 - "test": Fail handler msg Failed after 0.002s.
Step #10 - "test": Expected
Step #10 - "test":     <<-chan *v1helpers.ReceivedRequest | len:0, cap:100>: 0xc002dc1500
Step #10 - "test": to receive something.
Step #10 - "test": • Failure [3.185 seconds]
Step #10 - "test": Consul e2e with envoy and gloo [It] resolves consul services with hostname addresses (as opposed to IPs addresses) 
Step #10 - "test": /workspace/gloo/test/e2e/consul_test.go:203
Step #10 - "test": 
Step #10 - "test":   Failed after 0.002s.
Step #10 - "test":   Expected
Step #10 - "test":       <<-chan *v1helpers.ReceivedRequest | len:0, cap:100>: 0xc002dc1500
Step #10 - "test":   to receive something.
Step #10 - "test": 
Step #10 - "test":   /workspace/gloo/test/e2e/consul_test.go:233
Step #10 - "test": 
Step #10 - "test":   Full Stack Trace
Step #10 - "test":   github.com/solo-io/gloo/test/e2e_test.glob..func6.3.6()
Step #10 - "test":   	/workspace/gloo/test/e2e/consul_test.go:233 +0x1515
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc000befda0)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:113 +0xf6
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc000befda0)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/runner.go:64 +0x158
Step #10 - "test":   github.com/onsi/ginkgo/internal/leafnodes.(*ItNode).Run(0xc000fc5080)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/leafnodes/it_node.go:26 +0x95
Step #10 - "test":   github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc000c7c960, 0x0?, {0x70f3460, 0xc00038e640})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:215 +0x35a
Step #10 - "test":   github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc000c7c960, {0x70f3460, 0xc00038e640})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/spec/spec.go:138 +0x1ac
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc000b7cdc0, 0xc000c7c960)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:200 +0x15b
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc000b7cdc0)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:170 +0x256
Step #10 - "test":   github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc000b7cdc0)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/specrunner/spec_runner.go:66 +0x137
Step #10 - "test":   github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc000387b90, {0x7ff2a8cd5730, 0xc000559ba0}, {0x6425764, 0x9}, {0xc000fc5000, 0x2, 0x2}, {0x71349d8, 0xc00038e640}, ...)
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/internal/suite/suite.go:79 +0x6f6
Step #10 - "test":   github.com/onsi/ginkgo.runSpecsWithCustomReporters({0x71011e0?, 0xc000559ba0}, {0x6425764, 0x9}, {0xc000fc4fe0, 0x2, 0x64501c7?})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:245 +0x213
Step #10 - "test":   github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters({0x71011e0, 0xc000559ba0}, {0x6425764, 0x9}, {0xc0000f3e88?, 0x1, 0x1})
Step #10 - "test":   	/go/pkg/mod/github.com/onsi/ginkgo@v1.16.5/ginkgo_dsl.go:228 +0x258
Step #10 - "test":   github.com/solo-io/gloo/test/e2e_test.TestE2e(0x0?)
Step #10 - "test":   	/workspace/gloo/test/e2e/e2e_suite_test.go:47 +0x2fb
Step #10 - "test":   testing.tRunner(0xc000559ba0, 0x6576c28)
Step #10 - "test":   	/usr/local/go/src/testing/testing.go:1439 +0x214
Step #10 - "test":   created by testing.(*T).Run
Step #10 - "test":   	/usr/local/go/src/testing/testing.go:1486 +0x725
```

2022-09-15 21:32 UTC, sam-heilbron reviewed
Changes look good to me! Great comments on the API.

I won't approve so someone else has a chance to review and provide feedback.

2022-09-16 03:03 UTC, jenshu commented on projects/gloo/api/v1/options.proto
> +    // Settings for maximum durations and timeouts for streams on the route, Please refer to the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_compone
```suggestion
    // Settings for maximum durations and timeouts for streams on the route.
    // Please refer to the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-routeaction-maxstreamduration)
```
wrong link

2022-09-16 14:22 UTC, ianmacclancy commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +		a := prototime.DurationToProto(time.Second)
Nit as a short test but a,b, and c are non-descriptive variables. You could use ts, tm, and th for shorthand.

2022-09-16 15:00 UTC, jenshu reviewed
LGTM, will let Ian give final approval

2022-09-16 15:31 UTC, Bslabe123 commented on projects/gloo/pkg/plugins/basicroute/plugin_test.go
> +					GrpcTimeoutHeaderOffset: t,
Fixed

2022-09-19 14:57 UTC, ianmacclancy approved these changes

2022-09-19 14:57 UTC, merged