Passthrough failure mode allow 1.12 backport
solo-io/gloo pull request #7310
Opened 2022-10-10 12:23 UTC by inFocus7

_backport of #6942_

# Description

- Added `failure_mode_allow` to the `PassThroughAuth` definition.

# Context

We want something similar to the global `failure_mode_allow` setting, just for our passthrough auth. 

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [X] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [X] I have added tests that prove my fix is effective or that my feature works

2022-10-10 21:21 UTC, inFocus7 commented
adding WIP to this to cherry-pick teh small doc updates here https://github.com/solo-io/gloo/pull/7314

2022-10-11 14:07 UTC, jackstine submitted a review, later dismissed

2022-10-11 22:02 UTC, sam-heilbron requested changes
Let's pull in the updates from https://github.com/solo-io/gloo/pull/7314 (for guides, api comments and metrics)

2022-10-12 13:46 UTC, sam-heilbron commented
This looks good to me. Leaving open so @elcasteel and @jackstine can review

2022-10-12 14:06 UTC, jackstine approved these changes

2022-10-12 14:26 UTC, inFocus7 commented
/skip-ci

2022-10-12 14:26 UTC, merged

2022-10-12 15:36 UTC, kdorosh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // Defaults to an empty string, which is interpreted as `and`-ing the configs.
:clap: