Expose retry backoff settings v2
solo-io/gloo pull request #7415
Opened 2022-11-09 23:21 UTC by irateswami

# Description

Added the base and max interval for the retry policy backoff settings, pretty handy!

This  is a v2 branch of similar changes I make [here](https://github.com/solo-io/gloo/pull/7404), I was having some odd dependency issues that went away when I tried a new `git worktree`. Tests are all passing. 

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2022-11-10 15:30 UTC, kdorosh commented on projects/gloo/api/v1/options/retries/retries.proto
> +    // Specifies the base interval for a retry
nit; can we improve the comments here to more completely explain the functionality implemented here for users?

2022-11-10 15:31 UTC, nfuden commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +			if ms := baseInterval.AsDuration().Milliseconds(); ms >= 0 {
As in previous pr what happens when envoy gets a config with sub 1 ms? Should we care?

2022-11-10 15:31 UTC, nfuden commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		if maxInterval := retryPolicyInterval.GetMaxInterval(); maxInterval != nil {
What happens if max is smaller than min? Will it be valid envoy config? Should we warn our users?

2022-11-10 15:36 UTC, irateswami commented on projects/gloo/api/v1/options/retries/retries.proto
> +    // Specifies the base interval for a retry
Sure! I'll add some more color

2022-11-10 15:41 UTC, irateswami commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +			if ms := baseInterval.AsDuration().Milliseconds(); ms >= 0 {
All of the envoy documentation is in milliseconds, perhaps we could add something to the docs to make sure that our end users are only handing over ms?

2022-11-10 15:42 UTC, irateswami commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		if maxInterval := retryPolicyInterval.GetMaxInterval(); maxInterval != nil {
That's a good check, I didn't see anything about that in the docs. I'm sure it's not a valid config, I'm not sure how envoy handles that sort of issue. Technically it's a valid structure programmatically. I could add another check here and error out if the max is smaller than the base, that's not a big lift.

2022-11-10 16:52 UTC, sam-heilbron reviewed
This looks great! 
1. I think we can try to expose even more details to the end user so that they don't have to dig into the underlying API. These are published to our external docs (example: https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/external/envoy/config/core/v3/base.proto.sk/) and allow users to find all information about the behavior

2. If there is complex validation, we can add it into the plugin translation itself. However, if there are some basic min/max values, we could explore using proto validation constraints. An example is https://github.com/solo-io/solo-apis/blob/master/api/gloo/gloo/external/envoy/type/v3/percent.proto#L20. If you're curious, we (or someone on the team) can chat about what this provides / where in the translation chain this would be evaluated

2022-11-11 15:42 UTC, irateswami commented
Two flakes, seems related to this, posted a comment: https://github.com/solo-io/gloo/issues/4428

2022-11-11 15:43 UTC, irateswami commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +			if ms := baseInterval.AsDuration().Milliseconds(); ms >= 0 {
Changed! No longer check milliseconds

2022-11-11 15:43 UTC, irateswami commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		if maxInterval := retryPolicyInterval.GetMaxInterval(); maxInterval != nil {
Added a check for this

2022-11-11 17:10 UTC, nfuden requested changes
Pretty close. Only see one instance that would produce invalid envoy config

2022-11-11 17:10 UTC, nfuden commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		if maxInterval := retryPolicyInterval.GetMaxInterval(); maxInterval != nil {
https://github.com/envoyproxy/envoy/blob/43dde7800d6057406ef52dd1c0982a0028c558fa/api/envoy/config/core/v3/backoff.proto#L24
It is valid for base interval to be set without max but it is invalid for max to be set without base being set

2022-11-11 17:10 UTC, nfuden commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		// If max and/or/both base intervals are defined, return a RetryPolicy object that contains them
Needs update per https://github.com/envoyproxy/envoy/blob/43dde7800d6057406ef52dd1c0982a0028c558fa/api/envoy/config/core/v3/backoff.proto#L24

2022-11-11 17:10 UTC, nfuden commented on changelog/v1.13.0-beta26/expose_retry_backoff.yaml
> +    description: This feature exposes the base and max interval of the retry policy backoff settings
Should we mention how /where this is set?

2022-11-11 20:39 UTC, irateswami commented on changelog/v1.13.0-beta26/expose_retry_backoff.yaml
> +    description: This feature exposes the base and max interval of the retry policy backoff settings
Not sure what you mean here, could you give an example?

2022-11-11 20:47 UTC, nfuden commented on changelog/v1.13.0-beta26/expose_retry_backoff.yaml
> +    description: This feature exposes the base and max interval of the retry policy backoff settings
Basically why should customers care? 

```suggestion
    description: Expose the ability to set retry backoff policy's intervals. This can be set at the gateway, vs, or even the route level.
```

2022-11-11 21:28 UTC, irateswami commented on changelog/v1.13.0-beta26/expose_retry_backoff.yaml
> +    description: This feature exposes the base and max interval of the retry policy backoff settings
If it's okay with you I'll commit your change here if there's nothing more to add

2022-11-11 22:32 UTC, irateswami commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +		if maxInterval := retryPolicyInterval.GetMaxInterval(); maxInterval != nil {
I believe this is taken care of via the protobuf definition

2022-11-12 16:53 UTC, nfuden approved these changes

2022-11-12 23:41 UTC, jenshu commented on projects/gloo/api/v1/options/retries/retries.proto
> +        required: true
the [envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-retrypolicy-retrybackoff) have the base interval as required and the max interval as optional. why are we reversing that here?

2022-11-12 23:41 UTC, jenshu commented on projects/gloo/api/v1/options/retries/retries.proto
> +    RetryPolicyInterval retry_policy_interval = 4;
```suggestion
    RetryBackOff retry_back_off = 4;
```
nit: any reason not to name the message and field the same as envoy?

2022-11-14 16:17 UTC, irateswami commented on projects/gloo/api/v1/options/retries/retries.proto
> +        required: true
Fixed!

2022-11-14 16:17 UTC, jenshu commented on projects/gloo/api/v1/options/retries/retries.proto
> +        gte {nanos: 1000000}
this part also needs to be swapped, right?

2022-11-14 21:32 UTC, irateswami commented on projects/gloo/api/v1/options/retries/retries.proto
> +        gte {nanos: 1000000}
This reflects the envoy config, is there something I'm missing?

2022-11-15 18:15 UTC, sam-heilbron reviewed
Looks good!

2022-11-15 18:15 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/basicroute/plugin.go
> +	v3RetryPolicyBackOff := &envoy_config_route_v3.RetryPolicy_RetryBackOff{}
https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/backoff.proto In the envoy docs, the base_interval field is signaled to be required. In our current code, we initialize an empty RetryBackOff and seemingly allow a user to define a max without a base interval. Am I missing something or is that possible?

2022-11-15 18:35 UTC, nfuden commented on projects/gloo/api/v1/options/retries/retries.proto
> +import "validate/validate.proto";
```suggestion
// Validate is added to mimic envoy's setup and for when we finally implement validation.
// For now we reiterate this in code as we do not check the validation rules. 
import "validate/validate.proto";
```

2022-11-15 21:15 UTC, sam-heilbron approved these changes

2022-11-15 21:31 UTC, nfuden approved these changes

2022-11-15 21:31 UTC, merged