Updated docs for Multi Gateway Deployment
solo-io/gloo pull request #7440
Opened 2022-11-16 20:34 UTC by Bslabe123

# Description

Our docs for https://docs.solo.io/gloo-edge/latest/installation/advanced_configuration/multi-gw-deployment/ were out of date and reflected pre 1.12 behavior when we deployed the proxy CRs by default, now our docs include `gateway.persistProxySpec` to ensure the CRs get created.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-11-16 21:28 UTC, Nadine2016 approved these changes

2022-11-16 22:00 UTC, elcasteel requested changes
Based on slack conversation, this should either be a reminder to use latest glooctl or closed entirely.

2022-11-17 14:49 UTC, elcasteel commented on docs/content/installation/advanced_configuration/multi-gw-deployment.md
> +Assuming `glooctl` is at least v1.12, you can check everything is correct with `glooctl` commands:
Our typical recommendation is for glooctl to match the gloo version. There is a big jump from 1.11 to 1.12 that affects how we display proxies which is why we need a callout but just "glooctl 1.12" seems off here (sounds a bit to me that this won't work in gloo 1.11). Maybe someone from the docs team can weigh in on how to phrase this.

2022-11-17 14:56 UTC, Bslabe123 commented on docs/content/installation/advanced_configuration/multi-gw-deployment.md
> +Assuming `glooctl` is at least v1.12, you can check everything is correct with `glooctl` commands:
Created an issue in docs and handing this off https://github.com/orgs/solo-io/projects/22/views/1?filterQuery=multi+gateway

2022-11-17 14:56 UTC, closed without merging