Istio Integration: Wrong Port When Service TargetPort Is Different Fix
solo-io/gloo pull request #7466
Opened 2022-11-23 17:15 UTC by inFocus7

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-11-28 15:07 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
>  					key := Epkey{hostname, port, spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
seeing as how we're just using the service's port, might be more performant/better to move the istio integration outside the subset loop, as we don't care about them. 
trying that in my current local changes. 
will need to check if there was any specific reason we were using the subset ports previously, and if that's still necessary. i could try testing locally with a setup that requires `targetPort`, and one which doesn't.

2022-11-28 16:07 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
>  					key := Epkey{hostname, port, spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
manually tested with following conditions:
- only a port: `PASS`
- port + target port different: `PASS`
- port + target port same: `PASS`

2022-12-05 12:45 UTC, inFocus7 commented
making ready-for-review so all tests run

2022-12-06 12:49 UTC, inFocus7 commented
update: limiting resources on just gloo doesn't solve limited cpu issue when deploying gloo pod. trying limiting on gateway as well (although, not sure of its initial value since it isn't set in helm), and removing ALS so there's more cpu for gloo deployment 🤞🏼

2022-12-06 17:40 UTC, inFocus7 commented
note: last two commits are locally untested (since i get errors running built glooctl (although CI doesn't seem to face it)). The idea is to install the istio proxies _after_ the initial gloo setup using resources. not 100% certain it will fix the issue, but should hopefully separate needing resources while gloo installs and injecting the istio proxies later on.

2022-12-06 20:19 UTC, inFocus7 commented
update time:
istio proxy was deployed in all services installed, but wasn't necessary so just installed on the important pods for these tests: `gateway-proxy` & `testrunner`. So now 2 less istio proxies consuming resources 🤞🏼

2022-12-07 17:58 UTC, kdorosh commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
does this use the kube service port or target port?

2022-12-07 17:59 UTC, kdorosh commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
i thought istio typically just routes directly to pods to skip any k8s load balancing. so i would expect the service port to be ignored, and prefer the target port

2022-12-07 18:01 UTC, inFocus7 commented on test/kube2e/istio/istio_integration_test.go
> +				},
On mobile atm, so not 100%, but i believe target port is set below. Basically so i can create and test a service with multiple configs if port + targetPort (second optional)

2022-12-07 18:07 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
It uses the kube service port. I'll do a bit more investigation, but what we saw was that with istio integration, we need to route to the service port in order to hit the istio proxy (sidecar?). 
When the target port and port differed (as is with the HTTPBin example), we had issues since the pod's port was used (targetPort), but the istio proxy didnt receive a req.

We didn't have any tests beforehand, so hard to be 100% certain on what we previously expected. Which is why i created multiple tests

2022-12-07 18:08 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
I could also walk through this locally if that helps. Currently taking linch, but can set up environment pre-this-fix and post, to see the requests on gateway-proxy + istio.

2022-12-07 19:05 UTC, kdorosh commented on test/kube2e/istio/istio_integration_test.go
> +		}
super nit; i slightly prefer doing this logic before the service struct is initialized. it's a bit easier to read. e.g.

```golang
configuredTargetPort := 0 // or nil, whatever the default is
if targetPort != -1 {
  configuredTargetPort = targetPort
} 

svc := &service{
  // use configuredTargetPort here
}
```

2022-12-07 19:08 UTC, kdorosh commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
ah this makes sense after re-reading. the map is to upstream refs, not endpoints

2022-12-07 19:09 UTC, kdorosh commented on test/kube2e/istio/istio_integration_test.go
> +			table.Entry("with non-matching, yet valid, port and target (app) port", int32(8000), helper.TestRunnerPort, http.StatusOK),
to ensure they are different, can we use say `helper.TestRunnerPort + 1` instead of `8000`?

2022-12-07 19:10 UTC, kdorosh commented on test/kube2e/istio/istio_integration_test.go
> +			table.Entry("without target port, and port not matching app's port", int32(8000), -1, http.StatusServiceUnavailable),
same about not hardcoding `8000` here and instead incrementing the helper test runner port

2022-12-07 19:11 UTC, kdorosh commented on test/kube2e/istio/istio_suite_test.go
> +	_ = testutils.Kubectl("label", "namespace", testHelper.InstallNamespace, "istio-injection=enabled")
we should check errors?

2022-12-07 20:12 UTC, inFocus7 commented on test/kube2e/istio/istio_integration_test.go
> +		}
sounds good! From a service config i set up without a target port (+ this [unofficial k8s doc](https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/services-networking/service/)), the default value for a TargetPort is the Port.

2022-12-07 20:31 UTC, inFocus7 commented on test/kube2e/istio/istio_suite_test.go
> +	_ = testutils.Kubectl("label", "namespace", testHelper.InstallNamespace, "istio-injection=enabled")
good call, added error checks for the kubectl commands

2022-12-07 21:10 UTC, kdorosh commented on test/kube2e/istio/istio_integration_test.go
> +		}
yeah we can set the default to nil and only override if we have provided a target port in the test

2022-12-07 22:25 UTC, inFocus7 commented on test/kube2e/istio/istio_integration_test.go
> +		}
Tried but doesn't work, the `TargetPort` is of type `IntOrString` which doesn't allow a `nil` value

2022-12-08 16:54 UTC, ben-taussig-solo commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +			key := Epkey{hostname, uint32(kubeServicePort.Port), spec.GetServiceName(), spec.GetServiceNamespace(), usRef}
Nit: For readability, could we call out the field names in this key?
```suggestion
                        key := Epkey{
				Address:     hostname,
				Port:        uint32(kubeServicePort.Port),
				Name:        spec.GetServiceName(),
				Namespace:   spec.GetServiceNamespace(),
				UpstreamRef: usRef,
			}
			copy
```

2022-12-08 17:01 UTC, ben-taussig-solo commented on test/kube2e/istio/istio_suite_test.go
> +        cpu: 100m
is it necessary to set these resource limits on the Gloo deployment and Gateway Proxy podTemplate? If possible, could we reduce the helm overrides to just the istioIntegration settings?

2022-12-08 17:03 UTC, ben-taussig-solo commented on test/kube2e/istio/istio_suite_test.go
> +	kube2e.UpdateAlwaysAcceptSetting(ctx, false, testHelper.InstallNamespace)
Is this still relevant? I see that the issue linked on line 86 is closed

2022-12-08 18:23 UTC, inFocus7 commented on test/kube2e/istio/istio_suite_test.go
> +        cpu: 100m
It _might_ be possible, I added this before limiting the istio proxies deployed which ultimately fixed resrouce limitation. Pushing latest PR to see if managing the resources doesn't matter anymore 👍🏼

2022-12-08 19:12 UTC, inFocus7 commented on test/kube2e/istio/istio_suite_test.go
> +        cpu: 100m
Update: Will need these resource limitations. Removing them causes
```
Warning   FailedScheduling    pod/testrunner                        0/1 nodes are available: 1 Insufficient cpu.
```
(as seen in the [kube dumps](https://github.com/solo-io/gloo/actions/runs/3651018863/jobs/6167742200))

2022-12-08 20:27 UTC, inFocus7 commented on test/kube2e/istio/istio_suite_test.go
> +	kube2e.UpdateAlwaysAcceptSetting(ctx, false, testHelper.InstallNamespace)
latest commit removes this. unable to test locally at the moment, so using CI to make sure it still runs as expected 👍🏼

2022-12-09 19:31 UTC, ben-taussig-solo submitted a review, later dismissed
Just validated this manually using the steps in the description. Looks good and thanks for the detailed testing steps!

2022-12-12 20:18 UTC, kdorosh commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +				UpstreamRef: usRef,
i think this should be the copy ref, or else the pointer will update and be wrong at the end of the loop. same trick we do with the endpoints map

ideally this is tested and caught by a unit test for eds.go

2022-12-12 20:19 UTC, kdorosh requested changes
apparent bug, or at least simplification (if `copyRef` is unneeded. but i think it is) is required

2022-12-12 20:25 UTC, kdorosh commented on test/kube2e/istio/istio_integration_test.go
> +		table.DescribeTable("should act as expected with varied ports", func(port int32, targetPort int, expected int) {
love this test very compact :clap:

2022-12-12 22:06 UTC, sam-heilbron requested changes
I checked out your changes, undid the eds.go changes  (just using the version of the file on the master branch) and then ran your regression tests (thank you for adding them!) and they all passed.

Given that, it seems these tests are a good addition to validate some cases, but don't test the new behavior we've introduced. Can you add a test which passes with your changes but will fail without them?

Also, I agree with Kevin's point that our EDS logic is very complex and deserves some more enhanced unit tests to validate the logic.

2022-12-13 12:40 UTC, inFocus7 commented
> Can you add a test which passes with your changes but will fail without them?

I tried it too and got the same results. The `with non-matching, yet valid, port and target (app) port` should be the port that determines it's fixed, so unsure why it's passing on testrunner. I'll have to test it locally to see why `testrunner` doesn't have the issue, but when I set it up (locally) with `httpbin`, we do see the issue.

2022-12-13 12:45 UTC, inFocus7 commented
Self-performed local tests to find out what the issue is:
- [ ] using httpbin, instead of “testrunner”
- [X] For httpbin deployment, `ports.containerPort` is set. What if it's set in testrunner pod as well? (investigated by adding containerPort to the pods creation; not issue)
- [ ] maybe due to install gloo enterprise locally, but tests use OSS?
- [ ] Is the `curl`? hitting the gateway proxy service directly, instead of the IP?
- [X] test uses istio 1.11.4, i use 1.15.1 (looked into it; not issue)
- [X] I have autoinjection enabled locally (looked into it; not issue)
- [X] Maybe the existing services aren’t getting deleted/created? (looked into it; not issue)

2022-12-13 14:45 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +				UpstreamRef: usRef,
Ah great catch! Just pushed the change!

2022-12-13 17:12 UTC, inFocus7 commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +				UpstreamRef: usRef,
resolving again. False-flag ^. It was working since, after moving stuff back, i mistakenly still kept "uint32(kubeServicePort.Port)" as the Port which is the fix.

2023-01-24 21:53 UTC, inFocus7 commented
/kick

2023-01-25 14:50 UTC, inFocus7 commented
Latest changes (past two commits) have been reformating so that we only use the istio eds logic (adding endpoint with service information) when adding pods that have an `istio-proxy` container listening. 

Originally we didn't care for it, and did the istio eds logic as long as `isIstioIntegrationEnabled()` was true. If we want/need to keep that approach, then I'll simply revert the latest changes so we're _only_ updating the port to be the service port (what istio listens on) without caring for `istio-proxy` deployment.

2023-01-27 17:51 UTC, ben-taussig-solo commented on test/kube2e/istio/istio_integration_test.go
> +			Eventually(func() bool {
Nit: is there a particular reason we don't use `helpers.EventuallyResourceDeleted` here?

2023-01-27 18:02 UTC, inFocus7 commented on test/kube2e/istio/istio_integration_test.go
> +			Eventually(func() bool {
Good call, I forgot the reason earlier but after looking into it: 
`helper.EventuallyResourceDeleted` takes in a function parameter that returns a `resources.InputResource`. That is a type/interface we own and our input resources (VirtualServices, Clients, etc.) implement.
 
_But_ `ServiceClient` is a k8s resource, therefore it doesn't implement our `InputResource` interface, and we can't use it with `helper.EventuallyResourceDeleted`.

2023-01-30 14:22 UTC, inFocus7 commented
/kick

2023-01-31 13:50 UTC, sam-heilbron reviewed
Changes look good to me and love the new tests!

Thanks for calling out:
```
I noted that when istioIntegrationEnabled(), we'd always be routing to the <ServiceIP>:<ServicePort> even for pods that don't need it (Istio wouldn't (need to) be listening in on them). This shouldn't lead to an issue and it should still correctly resolve, therefore not taking care of this case, and just fixing the initial issue of needing to user ServicePort for istio integration.
```

Though this works, I wonder if this behavior is preferred. Since this is the existing behavior (before your changes) I don't think we need to change it as part of this work, but could you reach out to the field/product to clarify this behavior of the flag, and perhaps write up an issue for a new feature if we need to be able to dynamically determine if istio integration is enabled?

2023-01-31 13:50 UTC, sam-heilbron commented on test/kube2e/istio/istio_integration_test.go
> +			table.Entry("with non-matching, yet valid, port and target (app) port", int32(helper.TestRunnerPort+1), helper.TestRunnerPort, http.StatusOK),
This is a great example of both positive and negative test cases!!

2023-01-31 13:50 UTC, sam-heilbron commented on test/kube2e/istio/istio_suite_test.go
> +		cancel()
I think that cancel should happen regardless of the TEAR_DOWN env

2023-01-31 13:50 UTC, sam-heilbron commented on test/kube2e/istio/istio_suite_test.go
> +	ctx, cancel = context.WithCancel(context.Background())
This should probably be initialized in the BeforeSuite since we clean it up in the AfterSuite

2023-01-31 13:50 UTC, sam-heilbron commented on test/kube2e/istio/istio_suite_test.go
> +          cpu: 100m
As we move towards a more standard way of setting resource limits for tests, I think it would be valuable to call these out loudly in a comment. Perhaps indicating the behavior we noticed when we did not set resource limits, and even perhaps a tip in the PR outlining how developers can debug that behavior.

2023-01-31 16:00 UTC, inFocus7 commented
/kick

2023-01-31 17:07 UTC, sam-heilbron commented
/kick

https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=203cf664-80f9-4e81-a057-fadb86d79b76

```
Fail] Consul e2e with envoy and gloo [It] resolves consul services with hostname addresses (as opposed to IPs addresses) 
Step #10 - "test": /workspace/gloo/test/e2e/consul_test.go:237
```

I did not see an issue tracking this flake. If we see this more frequently we can create one

2023-01-31 17:08 UTC, sam-heilbron approved these changes
Great work!

2023-01-31 17:08 UTC, sam-heilbron commented on test/kube2e/istio/istio_suite_test.go
> +	// Install Gloo
nit: this comment is inaccurate. I think it's meant to be a few lines lower

2023-01-31 20:54 UTC, kdorosh approved these changes

2023-01-31 21:02 UTC, nfuden commented on test/kube2e/istio/istio_integration_test.go
> +			table.Entry("pointing to the wrong target port", int32(8000), helper.TestRunnerPort+1, http.StatusServiceUnavailable), // or maybe 404?
Do we have certainty here? I dont love an or as a comment here as it sounds like a potential flake. 
Perhaps we have gotten clarity since that merits the removal of this comment?

2023-01-31 21:06 UTC, sam-heilbron approved these changes

2023-01-31 21:08 UTC, nfuden commented on test/kube2e/istio/istio_suite_test.go
> +	gatewayPort  = int(80)
we seem to use this alot of places is it time to move this to gatewaydefaults? 
gatewaydefaults.DefaultGatewayPort?

I just dislike magic numbers proliferating

2023-02-01 17:07 UTC, merged