CVE Scanning: Fix Vulnerabilities and Improve Local Utilities
solo-io/gloo pull request #7490
Opened 2022-11-30 18:29 UTC by sam-heilbron

# Description

1. Fix vulnerabilities in 1.13 RC images
2. Improve utilities for scanning images locally

# Context

## Fix Vulnerabilities

## Add Scanning Utility

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-11-30 19:01 UTC, nfuden commented on Makefile
> +.PHONY: scan-version
nit: As we add new tools to our make file if they are not directly related to development defaults could we perhaps put them in a seperate go mod. 
In this case perhaps a make file for vulnerabilties or on-call?

2022-12-01 00:13 UTC, bewebi requested changes
The tool appears to function as intended, however identifying a vulnerability should not be considered (or present as) an error with the tool

2022-12-01 00:13 UTC, bewebi commented on hack/trivy/scan.go
> +// selected from a recent scan result: https://github.com/solo-io/gloo/issues/7361
Are there other images in the repo that we don't scan?

2022-12-01 00:13 UTC, bewebi commented on hack/trivy/scan.go
> +	var scanResults error
I'm not sure that a vulnerability scanner constitutes an error per se...in fact it's intended behavior
When I run 
```VERSION=1.13.0-rc1 make scan-version```
I get
```
2022/11/30 19:04:49 unable to run: 7 errors occurred:
	* vulnerabilities found for quay.io/solo-io/gloo:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/gloo-envoy-wrapper:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/discovery:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/ingress:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/sds:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/certgen:1.13.0-rc1
	* vulnerabilities found for quay.io/solo-io/access-logger:1.13.0-rc1


exit status 1
make: *** [scan-version] Error 1
```
which makes it seem like the scan itself failed, when really it did its job
Can we ensure that when the scan completes successfully, having identified CVEs, the output makes it clear that that is the case?

2022-12-01 10:46 UTC, sam-heilbron commented on hack/trivy/scan.go
> +// selected from a recent scan result: https://github.com/solo-io/gloo/issues/7361
Not to my knowledge, no. I used this issue and also checked the scan job logs to confirm

2022-12-01 10:47 UTC, sam-heilbron commented on hack/trivy/scan.go
> +	var scanResults error
Works for me!

2022-12-01 22:51 UTC, sam-heilbron commented on Makefile
> +.PHONY: scan-version
Yeah I like the idea. To be honest, I'm not sure what the ideal breakdown of separate makefiles would be, so i figured to keep it in one for now, close to the other security commands, and then we can migrate a whole bunch once we decide on the breakdown

2022-12-05 18:39 UTC, bewebi approved these changes
Looking good!

2022-12-05 19:48 UTC, bewebi submitted a review, later dismissed

2022-12-05 20:02 UTC, bewebi approved these changes

2022-12-05 21:13 UTC, nfuden approved these changes

2022-12-05 21:13 UTC, merged