Expose config filter accesslog v3 access log
solo-io/gloo pull request #7511
Opened 2022-12-05 18:13 UTC by ghost

# Description

Added the option to use runtime filter on access logs. 

This is one of the access log filters that is supported by envoy. 

Manual e2e test:

Build the gloo docker package: VERSION=some-version make gloo-docker -B
Run Gloo locally backed by a filesystem: https://docs.solo.io/gloo-edge/latest/installation/gateway/development/docker-compose-file/
Include the GLOO_VERSION in the up command: GLOO_VERSION=some-version docker-compose up
Update install/docker-compose-file/data/config/gateways/gloo-system/gateway-proxy.yaml
by adding a filter to an access log:

       filter:
        status_code_filter:
          comparison:
            op: GE
            value:
              runtime_key: "400"
and validate you can see in the config dump

# Context

User requested this feature to to make it easy to track access logs. 

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/2340

2022-12-05 21:52 UTC, jenshu commented on projects/gloo/api/v1/options/als/als.proto
> +    AccessLogFilter filter = 4;
how do you feel about moving this field up into the `AccessLog` message, so we don't have to repeat it for each output destination type?

2022-12-08 19:28 UTC, ashishb-solo commented on docs/data/ProtoMap.yaml
>    als.options.gloo.solo.io.AccessLog:
out of curiosity, what is the empty `docker-local` file that was added?

2022-12-08 19:30 UTC, ashishb-solo commented on test/e2e/access_log_test.go
> +								Filter: &als.AccessLogFilter{
test is a little hard to read cause the indentation is so deep. could you perhaps just break the or-filter into a separate variable?

2022-12-08 20:30 UTC, ashishb-solo commented
/kick https://github.com/solo-io/gloo/issues/7533

2022-12-08 22:43 UTC, sam-heilbron reviewed
Looking good! A couple of small comments about the tests, but appreciate having those e2e tests written.

Given this new functionality that we're exposing in the Gloo API, is it worth (perhaps in a follow up PR) outlining in our docs some valuable use cases of this filter?

2022-12-08 22:43 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +				_, err = testClients.GatewayClient.Write(gw, clients.WriteOpts{Ctx: ctx, OverwriteExisting: true})
We noticed that updating (patching) a resource occasionally can fail due to a potential bug in our codebase. Therefore, we introduced https://github.com/solo-io/gloo/blob/master/test/helpers/util.go#L20, which performs the patch and handles retries internally.

2022-12-08 22:43 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +				Eventually(func(g Gomega) {
I think when using the nested Gomega matchers, we need to ensure that the outermost Eventually succeeds. I think we need to have `Eventually(....).Should(Succeed())`.

You may want to try this out to confirm my suspicion, but I fear that the following test will pass:
```
Eventually(func(g Gomega) {
  g.Expect(1).To(Equal(2))
})
```
whereas, the following update will make it fail correctly
```
Eventually(func(g Gomega) {
  g.Expect(1).To(Equal(2))
}).Should(Succeed())
```

2022-12-08 22:43 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +				}, time.Second*21, time.Second*2)
I assume the other tests use these numbers, but any indication what the magic of 21 seconds is?

2022-12-09 12:45 UTC, nfuden commented on projects/gloo/api/v1/options/als/als.proto
> +message AndFilter {
Looking at the name here it raises a question: If the and filter has 0 sub filters how does envoy behave? Does it reject this configuration? If so we should consider adding a guard rail in the plugins/als/plugin.go

2022-12-09 14:43 UTC, jmassasolo commented on test/e2e/access_log_test.go
> +				Eventually(func(g Gomega) {
Yes, Your assumption is correct, tested it out. I will add it.

2022-12-09 14:47 UTC, jmassasolo commented on test/e2e/access_log_test.go
> +				}, time.Second*21, time.Second*2)
Not sure. I used the timeout and polling interval used in other access log tests.

2022-12-09 14:52 UTC, jmassasolo commented on projects/gloo/api/v1/options/als/als.proto
> +message AndFilter {
It takes it. filters is just set to null and is ignored.

2022-12-16 13:08 UTC, jbohanon requested changes
I don't think we're actually translating the new settings here. I think we need to implement a `copyFilterSettings` function in plugin.go to get the settings from our proto type to Envoy's and put them in the new config, then we need to update the tests to properly check for the filters config

2022-12-30 16:09 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +				_, err = testClients.GatewayClient.Write(gw, clients.WriteOpts{Ctx: ctx, OverwriteExisting: true})
Test updated

2022-12-30 17:27 UTC, jbohanon reviewed
Dismissing request change review

2022-12-30 18:56 UTC, sam-heilbron commented
/test

2022-12-30 19:05 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +				gw := gwdefaults.DefaultGateway(writeNamespace)
We can talk more about this but there are 2 ways we can apply resources to our cache:
1. Use the resourcesToCreate object, which are written for us in the JustBeforeEach of the TestContext. For this to work however, you'll need to define those resources in a BeforeEach (https://github.com/solo-io/gloo/blob/master/test/e2e/example_test.go#L117)
2. Patch the resource directly within the test (https://github.com/solo-io/gloo/blob/master/test/e2e/example_test.go#L146)

2022-12-30 19:05 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +				g.Expect(http.DefaultClient.Do(req)).ShouldNot(matchers.HaveOkResponse())
Do you think it's worth it to make this assertion even more explicit, that we're expecting a 404 response instead of not a 200?

2022-12-30 19:05 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +			}, time.Second*10, time.Second/2).Should(Succeed()) // Todo, restore to 30
Just a reminder about the TODO here

2022-12-30 19:05 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +		BeforeEach(func() {
👏

2022-12-30 19:05 UTC, sam-heilbron commented on test/e2e/access_log_test.go
> +		It("can create string access logs", func() {
I like this test a lot. What do you think about getting a 200, validating the logs don't have the request included (because of the filter), then do what you did to get a 404. To me that will explicitly demonstrate that this filter is filtering out the non-404s correctly

2022-12-30 19:05 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/als/plugin.go
> +	if err := validateFilterEnums(inFilter); err != nil {
nit: I remember we were surprised that the proto.Marshal wouldn't error with invalid enums. It might be helpful to call out in a comment why we validate the enums specifically and what can happen if we don't

2022-12-30 19:35 UTC, sheidkamp commented on projects/gloo/api/v1/options/als/als.proto
> +    repeated AccessLogFilter filters = 2 [(validate.rules).repeated = {min_items: 2}];
Because that's how they do it here: https://github.com/envoyproxy/envoy/blob/317efa53c6add02fa9533fc8f93f10f590077dca/api/envoy/config/accesslog/v3/accesslog.proto#L24

But followup question... Do we need to explicitly acknowledge the reuse of the Envoy API code? It looks like these sections were copy and pasted.

2022-12-30 19:40 UTC, sheidkamp commented on projects/gloo/api/v1/options/als/als.proto
> +    //.solo.io.envoy.config.core.v3.AccessLogFilter filter = 4;
Removed

2022-12-30 19:41 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +				gw := gwdefaults.DefaultGateway(writeNamespace)
I will take a closer look... this was an "inherited" test I didn't pay much attention to

2022-12-31 02:00 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +				g.Expect(http.DefaultClient.Do(req)).ShouldNot(matchers.HaveOkResponse())
good call

2022-12-31 02:00 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +			}, time.Second*10, time.Second/2).Should(Succeed()) // Todo, restore to 30
good catch

2022-12-31 02:12 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +		It("can create string access logs", func() {
I was putting the 200 call in the "Eventually" because I thought we needed to wait for the server to come up and accept requests. I put the 404 call after the 200 call so that if there was a delay in the logs becoming available, having the 404 in the log means that the earlier 200 should have been logged if it was going to be log.

I have updated this to a single 200 call before the eventually, but am also keeping the "not 200 in the logs" test in the eventually

2022-12-31 02:14 UTC, sheidkamp commented on projects/gloo/pkg/plugins/als/plugin.go
> +	if err := validateFilterEnums(inFilter); err != nil {
comment added

2022-12-31 02:39 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +				gw := gwdefaults.DefaultGateway(writeNamespace)
Some questions about this (for Tuesday) about the best way to approach this. There's a shared "before each", so modifying directly within the test seems appropriate, but the example is patching the virtual service, and I want to modify the Gateway which doesn't seem to have a patch function.

2023-01-03 12:10 UTC, jbohanon commented on projects/gloo/api/v1/options/als/als.proto
> +    repeated AccessLogFilter filters = 2 [(validate.rules).repeated = {min_items: 2}];
I would think it would be good to at least include somewhere in the proto or the PR comment the release or commit where the file was copied from. Could save a lot of digging later on if/when we need to update to match upstream

2023-01-03 14:44 UTC, jbohanon reviewed
Looks great so far!

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +	envoy_v32 "github.com/envoyproxy/go-control-plane/envoy/config/route/v3"
rename to something more descriptive such as `envoy_routeconfig`

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +	envoy_v31 "github.com/envoyproxy/go-control-plane/envoy/type/v3"
rename to something more descriptive such as `envoy_types`

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +	v31 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/config/core/v3"
rename to something more descriptive such as `gloo_envoy`

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +	v32 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/config/route/v3"
rename to something more descriptive such as `gloo_envoy_routeconfig`

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +	v3 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/type/v3"
rename to something more descriptive such as `gloo_envoy_types`

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +				Expect(err.Error()).To(ContainSubstring(searchStr))
If you change the error pattern in the translation, you can use the matcher `MatchError` here which will recursively check for the desired error

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin.go
> +	}
By doing this, we can check for error via `errors.Is(err, InvalidEnumValueError)` or in tests with `Expect(err).Should(MatchError(importname.InvalidEnumValueError))` instead of relying on raw string comparison
```suggestion
var (
        InvalidEnumValueError = errors.New("invalid value in Enum Field")
	WrapInvalidEnumValueError = func(filterName string, fieldName string, value string) error {
		return errors.Wrap(InvalidEnumValueError, "invalid value of %s in Enum field %s of %s", value, fieldName, filterName)
	}
```

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +		DescribeTable("Test We Correctly Handle Bad ENUM",
nit: 
```suggestion
		DescribeTable("Test We Correctly Handle Bad Enum",
```

2023-01-03 14:44 UTC, jbohanon commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +								// TODO - hardcoded values
Is this TODO going to be addressed in this PR? If not, please put your name or handle on it and a little more description

2023-01-03 14:44 UTC, jbohanon commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
Can we not nest this context in the `String Format` context beginning on L103?

2023-01-03 14:53 UTC, jbohanon approved these changes

2023-01-03 14:57 UTC, sheidkamp commented on projects/gloo/api/v1/options/als/als.proto
> +    repeated AccessLogFilter filters = 2 [(validate.rules).repeated = {min_items: 2}];
Added comment at the top of the file with (perma)link

2023-01-03 15:07 UTC, sheidkamp commented on projects/gloo/pkg/plugins/als/plugin_test.go
> +								// TODO - hardcoded values
todo addressed, removed

2023-01-03 15:09 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
We could, but we're not really testing the string formatter - that's somewhat incidental. I think the filter testing deserves its own "top level" entry independent of the output format. Let me know what you think.

2023-01-03 15:39 UTC, sheidkamp commented on projects/gloo/pkg/plugins/als/plugin.go
>  			}
I think this was from some debugging, reverting

2023-01-03 15:53 UTC, sheidkamp commented on projects/gloo/pkg/plugins/als/plugin.go
> +func translateFilter(inFilter *als.AccessLogFilter) (*envoyal.AccessLogFilter, error) {
My gut is that the best answer is "use OO/interfaces and don't pass anything either way", but going with passing as the pointer to the struct to keep things consistent across the code, as the "pass a pointer as an argument" seems to be a very common pattern.

2023-01-03 16:21 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +				gw := gwdefaults.DefaultGateway(writeNamespace)
Per our conversation removed this test.

2023-01-03 18:40 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
My question is "how valuable is this"... it looks like a substantial amount of work of get this going, to test what is really Envoy functionally (which is why I put in a smoke test instead of something comprehensive).

The biggest issue is going to be writing the matcher against the logs... we can't use a JSON matcher because we don't have JSON, we have the raw logs, and we can't use a string matcher because the JSON lines can come out in any order.

I'll take a swing at this this afternoon, but talking with Sam it seemed like his preference was to get this ticket closed (I'm out the rest of the week) than spending too much time on testing the actual functions of the filters

2023-01-03 18:46 UTC, jbohanon commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
I guess I would just argue that if we need the strings formatter tests at all, they should be in the appropriate context since we put the json tests in the json context. If we don't need them, I'm fine with that also

2023-01-03 20:15 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
I've updated the test names and added a comment to make clear what we're testing there... does this work?

2023-01-03 21:12 UTC, jbohanon commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
Did you push these changes? I don't see these changes or any of the other conversations you've resolved.

2023-01-03 21:19 UTC, sam-heilbron commented
/test

2023-01-03 21:22 UTC, jbohanon requested changes
Previous review has not been addressed

2023-01-03 21:22 UTC, jbohanon requested changes
Previous review has not been addressed

2023-01-03 21:58 UTC, sheidkamp commented on test/e2e/access_log_test.go
> +	Context("Test Filters (use string format)", func() {
They are showing up now.

2023-01-03 22:03 UTC, sam-heilbron approved these changes

2023-01-03 22:03 UTC, sam-heilbron approved these changes

2023-01-03 22:03 UTC, sam-heilbron approved these changes

2023-01-03 22:03 UTC, sam-heilbron approved these changes

2023-01-03 22:04 UTC, sam-heilbron commented
/test since this PR was opened from an account that is no longer part of the org, we need to manually trigger build-bot

2023-01-03 23:17 UTC, sheidkamp commented
/test

2023-01-04 12:53 UTC, jbohanon approved these changes

2023-01-04 14:51 UTC, jbohanon commented
closed in favor of https://github.com/solo-io/gloo/pull/7627 due to administrative difficulties with this PR.

2023-01-04 14:51 UTC, closed without merging