`glooctl check --timeout <float64>`
solo-io/gloo pull request #7523
Opened 2022-12-07 16:37 UTC by Bslabe123

# Description

Added  --timeout flag to `glooctl check` to adjust the cluster connection check timeout.

# Context

	Prior to this change we hardcoded the timeout to five seconds which was not sufficient for large clusters given the mechanics of the check. To do this check, we create a settings client and get settings in the cluster and assure that an error has not occurred. The check would ideally be O(1) but in reality is O(#settings in cluster).

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-12-07 17:10 UTC, sam-heilbron commented on changelog/v1.14.0-beta2/glooctl-check-timeout.yaml
> +    description: Added  --timeout flag to `glooctl check` to adjust the cluster connection check timeout.
👏 love the clarity of this changelog!

2022-12-07 17:10 UTC, sam-heilbron commented on docs/content/reference/cli/glooctl_check.md
> +      --timeout float                     cluster connection check timeout (default 5)
Sometimes I find timeouts confusing because it's unclear what units the timeout uses, and what it applies to. Can we clarify those two points in our docs so users know when to use this and what impact it has?

2022-12-07 17:10 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/check/root.go
> +	client, err := helpers.GetKubernetesClientWithTimeout(time.Duration(int(opts.Check.Timeout * float64(time.Second.Nanoseconds()))))
We're converting this to a duration. Any reason we wouldn't just make the timeout variable a string that we unmarshal into a duration. So the user could supply "5s" or "1m" depending on their needs?

2022-12-07 17:12 UTC, nfuden commented on projects/gloo/cli/pkg/cmd/options/options.go
> +	Timeout float64
It looks like this is not the only timeout.
Have we looked at secretclient timeout and how that is set and how it may or may not interact with this?

It seems confusing to me that we have this timeout that seems to set a default timeout and then a seperate secretclienttimeout. 
What happens if both are set and secret client timeout is higher than this timeout?

Should this be configurable in all the locations that secretclient timeout is configurable?

2022-12-07 17:14 UTC, nfuden requested changes
The general idea seems good, however I am concerned with how this diverges from the secretclienttimeout and makes no mention of it.

While I am comfortable with taking a different approach it feels like the prior art was not considered in this case and would want to understand why we are taking the different approach as well as how the two play together.

2022-12-07 19:29 UTC, Bslabe123 commented on projects/gloo/cli/pkg/cmd/check/root.go
> +	client, err := helpers.GetKubernetesClientWithTimeout(time.Duration(int(opts.Check.Timeout * float64(time.Second.Nanoseconds()))))
That would be more intuitive! Added

2022-12-09 16:08 UTC, Bslabe123 commented
See: https://github.com/solo-io/gloo/pull/7535

2022-12-09 16:08 UTC, closed without merging