Feature/expose suppress envoy headers v2
solo-io/gloo pull request #7633
Opened 2023-01-05 19:12 UTC by irateswami

# Description

This change exposes the suppress envoy headers field, within a router object. Previously the router object had no args but was present, so this is the first field to be exposed from that. 

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2023-01-05 19:16 UTC, gunnar-solo commented on changelog/v1.14.0-beta5/suppress-envoy-headers.yaml
> +    description: Sometimes its desirable to call another instance of Gloo and not pass any of the x-envoy headers, this allows that.
nit: this is a user-facing changelog.  Make it declarative (also fix `its` typo)

2023-01-05 19:18 UTC, gunnar-solo commented on projects/gloo/api/v1/options.proto
> +    Router router = 18;
I was _just about_ to complain about having an object with only 1 field, but then saw that there were several more fields that envoy stuffs into its `Router` that we may want to have later

2023-01-05 19:24 UTC, sam-heilbron reviewed
Looking great! 

Let's definitely add an e2e test to demonstrate this functionality since anytime we're messing with building a new filter config we want to verify it is accepted by envoy.

2023-01-05 19:24 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +message Router{
Let's define this in a separate router package, like we do for our other filters. See: https://github.com/solo-io/gloo/tree/master/projects/gloo/api/v1/options for some examples

2023-01-05 19:24 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +    Router router = 18;
Can we add an explanatory comment about what the Router properties are and perhaps link to envoy documents? These proto comments are published in our public api reference docs (https://docs.solo.io/gloo-edge/latest/reference/api/github.com/solo-io/gloo/projects/gloo/api/v1/options.proto.sk/#httplisteneroptions) and are generally the way that users can understand how/when to use these settings

2023-01-05 19:24 UTC, sam-heilbron commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				/**
Why is this commented out?

2023-01-05 19:24 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	if router := h.listener.Options.GetRouter(); router != nil {
Could we combine these two cases: router options defined, router options not defined so that we just build the router config (with or without options) and then append the Router filter with that configuration always?

2023-01-05 19:24 UTC, sam-heilbron commented on projects/gloo/api/v1/options.proto
> +// Router is an extension of the envoy http filters
nit: The Router is an http filter

2023-01-05 19:29 UTC, gunnar-solo commented on projects/gloo/pkg/translator/network_filters.go
> +		return envoyHttpFilters
nit:  I prefer the Terminal filter logic to be more explicitly grouped.  The code as-is could potentially be separated by someone not being careful on future edits.  Specifically:
```go
if router != nil {
  // append your changes
} else {
  // append default router
}

return envoyHttpFilters
```

2023-01-05 19:30 UTC, gunnar-solo requested changes
Some small nits which would be nice to address.  Overall looks good!

Looking for a finished e2e test before full approval, though

2023-01-05 19:40 UTC, irateswami commented on projects/gloo/api/v1/options.proto
> +    Router router = 18;
Thanks!

2023-01-05 19:41 UTC, irateswami commented on projects/gloo/pkg/translator/network_filters.go
> +	if router := h.listener.Options.GetRouter(); router != nil {
Yeah that's a good point, I can change that

2023-01-05 19:45 UTC, irateswami commented on changelog/v1.14.0-beta5/suppress-envoy-headers.yaml
> +    description: Sometimes its desirable to call another instance of Gloo and not pass any of the x-envoy headers, this allows that.
Ah that pesky apostrophe. Can you clarify what you mean by declarative?

2023-01-05 20:01 UTC, irateswami commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				/**
forgot to delete

2023-01-08 19:05 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					// Set a virtual cluster matching everything
This comment more accurately describes the test above "correctly configures envoy to emit virtual cluster statistics". What we're really doing here is configuring an http listener option to set suppressEnvoyHeaders to true.

2023-01-08 19:05 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					_, err := testClients.ProxyClient.Write(proxy, clients.WriteOpts{})
nit: can we include the Ctx in the clients.WriteOpts?

2023-01-08 19:05 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					// This will hit the virtual host with the above virtual cluster config
What is the purpose of this line? I imagine it is to ensure that in addition to Envoy containing the configuration we expect (which we assert a few lines later), it's that we can route traffic to the upstream (envoy cluster) when we set suppressEnvoyHeaders. This assertion is probably good enough, though if we wanted to make it even more expressive, we could probably assert that a response doesn't return any of the envoy headers.

2023-01-08 19:05 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					// Set a virtual cluster matching everything
Can we update this comment to clarify what we're configuring? It seems that we're explicitly not defining config for the http listener options

2023-01-08 19:05 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					// We expect the envoy configuration to contain these properties in the configuration dump
I think what you meant to say is: "We expect the envoy configuration NOT to contain these properties in the configuration dump"

2023-01-08 19:07 UTC, sam-heilbron commented on projects/gloo/api/v1/options/router/router.proto
> +option go_package = "github.com/solo-io/gloo/projects/gloo/pkg/api/v1";
I think we want the go_package to match the location of the generated go code. See https://github.com/solo-io/gloo/blob/master/projects/gloo/api/v1/options/protocol_upgrade/protocol_upgrade.proto#L5 for an example.

2023-01-08 19:09 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	if routerFilter := h.listener.GetOptions().GetRouter(); routerFilter != nil {
nit: We can consolidate these nested conditionals, since the Getter methods protect us from NPEs:
```go
if h.listener.GetOptions().GetRouter().GetSuppressEnvoyHeaders().GetValue() {
  // custom logic if user set "successEnvoyHeaders" to true
}
```

2023-01-08 19:13 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	envoyHttpFilters = append(envoyHttpFilters, plugins.MustNewStagedFilter(
In our other plugins, which are used to generate Http Filters, we use NewStagedFilter (example: https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/plugins/gzip/plugin.go#L58) and if an error occurs during marshaling (it shouldn't) we return the error. We may want to follow a similar paradigm for consistency. MustNewStagedFilter is a little misleading of a name since if an error occurs, instead of panicing we just drop the error on the floor.

2023-01-09 19:21 UTC, ianmacclancy commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				Expect(routeFilter.GetName()).To(Equal("envoy.filters.http.router"))
Are we skipping validation on the boolean value as it is returned in a format we cannot easily validate?

2023-01-10 03:09 UTC, ianmacclancy commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				Expect(routeFilter.GetName()).To(Equal("envoy.filters.http.router"))
I dont see any added comments or validation on the string value existing - opening this back up

2023-01-10 15:14 UTC, sam-heilbron requested changes
I think we've subtly changed the way we translate the HCM http filters, and we should probably just keep it as it was before. Let's hop on a call if you have any questions about this

2023-01-10 15:14 UTC, sam-heilbron commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +		Entry(
We can keep this here, but I'm not sure this is the best place for this test. At the top of these tests I see:
```
// These tests validate that the ListenerSubsystemTranslatorFactory produces Translators
// which in turn create Envoy Listeners and RouteConfigurations with expected values
// The tests are non-exhaustive, as we expect each translator to more rigorously test the
// edge cases. Instead, these tests focus on the high level Envoy resources that are created.
```

Again, we can keep them in here, but this test seems like it fits more with the tests defined in translator_test.go, which perform similar validation to this test

2023-01-10 15:14 UTC, sam-heilbron commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				typedConfig, err := sslutils.AnyToMessage(hcmFilter.GetConfigType().(*envoy_config_listener_v3.Filter_TypedConfig).TypedConfig)
I would check out https://github.com/solo-io/gloo/blob/master/projects/gloo/pkg/translator/translator_test.go#L395 for an example of unmarshaling this configuration to the proper types. It uses a utility to simplify this, as well as allows us to assert values on types, not just typeUrls

2023-01-10 15:14 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	var err error
I don't think this is a safe change. 
Previously we would compute all http filters, and if we encountered an error we would add it to a report (put the status on the top level gateway resource) and continue. This way all valid http filters would be placed on the HCM.

Now if we encounter an error, we return an empty network filter.

2023-01-10 15:14 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	if err != nil {
We should be following the same pattern that we do above:

1. Create the filter
2. If it succeeds, append it
3. If it fails, add it as an error to the report

2023-01-10 15:40 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	var err error
https://github.com/solo-io/gloo/pull/7633#discussion_r1065905640

We wouldn't be appending a filter in a bad state, we would be adding that to the report.

2023-01-11 03:36 UTC, sam-heilbron reviewed
LGTM! Mostly nits. I think we can clarify some of the testing challenges in a huddle tomorrow

2023-01-11 03:36 UTC, sam-heilbron commented on projects/gloo/pkg/translator/network_filters.go
> +	var err error
I think we can delete this as it is unused

2023-01-11 03:36 UTC, sam-heilbron commented on test/e2e/happypath_test.go
> +					// This will hit the virtual host with the above virtual cluster config
We can sync tomorrow on this. The example_test (https://github.com/solo-io/gloo/blob/master/test/e2e/example_test.go#L57) provides an example for how we can route to a destination.

It works because in the setup we initialize a server, and an upstream referencing that server: https://github.com/solo-io/gloo/blob/master/test/e2e/test_context.go#L75.

`TestUpstreamReachable()` performs a request that hits a service as well

2023-01-11 03:36 UTC, sam-heilbron commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				Expect(hcm.HttpFilters).To(HaveLen(2))
We should be consistent with the Offset we use in a test. https://onsi.github.io/gomega/#making-assertions-in-helper-functions

```
To get around this, Gomega provides versions of Expect, Eventually and Consistently named ExpectWithOffset, EventuallyWithOffset and ConsistentlyWithOffset that allow you to specify an offset in the call stack. 
```

2023-01-11 03:36 UTC, sam-heilbron commented on projects/gloo/pkg/translator/listener_subsystem_test.go
> +				ExpectWithOffset(1, filterChain.GetFilterChainMatch()).To(BeNil())
It doesn't hurt to have this, but is this validating something in particular? This seems irrelevant to what we're validating

2023-01-11 14:17 UTC, gunnar-solo commented on projects/gloo/pkg/translator/network_filters.go
> +	envoyHttpFilters = append(envoyHttpFilters, newStagedFilter.HttpFilter)
thanks for the adjustment, here (as opposed to the original iteration).  I enjoy the choice of assembly pattern, rather than having 2 different `return` paths

2023-01-11 14:18 UTC, gunnar-solo commented on test/e2e/happypath_test.go
> +				It("it correctly DID NOT pass the suppress envoy headers config", func() {
chuckling at this assertion text

2023-01-12 15:59 UTC, ianmacclancy requested changes

2023-01-12 15:59 UTC, ianmacclancy commented on test/e2e/happypath_test.go
> +					headers := response.Header
Extra lines from testing - need to pull these out

2023-01-12 17:14 UTC, ianmacclancy approved these changes
LGTM!

2023-01-12 17:26 UTC, sam-heilbron approved these changes

2023-01-12 18:03 UTC, merged