Optional Ports
solo-io/gloo pull request #7646
Opened 2023-01-09 14:57 UTC by Bslabe123

# Description

Please include a summary of the changes.

This bug fixes ... \ This new feature can be used to ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-01-10 15:56 UTC, ben-taussig-solo commented on install/helm/gloo/generate/values.go
> +	WasmCachePortExposed  *bool             `json:"wasmCachePortExposed, omitempty" desc:""`
Can we get a description for this field?

2023-01-10 16:00 UTC, Bslabe123 commented on install/helm/gloo/generate/values.go
> +	WasmCachePortExposed  *bool             `json:"wasmCachePortExposed, omitempty" desc:""`
Sure! But is there any more info I can put in the description that the name doesn't already convey or do we just want descriptions on all fields?

2023-01-10 16:02 UTC, ben-taussig-solo commented on install/helm/gloo/generate/values.go
> +	MonitoringPortExposed          *bool                        `json:"monitoringPortExposed,omitempty"`
Can we get descriptions for `MonitoringPortExposed` and `ConfigDumpServicePortExposed`?

2023-01-10 16:15 UTC, ben-taussig-solo commented on install/helm/gloo/templates/8-gateway-proxy-service.yaml
> +{{- if and $spec.failover.enabled $spec.failover.port }}
I think we might need to update the description for failover to call out that setting the port to 0 will disable it

2023-01-10 16:17 UTC, ben-taussig-solo commented on install/helm/gloo/templates/8-gateway-proxy-service.yaml
> +{{- end }} {{/* if .Values.gatewayProxies.gatewayProxy.configDumpServicePortExposed */}}
I might just be missing it, but I don't see an `{{- if ... }}` matching this `{{- end }}` -- are we sure that `configDumpServicePortExposed` is working properly here

2023-01-10 16:20 UTC, ben-taussig-solo commented on install/helm/gloo/generate/values.go
> +	WasmCachePortExposed  *bool             `json:"wasmCachePortExposed, omitempty" desc:""`
I think we want descriptions for all fields. Also I think it's important to describe:
 - the default value (probably true?)
 - What port gets exposed if this is set to true

2023-01-10 16:21 UTC, ben-taussig-solo commented
The helm changes look good for the most part, but I think we need a lot more testing -- can you add more helm tests to cover all of the additions to the helm chart

2023-01-10 16:24 UTC, Bslabe123 commented on install/helm/gloo/templates/8-gateway-proxy-service.yaml
> +{{- end }} {{/* if .Values.gatewayProxies.gatewayProxy.configDumpServicePortExposed */}}
Thats correct, Just caught that when running through the adding of descriptions

2023-01-10 19:32 UTC, Bslabe123 commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +        {{- if $global.istioSDS.enabled }}
If istioSDS is disabled it wouldnt make sense to expose this port so it gets guareded by `if $global.istioSDS.enabled`, this new description is now included in the next commit

2023-01-13 14:44 UTC, ben-taussig-solo commented on install/test/helm_test.go
> +						rb = ResourceBuilder{
Why do we get the service twice in this test? can we just call `testManifest.Expect("Service", gatewayProxyMonitoringService.Namespace, gatewayProxyMonitoringService.Name).To(BeNil())` (currently line 2686) on line 2675?

2023-01-13 14:46 UTC, ben-taussig-solo commented on install/test/helm_test.go
> +								"gateway.validation.enabled=false",
Can you explain why we need to disable validation here?

2023-01-16 14:54 UTC, Bslabe123 commented on install/test/helm_test.go
> +								"gateway.validation.enabled=false",
Its not any new behavior, it's just to show that all ports on this service can be disabled. Its slightly neater and makes the test slightly smaller.

2023-01-16 16:04 UTC, ben-taussig-solo commented on install/test/helm_test.go
> +					It("Should disable ports when zeroed/toggled", func() {
Nit: "should disable ports when zeroed/toggled for gateway-proxy deployment"

2023-01-16 16:20 UTC, ben-taussig-solo commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
>          - containerPort: 8234
Update: there is not -- it is hardcoded to 8234 everywhere in our helm charts. I think we should leave this as is because this port might /need/ to be 8234

2023-01-16 16:20 UTC, ben-taussig-solo submitted a review, later dismissed
Looks good, new settings are all tested

2023-01-16 16:32 UTC, ben-taussig-solo submitted a review, later dismissed
Reapproving after Brendan updated some test names :)

2023-01-16 17:28 UTC, jenshu commented on install/helm/gloo/generate/values.go
> +	Enabled    *bool   `json:"enabled,omitempty" desc:"(Enterprise Only): Configure this proxy for failover (note: setting the port to 0 will disable failover)"`
this is a boolean. should it say "setting this field to false will disable failover" ? or was the comment supposed to be added on the `port` field below instead?

2023-01-16 17:45 UTC, Bslabe123 commented on install/helm/gloo/generate/values.go
> +	Enabled    *bool   `json:"enabled,omitempty" desc:"(Enterprise Only): Configure this proxy for failover (note: setting the port to 0 will disable failover)"`
More of just a notice that another field could also have the same effect as this one, changed the desciptions so we call it out on both fields now

2023-01-16 17:57 UTC, jenshu commented on install/helm/gloo/templates/1-gloo-deployment.yaml
>              port: {{ .Values.gloo.deployment.xdsPort }}
this also relies on xdsPort. should the readiness probe be disabled if xdsPort=0?

2023-01-16 17:59 UTC, Bslabe123 commented on install/helm/gloo/templates/1-gloo-deployment.yaml
>              port: {{ .Values.gloo.deployment.xdsPort }}
Unless xdsPort still appears under `ports:` if we leave the readiness probe in then I dont see a reason to disable it

2023-01-16 20:36 UTC, jenshu requested changes
there seem to be some other places where we still need to disable certain things if port=0, e.g. settings, configmaps, and other places where these ports are referenced

2023-01-16 20:36 UTC, jenshu commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +{{- if .Values.gloo.deployment.restXdsPort }}
the readinessProbe should have a separate check because it's using xdsPort vs restXdsPort

2023-01-17 16:35 UTC, Bslabe123 commented
See: https://github.com/solo-io/gloo/pull/7687

2023-01-17 16:35 UTC, closed without merging