Optional Ports for gateway-proxy pods and services
solo-io/gloo pull request #7687
Opened 2023-01-17 16:06 UTC by Bslabe123

# Description

When we create Gloos k8s manifest via helm we expose all ports on gateway-proxy pods/services by default. In certain situations it may be prudent to not allow traffic on certain ports (i.e. HTTPS but no HTTP traffic). There also may be situations in which leaving a port open may lead to unneeded resources being created (as mentioned in the issue, hyperscaler firewall rules). We would like to introduce a toggle/convention to allow anyone building helm charts to disable the exposing of certain ports on gateway-proxy pods/services.

# Context

We have decided to make 0 a reserved value indicating that the port should be disabled, when rendering the helm chart we wrap the port declaration in an if(port != 0)/else statement. We also call this out loudly in the field description since its a less explicit toggle. For hardcoded ports (i.e. configDumpServicePortExposed) we introduce dedicated toggle instead.

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-01-17 18:14 UTC, ben-taussig-solo approved these changes

2023-01-17 21:03 UTC, sam-heilbron requested changes
@jenshu raises a good point about the relationship between `disableHttpGateway` and setting httpPort=0 on gateway-proxy. Why do we need both flags?

2023-01-17 21:03 UTC, sam-heilbron commented on install/helm/gloo/templates/8-gateway-proxy-service.yaml
> +  {{- if and (not $gatewaySettings.disableHttpsGateway) $spec.service.httpsPort }}
Is it the service httpsPort or the podTemplate httpsPort that should be part of the conditional?

2023-01-17 21:03 UTC, sam-heilbron commented on install/helm/gloo/templates/8-gateway-proxy-service.yaml
> +{{- if and .Values.global.glooStats.enabled .Values.global.glooStats.serviceMonitorEnabled }}
Is this related to the http(s) port disabling or just an additional change?

2023-01-17 21:35 UTC, jenshu commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +{{- end }}
i think this change should be undone

2023-01-18 17:29 UTC, Bslabe123 commented
See: https://github.com/solo-io/gloo/issues/7377#issuecomment-1387445788

2023-01-18 17:29 UTC, closed without merging