7659 disable envoy core dumps
solo-io/gloo pull request #7740
Opened 2023-01-26 18:56 UTC by ashishb-solo

# Description

Provide a means to disable core dumps by setting an environment variable `DISABLE_CORE_DUMPS`. This value can also be set at the time of installation by running `helm install --set gatewayProxies.gatewayProxy.disableCoreDumps=true ...`

# Context

Users needed this feature to disable core dumps

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-01-26 19:25 UTC, ben-taussig-solo commented on install/test/helm_test.go
> +							// testManifest.Expect("Deployment", "Spec.Template.Spec.Containers[0].Env", "Value").To(Equal("true"))
Should this be uncommented?

2023-01-26 19:27 UTC, ben-taussig-solo commented
changes look good, evaluating manually before proceeding with approval

2023-01-26 19:28 UTC, ashishb-solo commented on install/test/helm_test.go
> +							// testManifest.Expect("Deployment", "Spec.Template.Spec.Containers[0].Env", "Value").To(Equal("true"))
nee, it should be deleted. thanks for the catch

2023-01-26 19:30 UTC, ashishb-solo commented on install/test/helm_test.go
> +							// testManifest.Expect("Deployment", "Spec.Template.Spec.Containers[0].Env", "Value").To(Equal("true"))
https://github.com/solo-io/gloo/pull/7740/commits/2cdb1cadb87a980a83e4e4f092e0696dab436c77

2023-01-26 19:50 UTC, nfuden commented on install/test/helm_test.go
> +						It("can set the DISABLE_CORE_DUMPS environment variable", func() {
Do we see passing any other env vars in the future like this?
If so do we think it make sense to parameterize this? 

Also happy to punt on that aspect as its definitely not needed

2023-01-26 19:53 UTC, nfuden commented on projects/envoyinit/cmd/docker-entrypoint.sh
> +set -eu
Is there a specific reason we are using u? Or just doing this to align to best practices?

2023-01-26 19:57 UTC, ashishb-solo commented on projects/envoyinit/cmd/docker-entrypoint.sh
> +set -eu
I tend to prefer strictness in bash scripts, but was also a bit ambivalent on this, since it's a fairly straightforward start-up script and if it fails due to some unknown reason, then the deployment will just never start. I have tested it extensively though. Thoughts? I'm happy to revert this.

2023-01-26 20:14 UTC, ashishb-solo commented on projects/envoyinit/cmd/docker-entrypoint.sh
> +set -eu
On the other hand, `-u` only raises an error if there are undefined variables, and there are only 2 variables in the script, both of which have default values, so I don't think it adds any harm to have `-u` in there for now.

2023-01-26 21:15 UTC, nfuden submitted a review, later dismissed

2023-01-26 21:22 UTC, sam-heilbron commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- if $spec.logLevel }}
I think this was unintentional and should be removed?

2023-01-27 14:09 UTC, ashishb-solo commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- if $spec.logLevel }}
I don't think so. I'm not sure why they're showing up in the diff, but those lines have been there since 2021: https://github.com/solo-io/gloo/blame/4e0a6f170cbc8670557092b151fd8edca3438411/install/helm/gloo/templates/7-gateway-proxy-deployment.yaml#L205

2023-01-27 14:16 UTC, ashishb-solo commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- if $spec.logLevel }}
And this seems to be present in our other deployments too, so I think it belongs there:
https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/1-gloo-deployment.yaml#L229
https://github.com/solo-io/gloo/blob/master/install/helm/gloo/templates/3-discovery-deployment.yaml#L90

2023-01-27 15:05 UTC, jenshu commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- if $spec.logLevel }}
it was removed recently via https://github.com/solo-io/gloo/pull/7717

probably just a merge issue caused it to get added back

2023-01-27 15:06 UTC, jenshu requested changes
need to remove the logLevel

2023-01-27 15:10 UTC, ashishb-solo commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +      {{- if $spec.logLevel }}
Got it, thanks! I've removed it: https://github.com/solo-io/gloo/pull/7740/commits/9a8e4d4eeba5235b50e314cc6ff63cb1d436bf1f

2023-01-27 15:38 UTC, ben-taussig-solo approved these changes
Got on a call with Ashish who demo'd this functionality working as expected in the PR description

2023-01-27 15:45 UTC, ashishb-solo commented
Thanks! Just need @jenshu to resolve the review and @nfuden to approve again

2023-01-27 15:50 UTC, jenshu approved these changes

2023-01-27 15:50 UTC, merged