Create .trivyignore to resolve security alerts
solo-io/gloo pull request #7815
Opened 2023-02-08 14:22 UTC by ben-taussig-solo

# Description
 - Creates a `.trivyignore` file, which is set to ignore [CVE-2022-41721](https://nvd.nist.gov/vuln/detail/CVE-2022-41721)
 - This CVE does not affect the gateway-proxy image, therefore we can ignore it

2023-02-08 15:07 UTC, ashishb-solo approved these changes

2023-02-08 15:53 UTC, sam-heilbron requested changes
Can you include steps to verify these changes? I agree that adding this CVE to the trivyignore will skip it, but I found when running locally that other vulnerabilities were identified. I was using trivy version v0.30 (matching CI)

2023-02-08 15:53 UTC, sam-heilbron commented on changelog/v1.14.0-beta10/security-update.yaml
> +      Create .trivyignore file and ignore CVE-2022-41721, a vulnerability in golang.org/x/net.
Love the description here!

2023-02-08 19:54 UTC, ben-taussig-solo commented
> Can you include steps to verify these changes? I agree that adding this CVE to the trivyignore will skip it, but I found when running locally that other vulnerabilities were identified. I was using trivy version v0.30 (matching CI)

The following script validates OSS releases -- it scans the problematic versions, then checks out and builds the fix branches ([v1.11.x fix branch](https://github.com/solo-io/gloo/pull/7820), [v1.10.x fix branch](https://github.com/solo-io/gloo/pull/7819)), then scans the built images. After running this, you can look through `_output/scans` to confirm that the fix branches resolve the issue. There are still issues with some LTS branches in enterprise -- I propose we move ahead with the OSS fixes (I.E, merge this PR are the ones linked above) and then wrap up the enterprise fixes after that.

```sh
# iterate over all affected versions
for oss_version in v1.10.43 v1.11.50 v1.12.42; do
    # create a new directory for each version
    TAGGED_VERSION=$oss_version make scan-version
done

# iterate over fix branches. note that v1.12 does not require a fix branch, as the trivyignore updates allow the scan to go through
for fixed_oss_branch in security-update-yaml-1-10 security-update-yaml-1-11; do
    export VERSION=$fixed_oss_branch
    # checkout and build the version with the fix
    git checkout $fixed_oss_branch
    make docker

    # come back to the security-update-net branch
    git checkout security-update-net

    # scan the fixed version
    make scan-version
done
```

2023-02-09 00:06 UTC, sam-heilbron commented on Makefile
> +.PHONY: scan-enterprise-version
Happy to have this here if you think it's valuable, but it feels like this leaks implementation details of our enterprise project. There is a make target in the enterprise repo https://github.com/solo-io/solo-projects/blob/master/Makefile#L1781 which you can use to scan those images if you'd like

2023-02-09 18:15 UTC, ben-taussig-solo commented on Makefile
> +.PHONY: scan-enterprise-version
gotcha -- I was not aware of the enterprise make target, I will remove this

2023-02-09 18:16 UTC, ben-taussig-solo commented on Makefile
> +.PHONY: scan-enterprise-version
Removed here: https://github.com/solo-io/gloo/pull/7815/commits/f9f9449ac864bceb08bd460290a776676396c52b

2023-02-10 17:15 UTC, Bslabe123 commented
> > Can you include steps to verify these changes? I agree that adding this CVE to the trivyignore will skip it, but I found when running locally that other vulnerabilities were identified. I was using trivy version v0.30 (matching CI)
> 
> The following script validates OSS releases -- it scans the problematic versions, then checks out and builds the fix branches ([v1.11.x fix branch](https://github.com/solo-io/gloo/pull/7820), [v1.10.x fix branch](https://github.com/solo-io/gloo/pull/7819)), then scans the built images. After running this, you can look through `_output/scans` to confirm that the fix branches resolve the issue. There are still issues with some LTS branches in enterprise -- I propose we move ahead with the OSS fixes (I.E, merge this PR are the ones linked above) and then wrap up the enterprise fixes after that.
> 
> ```shell
> # iterate over all affected versions
> for oss_version in v1.10.43 v1.11.50 v1.12.42; do
>     # create a new directory for each version
>     TAGGED_VERSION=$oss_version make scan-version
> done
> 
> # iterate over fix branches. note that v1.12 does not require a fix branch, as the trivyignore updates allow the scan to go through
> for fixed_oss_branch in security-update-yaml-1-10 security-update-yaml-1-11; do
>     export VERSION=$fixed_oss_branch
>     # checkout and build the version with the fix
>     git checkout $fixed_oss_branch
>     make docker
> 
>     # come back to the security-update-net branch
>     git checkout security-update-net
> 
>     # scan the fixed version
>     make scan-version
> done
> ```

Just verified this script I'm happy to sign off if sam doesnt have any other concerns!

2023-02-13 14:41 UTC, nfuden commented on .trivyignore
> +# No handlers exposed by the control plane fall victim to this attack
nit: can we add the info that its due to no usage of the maxbyteshandler?

2023-02-13 14:56 UTC, sam-heilbron approved these changes

2023-02-13 16:09 UTC, ben-taussig-solo commented on .trivyignore
> +# No handlers exposed by the control plane fall victim to this attack
resolved here: 442448cbfbbc0a52e538fc96fa69ca95311a6874

2023-02-13 17:02 UTC, sam-heilbron approved these changes

2023-02-13 18:42 UTC, Bslabe123 submitted a review, later dismissed

2023-02-14 20:12 UTC, sam-heilbron approved these changes

2023-02-14 20:35 UTC, Bslabe123 approved these changes

2023-02-15 18:13 UTC, merged