refactor(ssl.proto): extracted from `v1` package to `ssl` package
solo-io/gloo pull request #7817
Opened 2023-02-08 15:47 UTC by gunnar-solo

# Description
TL;DR:
make this change:
`ssl.proto`
```proto
-option go_package = "github.com/solo-io/gloo/projects/gloo/pkg/api/v1";
+option go_package = "github.com/solo-io/gloo/projects/gloo/pkg/api/v1/ssl";
```

then fix resulting build errors

# Context
This is meant to support https://github.com/solo-io/gloo/issues/7693 by preventing a circular dependency caused by adding an `ssl_config` field to `dynamic_forward_proxy.proto`.  It both
a) resolves said circular dependency via refactor
b) adds the field, to prove it _is_ resolved

a follow-up PR will actually _consume_ said new field

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-02-08 21:46 UTC, nfuden commented on changelog/v1.14.0-beta10/7693-refactor-ssl.yaml
> +  descrption: Extract the generated files from `ssl.proto` into their own go package.  This is meant to support a follow-up PR by resolving a circular dependency
```suggestion
  description: Extract the generated files from `ssl.proto` into their own go package.  This is meant to support a follow-up PR by resolving a circular dependency where ssl can be used in more places.
```

2023-02-08 22:52 UTC, elcasteel commented on projects/gloo/api/v1/ssl.proto
> -option go_package = "github.com/solo-io/gloo/projects/gloo/pkg/api/v1";
I'm not super well versed in conventions here, but should we also move this to a new directory?

2023-02-08 22:54 UTC, elcasteel commented
Have you attempted the solo-projects side of this change? Maybe worth doing a draft of that so that we don't accidentally prevent ourselves from being able to bump to a new gloo version if it turns out to require more than a few hours of work.

2023-02-09 13:50 UTC, jbohanon commented on changelog/v1.14.0-beta10/7693-refactor-ssl.yaml
> +  descrption: description: Extract the generated files from `ssl.proto` into their own go package.  This is meant to support a follow-up PR by resolving a circular dependency where ssl can be used in
looks like LCB is displeased with this yaml

2023-02-09 15:24 UTC, nfuden commented on changelog/v1.14.0-beta10/7693-refactor-ssl.yaml
> +- type: NON_USER_FACING
Is this breaking for people using gloo as a library for their controllers?

2023-02-09 15:30 UTC, jenshu commented on changelog/v1.14.0-beta10/7693-refactor-ssl.yaml
> +- type: NON_USER_FACING
yes. i wish solo-apis had its own changelogs

2023-02-13 19:45 UTC, jenshu commented on install/helm/gloo/crds/gateway.solo.io_v1_Gateway.yaml
> +                          sslConfig:
do we know what's causing the CRD updates?
moving the import to another pkg shouldn't have an effect on the CRDs, right?

2023-02-13 19:46 UTC, jenshu commented on projects/gloo/api/v1/options/dynamic_forward_proxy/dynamic_forward_proxy.proto
> +  .gloo.solo.io.UpstreamSslConfig ssl_config = 3;
oh i see. should this be removed from this PR and added to the follow-up instead?

2023-02-13 20:15 UTC, jenshu requested changes
LGTM aside from the addition in dfp proto which should be a separate PR

2023-02-13 21:52 UTC, jenshu approved these changes

2023-02-13 22:09 UTC, nfuden approved these changes

2023-02-14 05:09 UTC, merged