refactor(upgrade): simplify return branches of GetUpgradeVersions
solo-io/gloo pull request #8117
Opened 2023-04-21 17:43 UTC by gunnar-solo

# Description
Fixed a bug where `changelog` directory would always be dependent on `gloo` repository

_and_

offered a refactor of said method to make it easier to develop on

# Checklist:
- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/master/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-04-21 17:45 UTC, gunnar-solo commented on test/kube2e/upgrade/upgrade_utils.go
> +func GetUpgradeVersions(ctx context.Context, repoName string) (*versionutils.Version, *versionutils.Version, error) {
since this is a full refactor of the `GetUpgradeVersions` method, I recommend not using the delta view

2023-04-21 18:43 UTC, gunnar-solo commented
/kick https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=d983fa90-3d63-4d73-a37a-670ffefb6067

2023-04-21 20:46 UTC, ianmacclancy commented on test/kube2e/upgrade/upgrade_utils.go
> +	// get the latest and upcoming releases of the current branch
flow order nit: We get the files, get the git client, use the files, then use the github client. Let's get the files, use the files, get the github client, use the github client

2023-04-21 20:50 UTC, ianmacclancy requested changes
Ordering and description changes

2023-04-21 20:50 UTC, ianmacclancy commented on test/kube2e/upgrade/upgrade_utils.go
> +//   - 😃 (prevLtsRelease, latestRelease, nil)
Not sure what we are saying with these options. The mid option is actually an expected situation so would also be a smile?
If we want to break down the possible options we could be more informative 
- val, val, nil - we have all versions we want, no errors
- val, nil, nil - we are testing the first release of a minor version, no errors
- nil, nil, err - we are unable to fetch versions for upgrade tests

2023-04-24 15:21 UTC, bewebi commented on test/kube2e/upgrade/upgrade_utils.go
> +//   - (prevLtsRelease, nil, nil):           only prevLtsRelease computable
```suggestion
//   - (prevLtsRelease, nil, nil):           only prevLtsRelease computable (ie current branch has never been released)
```
The inline comment explains this case, but I think it's helpful here as well
Feel free to reword

2023-04-24 15:41 UTC, ianmacclancy approved these changes

2023-04-24 16:39 UTC, merged