Backport Regex Fixes - 1.13
solo-io/gloo pull request #8183
Opened 2023-05-02 19:26 UTC by ianmacclancy

# Description
hand cherrypick changes from [PR: 8143](https://github.com/solo-io/gloo/pull/8143/files)

RouteOptions HostRewriteType_RewritePathRegex does not exist in 1.13 but does in 1.14 onwards so these changes had to be excluded

2023-05-02 19:38 UTC, bewebi submitted a review, later dismissed
Guessing buildbot failure is a flake

2023-05-02 19:39 UTC, gunnar-solo commented
/kick https://console.cloud.google.com/cloud-build/builds;region=global/fed4a777-cfd1-4ed0-86aa-01bd63119ab1?project=solo-public

2023-05-02 19:39 UTC, gunnar-solo submitted a review, later dismissed

2023-05-02 19:54 UTC, ianmacclancy commented
/kick same petstore flake

2023-05-02 21:46 UTC, ianmacclancy commented
/kick - petstore issue

2023-05-03 13:23 UTC, ianmacclancy commented
/kick

2023-05-03 16:06 UTC, sam-heilbron requested changes

2023-05-03 16:49 UTC, ianmacclancy commented on changelog/v1.13.17/routeoptions-regex-validation.yaml
> +    description: >-
This is called out in the pr description, missed the update to the changelog in the backport

2023-05-03 18:38 UTC, sam-heilbron approved these changes

2023-05-03 19:19 UTC, bewebi approved these changes

2023-05-03 19:20 UTC, merged