Oauth2 ClaimsToMetadata API
solo-io/gloo pull request #8257
Opened 2023-05-19 19:07 UTC by jmhbh

# Description
- This API change on the `OidcAuthorizationCode` and `AccessTokenValidation` will allow us to proceed with implementation in the `ext-auth-service` to support extracting claims from either the `IdToken` or `AccessToken` for the `OidcAuthorizationCode` flow or from the `AccessToken` for the `AccessTokenValidation` flow. 

# Context:
- Currently, in Gloo Platform, we cannot pair an ext-auth policy with `AccessTokenValidation` configured with a rate limit policy, and in order to configure a rate limit and ext auth policy for the OIDC flow we require an additional JWT policy to extract the claims from the id/accesstoken to headers. 
- In order to add support for configuring a rate limit policy in Gloo Platform with an ext-auth policy that uses any OAuth2 flow. We landed on an approach in this [design doc](https://soloio.slab.com/posts/portal-support-o-auth-security-for-usage-plans-ykvns72m) to enrich the current API with a `ClaimsToMetadata` API that would allow us to implement changes in the ext-auth-service to extract the claims from a token and emit it as dynamic metadata to be consumed by the rate limit filter.
- The idea is that a user configuring an ext auth policy using OIDC with this new API and would like claims to be extracted and emitted as metadata from the idToken and accessToken would do the following:
```
apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oidc-auth
  namespace: gloo-mesh
spec:
  applyToRoutes:
    - route:
        labels:
          oauth: "true"
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
      cluster: cluster-1
    glooAuth:
      configs:
        - oauth2:
            oidcAuthorizationCode:
              ...
              claimsToMetadata:
                 idToken:
                 - claim: sub
                    metadataKey: userId
                 accessToken:
                 - claim: custom_claim
                    metadataKey: customClaimKey
```
Similarly for a user configuring an ext auth policy that uses AccessValidation and want to extract claims from the accessToken and emit metadata that is consumed by the rate limit filter would do the following:

```             
apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: access-validation-auth
  namespace: gloo-mesh
spec:
  applyToRoutes:
    - route:
        labels:
          oauth: "true"
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
      cluster: cluster-1
    glooAuth:
      configs:
        - oauth2:
             accessTokenValidationConfig: 
                ...
              claimsToMetadata:
                 accessToken:
                 - claim: sub
                    metadataKey: userId
                 - claim: custom_claim
                    metadataKey: customClaimKey                
```

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/main/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-05-22 19:37 UTC, marcogschmidt reviewed
Thanks for documenting the PR so well! I think we can simplify the API a bit, let me know what you think.

2023-05-22 19:37 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    AccessToken access_token = 2;
After thinking more about this and looking the examples you added (thanks!), I am wondering whether we need this distinction in the API. My thinking:
- `AccessTokenValidation` only concerns itself with the `access_token`. It currently ignores the `id_token` and I think it should continue doing so. Therefore we don't need any config related to the `id_token` there.
- `OidcAuthorizationCode`: the docs for that field say `can also authorize the access token if configured`, but looking at the code I don't find any logic to validate the `access_token`; all we seems to be doing is adding it to a header. The text might refer to [this commented out config](https://github.com/solo-io/gloo/blob/becaafbd0222e440172e042a506b28f6537fa305/projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto#L639); this is supported by the fact that both have been added in [the same PR](https://github.com/solo-io/gloo/pull/3171). To be able to extract the claims here we would need to parse the `access_token`, but since there is not guarantee that it is a JWT, we would need to basically repeat what we are doing in the `AccessTokenValidation` API, which I think we should not do, even more so because we can chain the two auth existing steps to achieve this (*). TL;DR similar comment to the previous bullet point, i.e. that we do not need to account for the `access_token` here.

(*) If the user wants to use OIDC to authenticate and then also validate the `access_token` and extract claims they can do something like this:

```yaml
apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: oidc-auth
  namespace: gloo-mesh
spec:
  applyToRoutes: [] #omitted for brevity
  config:
    server: {} #omitted for brevity
    glooAuth:
      configs:
      - oauth2:
          oidcAuthorizationCode: {} #omitted for brevity
      - accessTokenValidationConfig:
          # either JWT or introspection
          claimsToMetadata:
            usagePlan: usage-plan-id
```

2023-05-22 19:37 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    }
Assuming that we apply the suggestion in my previous comment, the `claims_to_metadata` fields might just be simple string/string maps.

2023-05-22 19:37 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +        string claim = 1;
Some questions:
- what if the claim is not a simple string data type? (e.g. it's a list, an object, a comma-separated list (e.g. scopes), a bool, etc)
- can it contain special characters? Thinking specifically about `.`, which in the future we might want to use to access nested data, e.g. using XPath notation

We should document the valid format for this field here.

2023-05-22 20:54 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    AccessToken access_token = 2;
This makes sense, thanks for the comment. I took a look at the code as well, and it doesn't look like we're parsing the accessToken at all so this approach makes more sense.

2023-05-22 21:03 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +        string claim = 1;
This is a good callout, we should document that the data type of the claim value can be any of a list, an object, or a bool. In terms of special characters, I don't see why the value cannot contain them. I think for the rate limit use case we will primarily be interested in the claim value being a simple string, but there potentially could be a future use case where we could leverage the claim value containing special characters? Either way since we are just passing this on as dynamic metadata we shouldn't add any logic that will prevent claim values with special characters from being passed on within the ext-auth-service.

2023-05-23 20:35 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +        string claim = 1;
I was referring to the value of the field that we use to look up the claim, I realize that was not clear, sorry. I think that we should validate that it is just a DNS label (same as labels, annotations, etc), so it can contain only `[a-zA-Z\-_]` chars. Example:

```yaml
claimsToMetadata:
  sub: subject # ok
  my-claim: myClaim # ok
  foo.bar: fooBar # invalid 
```

So you plan on handling claims of any type? So that means that we will copy whatever structure that claim has to the dynamic metadata right (which is possible since it's proto `Struct` field)?

2023-05-23 20:39 UTC, marcogschmidt requested changes

2023-05-23 20:39 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    //   email: email
I think we should invert the order of claim name and MD field name here. That way:
- we can automatically guarantee that metadata keys will be unique
- we allow users to copy the same claim to more than one field (can't see why they would do that, but since we get this for free, why not?)

2023-05-23 20:39 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // claim values can be a bool, string, or list and can contain special characters.
We should say that claims can be on any type and that their structure will be reflected in the dynamic metadata entry 1:1.

2023-05-23 20:47 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +        string claim = 1;
gotcha, that makes sense. The types of the claim value should be either a list, a bool or a string, and in the `ext-auth-service` we will determine the type of the claim value and use the approiate type `structpb.Value_StringValue`, `structpb.Value_ListValue` or `structpb.Value_BoolValue`. The dynamic metadata has the `Struct` type and the claim value could be any json value, but in order to create the correct data structure we would have to recursively figure out each type within the json object. I think we should start with supporting the claim value being a bool, string or list for now and if we get a request to support the claim value being a complex json object we could tackle it then.

2023-05-23 20:47 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    //   email: email
that makes sense, will make this change.

2023-05-24 14:43 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // When specified, the matching claims from the access token will be emitted as dynamic metadata.
```suggestion
    // When specified, the matching claims from the ID token will be emitted as dynamic metadata.
```

2023-05-24 14:43 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // claim values can be a bool, string, or list.
Here we should just say that the structure of the claim will be preserved in the metadata struct.

2023-05-24 14:43 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    map<string, string> metadata_keys_to_claim = 20;
Name implies MD -> claims. Should be something like `dynamic_metadata_from_claims` or `claims_to_dynamic_metadata`.

2023-05-24 14:46 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // Note that metadata keys must be unique, and the claim names must match the regular expression for DNS labels `[a-zA-Z\-_]`.
Thanks, I forgot to update this after the implementation yesterday. The correct regex should actually be `^[a-zA-Z\-_]*$`

2023-05-24 14:49 UTC, jmhbh commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // Note that metadata keys must be unique, and the claim names must match the regular expression for DNS labels `[a-zA-Z\-_]`.
well, this regex should only apply for the claim key and not the fields within the claim value. AFAIK, the claim names should only contain lower/upper case alphabets with `-` or `_` as separators so the DNS label actually makes sense to me.

2023-06-12 19:00 UTC, rinormaloku submitted a review, later dismissed
LGTM

2023-06-13 17:10 UTC, jbohanon approved these changes

2023-06-13 18:02 UTC, marcogschmidt approved these changes

2023-06-13 18:03 UTC, jbohanon approved these changes

2023-06-13 18:46 UTC, merged