OPA object support
solo-io/gloo pull request #8383
Opened 2023-06-12 19:34 UTC by tjons

# Description

This PR adds a new field to the OpaAuthOptions API that we plan to use in `ext-auth-service` to allow users to return an optional decision reason from evaluating OPA policies. https://soloio.slab.com/posts/opa-response-passthru-design-doc-3lldb91f has more context on how we plan to use this in platform. 

# Checklist:

- [ ] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/main/changelogutils) which references the issue that is resolved.
- [ ] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [ ] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [ ] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-06-13 20:09 UTC, marcogschmidt requested changes

2023-06-13 20:09 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    // Return the reason given from the OPA engine after a decision made on this policy
It's not clear from the comment how the decision will be returned. We should be specific in these user facing docs. From the ext auth PR I see that it will be returned in the dynamic metadata. We should mention that and also specify:
- under which key it will be available in the metadata
- what the structure of the entry will be

Related to these two points, I will leave a couple of comment in the ext auth PR.

2023-07-13 14:13 UTC, sam-heilbron commented
/kick 
Build-bot flaked with a new error, so I created https://github.com/solo-io/gloo/issues/8463 to track it.

2023-07-13 18:59 UTC, sam-heilbron submitted a review, later dismissed

2023-07-13 20:00 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    //       -> reason
This might be a bit misleading:
- First because the name of the AuthConfig might actually interpreted as the name of the CR itself; we should probably call it something like ` name of the auth step, i.e. spec.configs[].name`. Unfortunately we don't have a clear naming convention for these "auth steps" and we seem to use "auth configs" ambiguously in the proto docs.
- Second because the metadata will be prefixed with the name of the ext auth filter when it's emitted by the `ext_authz` filter, so when a user actually gets to consume it the structure of the metadata will be:
```yaml
envoy.filters.http.ext_authz:
  myOpaStepName:
    reason: because
```

2023-07-13 21:09 UTC, marcogschmidt approved these changes

2023-07-13 21:32 UTC, sam-heilbron approved these changes

2023-07-13 21:32 UTC, merged