Envoy gloo bump for inja escaped characters
solo-io/gloo pull request #8499
Opened 2023-07-21 21:41 UTC by jbohanon

# Description

This gets the latest envoy-gloo in order to test functionality with new Inja feature and new custom callback

# Context

See context [here](https://github.com/solo-io/envoy-gloo/pull/258)

# Checklist:

- [x] I included a concise, user-facing changelog (for details, see https://github.com/solo-io/go-utils/tree/main/changelogutils) which references the issue that is resolved.
- [x] If I updated APIs (our protos) or helm values, I ran `make -B install-go-tools generated-code` to ensure there will be no code diff
- [x] I followed guidelines laid out in the Gloo Edge [contribution guide](https://docs.solo.io/gloo-edge/latest/contributing/)
- [x] I opened a draft PR or added the work in progress label if my PR is not ready for review
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2023-07-23 17:47 UTC, jbohanon commented on docs/content/guides/traffic_management/request_processing/transformations/_index.md
> +- `raw_string(string)`: returns the input string with escaped characters intact. Useful for constructing JSON response bodies.
nit:
```suggestion
- `raw_string(string)`: returns the input string with escaped characters intact. Useful for constructing JSON request or response bodies.
```

2023-07-23 17:47 UTC, jbohanon commented on docs/content/guides/traffic_management/request_processing/transformations/_index.md
> +This attribute is used to set for the entire transformation whether Inja should be configured to preserved escaped characters in strings. This is particularly useful when using context from the reque
nit:
```suggestion
This attribute is used to set for the entire transformation whether Inja should be configured to preserve escaped characters in strings. This is particularly useful when using context from the request or response body to construct new JSON bodies.
```

2023-07-23 17:47 UTC, jbohanon commented on projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
> +  bool escape_characters = 12;
```suggestion
  // Use this field to set Inja behavior when rendering strings which contain
  // characters that would need to be escaped to be valid JSON. Note that this
  // sets the behavior for the entire transformation. Use raw_strings function
  // for fine-grained control within a template.
  bool escape_characters = 12;
```

2023-07-23 17:47 UTC, jbohanon commented on test/e2e/route_transformation_test.go
> +		defaultPostBody := "{\"body\":\"test\"}"
nit:
```suggestion
		defaultPostBody := `{"body":"test"}`
```

2023-07-24 15:21 UTC, nfuden requested changes
We should allow for inheritance either via a gateway or settings level default

2023-07-24 15:21 UTC, nfuden commented on projects/gloo/api/external/envoy/extensions/transformation/transformation.proto
> +  bool escape_characters = 12;
Can we make this a nullable bool? that way we can do inheritance more easily

2023-07-27 18:55 UTC, elcasteel commented on projects/gloo/api/v1/settings.proto
> +    TransformationOptions transformation_options = 16;
I think this is a breaking change to change `16` from a bool to a TransformationOptions

2023-07-27 19:06 UTC, jbohanon commented on projects/gloo/api/v1/settings.proto
> +    TransformationOptions transformation_options = 16;
It is, but the field we're changing was introduced in an earlier 1.15 beta

2023-07-27 19:24 UTC, nfuden commented on projects/gloo/api/v1/settings.proto
> +    TransformationOptions transformation_options = 16;
wasnt it backported to 1.14 though?

2023-07-27 19:27 UTC, jbohanon commented on projects/gloo/api/v1/settings.proto
> +    TransformationOptions transformation_options = 16;
Sure was... that's a bummer. I'll get that changed

2023-07-27 19:27 UTC, jbohanon commented on projects/gloo/api/v1/settings.proto
> +    TransformationOptions transformation_options = 16;
Sure was... that's a bummer. I'll get that changed

2023-07-27 20:06 UTC, elcasteel approved these changes
LGTM!

2023-07-27 20:16 UTC, elcasteel submitted a review, later dismissed

2023-07-27 20:25 UTC, nfuden commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +		for i := range headers {
for i, hdr := range headers is more idiomatic and only an extra allocation

2023-07-27 20:29 UTC, jbohanon commented on projects/gloo/pkg/plugins/transformation/plugin.go
> +		for i := range headers {
It's one allocation, but it copies  the slice val out to the temp on every loop iteration

2023-07-27 20:36 UTC, nfuden approved these changes

2023-07-27 21:07 UTC, nfuden approved these changes

2023-07-28 12:07 UTC, elcasteel approved these changes

2023-07-28 12:09 UTC, merged