WIP: v1 API for Azure OIDC distributed claims impl
solo-io/gloo pull request #8859
Opened 2023-11-05 02:37 UTC by tjons

# Description

Please include a high level summary of the changes.

This bug fixes ... \ This new feature can be used to ...

_Fill out any of the following sections that are relevant and remove the others_
## API changes
- Added x field to y resource
- ...

## Code changes
- Fix error in `Foo()` function
- Add `Bar()` function
- ...

## CI changes
- Adjusted schedule for x job
- ...

## Docs changes
- Added guide about feature x to public docs
- Updated README to account for y behavior
- ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

See slack conversation [here](https://solo-io-corp.slack.com/archives/some/post)

## Interesting decisions
 
We chose to do things this way because ...

## Testing steps

I manually verified behavior by ...

## Notes for reviewers

Be sure to verify intended behavior by ...

Please proofread comments on ...

This is a complex PR and may require a huddle to discuss ...

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-11-08 18:54 UTC, Sodman commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message Azure {
If we're using these messages twice in the same proto would it make sense to define the message once at a higher level and use the same message in both places?

2023-11-08 20:04 UTC, EItanya commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message DefaultOIDCProvider {}
Since this is already nested should we just call it default?

2023-11-08 20:07 UTC, tjons commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message DefaultOIDCProvider {}
yes good idea

2023-11-08 20:08 UTC, tjons commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message Azure {
yes good thinking

2023-11-08 20:20 UTC, tjons commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message DefaultOIDCProvider {}
actually I'm going to take @Sodman's idea and move these types to the top level (see latest change)... I think they should stay suffixed with `-OidcProvider` to make it clear what they're for. Otherwise, it would be `extauthv1.Default` which is really confusing (what default?)... wdyt?

2023-11-08 20:27 UTC, EItanya commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +    message DefaultOIDCProvider {}
Agreed since they are no longer nested

2023-11-08 20:28 UTC, EItanya commented
This API makes sense to me. I think it would be a good idea if @marcogschmidt would take a look at this. He's one of the most familiar with this API.

2023-11-09 15:16 UTC, marcogschmidt requested changes

2023-11-09 15:16 UTC, marcogschmidt commented on projects/gloo/api/v1/enterprise/options/extauth/v1/extauth.proto
> +            AzureOidcProvider azure = 27;
We cannot use the same type we have in the `AuthConfigSpec` here. The `ExtAuthConfig` message is what is sent via xDS to ext auth from the control plane in Gloo Edge Enterprise. The assumption is that it contains the _fully resolved_ , self-contained, configuration for the server. This means that e.g. this message cannot contain references to resources, but must contain the information that we need from the referenced objects. 

Just to explain this a little better in case the above is not clear:
- to configure the server we need to do two things:
  - read all the resources from storage that are needed to configure it
  - configure the server state based these resources
- when in **k8s controller mode** (how we use it in GP), the server does both of these things itself
- when in **xDS mode** the server expects the control plane to do the first part, and then just send over the `ExtAuthConfig`, which it uses to configure itself

When deployed in xDS mode, the server has no way of e.g. reading secrets or config maps. That's why if you check the `ExtAuthConfig` you will see that secrets appear as strings, e.g.

```protobuf
string client_secret = 2 [(extproto.sensitive) = true];
```

**TL;DR** we need two different messages for `AzureOidcProvider`:
- one with the secret ref that is what we use on the `AuthConfigSpec`
- one with the resolved secret value that we need for the internal xDS API

2023-11-09 15:53 UTC, marcogschmidt approved these changes

2023-11-09 16:28 UTC, Sodman approved these changes
LGTM!

2023-11-09 16:28 UTC, merged