Fix the control plane server max grpc recv size configuration
solo-io/gloo pull request #8875
Opened 2023-11-08 04:06 UTC by zouxu09

# Description

This bug fixes can be used to set the control plane grpc server `max_recv_size` to a value greater than 4MB.

# Changes

## Bug fixes
- Fix bug in setupSyncer.Setup function to set the grpc server `max_recv_size` to a value greater than 4MB

## Backwards compatibility
- Backwards compatibility is not broken

## Documentation
- Update docs to reflect changes

## Code changes
- Added the missing maxRecvSize to xdsGrpcServerOpts in setupSyncer.Setup function

# Context

Users ran into this bug when there's a large number of ingresses being translated to xds configurations. The default grpc server `max_recv_size` is 4MB, which is too small for the large number of ingresses. This bug fixes allows users to set the grpc server `max_recv_size` to a value greater than 4MB.

## Testing steps

I manually verified behavior by seting the validationServerGrpcMaxSizeBytes

## Notes for reviewers

A also added some logging to help troubleshoot the issue.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-11-14 16:51 UTC, elcasteel reviewed
Overall looks good. Can you add a changelog following these instructions: https://github.com/solo-io/go-utils/blob/main/changelogutils/README.md

2023-11-14 16:51 UTC, elcasteel commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +		if maxGrpcRecvSize >= 0 {
we already checked and returned an error if `maxGrpcRecvSize <0`

2023-11-18 00:09 UTC, davidjumani commented
Apart from Ethans && Seth's comments LGTM

2023-11-22 15:22 UTC, davidjumani commented
@zouxu09 Would you be able to look into addressing the comments? If not, we edit this next week and merge

2023-12-01 15:21 UTC, davidjumani commented
/kick again

2023-12-05 16:09 UTC, sheidkamp approved these changes

2023-12-05 16:26 UTC, davidjumani approved these changes

2023-12-05 16:43 UTC, davidjumani commented
/kick

2023-12-05 20:42 UTC, davidjumani commented
/kick dial tcp 127.0.0.1:9444: connect: connection refused

2023-12-07 16:03 UTC, sheidkamp commented
/kick where are the results?

2023-12-11 16:59 UTC, sheidkamp commented
FAilure when pulling the tests in locally:
```
  [FAILED] Timed out after 30.000s.
  The function passed to Eventually failed at /Users/sethheidkamp/go/src/github.com/solo-io/gloo/test/v1helpers/test_upstream.go:444 with:
  Unexpected error: Post "http://localhost:9082/1": read tcp [::1]:54499->[::1]:9082: read: connection reset by peer
      <*url.Error | 0xc000ce50b0>: 
      Post "http://localhost:9082/1": read tcp [::1]:54499->[::1]:9082: read: connection reset by peer
      {
          Op: "Post",
          URL: "http://localhost:9082/1",
          Err: <*net.OpError | 0xc00078ab40>{
              Op: "read",
              Net: "tcp",
              Source: <*net.TCPAddr | 0xc000367dd0>{
                  IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                  Port: 54499,
                  Zone: "",
              },
              Addr: <*net.TCPAddr | 0xc000367e00>{
                  IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
                  Port: 9082,
                  Zone: "",
              },
              Err: <*os.SyscallError | 0xc000eaa980>{
                  Syscall: "read",
                  Err: <syscall.Errno>0x36,
              },
          },
      }
  In [It] at: /Users/sethheidkamp/go/src/github.com/solo-io/gloo/test/consulvaulte2e/consul_vault_test.go:248 @ 12/11/23 11:58:19.919

  Full Stack Trace
    github.com/solo-io/gloo/test/consulvaulte2e_test.glob..func1.4()
    	/Users/sethheidkamp/go/src/github.com/solo-io/gloo/test/consulvaulte2e/consul_vault_test.go:248 +0xc3c
------------------------------
S

Summarizing 1 Failure:
  [FAIL] Consul + Vault Configuration Happy Path e2e [It] can do function routing with consul services
  /Users/sethheidkamp/go/src/github.com/solo-io/gloo/test/consulvaulte2e/consul_vault_test.go:248

Ran 1 of 2 Specs in 35.410 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 1 Skipped
--- FAIL: TestE2e (35.49s)
FAIL
```

2023-12-11 21:08 UTC, davidjumani commented
Another failure when running the console vault tests locally
```
  [FAILED] Timed out after 60.001s.
  The function passed to Eventually failed at /Users/djumani/lab/gloo/test/v1helpers/test_upstream.go:444 with:
  Unexpected error: Post "https://localhost:9444/1": EOF
      <*url.Error | 0xc0018daf30>: 
      Post "https://localhost:9444/1": EOF
      {
          Op: "Post",
          URL: "https://localhost:9444/1",
          Err: <*errors.errorString | 0x109380470>{s: "EOF"},
      }
  In [It] at: /Users/djumani/lab/gloo/test/v1helpers/test_upstream.go:340 @ 12/11/23 12:00:42.513

  Full Stack Trace
    github.com/solo-io/gloo/test/v1helpers.TestUpstreamReachableWithOffset(0x1?, 0xf3cbe0?, 0xc0006e6550, 0xc001f75dc0?)
    	/Users/djumani/lab/gloo/test/v1helpers/test_upstream.go:340 +0x98
    github.com/solo-io/gloo/test/v1helpers.TestUpstreamReachable(...)
    	/Users/djumani/lab/gloo/test/v1helpers/test_upstream.go:334
    github.com/solo-io/gloo/test/consulvaulte2e_test.glob..func1.3()
    	/Users/djumani/lab/gloo/test/consulvaulte2e/consul_vault_test.go:226 +0x1418
------------------------------

```

2023-12-11 21:36 UTC, davidjumani commented
More on the failure / discussion moving forward [here](https://solo-io-corp.slack.com/archives/G01EERAK3KJ/p1702312690362449)

2023-12-12 14:20 UTC, sam-heilbron requested changes
Thanks for the contribution! I have a few questions about the need for the change in the first place, and some thoughts around potential ways to improve our testing in this space. Please let me know if any of this is unclear.

2023-12-12 14:20 UTC, sam-heilbron commented on changelog/v1.16.0-beta29/grpc-recv-size.yaml
> +  description: The default grpc server max_recv_size is 4MB, which can be small for a large number of ingresses. This fix allows users to set the grpc server max_recv_size to a value greater than 4MB
Gloo operates as an xDS server, which under the hood is a gRPC server. A gRPC server has a few options:
- [MaxRecvMsgSize](https://github.com/grpc/grpc-go/blob/a03c7f1faa6b1ae4eb9b1c8e5a10a517cb7e7778/server.go#L390) - defaults to 4MB
- [MaxSendMsgSize](https://github.com/grpc/grpc-go/blob/a03c7f1faa6b1ae4eb9b1c8e5a10a517cb7e7778/server.go#L398)- defaults math.MaxInt32

The server is serving up data to be consumed by a proxy (gw-proxy, ingress-proxy) and so the default MaxSendMsgSize is appropriate, because the xDS configuration can be quite large. 

I don't quite follow why we would need a value larger than the default for the MaxRecvMsgSize. Often, the xDS server receives small objects from the proxy, either an ACK or a NACK. Can you provide an example of a response that was too large for the xDS server to receive, and the corresponding stack trace? It would help us to understand under which circumstances this can happen, and thus to be able to effectively tune this value and introduce tests for it

2023-12-12 14:20 UTC, sam-heilbron commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +	// Use the same maxGrpcMsgSize for validation server, proxy debug server and control plane server as the message size is determined by the size of proxies.
I like this helpful comment here. However, as a user of the project, I would look at the API definition and not the underlying code. I think that https://github.com/solo-io/gloo/blob/main/projects/gloo/api/v1/settings.proto#L785 would be the appropriate place to also include this comment.

Separately, we are taking an API that was defined for a specific purpose (setting the message size for the validation server) and expanding that purpose to apply it to a more general case. I am ok with this, though an alternative would have been to introduce a separate API. Did you consider using a separate API, and if not, could you share some of the rationale for why not? (I can see an argument for why you should only need to configure this once)

2023-12-12 14:20 UTC, sam-heilbron commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +		s.previousXdsServer.maxGrpcRecvSize = maxGrpcRecvSize
This correctly sets the previousXdsServer to have this value, however https://github.com/solo-io/gloo/blob/main/projects/gloo/pkg/syncer/setup/setup_syncer.go#L273 still does not check to see if this value has changed. At the moment, I think that if you take the following steps:
1. Install gloo
2. Modify the API to change the max grpc recv size

You will see that the previous xds server is still running, and was not updated.

I think that it would be valuable to introduce tests which demonstrate that:
1. Setting the value in the API, sets the underlying gRPC server
2. Updating the value in the API, also updates the underlying gRPC server

2024-01-10 16:43 UTC, sam-heilbron commented
@zouxu09 Since this PR has not had any updates in the last month, I am closing it as stale. I left some review comments on it, so if you would like to continue this work, feel free to re-open the PR and address those comments. Thanks!

2024-01-10 16:43 UTC, closed without merging