feat: Allow users to disable extauth sidecar on a per proxy basis
solo-io/gloo pull request #8898
Opened 2023-11-13 23:58 UTC by davidjumani

# Description

When multiple gateway proxies are defined as well as extauth enabled, a user might want to enable the sidecar for a subset of gateway proxies (since some of them do not require extauth) to reduce resource usage and unnecessary network calls to an unused sidecar.
This feature adds the new helm value `gatewayproxy.proxyName.disableExtauthSidecar` to disable the extauth sidecar on it
It also adds additional helper methods to merge resources while omitting keys in those resources which should not be overwritten if empty

_Fill out any of the following sections that are relevant and remove the others_
## Helm changes
- Added a new `gatewayproxy.proxyName.disableExtauthSidecar` value

## Code changes
N/A

## CI changes
N/A

## Docs changes
N/A

# Context

https://github.com/solo-io/gloo/issues/8430

## Interesting decisions
 
Had initially thought of the idea to omit fields in an overwrite based on keys as in ddc6774fe70399bdbbd37a870b3f777d9a63f9ab but decided against it as future changes would require modifying those keys if the same field is modified in different locations. Eg: if one part of the code did not want the field modified it would add the key to the list of omitKeys but another part of the code when changing the field would need to remove it from the list

## Testing steps

Unit tests in enterprise to validate the behaviour of the new helm fields and helpers

## Notes for reviewers

N/A

Please proofread comments on ...

N/A

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2023-11-14 17:41 UTC, sheidkamp requested changes
One nit, but LGTM

2023-11-14 17:41 UTC, sheidkamp commented on install/helm/gloo/generate/values.go
> +	DisableExtauthSidecar          *bool                            `json:"disableExtauthSidecar,omitempty" desc:"When extAuth.envoySidecar is set to true, every gateway proxy pod will come up with an e
`When extAuth.envoySidecar is set to true` ... wrong field name?

2023-11-15 02:04 UTC, sheidkamp approved these changes

2023-11-15 16:27 UTC, jenshu commented on install/helm/gloo/templates/_helpers.tpl
> +{{ printf "\n" }}{{/* This template is set to a new line. There may be scenarios where a field is initailly set to this value and the same field is appended to later on. Since this is just a new line
> There may be scenarios where a field is initailly set to this value and the same field is appended to later on. 

just curious, in which cases would the field get modified or appended to multiple times?
did the hardcoded magic string not work in that scenario?

2023-11-15 17:20 UTC, davidjumani commented on install/helm/gloo/templates/_helpers.tpl
> +{{ printf "\n" }}{{/* This template is set to a new line. There may be scenarios where a field is initailly set to this value and the same field is appended to later on. Since this is just a new line
As of now, certain fields are set based on flags. Eg: [extauth sidecar](https://github.com/solo-io/solo-projects/blob/main/install/helm/gloo-ee/templates/_helpers.tpl#L12)
If in the future another feature is added and requires a helper container, it would append to the `extraContainersHelper` field. If extauth sidecar is disabled, it will append to a new line and if not, to the extauth sidecar container. So rendering the `extraContainersHelper` field will not cause any issues

2023-11-16 14:28 UTC, jenshu approved these changes

2023-11-16 14:47 UTC, merged