[1.15.x] Resolve rest EDS upgrade failure
solo-io/gloo pull request #8982
Opened 2023-12-13 19:32 UTC by ben-taussig-solo

# Description
 - WIP

2023-12-14 00:39 UTC, sam-heilbron commented on test/kube2e/upgrade/upgrade_test.go
> +			It("doesn't error when settings.enableRestEds is set to true", func() {
I like the idea of a kubernetes test. I just want to call out that we have an existing integration test that is attempting to valdate the behavior of REST EDS: https://github.com/solo-io/gloo/blob/main/test/e2e/happypath_test.go#L54. Regardless of your decision around where an effective test should live, I think we should find an answer for why the existing tests did not catch this behavior

2023-12-15 19:26 UTC, sam-heilbron requested changes
Generally looks good.

2023-12-15 19:26 UTC, sam-heilbron commented on Makefile
> +ENVOY_GLOO_IMAGE ?= quay.io/solo-io/envoy-gloo:2d9b6aa2ab4fbc8c47ebb55e438c05a654546fec
We have a mechanism in Gloo Edge (https://github.com/solo-io/gloo/blob/main/.github/workflows/codegen.yaml#L26) to introduce code that will prevent CI from passing. Given that this is a temporary change, to demonstrate other functionality, can we add this DO_NOT_SUBMIT to somewhere in the code? THat will prevent this PR from merging accidentally

2023-12-15 19:26 UTC, sam-heilbron commented on ci/cloudbuild/run-tests.yaml
> +    { # try to pull release assets first
Can you help me understand these changes? What problem does this solve / how does it manifest itself

2023-12-15 19:26 UTC, sam-heilbron commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update CI to better support unreleased assets from envoy-gloo-ee CI builds
nit: envoy-gloo not, envoy-gloo-ee right?

2023-12-15 19:26 UTC, sam-heilbron commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update envoy-gloo to resolve issues configuring rest EDS
Given that we are pulling in functionality from an external project (envoy-gloo), I think we should have an integration test which demonstrates that this functionality in Edge works as expected. Since we have uncovererd a bug, I think this is a chance to expand our tests in Gloo Edge to prevent future regressions. Can we add a test that will fail without this dependency change, and that succeeds with it?

2023-12-15 19:27 UTC, ben-taussig-solo commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update CI to better support unreleased assets from envoy-gloo-ee CI builds
yes, good catch

2023-12-15 19:30 UTC, ben-taussig-solo commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update envoy-gloo to resolve issues configuring rest EDS
I think the plan as discussed in stand-up was to merge data-plane bumps without testing updates and then do the testing updates as a fast-follow. I need to sync with Manuel about that. I agree that we need to have testing against this functionality (and also that we need to repair existing gaps in our tests as described [here](https://github.com/solo-io/gloo/issues/8968#issuecomment-1856085120))

2023-12-15 19:45 UTC, sam-heilbron commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update envoy-gloo to resolve issues configuring rest EDS
I'm a bit concerned about `I think the plan as discussed in stand-up was to merge data-plane bumps without testing updates and then do the testing updates as a fast-follow.`

What is the value of introducing code without corresponding tests that demonstrate it to behave the way we would expect? If it comes down to a timing issue (we need this functionality merged into Gloo Edge by some time) then I think we can regroup on how to most efficiently verify (can be manual) this functionality. 

As an aside, I would expect that we can write some automated tests for this in <1 day, so I'd be surprised if our delivery of this feature being delayed a day was unnacceptable to product.

2023-12-18 14:18 UTC, ben-taussig-solo commented on ci/cloudbuild/run-tests.yaml
> +    { # try to pull release assets first
this is a backport of this PR to v1.15.x. This allows us to test unreleased envoy-gloo assets in gloo OSS CI
https://github.com/solo-io/gloo/pull/8731

2023-12-18 14:21 UTC, ben-taussig-solo commented on Makefile
> +ENVOY_GLOO_IMAGE ?= quay.io/solo-io/envoy-gloo:2d9b6aa2ab4fbc8c47ebb55e438c05a654546fec
resolved here: https://github.com/solo-io/gloo/pull/8982/commits/0024443b15a1095fc8b11d42a4b1bf8da971b113

2023-12-18 14:21 UTC, ben-taussig-solo commented on changelog/v1.15.18/rest-eds-upgrade-failure.yaml
> +      Update CI to better support unreleased assets from envoy-gloo-ee CI builds
resolved here: https://github.com/solo-io/gloo/pull/8982/commits/b62f7043a0ac483b399a4b9605a02bcbbe0a5290

2023-12-18 16:12 UTC, sam-heilbron commented on Makefile
> +# DO_NOT_SUBMIT
I would inspect the do-not-submit script to confirm how this works. If this comment were having an impact, I would expect the static analysis job would fail during the final step.

2023-12-18 16:15 UTC, sam-heilbron commented on ci/cloudbuild/run-tests.yaml
> +    { # try to pull release assets first
Super helpful! Personally it's hard to find this history/rationale. It could be that I didn't look deeply enough into the commit history, so I'm fine with that as the solution. Do you think a comment outlining why we perform this action would be useful?

Secondly, this adds complexity into our cloudbuild definition. If I'm a developer executing code locally, is there a situation that I would ever want to perform these actions? If so, I'd be in favor of defining this complexity in a re-usable place. This way, if/when we change cloud providers we don't have to re-write this logic again

2023-12-18 16:38 UTC, ben-taussig-solo commented on Makefile
> +# DO_NOT_SUBMIT
Looking at the [codegen logs](https://github.com/solo-io/gloo/actions/runs/7249379897/job/19747239624?pr=8982), we can see that the script is running but it doesn't seem to actually be scanning any files (or at least we're failing to increment the file count)

```
Run ./ci/do-not-submit.sh changelog/v1.15.18/rest-eds-upgrade-failure.yaml Makefile ci/cloudbuild/run-tests.yaml
0 go files checked, none contain DO_NOT_SUBMIT
````

I think that suggests that the checks we're doing against the filenames passed into the script are not working as intended

For now I'm just going to leave this PR as a draft

2023-12-18 16:44 UTC, sam-heilbron commented on Makefile
> +# DO_NOT_SUBMIT
`I think that suggests that the checks we're doing against the filenames passed into the script are not working as intended` I'm not sure I agree with this. To me it means that the script behaves a certain way, and we're not using it that way. I think our options are: expand the script to fit our use case, adjust our use case to fit the script.

https://github.com/solo-io/gloo/blob/main/ci/do-not-submit.sh#L8

It seems like the comment format isn't following what the script expects

2023-12-19 14:39 UTC, ben-taussig-solo commented on ci/cloudbuild/run-tests.yaml
> +    { # try to pull release assets first
Updated commentary in [536529d](https://github.com/solo-io/gloo/pull/8982/commits/536529d0cf282afd76e2fee7eb20c338577b994e)

```sh
  - |
    { # try to pull release assets first
      # release assets are in v1.x.y (semver, prefixed with a literal v) format
      ENVOY_VERSION=v$$(make print-ENVOY_GLOO_IMAGE | cut -d: -f2)
      gsutil cp gs://solo-public-artifacts.solo.io/envoy/$$ENVOY_VERSION/envoy.stripped /workspace/envoy
      chmod +x /workspace/envoy
    } || { 
      # if that fails, pull from CI
      # CI assets are in SHA format -- the difference from the above is that the SHA is not prefixed with a literal v
      ENVOY_VERSION=$$(make print-ENVOY_GLOO_IMAGE | cut -d: -f2)
      gsutil cp gs://solo-public-artifacts.solo.io/envoy/$$ENVOY_VERSION/envoy /workspace/envoy
      chmod +x /workspace/envoy
```

I also put up a PR against main with the same change here: https://github.com/solo-io/gloo/pull/8997

2023-12-19 14:55 UTC, ben-taussig-solo commented on Makefile
> +# DO_NOT_SUBMIT
I put an issue up discussing potential improvements to this functionality: https://github.com/solo-io/gloo/issues/8998

As such, I am resolving the thread.

2024-01-15 16:59 UTC, closed without merging