Add istio auto mtls support
solo-io/gloo pull request #9165
Opened 2024-02-19 16:17 UTC by npolshakova

# Description

## API changes
- Added `autoMtlsEnabled` to Gloo settings under IstioOptions.
- Added `sdsEnabled` and `istioAutoMtlsEnabled` to Gloo Gateway helm. This is a temporary value until the Gloo Gateway helm chart is merged. 

## Code changes
- Cluster translator will add two transport socket matches for tlsMode and plaintext if istioAutoMtls is enabled
- Kubernetes eds plugin will add the istio tlsMode metadata in computeGlooEndpoints if istioAutoMtls is enabled to the endpoint. This has access to the Pods, which will have the istio injection label
- The same sds/istio-proxy helm values will control the sds sidecar and istio-proxy on the Gloo Edge side. The Gloo Gateway will have a temporary helm value to enable Istio integration until the helm chart merge is complete. 

## CI changes
- [ ] TODO: Add e2e test for Gloo Edge with automtls enabled
- [ ] TODO: Add e2e test for Gloo Gateway with automtls enabled 

## Docs changes
- [ ] TODO: Need to add Istio automtls docs. This should probably go in after helm chart merge to have more accurate helm chart values

## Try it out:

To run the gloo-gateway (no istio) setup, run this in the `gloo/projects/gateway2` directory:

```
make build docker kind install-gloo-gateway
```

Create a Gateway resource and you should only see one container:
```
❯ kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: http
spec:
  gatewayClassName: gloo-gateway
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 8080
    protocol: HTTP
EOF
```

To run the istio setup:

```
make build docker kind install-istio-gloo-gateway
```

This will install istio and bookinfo in the mesh. It will also apply the Gateway, HTTPRoute and AuthorizationPolicy to test mtls with the istio integration. 

Send traffic by port-forwarding the gateway:
```
❯ k port-forward deployment/gloo-proxy-http 8080:8080
```

And then sending a request through the gateway with the example HTTPRoute from the setup script:
```
❯ curl -I localhost:8080 -H "host: www.example.com" -v
```

# Demo:

https://drive.google.com/file/d/1Jonyy1AbHjS5GcUkgMZ-ZujvzgBpsFqL/view?usp=sharing 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-03-04 16:37 UTC, lgadban commented on projects/gateway2/README.md
> + CLUSTER_NAME=solo-test-cluster ci/kind/setup-kind.sh; CLUSTER_NAME=solo-test-cluster make kind-build-and-load
nit: is there a compelling reason to use a custom cluster name rather than just relying on the default?

2024-03-04 16:38 UTC, npolshakova commented on projects/gateway2/README.md
> + CLUSTER_NAME=solo-test-cluster ci/kind/setup-kind.sh; CLUSTER_NAME=solo-test-cluster make kind-build-and-load
Nope- this is just copied from my notes for setting up the e2e test environment. The default should work!

2024-03-04 20:42 UTC, npolshakova commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  glooMtls:
TODO: remove glooMtls from values and template

2024-03-04 21:11 UTC, npolshakova commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +		GlooMtls: bootstrap.GlooMtls{
TODO: remove Gloo Mtls

2024-03-06 15:28 UTC, npolshakova commented on projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
> +        - name: {{ .Chart.Name }}
Nope, I think this was just carried over from copying the templating.

2024-03-06 15:47 UTC, npolshakova commented on projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
> +          {{- if $gateway.istioSDS.enabled }}
Nope- just fixed this as part of fixing the indenting. It was left over from the old templating that checked glooMtls.enabled vs. istioSDS.enabled

2024-03-06 15:47 UTC, npolshakova commented on projects/gloo/constants/istio.go
> +	// Env variable to enable the Istio mtls integration to add the istio-proxy sidecar
Yep, that's a good point!

2024-03-06 15:50 UTC, npolshakova commented on projects/gloo/constants/istio.go
> +package constants
Yeah I can add them here! Which ones are you thinking? Most of the constants here are currently values that get used in the sslConfig or automtls translation. I think `IstioMtlsEnabled` is the env value, but I can add `ENABLE_ISTIO_INTEGRATION` here as well.

2024-03-06 16:02 UTC, npolshakova commented on projects/gloo/pkg/syncer/setup/setup_syncer.go
> +		IstioSDSEnabled: isEnvTruthy(constants.IstioMtlsEnabled),
Yep, I think that's a good idea- the helm value that this is based off isn't experimental but I think the env approach should be an interim solution!

2024-03-06 16:05 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +		if !sslConfigDisabled(sslConfig) {
Yep! At one point I wanted to add a log here that the automtls was disabled, but I think that's a pretty explicit user choice so I don't think we need it?

2024-03-06 16:10 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +	}
So I think this is more similar to the `sslConfigTranslator utils.SslConfigTranslator` that gets passed in. I'm not sure if a plugin makes sense since this depends on the sslConfig that gets fed into that translator. Maybe if there was a combined sslConfig plugin, that would make sense to go there? I could create a `utils.IstioAutoMtlsTranslator` that gets passed in here? 

But I think a plugin here would be messier because it doesn't seem like there are any ClusterPlugins currently and it feels like there is a lot of shared logic between calling the SslConfigTranslator vs. translating for automtls?

I might also be missing something on the edge side, so this might be easier to chat about while looking at the code on a call!

2024-03-06 16:10 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +		Name:            "tlsMode-disabled",
Good catch!

2024-03-06 16:11 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +		Name:            "tlsMode-" + constants.IstioMutualTLSModeLabel,
Yep, this was copied from the istio code, but I'm fine using the const for `tlsMode` here as well!

2024-03-06 16:13 UTC, npolshakova commented on projects/gloo/pkg/translator/endpoints.go
> +	if autoMtlsEnabled {
Do you think it's worth having a separate plugin for eds? I was on the fence here because it seemed a little overkill for just getting the metadata label?

2024-03-06 20:44 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +	}
Added the plugin approach and I think it's a lot cleaner now: https://github.com/solo-io/gloo/pull/9165/commits/0e97ecd68a6a289561e4bad2d26fb43adfb827c0

2024-03-06 20:56 UTC, npolshakova commented on projects/gloo/pkg/translator/endpoints.go
> +	if autoMtlsEnabled {
Added a new `getEndpointMetadata` that adds both the istio metadata and keeps `getLbMetadata` separate

2024-03-06 23:25 UTC, lgadban reviewed
still need to review endpoints.go

2024-03-06 23:25 UTC, lgadban commented on projects/gloo/pkg/translator/clusters.go
> +	sslConfig := upstream.GetSslConfig()
do we still need this change now that the auto mtls stuff is in a plugin?

2024-03-06 23:25 UTC, lgadban commented on projects/gloo/pkg/translator/clusters.go
> +func sslConfigDisabled(sslConfig *ssl.UpstreamSslConfig) bool {
can we add a godoc and rename this function to be a bit more descriptive?
I'm struggling to see the reasoning for this -- are we saying that if the sslConfig is NOT nil but autoMtls is disabled AND all the values on the sslConfig are the zero-values, return true?
we might want to talk this one through

2024-03-06 23:25 UTC, lgadban commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	if p.settings.GetGloo().GetIstioOptions().GetEnableAutoMtls() && sslConfig == nil {
do we not need to check the disableAutoMtls flag here?

2024-03-07 02:52 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +	sslConfig := upstream.GetSslConfig()
We can move it down closer to the check, but I think this should be on it's own line to make the if statement cleaner.

2024-03-07 02:59 UTC, npolshakova commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	if p.settings.GetGloo().GetIstioOptions().GetEnableAutoMtls() && sslConfig == nil {
If the `disableAutoMtls` is set it'll also result in a non-nil `sslConfig`

2024-03-07 03:02 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +func sslConfigDisabled(sslConfig *ssl.UpstreamSslConfig) bool {
Yeah let's talk through this one- currently if the sslConfig is not nil, the SslConfigTranslator will return a envoyauth.UpstreamTlsContext [here](https://github.com/solo-io/gloo/blob/112ed69f2156b2456da4af6ef4f3c1fc89809adc/projects/gloo/pkg/utils/ssl.go#L78). So if just `disableAutoMtls` is set, it breaks regular upstream. So this check if `GetDisableIstioAutoMtls` is set AND no other sslConfig is set, skip translation.

2024-03-07 21:03 UTC, yuval-k commented on install/helm/gloo/values-template.yaml
> +      enableAutoMtls: false
where is this used? i don't think this is automatically merged into the settings in the helm chart? I looked at `install/helm/gloo/templates/18-settings.yaml`

2024-03-07 21:07 UTC, yuval-k commented on install/helm/gloo/values-template.yaml
> +      enableAutoMtls: false
(asking as i would like to be able to enabled this in the helm chart)

2024-03-07 21:15 UTC, npolshakova commented on install/helm/gloo/values-template.yaml
> +      enableAutoMtls: false
Ah good catch- currently setting here in the helm chart doesn't do anything. It needs to be set in the settings CR. I'll add it to `18-settings.yaml` and the helm chart

2024-03-08 16:49 UTC, lgadban commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	// if the upstream has mtls enabled, and the sslConfig is not nil, then we need to add the istio mtls match
this doesn't sound right?

2024-03-08 16:49 UTC, lgadban commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	// if the upstream has mtls enabled, and the sslConfig is not nil, then we need to add the istio mtls match
```suggestion
	// if istio auto mtls is enabled, and the sslConfig is nil, then we need to add the istio mtls match
```

2024-03-08 16:49 UTC, lgadban commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +		if istioIntegrationEnabled && !addr.IsHeadless && !autoMtls {
this is confusing to me; should we be modifying this conditional to include the autoMtls logic as well?
seems like we're crossing concerns a bit

2024-03-08 18:35 UTC, npolshakova commented on projects/gloo/pkg/plugins/kubernetes/eds.go
> +		if istioIntegrationEnabled && !addr.IsHeadless && !autoMtls {
Addressed in https://github.com/solo-io/gloo/pull/9165/commits/6284d3f51079e2ed9a712a3410b104c3670a4ace after chating

2024-03-08 18:35 UTC, npolshakova commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	// if the upstream has mtls enabled, and the sslConfig is not nil, then we need to add the istio mtls match
Addressed in https://github.com/solo-io/gloo/pull/9165/commits/6284d3f51079e2ed9a712a3410b104c3670a4ace after chatting

2024-03-08 19:24 UTC, npolshakova commented on projects/gloo/pkg/translator/clusters.go
> +func sslConfigDisabled(sslConfig *ssl.UpstreamSslConfig) bool {
resolved moved disableAutoMtls to upstream instead of sslConfig

2024-03-08 20:20 UTC, lgadban approved these changes
added a nit, won't hold up approval over it, seems like the factoring can be improved in  endpoints.go but don't feel too strongly.
LMK if you want to talk through it

2024-03-08 20:20 UTC, lgadban commented on projects/gloo/pkg/translator/endpoints.go
> +		metadata := getEndpointMetadata(upstream, addr.GetMetadata().GetLabels(), "", enableAutoMtls)
nit: feels like we shouldn't change the entrypoint (see below comment)

2024-03-08 20:20 UTC, lgadban commented on projects/gloo/pkg/translator/endpoints.go
> +func getEndpointMetadata(upstream *v1.Upstream, labels map[string]string, zeroValue string, enableAutoMtls bool) *envoy_config_core_v3.Metadata {
IMO this should just be `getEndpointMetadata(labels map[string]string)` and conditionally called from `getLbMetadata(...)` above

2024-03-10 15:30 UTC, sam-heilbron submitted a review, later dismissed
LGTM! A few nits/questions, but feel free to resolve them and either not handle it, or handle in a follow-up

2024-03-10 15:30 UTC, sam-heilbron commented on projects/gloo/pkg/translator/translator_test.go
> +	csrf_v31 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3"
nit: I think some of these aliases could be a bit more expressive

2024-03-10 15:30 UTC, sam-heilbron commented on test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
> +    controllerName: solo.io/gloo-gateway
It's probably fine to leave for now, but right now these Helm API values do nothing

2024-03-11 01:50 UTC, npolshakova commented on projects/gloo/cli/pkg/cmd/install/v2/install.go
> +	// TODO(npolshak): Need a better way for the cli to access helm values here
And just not provide the `IstioValues`? Yeah that works!

2024-03-11 01:52 UTC, npolshakova commented on .github/workflows/composite-actions/istio-tests/action.yaml
> +        version: ${{ matrix.kube-version.kubectl }}
Yeah I think we might want to add the istio versions here as part of the follow up issue to add test coverage for istio versions, so we still might want it as a separate action.

2024-03-11 01:53 UTC, npolshakova commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> -          - name: ENABLE_ISTIO_INTEGRATION
Yep, now it's: 
```
lookupResult, found := os.LookupEnv(constants.IstioInjectionEnabled)
```

2024-03-11 01:56 UTC, npolshakova commented on projects/gateway2/deployer/deployer.go
> +	Settings       *v1.Settings
Yep- settings isn't currently used in the deployer so I can remove!

2024-03-11 01:56 UTC, npolshakova commented on projects/gateway2/deployer/deployer_test.go
> +			},
I don't think it's needed anymore! Will remove

2024-03-11 01:58 UTC, npolshakova commented on projects/gloo/api/v1/upstream.proto
> +    // If set to true, the proxy will not allow automatic mTLS detection for Istio upstreams.
How does this sound? 

```
 If set to true, the proxy will not allow automatic mTLS detection for Gloo Upstreams selecting Istio injected workloads.
```

2024-03-11 02:01 UTC, npolshakova commented on projects/gloo/pkg/translator/translator_test.go
> +	csrf_v31 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3"
I don't think these are net new- just reorganized the imports. But I can rename them to be more consistent with the rest of the code base: 

```
	bufferv3 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/filters/http/buffer/v3"
	gloocsrf "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/extensions/filters/http/csrf/v3"
```

It looks like `v3 "github.com/solo-io/gloo/projects/gloo/pkg/api/external/envoy/config/core/v3"` is used as `v3` everywhere, so I'm leaning towards leaving it.

2024-03-11 02:02 UTC, npolshakova commented on test/kube2e/istio/artifacts/gloo-gateway-helm.yaml
> +    controllerName: solo.io/gloo-gateway
Yep, copied over from the conformance tests, but I think these are just the defaults?

2024-03-11 02:05 UTC, npolshakova commented on projects/gloo/pkg/translator/endpoints.go
> +func getEndpointMetadata(upstream *v1.Upstream, labels map[string]string, zeroValue string, enableAutoMtls bool) *envoy_config_core_v3.Metadata {
Some of the earlier feedback I got was having `getLbMetadata` call Istio specific logic made it hard to follow what `getLbMetadata` was responsible for. How about addressing https://github.com/solo-io/gloo/pull/9165#discussion_r1518396454 instead? So it would still be getEndpointMetadata but change the function that gets passed

2024-03-11 02:08 UTC, npolshakova commented on projects/gloo/pkg/translator/route_config.go
> +		routeMetadata = getEndpointMetadata(nil, destination.GetSubset().GetValues(), "", enableAutoMtls)
I think if istio auto mtls is enabled, we want to get both `getLbMetadata` and the istio metadata. The istio metadata is set for `envoy.transport_socket_match` and the load balance metadata is set for `envoy.lb`.

2024-03-11 13:42 UTC, sam-heilbron submitted a review, later dismissed

2024-03-11 16:12 UTC, lgadban commented on projects/gloo/pkg/translator/route_config.go
> +		routeMetadata = getEndpointMetadata(nil, destination.GetSubset().GetValues(), "", enableAutoMtls)
how confident are we that the istio metadata is relevant here? Seems like this is mainly for subset loadbalancing, which is a separate concern from what istio automtls is actually providing

2024-03-11 18:03 UTC, lgadban requested changes

2024-03-11 18:03 UTC, lgadban commented on projects/gloo/pkg/translator/route_config.go
> +	enableAutoMtls           bool
no longer needed right? same with all changes to this file now it looks like

2024-03-11 19:23 UTC, lgadban commented on projects/gloo/pkg/translator/translator.go
> +type IstioTranslatorConfig struct {
what is this used for?

2024-03-11 19:24 UTC, npolshakova commented on projects/gloo/pkg/translator/translator.go
> +type IstioTranslatorConfig struct {
I think this can be removed- the auto mtls plugin now is initialized with these values

2024-03-12 02:17 UTC, npolshakova commented
https://github.com/solo-io/gloo/actions/runs/8238795640/job/22541536443?pr=9165 flaked due to https://github.com/solo-io/gloo/issues/8554. Since we're adding a new istio regression run, https://github.com/solo-io/gloo/pull/9165/commits/136a43d3963de84cdfc96a11da6a56017a6c08d5 mitigates the status flake:

```
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 6 Skipped
PASS | FOCUSED

All tests passed...
Will keep running them until they fail.
This was attempt #31
No, seriously... you can probably stop now.
```

2024-03-12 16:50 UTC, lgadban requested changes

2024-03-12 16:50 UTC, lgadban commented on projects/gateway2/discovery/translator.go
> +func NewTranslator(cli client.Client, inputChannels *xds.XdsInputChannels, enableIstioAutoMtls bool) Translator {
what does `enableIstioAutoMtls` do now? seems unused...

2024-03-12 17:18 UTC, lgadban commented on .github/workflows/istio-tests.yaml
> +        kube-e2e-test-type: [ 'istio-auto', 'gloo-gateway' ]
does this mean we only test legacy with istio-auto now?

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gateway2/controller/controller.go
> +	Settings     *v1.Settings
I don't see this used anywhere in this component, can we remove it?

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gateway2/controller/start.go
> +	if err = discovery.NewDiscoveryController(ctx, mgr, inputChannels, cfg.Opts.Settings.GetGloo().GetIstioOptions().GetEnableAutoMtls().GetValue()); err != nil {
This new `enableAutoMtls` value is not used inside of this discovery controller, can we remove it?

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gloo/pkg/bootstrap/opts.go
> +	IstioSDSEnabled bool
nit (non-blocking): The name here stutters (https://sben.dev/stutter/) a bit. Given that these are IstioValues, could we just remove the `istio` prefix from the field names?

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gloo/pkg/bootstrap/opts.go
> +	GlooOptions                *v1.GlooOptions
I can't see these values being used, am I missing something?

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/istio_automtls/istio_automtls_suite_test.go
> +func TestGzip(t *testing.T) {
```suggestion
func TestIstioAutoMtls(t *testing.T) {
```

2024-03-12 17:36 UTC, sam-heilbron commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	p.ctx = params.Ctx
Each of the plugin functions, in this instance ProcessUpstream, should pass params that have a context on them. Is there a reason we want to persist the context on the plugin instead of just using what is passed in? The go recommendation (https://go.dev/blog/context-and-structs) is to avoid storing context on a struct, and prefer to use it passed as an argument

2024-03-12 17:44 UTC, npolshakova commented on .github/workflows/istio-tests.yaml
> +        kube-e2e-test-type: [ 'istio-auto', 'gloo-gateway' ]
No, the regression tests run the normal Istio test with no auto mtls: https://github.com/solo-io/gloo/actions/runs/8251250967/job/22569675558?pr=9165. 

This new suite will eventually have the matrix of different Istio versions.

2024-03-12 17:44 UTC, npolshakova commented on projects/gateway2/controller/controller.go
> +	Settings     *v1.Settings
Yeah I think this got added back in the merge 😢

2024-03-12 17:49 UTC, npolshakova commented on projects/gloo/pkg/bootstrap/opts.go
> +	IstioSDSEnabled bool
Yep, it was supposed to reflect the helm value back when this was a copy of the istio helm values from values.go. Can rename!

2024-03-12 18:24 UTC, npolshakova commented on projects/gloo/pkg/bootstrap/opts.go
> +	GlooOptions                *v1.GlooOptions
I think `GlooOptions` isn't getting used anymore either- the plugin now has access to the settings and is getting the autoMtlsEnabled value from that.

2024-03-12 18:29 UTC, npolshakova commented on projects/gloo/pkg/plugins/istio_automtls/plugin.go
> +	p.ctx = params.Ctx
The azure plugin does this as well, so that's where this came from. But I think all the uses of the ctx use the param context and that makes more sense that using the one that's persisted on the plugin. Especially any logging happens on `ProcessUpstream` and there's no logging on the plugin initialization.

2024-03-12 19:38 UTC, lgadban commented on .github/workflows/istio-tests.yaml
> +        kube-e2e-test-type: [ 'istio-auto', 'gloo-gateway' ]
perfect, ty!

2024-03-12 20:50 UTC, npolshakova commented
/kick build-bot

2024-03-13 16:35 UTC, lgadban approved these changes

2024-03-13 16:35 UTC, lgadban commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +		It("autoMtls should translate EDS metadata", func() {
should this test really be in this file? there are no functional changes to `eds.go` and the behavior tested here is in `translator/endpoints.go`.
If this does make sense then all good!

2024-03-13 16:35 UTC, lgadban commented on test/kube2e/istio/istio_suite_test.go
> +	defer cancel()
why?

2024-03-13 16:49 UTC, npolshakova commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +		It("autoMtls should translate EDS metadata", func() {
We don't need a net new test but should make sure the tlsMode label is picked up. This was added when we had the conditional parsing for the tlsMode data.

2024-03-13 16:51 UTC, npolshakova commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +		It("autoMtls should translate EDS metadata", func() {
Actually, it doesn't look like any tests in this file check that `Metadata.Labels`. So yes, we need a test to check the labels are getting set. I can rename the test, but we do want to keep the checks here since it adds new coverage.

2024-03-13 16:55 UTC, npolshakova commented on test/kube2e/istio/istio_suite_test.go
> +	defer cancel()
We should be able to reuse the test context, this was in a different file before.

2024-03-13 17:39 UTC, lgadban approved these changes
excellent work!

2024-03-13 17:39 UTC, lgadban commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +			Expect(endpoints[0].Metadata.Labels).To(HaveKeyWithValue(constants.IstioTlsModeLabel, "istio"))
my point is more that the assertion here relies on the metadata changes present in the endpoint translator (i.e. `translator/endpoints.go`) so it seems like this functionality should be tested there, e.g. https://github.com/solo-io/gloo/blob/npolshak/istio-auto-mtls/projects/gloo/pkg/translator/translator_test.go#L1819

I definitely agree that we need to test this metadata propagation and i'm fine leaving as-is, more so calling out that it seems a little confusing to have this logic tested as part of the EDS plugin

2024-03-13 17:44 UTC, npolshakova commented on projects/gloo/pkg/plugins/kubernetes/eds_test.go
> +			Expect(endpoints[0].Metadata.Labels).To(HaveKeyWithValue(constants.IstioTlsModeLabel, "istio"))
It's also tested in the translator tests, but I think have a direct call to `FilterEndpoints` is better than just relying the parent translator tests. If there's any issues with `FilterEndpoints` missing metadata it will be easier to debug here than the translator. It doesn't rely on any imports from the translator, it's only scoped to things in the eds.go file. 

https://github.com/solo-io/gloo/blob/npolshak/istio-auto-mtls/projects/gloo/pkg/translator/translator_test.go#L1819  runs through the whole translate().

2024-03-13 19:20 UTC, sam-heilbron approved these changes

2024-03-13 20:00 UTC, npolshakova commented
retrigger bulldozer

2024-03-13 20:01 UTC, merged