add_additionalLabels_to_chart
solo-io/gloo pull request #9195
Opened 2024-02-26 20:53 UTC by TheCubicleJockey

# Description
This new feature is to add additionalLabels to helm chart

# Context
See issue [here](https://github.com/solo-io/gloo/issues/9035)

## Testing steps
I manually verified behavior by templating the helm chart with different values

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-09 16:02 UTC, davidjumani commented
/kick

2024-04-09 19:16 UTC, davidjumani requested changes
The overall idea is good and simplifies the charts, just a few changes are required
- Remove the `gloo: gloo` from the default label set
- For simplicity do not pass the context as a `context` variable but just `.`
- Run the tests in the install directory and try to fix them

2024-04-09 19:16 UTC, davidjumani commented on install/helm/gloo/templates/_helpers.tpl
> +gloo: gloo
The `gloo` label indicates components such as proxy, rbac, etc. This should not be part of the default labels

2024-04-09 19:16 UTC, davidjumani commented on install/helm/gloo/templates/0-namespace.yaml
> +    {{- include "gloo.labels" (dict "context" .) | nindent 4 }}
We can pass it as `{{- include "gloo.labels" . }}` and modify `gloo.labels` accordingly

2024-04-09 19:16 UTC, davidjumani commented on install/helm/gloo/templates/_helpers.tpl
> +{{- with .context.Values.additionalLabels }}
Can simplify this to {{- with .Values.additionalLabels }}

2024-04-15 17:57 UTC, TheCubicleJockey commented on install/helm/gloo/templates/0-namespace.yaml
> +    {{- include "gloo.labels" (dict "context" .) | nindent 4 }}
Resolved in next push

2024-04-16 15:39 UTC, davidjumani requested changes
Thanks for addressing the comments. One last thing - Can you please make the following changes ?

2024-04-16 15:39 UTC, davidjumani commented on install/helm/gloo/templates/1-gloo-deployment.yaml
> +    {{- include "gloo.labels" . }}
```suggestion
    gloo: gloo
    {{- include "gloo.labels" . }}
```
And so for all other occurrences of `gloo: gloo` that has been removed

2024-04-17 14:22 UTC, davidjumani commented
@TheCubicleJockey Can you please rebase and fix the conflicts as well as revert all occurrences of `gloo: gloo` that have been removed

2024-04-26 19:50 UTC, davidjumani commented
/kick

2024-04-26 19:57 UTC, davidjumani commented
/kick

2024-04-29 00:10 UTC, davidjumani commented
/kick

2024-04-30 17:43 UTC, davidjumani commented
Moving this to draft until the enterprise changes are addressed

2024-05-09 14:34 UTC, TheCubicleJockey commented
Please let me know what needs done to get this moved over the line. My client (your enterprise client) is wanting this merged.

2024-05-15 22:43 UTC, davidjumani commented
Hi @TheCubicleJockey I'm continuing this in a [new PR](https://github.com/solo-io/gloo/pull/9491) for faster development

2024-05-15 22:43 UTC, closed without merging