Fixing #9211
solo-io/gloo pull request #9212
Opened 2024-03-03 07:39 UTC by codeverifier

- Added kubernetes version
- Fixed prettifying output
- Fixed image version display

2024-03-03 08:33 UTC, codeverifier commented
output now looks like,

```
{
  "glooVersion": {
    "client": {
      "version": "1.0.1-dev"
    },
    "server": [
      {
        "type": "Gateway",
        "enterprise": true,
        "kubernetes": {
          "containers": [
            {
              "Tag": "1.14.15",
              "Name": "observability-ee",
              "Registry": "quay.io/solo-io"
            },
            {
              "Tag": "1.14.15",
              "Name": "gloo-ee",
              "Registry": "quay.io/solo-io",
              "OssTag": "1.14.29"
            },
            {
              "Tag": "1.14.15",
              "Name": "gloo-ee-envoy-wrapper",
              "Registry": "quay.io/solo-io"
            }
          ],
          "namespace": "gloo-system"
        }
      }
    ]
  },
  "kubernetesVersion": {
    "major": "1",
    "minor": "24",
    "gitVersion": "v1.24.13+k3s1",
    "gitCommit": "3f79b289229dc0452c5cde26cccfa069805c5610",
    "gitTreeState": "clean",
    "buildDate": "2023-04-20T01:39:02Z",
    "goVersion": "go1.19.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

2024-03-07 02:54 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/cmd.go
> +		formattedVer, err := getFormattedJson(wrappedVersions) // GetJson(vrs)
```suggestion
		formattedVer, err := getFormattedJson(wrappedVersions)
```

2024-03-07 02:55 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/cmd.go
> +		formattedVer, err := getFormattedYaml(wrappedVersions) // GetJson(vrs)
```suggestion
		formattedVer, err := getFormattedYaml(wrappedVersions)
```

2024-03-07 08:47 UTC, codeverifier commented on changelog/v1.17.0-beta11/9211-improve-glooctl-version.yaml.yaml
> +changelog:
good catch

2024-03-07 08:49 UTC, codeverifier commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +	return []*version.ServerVersion{serverVersion}, k8ServerVersion, nil
historical reasoning is beyond me. but i agree that this can be simplified.

2024-03-07 13:44 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +	return []*version.ServerVersion{serverVersion}, k8ServerVersion, nil
according to [here](https://github.com/solo-io/gloo/blob/112ed69f2156b2456da4af6ef4f3c1fc89809adc/projects/gloo/api/grpc/version/version.proto#L55-L56) it was indeed intended to return multiple gloo instances on a cluster. it currently won't do that because if you don't pass in a namespace, it defaults to `gloo-system` and it doesn't seem like there's a way to default to "all namespaces". we _could_ fix that by allowing some way to specify "all namespaces" and return multiple gloo versions, but i think that's out of the scope of this PR

and looking at the version.proto, another possible place we could insert the k8s version is adding a new field to [Version](https://github.com/solo-io/gloo/blob/112ed69f2156b2456da4af6ef4f3c1fc89809adc/projects/gloo/api/grpc/version/version.proto#L53) - so we could have a gloo `ClientVersion`, list of gloo `ServerVersion`s, and a `KubernetesVersion`

2024-03-07 15:11 UTC, sam-heilbron reviewed
Thanks for tackling this! I left some thoughts about ways to expand the API using the proto as the source of truth. Let me know if that doesn't make sense and I'm happy to huddle, or outline what I had in mind

2024-03-07 15:11 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +func (k *kube) Get(ctx context.Context) ([]*version.ServerVersion, *kube1vVersion.Info, error) {
Taking a look at the API that exists (https://github.com/solo-io/gloo/blob/main/projects/gloo/api/grpc/version/version.proto#L30) I think we may want to approach this slightly differently.

At the moment we have a ServerVersion concept, and there is one concrete type that we implement, a KubernetesServerVerision.

At the moment that type (https://github.com/solo-io/gloo/blob/main/projects/gloo/api/grpc/version/version.proto#L46) has a list of contains and namespace where GLoo is installed.

I think we could expand this API to also have cluster metadata. The downside is that this would lead us to duplicate the values if we did have multiple installs of gloo in the same cluster (each ServerVersion would have a reference to the same cluster metadata), but I think the benefit is that it allows us to use the existing API

2024-03-07 16:32 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +func (k *kube) Get(ctx context.Context) ([]*version.ServerVersion, *kube1vVersion.Info, error) {
see https://github.com/solo-io/gloo/pull/9212#discussion_r1516178018, i think it might be more appropriate to put the new field (KubernetesVersion / KubernetesServerVersion) in Version, so there is just one instance returned, rather than one per gloo instance

2024-03-07 22:56 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +func (k *kube) Get(ctx context.Context) ([]*version.ServerVersion, *kube1vVersion.Info, error) {
nice! yeah totally agreed with @jenshu . i didn't look far enough down in the proto 😮‍💨 , but where she proposes is exactly where I'd put it

2024-03-18 05:27 UTC, codeverifier commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +func (k *kube) Get(ctx context.Context) ([]*version.ServerVersion, *kube1vVersion.Info, error) {
I was worried you guys might say that 😅, i just didnt want to touch the proto.
but agreed. made the change.

2024-03-18 17:07 UTC, jenshu requested changes

2024-03-18 17:07 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +	// check for special case of image string following <registry:port/name>
it's a bit hard to follow what this function is doing. can you document here what an example input/output would be?

2024-03-18 17:07 UTC, jenshu commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +		copyArr[0] = arr[0] + ":" + arr[1]
seems to be a bug here: if `arr` is of length 2, then `copyArr` is initialized with length=0, and this line results in a panic trying to reference `copyArr[0]`

2024-03-18 22:23 UTC, codeverifier commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +		copyArr[0] = arr[0] + ":" + arr[1]
good catch, il add a test case for it.

2024-03-19 21:02 UTC, jenshu reviewed
thanks for the comments and tests!

2024-03-20 19:03 UTC, jenshu submitted a review, later dismissed

2024-03-20 21:35 UTC, sam-heilbron commented
/kick build-bot seems hung?

2024-03-20 21:40 UTC, sam-heilbron submitted a review, later dismissed
nice work!

2024-03-20 21:40 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +	}
These lines feel redundant. `GetConfig` just calls `GetConfigWithContext` and passes an empty string, so I think we can just simplify this to:
```suggestion
	cfg, err = kubeutils.GetConfigWithContext("", "", k.kubeContext)
```

2024-03-20 21:40 UTC, sam-heilbron commented on projects/gloo/cli/pkg/cmd/version/version_test.go
> +			//client.EXPECT().GetClusterVersion().Return(nil, nil).Times(0)
nit: Can we delete this, or should we re-add the assertion?

2024-03-20 21:45 UTC, codeverifier commented on projects/gloo/cli/pkg/cmd/version/clients.go
> +	}
i assume this was probably left for backwards compatibility or something and never refactored. i can remove it.

2024-03-21 02:54 UTC, jenshu approved these changes

2024-03-21 11:13 UTC, sam-heilbron approved these changes

2024-03-21 11:14 UTC, sam-heilbron commented
bulldozer

2024-03-21 11:15 UTC, merged