add RouteOption policy attachment
solo-io/gloo pull request #9281
Opened 2024-03-28 03:00 UTC by lgadban

# Description

Please include a high level summary of the changes.

This bug fixes ... \ This new feature can be used to ...

_Fill out any of the following sections that are relevant and remove the others_
## API changes
- Added x field to y resource
- ...

## Code changes
- Fix error in `Foo()` function
- Add `Bar()` function
- ...

## CI changes
- Adjusted schedule for x job
- ...

## Docs changes
- Added guide about feature x to public docs
- Updated README to account for y behavior
- ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

See slack conversation [here](https://solo-io-corp.slack.com/archives/some/post)

## Interesting decisions
 
We chose to do things this way because ...

## Testing steps

I manually verified behavior by ...

## Notes for reviewers

Be sure to verify intended behavior by ...

Please proofread comments on ...

This is a complex PR and may require a huddle to discuss ...

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-03-29 21:34 UTC, ilackarms requested changes

2024-03-29 21:34 UTC, ilackarms commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
i believe we should go with `target_refs` here unless we want to make the change in a follow up

2024-03-29 21:34 UTC, ilackarms commented on projects/gateway2/controller/controller.go
> +// TODO: move to RtOpt plugin when breaking the logic to RouteOption-specific controller
👍

2024-03-29 21:34 UTC, ilackarms commented on projects/gateway2/translator/plugins/plugins.go
> +	GetName() string
a comment here would be nice (in particular explaining why it's necessary for every plugin to impement GetName, and that the return value should be unique amongst plugins)

though i wonder if the return value should be unique against plugins would it be better to store these in a map somewhere

2024-03-29 21:34 UTC, ilackarms commented on projects/gateway2/translator/plugins/plugins.go
> +	GetName() string
no strong feeling on this though but the comment would be nice

2024-03-31 21:36 UTC, lgadban commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
yeah this should be considered out of scope for this PR

2024-03-31 21:37 UTC, lgadban commented on projects/gateway2/translator/plugins/plugins.go
> +	GetName() string
was not intended to be that formal, was simply a way of providing a sane logging flow.
going to remove so it can be addressed holistically later

2024-04-02 13:26 UTC, jenshu commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
just a note that if we make this change in a follow-up, it will be a breaking change

2024-04-02 13:30 UTC, jenshu commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
should this field go in the VirtualHostOptions in options.proto instead of here?

2024-04-02 14:44 UTC, lgadban commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
I don't think the intent would be to release without adding any necessary functionality, more so that there was a limited scope for this work and the follow on work that depends on this

2024-04-02 14:49 UTC, lgadban commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
This is specifically for RouteOptions (notably VHostOptions is a different set of config that is associated with gwapi.Listener/envoy VirtualHost that is coming in the next set of work related to policy)

>or maybe target refs only applies in the standalone case?

Correct, `targetRef` is purely for the case of attaching a policy object, in this case a `RouteOption` resource, to another resource (e.g. HTTPRoute)
So this is indeed only relevant when using a `RouteOption` standalone object.

2024-04-02 16:01 UTC, jenshu commented on projects/gateway/api/v1/external_options.proto
> +  core.skv2.solo.io.PolicyTargetReference target_ref = 5;
sorry yeah i meant RouteOptions.
ok makes sense!

2024-04-03 15:44 UTC, sam-heilbron commented
/kick 

Logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=935fe1f3-ada2-4021-917a-39f2fe3b3464
Error:
```
Step #1 - "run-tests": Step #8 - "run-e2e-tests": [38;5;9m[1mSummarizing 1 Failure:[0m
Step #1 - "run-tests": Step #8 - "run-e2e-tests":   [38;5;9m[FAIL][0m [0mStaged Transformation [38;5;243mno auth [0mcan enable enhanced logging [38;5;9m[1m[It] staged logging enabled, individual logging enabled[0m
Step #1 - "run-tests": Step #8 - "run-e2e-tests":   [38;5;243m/workspace/gloo/test/e2e/staged_transformation_test.go:644[0m
Step #1 - "run-tests": Step #8 - "run-e2e-tests": 
```

GitHub issue: https://github.com/solo-io/gloo/issues/9292

2024-04-03 15:45 UTC, sam-heilbron submitted a review, later dismissed

2024-04-03 20:24 UTC, sam-heilbron submitted a review, later dismissed

2024-04-04 01:43 UTC, jenshu commented on projects/gateway2/translator/plugins/routeoptions/query/indexers.go
> +		panic(fmt.Sprintf("wrong type %T provided to indexer. expected gateway.solo.io.RouteOption", obj))
should this log an error instead of panicking?

2024-04-04 01:43 UTC, jenshu commented on projects/gateway2/translator/plugins/utils/sort_objects.go
> +		panic(err)
should this log an error instead of panicking?

2024-04-04 14:50 UTC, lgadban commented on projects/gateway2/translator/plugins/routeoptions/query/indexers.go
> +		panic(fmt.Sprintf("wrong type %T provided to indexer. expected gateway.solo.io.RouteOption", obj))
this is using the pattern in existing query indexers, such as here: https://github.com/solo-io/gloo/blob/main/projects/gateway2/query/indexers.go#L28

notably this function can not return an error, and if we hit this case, the Listing won't work and we are broken.
This would only happen if the indexing is setup incorrectly, which is essentially a developer error.

My opinion is to leave it -- wdyt?

2024-04-04 15:22 UTC, lgadban commented on projects/gateway2/translator/plugins/utils/sort_objects.go
> +		panic(err)
this also was adapted [from elsewhere](https://github.com/solo-io/gloo-mesh-enterprise/blob/main/pkg/translator/utils/sort_creation_timestamp.go#L21) -- and also is essentially a developer error, i.e. passing an incorrect object to `Sort...(...)`

we could switch this one to a dpanic and pass in a logger. wdyt?

2024-04-04 15:24 UTC, jenshu commented on projects/gateway2/translator/plugins/routeoptions/query/indexers.go
> +		panic(fmt.Sprintf("wrong type %T provided to indexer. expected gateway.solo.io.RouteOption", obj))
that sounds reasonable

2024-04-04 15:24 UTC, jenshu commented
LGTM, pending @ilackarms review

2024-04-04 16:28 UTC, ilackarms commented on projects/gateway2/extensions/extensions.go
> +	plugins := registry.BuildPlugins(queries, e.mgr.GetClient())
i expect we will want to just pass `client`+`scheme` eventually since the plugins may be initializing their own queries (such as portal) but we can wait til we need it to make that change

2024-04-04 16:30 UTC, ilackarms commented on projects/gateway2/translator/plugins/routeoptions/query/indexers.go
> +		panic(fmt.Sprintf("wrong type %T provided to indexer. expected gateway.solo.io.RouteOption", obj))
in general i think we usually prefer dpanics over panics but i agree we should keep consistent, changing it all at once if we decide to do so

2024-04-04 16:32 UTC, ilackarms commented on projects/gateway2/translator/plugins/routeoptions/route_options_plugin.go
> +	routeOptions = p.handleAttachment(ctx, routeCtx)
nit: `routeOptions := ...`

2024-04-04 16:33 UTC, lgadban commented on projects/gateway2/translator/plugins/routeoptions/query/indexers.go
> +		panic(fmt.Sprintf("wrong type %T provided to indexer. expected gateway.solo.io.RouteOption", obj))
the challenge with a dpanic here is we don't have control of the signature to this function, so we would need to use some weirdness to get access to the logger to do a dpanic.

agreed on keeping it consistent for now as well

2024-04-04 19:57 UTC, ilackarms approved these changes

2024-04-04 19:57 UTC, lgadban commented
/kick

2024-04-04 20:50 UTC, jenshu approved these changes

2024-04-04 20:52 UTC, merged