Refactor Makefile docker variant targerts and fix for m1 machines
solo-io/gloo pull request #9322
Opened 2024-04-04 19:31 UTC by davidjumani

# Description

- Refactor the Makefile grouping targets based on variants to simplify large make targets
- Adds the amd64 platform for all distroless base images since we only publish amd64 images and use amd64 envoy. This also unblocks distroless dev on m1. 
When building distroless images on m1, it fails when using the distroless-base image even if it exists as the arch is amd64. It tries to fetch the arm64 distroless-base image from quay that doesn't exist and shows this error
`
ERROR: failed to solve: [quay.io/solo-io/distroless-base:1.0.1-dev](http://quay.io/solo-io/distroless-base:1.0.1-dev): failed to resolve source metadata for [quay.io/solo-io/distroless-base:1.0.1-dev](http://quay.io/solo-io/distroless-base:1.0.1-dev): unexpected status from HEAD request to https://quay.io/v2/solo-io/distroless-base/manifests/1.0.1-dev: 401 UNAUTHORIZED
`
This fixes it by ensuring we only use amd64 images for distroless builds

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-11 15:37 UTC, sheidkamp requested changes
One spot where it looks like there was a c/p error. Otherwise LGTM.

2024-04-11 15:37 UTC, sheidkamp commented on Makefile
> +
Should these be `-distroless`?

2024-04-11 15:39 UTC, sheidkamp requested changes
one more c/p error

2024-04-11 15:39 UTC, sheidkamp commented on Makefile
> +docker-standard: kubectl-distroless-docker
these `docker-standards` should be `docker-distroless`

2024-04-11 15:48 UTC, sheidkamp approved these changes

2024-04-11 15:50 UTC, davidjumani commented on Makefile
> +
Good catch! Thanks

2024-04-11 15:51 UTC, davidjumani commented on Makefile
> +docker-standard: kubectl-distroless-docker
Good catch! Thanks

2024-04-12 16:45 UTC, bewebi commented on ci/kind/setup-kind.sh
> +IMAGE_VARIANT="${IMAGE_VARIANT:-standard}"
Doesn't this need to get passed as an env var to step #2 below?

2024-04-12 16:58 UTC, sheidkamp approved these changes

2024-04-12 17:02 UTC, bewebi submitted a review, later dismissed
LGTM

2024-04-12 19:03 UTC, nfuden approved these changes

2024-04-12 19:18 UTC, sheidkamp approved these changes

2024-04-12 20:05 UTC, merged