Add status syncer to fix RouteOptions statuses
solo-io/gloo pull request #9373
Opened 2024-04-16 15:54 UTC by npolshakova

# Description

Statuses are back on RouteOptions with targetRefs!

```
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"gateway.solo.io/v1","kind":"RouteOption","metadata":{"annotations":{},"name":"foo","namespace":"default"},"spec":{"options":{"extauth":{"configRef":{"name":"basic-auth","namespace":"gloo-system"}},"retries":{"numRetries":3,"perTryTimeout":"5s","retryOn":"connect-failure"},"timeout":"10s"},"targetRef":{"group":"gateway.networking.k8s.io","kind":"HTTPRoute","name":"example-route"}}}
  creationTimestamp: "2024-04-16T15:34:00Z"
  generation: 2
  name: foo
  namespace: default
  resourceVersion: "7924"
  uid: 1892c23e-9779-4130-85b4-792beba4bf6b
spec:
  options:
    extauth:
      configRef:
        name: basic-auth
        namespace: gloo-system
    retries:
      numRetries: 3
      perTryTimeout: 5s
      retryOn: connect-failure
    timeout: 10s
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
status:
  statuses:
    gloo-system:
      reportedBy: gloo-kube-gateway
      state: Accepted

```

2024-04-16 21:22 UTC, lgadban commented
just confirmed locally off this branch that errors are being propagated as well:
```
status:
  statuses:
    gloo-system:
      reason: "2 errors occurred:\n\t* *faultinjection.plugin: invalid abort status
        code '0', must be in range of [200,600). Route Name: http~example_com-route-0-matcher-0\n\t*
        *faultinjection.plugin: invalid abort status code '0', must be in range of
        [200,600). Route Name: http~example_com-route-1-matcher-0\n\n"
      reportedBy: gloo-kube-gateway
      state: Rejected
      subresourceStatuses:
        gloo-kube-gateway-api~default~default-gw:
          reason: "1 error occurred:\n\t* Route Error: ProcessingError. Reason: *faultinjection.plugin:
            invalid abort status code '0', must be in range of [200,600). Route Name:
            http~example_com-route-0-matcher-0; Route Error: ProcessingError. Reason:
            *faultinjection.plugin: invalid abort status code '0', must be in range
            of [200,600). Route Name: http~example_com-route-1-matcher-0\n\n"
          reportedBy: gloo-kube-gateway
          state: Rejected
```

2024-04-18 15:16 UTC, sam-heilbron reviewed
I just focused on the testing portion for this first pass. I'm happy to review the status syncing work as well, but trying to separate the two in my head

2024-04-18 15:16 UTC, sam-heilbron commented on pkg/utils/kubeutils/portforward/api_forwarder.go
> +func (f *apiPortForwarder) LocalPort() int {
I like this addition, and am happy to keep it. Originally, this was just returned within the `Address` method. If we want to expose more methods to give granular access to properties, should we also expose a method for localAddress?

2024-04-18 15:16 UTC, sam-heilbron commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
My hope with the gloogateway.Context (https://github.com/solo-io/gloo/blob/main/test/kubernetes/testutils/gloogateway/context.go#L3) was that it contains all the properties of the installation, and the TestInstallation can contain whatever references it needs. Instead of re-defining the properties on this new struct, what if we just made the entire gloogateway.Context available on this object? That way, as we add more properties to it, the TestInstallation gets them for free

2024-04-18 15:16 UTC, sam-heilbron commented on test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
> +  singleNamespace: false
Since this is an intentional change, and a requirement of the feature, I think it could be valuable to have a comment here indicating why we set this value, and perhaps linking any relevant github issues? Ideally it will help us avoid questions around why we set this

2024-04-18 15:16 UTC, sam-heilbron commented on test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
> -  glooRbac:
Could we set this, but explicitly set it to false? That way we can add a comment about why this is required to be clusterscoped, and link the relevant issues/context

2024-04-18 15:16 UTC, sam-heilbron commented on test/kubernetes/testutils/cluster/context.go
> +	RouteOptionClient gatewayv1.RouteOptionClient
I was hoping that a cluster.Context has no knowledge of Edge/Gateway concepts, it is just a kubernetes cluster with utilities. I figured that if we need a set of clients for edge purposes, those should be created per testInstallation, since clients would operate against resources of an installation

2024-04-18 15:39 UTC, npolshakova commented on pkg/utils/kubeutils/portforward/api_forwarder.go
> +func (f *apiPortForwarder) LocalPort() int {
I'm leaning towards moving away from the port forward testing- it looks isn't as stable in ci: https://github.com/solo-io/gloo/actions/runs/8739466981/job/23980869526  

I'm moving towards creating a `curl` deployment as part of the setup and sending requests from there: https://github.com/solo-io/gloo/pull/9373/commits/dae5bbf755eda66fc87b3a3dff3d046cdbfb44f0

2024-04-18 15:42 UTC, npolshakova commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
But then we're tying the `gloogateway.Context` to the installation, so for classic edge apis you need to still set this value in order to get the namespace? Maybe we should rename the context?

2024-04-18 15:43 UTC, npolshakova commented on test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
> +  singleNamespace: false
Do you think we need a docs change here? I created a related issue, but it's not specifically calling out that we need to document this as a requirement for Gloo Gateway: https://github.com/solo-io/solo-projects/issues/6058

2024-04-18 15:52 UTC, npolshakova commented on test/kubernetes/testutils/cluster/context.go
> +	RouteOptionClient gatewayv1.RouteOptionClient
I think I can't move it into the test itself because we invoke the test with: 
```
testInstallation.RunTest(ctx, route_options.ConfigureRouteOptionsWithTargetRef)
```

So it needs to be part of the testInstallation, it can't just be initialized on the test itself. Does that sound reasonable?

2024-04-18 16:01 UTC, sam-heilbron commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
I'm a bit confused, an installation is a running instance of Gloo. I figured it has 2 types of things: metadata about the install (gloogateway.Context), utilities to help tests interact with the install (TestInstalllation).

2024-04-18 16:01 UTC, sam-heilbron commented on test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
> +  singleNamespace: false
yeah great call! I like having our tests as the last line of defense, since sometimes we forget to publicly document behaviors, but I really like putting this in our user-facing docs too

2024-04-18 16:02 UTC, sam-heilbron commented on test/kubernetes/testutils/cluster/context.go
> +	RouteOptionClient gatewayv1.RouteOptionClient
`So it needs to be part of the testInstallation, it can't just be initialized on the test itself. Does that sound reasonable?`

Oh I agree with this. What I was proposing was that the TestInstallation have a set of clients. So tests can use them

2024-04-18 16:28 UTC, sam-heilbron commented on test/kubernetes/e2e/features/route_options/route_options.go
> +func curl(ctx context.Context, ns, fromDeployment, fromContainer, fdqnAddr, host string) (string, error) {
I had imagined that we could invert the relationship here. Instead of having curl information, and using the kubecli, I thought that a kubeCli command that we expose is "ExecCurl" and we pass it the curlOptions that we want to exec. Then the details how how we do it are isolated to the kubeCli

2024-04-18 16:50 UTC, npolshakova commented on test/kubernetes/e2e/features/route_options/route_options.go
> +func curl(ctx context.Context, ns, fromDeployment, fromContainer, fdqnAddr, host string) (string, error) {
Yeah I think that makes sense- that way all the args (ns, fromDeployment, fromContainer, fdqnAddr, host, etc.) can be combined in `curlOptions` and have sane defaults/error if fields aren't set. The tricky part here is you need to know to setup a curl deployment for this to work.

2024-04-18 17:14 UTC, npolshakova commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
If I'm running a gloo classic edge api with the new framework, do I need to define a `gloogateway.Context`? If I associate the `gloogateway.Context` with the TestInstalllation I think we should rename the resource. 

Since I'm using the installation namespace in the test assertion I need it to either be on the TestInstalllation or we need to also pass the context here and make it an interface (to support non Gloo Gateway tests): 

```
testInstallation.RunTest(ctx, route_options.ConfigureRouteOptionsWithTargetRef)
```

2024-04-18 17:20 UTC, npolshakova commented on test/kubernetes/e2e/k8sgateway/manifests/k8s-gateway-test-helm.yaml
> -  glooRbac:
Created one: https://github.com/solo-io/solo-projects/issues/6064

2024-04-18 20:23 UTC, jbohanon commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
I think @sam-heilbron's intention (ccorrect me if I'm wrong) is to remove the distinction between "edge" and "gateway" as products, and lean in toward "gloo gateway" is the product and within that there are classic gateway resources and k8s gateway resources. From this perspective, ALL of our tests here are "gloo gateway" tests

2024-04-18 21:00 UTC, sam-heilbron commented on test/kubernetes/e2e/framework.go
> +		// Namespace is the namespace where the installation of Gloo Gateway is running
Oh yeah sorry for the confusion. Yeah @jbohanon is correct. My hope was just that you install Gloo Gateway, and perhaps you have k8s gateway integration enabled, perhaps not. Perhaps you have istio enabled, perhaps not. But ulimately, there are some properties about that installation that we track in a `gloogateway.Context`. And as you show on your PR, there are situations where tests may want to consume that information

2024-04-18 21:01 UTC, sam-heilbron commented on test/kubernetes/e2e/features/route_options/route_options.go
> +					// Check status on solo-apis client object
Can we use https://github.com/solo-io/gloo/blob/main/test/helpers/input_resources.go#L27 instead? Since it accepts "getter" method

2024-04-18 22:39 UTC, npolshakova commented on test/kubernetes/e2e/features/route_options/route_options.go
> +					// Check status on solo-apis client object
The downside is I think this doesn't let you check other fields on the status like: 
```
g.Expect(routeOption.GetNamespacedStatuses().GetStatuses()[installation.Metadata.InstallNamespace].GetReportedBy()).To(Equal("gloo-kube-gateway"))
						g.Expect(routeOption.GetNamespacedStatuses().GetStatuses()[installation.Metadata.InstallNamespace].GetState()).To(Equal(core.Status_Accepted))
					
```

But that could be a separate check?

2024-04-18 22:41 UTC, npolshakova commented on test/kubernetes/e2e/features/route_options/route_options.go
> +					// Check status on solo-apis client object
Added the change here: https://github.com/solo-io/gloo/pull/9373/commits/58f6eb5a047a28a9c4dae4833eae3d473fa8665f

2024-04-18 22:41 UTC, npolshakova commented on test/kubernetes/e2e/features/route_options/route_options.go
> +func curl(ctx context.Context, ns, fromDeployment, fromContainer, fdqnAddr, host string) (string, error) {
Moved testing changes to: https://github.com/solo-io/gloo/pull/9388

2024-04-19 13:36 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +	registryPerProxy   map[*v1.Proxy]*registry.PluginRegistry
"This instance of proxy" != this proxy. The proxy object will be different even with the same name/namespace (route attachments, changes to proxy).

2024-04-19 13:40 UTC, npolshakova commented on projects/gateway2/proxy_syncer/proxy_syncer.go
> +		s.queueStatusForProxies(proxies, &pluginRegistry)
This doesn't need to synchronously, we can push to a channel here.

2024-04-19 13:56 UTC, npolshakova commented on projects/gateway2/proxy_syncer/proxy_syncer.go
> +				proxy.GetMetadata().GetLabels()[utils.ProxyId] = uuid.New().String()
Store generation/count per proxy name.namespace (drop the older counts)

2024-04-22 17:38 UTC, lgadban reviewed
1st pass, simple questions on commentary

2024-04-22 17:38 UTC, lgadban commented on projects/gateway2/status/status_syncer.go
> +// QueueStatusForProxiesFn queues a status sync for a given set of Proxy resources along with the plugins that produced them
wrong comment?

2024-04-22 17:38 UTC, lgadban commented on projects/gateway2/status/status_syncer.go
> +	// maps a proxy to the sync iteration that produced it
can we elaborate here explaining how the namespacedName -> syncCount mapping is sufficient given that a proxy's namespacedName is the same across many syncs even if the underlying Proxy itself has changed

2024-04-22 18:27 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +// QueueStatusForProxiesFn queues a status sync for a given set of Proxy resources along with the plugins that produced them
Copied it over from the proxy_syncer comment, will update both!

2024-04-23 17:18 UTC, lgadban commented on projects/gateway2/status/status_syncer.go
> +			if len(f.resyncsPerProxy) == 0 {
why is this happening inside the `range proxiesToReport`?

it seems like this is effectively saying "if we don't have any proxies to sync status for, throw away whatever plugins are maintained because they are no longer needed"

if `f.resyncPerProxy` is empty but there are multiple proxies in `proxiesToReport`, wouldn't this break after the first iteration of the loop?

2024-04-23 17:18 UTC, lgadban commented on projects/gateway2/status/status_syncer_test.go
> +		Expect(registryMap).ToNot(ContainElement(123))
how would proxyTwo sync it's status if the plugins for `123` are now gone?

2024-04-23 17:29 UTC, lgadban commented on projects/gateway2/status/status_syncer_test.go
> +		// Ensure proxy one has been removed from the queue after handling reports, but proxy two is still present
actually, my comment below might not be accurate; is this comment correct? seems like proxy two is NOT present

2024-04-23 17:35 UTC, npolshakova commented on projects/gateway2/status/status_syncer_test.go
> +		Expect(registryMap).ToNot(ContainElement(123))
Both proxies are in the list here: 

```
// Handle the proxy reports only for proxy one (this is invoked as a callback in the envoy translator syncer)
		proxiesWithReports := []translatorutils.ProxyWithReports{
			{
				Proxy: proxyOne,
				Reports: translatorutils.TranslationReports{
					ProxyReport:     &validation.ProxyReport{},
					ResourceReports: reporter.ResourceReports{},
				},
			},
			{
				Proxy: proxyTwo,
				Reports: translatorutils.TranslationReports{
					ProxyReport:     &validation.ProxyReport{},
					ResourceReports: reporter.ResourceReports{},
				},
			},
		}
		ctx := context.Background()
		syncer.HandleProxyReports(ctx, proxiesWithReports)
```

The comment is off- it's from an older iteration of the test. I can update it to call HandleProxyReports twice though and first check 1) proxy one is correctly handled, the plugins are still present. 2) proxy two is correctly handled, everything is cleaned up

2024-04-23 17:35 UTC, npolshakova commented on projects/gateway2/status/status_syncer_test.go
> +		// Ensure proxy one has been removed from the queue after handling reports, but proxy two is still present
Yep, the comment is wrong- I'll update the test: https://github.com/solo-io/gloo/pull/9373#discussion_r1576637014

2024-04-23 17:38 UTC, npolshakova commented on projects/gateway2/status/status_syncer_test.go
> +		// Ensure proxy one has been removed from the queue after handling reports, but proxy two is still present
Ah, actually I already have that test as part of `should queue proxy, handle report and clean up after report is processed`. I just need to fix the comment here.

2024-04-23 17:39 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +		if f.resyncsPerProxy[proxyKey] > proxySyncCount {
Yep exactly, that's what the last unit test shows. If the syncCount is higher, we continue because we can ignore the older sync reports since they are not the latest report.

2024-04-23 17:41 UTC, npolshakova commented on projects/gateway2/status/status_syncer_test.go
> +		Expect(registryMap).ToNot(ContainElement(123))
Actually that test is already present^. I'm just going to fix the comment here.

2024-04-23 17:43 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +			if len(f.resyncsPerProxy) == 0 {
I think this should be moved to the end of the HandleProxyReports(). I agree, it doesn't need to be in this for loop.

2024-04-23 17:47 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +		if f.resyncsPerProxy[proxyKey] > proxySyncCount {
Added a comment: https://github.com/solo-io/gloo/pull/9373/commits/e647278a6f0520a62061e9d43155e36e136858e6

2024-04-23 17:48 UTC, npolshakova commented on projects/gateway2/status/status_syncer.go
> +			if len(f.resyncsPerProxy) == 0 {
Moved out of the loop: https://github.com/solo-io/gloo/pull/9373/commits/e647278a6f0520a62061e9d43155e36e136858e6

2024-04-23 17:48 UTC, npolshakova commented on projects/gateway2/status/status_syncer_test.go
> +		Expect(registryMap).ToNot(ContainElement(123))
Updated comment: https://github.com/solo-io/gloo/pull/9373/commits/e647278a6f0520a62061e9d43155e36e136858e6

2024-04-23 18:08 UTC, lgadban requested changes
can we update the changelog to resolve this issue: https://github.com/solo-io/solo-projects/issues/6084

2024-04-24 01:16 UTC, lgadban reviewed
mostly LGTM, just a few more items to possibly cleanup

2024-04-24 01:16 UTC, lgadban commented on projects/gateway2/controller/start.go
> +		cfg.StatusReporter,
why are RouteOptionClient and StatusReporter needed on the ProxySyncer?
can we remove from `NewProxySyncer(...)` as well as on the struct itself?

2024-04-24 14:46 UTC, ilackarms submitted a review, later dismissed

2024-04-25 16:32 UTC, lgadban approved these changes

2024-04-25 17:06 UTC, sam-heilbron approved these changes

2024-04-25 17:06 UTC, merged