test/e2e: add debugging guide for new framework
solo-io/gloo pull request #9415
Opened 2024-04-29 17:25 UTC by shashankram

Adds a debugging guide to list basic workflows to enable running tests using a debugger.

2024-04-29 18:07 UTC, sam-heilbron reviewed
small notes, ill follow up with more thoughts later on

2024-04-29 18:10 UTC, shashankram commented on changelog/v1.17.0-beta24/e2e-dbg.yaml
> +    skipCI: false
I used my GME helper script! Do we have an equivalent Make target to auto-create a changelog file in the correct directory?

2024-04-29 18:54 UTC, sam-heilbron commented on changelog/v1.17.0-beta24/e2e-dbg.yaml
> +    skipCI: false
https://github.com/solo-io/gloo/tree/main/devel/tools

2024-04-30 14:27 UTC, shashankram commented on test/kubernetes/e2e/debugging.md
> +Setting `SKIP_INSTALL` to `true` will skip the installation of Gloo, which is useful to debug against a pre-existing/stable environment with Gloo already installed.
I disagree that this is the wrong place to reference. It's something I use to quickly debug tests that is worth noting.

2024-04-30 17:51 UTC, sheidkamp requested changes
Looks good! I was able to get the tests running easily.

I got a little confused about what some terms meant, and have comments where that happened.

2024-04-30 17:51 UTC, sheidkamp commented on test/kubernetes/e2e/debugging.md
> +The entry point for an e2e test is a Go test function of the form `func TestXyz(t *testing.T)` which represents a top level suite against an installation mode of Gloo. For example, the `TestK8sGatewa
Consider adding a link into the code

2024-04-30 17:51 UTC, sheidkamp commented on test/kubernetes/e2e/debugging.md
> +Each feature suite is invoked as a subtest of the top level suite. The subtests use [testify](https://github.com/stretchr/testify) to structure the tests in the feature's test suite and make use of t
You are referring to "Top Level Suites", "Feature Suites", and "Subtests" in this section - can you define each of these and/or provide links?

2024-04-30 18:42 UTC, sheidkamp commented on changelog/v1.17.0-beta24/e2e-dbg.yaml
> +changelog:
Comment to allow updated review

2024-04-30 18:45 UTC, sheidkamp submitted a review, later dismissed

2024-04-30 19:09 UTC, shashankram commented on test/kubernetes/e2e/debugging.md
> +Each feature suite is invoked as a subtest of the top level suite. The subtests use [testify](https://github.com/stretchr/testify) to structure the tests in the feature's test suite and make use of t
rephrased this, but the lines above are meant to convey these terms.

2024-04-30 19:39 UTC, sheidkamp submitted a review, later dismissed

2024-04-30 19:54 UTC, sam-heilbron approved these changes

2024-04-30 20:36 UTC, sheidkamp approved these changes

2024-04-30 20:36 UTC, merged