Adding tilt for enhanced development
solo-io/gloo pull request #9420
Opened 2024-04-30 17:27 UTC by davidjumani

# Description

This PR adds the ability to bring up, run and debug edge via tilt.
It is as simple as running `tilt up` once your cluster is configured.
The full guide is found in devel/tilt

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-04-30 17:28 UTC, davidjumani commented
/skip-ci

2024-04-30 18:22 UTC, ashishb-solo commented on devel/tilt/tilt.md
> +This allows
looks like an incomplete sentence here

2024-04-30 18:43 UTC, davidjumani commented on devel/tilt/tilt.md
> +This allows
Updated!

2024-04-30 19:58 UTC, ashishb-solo approved these changes

2024-04-30 22:28 UTC, bewebi requested changes
It mainly seems to work as intended however updates seem to fail with the following error when set up using the steps from `devel/tilt/tilt/md`:
```
/app/start.sh: 34: cannot create process.txt: Read-only file system
```
This seems to stem from the Gloo deployment having a `securityContext` with `readOnlyRootFilesystem: true` and Tilt having to write to the pod's filesystem on startup
Manually triggering update from the Tilt UI seems to override the `securityContext`, enabling updates to occur without this error

If there is a way to avoid having the `securityContext` contain `readOnlyRootFilesystem: true` on the initial `tilt up` command that would be ideal, perhaps by ensuring that `.test/kube2e/helm/artifacts/helm.yaml` specifies `securityContext` without `readOnlyRootFilesystem: true`
If this is not reasonable, and perhaps even if it is, the instructions should identify that manually triggering update is a useful troubleshooting step

2024-04-30 22:28 UTC, bewebi commented on tilt-settings.yaml
> +    binary_name: gloo-linux-arm64
Not all devs will be using this binary
If there's a way to dynamically determine which should be used, that would be great, though I'm not sure if that's reasonable

As an alternative we can add a commented line that calls out that some devs may need to use the AMD binary
```suggestion
    binary_name: gloo-linux-arm64
    # binary_name: gloo-linux-amd64 # devs on AMD machines will need to use this binary instead
```

2024-05-01 14:15 UTC, davidjumani commented on tilt-settings.yaml
> +    binary_name: gloo-linux-arm64
Thanks, I've updated the docs as well as made provision for the architecture

2024-05-01 16:43 UTC, bewebi approved these changes
Awesome changes, works like a charm!

2024-05-01 16:44 UTC, davidjumani commented
/skip-ci

2024-05-02 16:23 UTC, ashishb-solo approved these changes

2024-05-02 18:14 UTC, davidjumani commented
/skip-ci

2024-05-02 18:15 UTC, merged