Lambda 302 tests
solo-io/gloo pull request #9455
Opened 2024-05-06 21:31 UTC by bewebi

# Description

Please include a high level summary of the changes.

This bug fixes ... \ This new feature can be used to ...

_Fill out any of the following sections that are relevant and remove the others_
## API changes
- Added x field to y resource
- ...

## Code changes
- Fix error in `Foo()` function
- Add `Bar()` function
- ...

## CI changes
- Adjusted schedule for x job
- ...

## Docs changes
- Added guide about feature x to public docs
- Updated README to account for y behavior
- ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

See slack conversation [here](https://solo-io-corp.slack.com/archives/some/post)

## Interesting decisions
 
We chose to do things this way because ...

## Testing steps

I manually verified behavior by ...

## Notes for reviewers

Be sure to verify intended behavior by ...

Please proofread comments on ...

This is a complex PR and may require a huddle to discuss ...

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-05-08 19:08 UTC, ashishb-solo requested changes
Looks great! Bernie and I met on a huddle and demonstrated that the envoy bump fixes the issue. With the bump, the test behaves as expected, and without the bump, the test returns an error.

The last ask is for an additional test to ensure that we are testing an additional failure case. At that point, I'm happy to approve

2024-05-09 12:15 UTC, ashishb-solo reviewed
Looks great! A few comments, but hopefully not too difficult to address

2024-05-09 12:15 UTC, ashishb-solo commented on changelog/v1.17.0-beta26/envoy-bump-and-test-multivalueheader-fix.yaml
> +      type with `unwrapAsApiGateway` enabled would lead to a 500 response
I found the changelog description a little hard to understand. What do you think of this? (Note that I left out the part about the version bump since that should be captured by the `dependency*` fields.)

```suggestion
      Fix a bug when Lambdas that return non-string types with `unwrapAsApiGateway` enabled would lead to a 500 response
```

2024-05-09 12:15 UTC, ashishb-solo commented on test/e2e/aws_test.go
> +	// this tests the case where a lambda returns malformed multiValueHeaders, a case which previously caused Envoy to
could you explain exactly _why_ we consider the headers to be malformed ?

2024-05-09 12:15 UTC, ashishb-solo commented on test/gomega/matchers/contain_headers.go
> +func ContainHeaderKeysExact(keys []string) types.GomegaMatcher {
i would personally prefer calling this `OnlyContainHeaderKeys` (or `OnlyContainHeaderKeysAndValues`), but happy to leave this as it is. Whichever you like the most!

2024-05-09 12:15 UTC, ashishb-solo commented on test/e2e/aws_test.go
> +				Custom:     And(testmatchers.ContainHeaders(params.expectedHeaders), testmatchers.ContainHeaderKeysExact(params.exactExpectedHeaderKeys)),
Do we need both `ContainHeaders` and `ContainHeaderKeysExact`? Can we get rid of `ContainHeaders`? If I understand correctly, `ContainHeaders` can never fail unless `ContainHeaderKeysExact` also fails (but I could be wrong here)

2024-05-09 12:39 UTC, nfuden commented on changelog/v1.17.0-beta26/envoy-bump-and-test-multivalueheader-fix.yaml
> +      type with `unwrapAsApiGateway` enabled would lead to a 500 response
Should we escalate this to a fix to make sure it shows up in the changelog? or are we putting that in the EE?

2024-05-09 12:40 UTC, nfuden commented on test/gomega/matchers/contain_headers.go
> +func ContainHeaderKeysExact(keys []string) types.GomegaMatcher {
nit: for the above comment I would consider prepending a `nit:` tag

2024-05-09 15:25 UTC, bewebi commented on test/e2e/aws_test.go
> +				Custom:     And(testmatchers.ContainHeaders(params.expectedHeaders), testmatchers.ContainHeaderKeysExact(params.exactExpectedHeaderKeys)),
`ContainHeaders` checks the _values_ of the headers, but doesn't require that those specified constitute all headers
`ContainHeaderKeysExact` checks that the specified keys constitute the exact set of header keys

In theory either could fail but not the other (eg we check one header via `ContainHeaders` and it's value is wrong, but `ContainHeaderKeysExact` shows that we have all of the expected keys and no others)

In practice I don't expect devs to set both
If we want to formalize that we can only test one or the other that can be implemented and it might read a little cleaner
We could also opt to not strictly assert that we have no extra headers in the malformed case, which would remove the need for all of the new logic that checks that

2024-05-09 15:29 UTC, bewebi commented on changelog/v1.17.0-beta26/envoy-bump-and-test-multivalueheader-fix.yaml
> +      type with `unwrapAsApiGateway` enabled would lead to a 500 response
https://github.com/solo-io/gloo/pull/9455/commits/90c197c58e05afeefcf4056651f7a13d4ae4fb6b

2024-05-09 15:29 UTC, bewebi commented on test/e2e/aws_test.go
> +	// this tests the case where a lambda returns malformed multiValueHeaders, a case which previously caused Envoy to
https://github.com/solo-io/gloo/pull/9455/commits/e36b6ea1667a1530b4bdd753544a3da44136ef54

2024-05-09 15:36 UTC, nfuden approved these changes

2024-05-09 16:46 UTC, ashishb-solo commented on test/e2e/aws_test.go
> +				Custom:     And(testmatchers.ContainHeaders(params.expectedHeaders), testmatchers.ContainHeaderKeysExact(params.exactExpectedHeaderKeys)),
Ah, I see now - I misread `ContainHeaderKeysExact` before and thought it was checking values also. Thanks for explaining!

2024-05-09 16:47 UTC, ashishb-solo commented on test/gomega/matchers/contain_headers.go
> +func ContainHeaderKeysExact(keys []string) types.GomegaMatcher {
in retrospect, i think the current name is better, so i'm closing this

2024-05-09 16:47 UTC, ashishb-solo approved these changes

2024-05-09 17:28 UTC, bewebi commented
bulldozer?

2024-05-09 17:29 UTC, merged