helm: Add additional labels to charts
solo-io/gloo pull request #9491
Opened 2024-05-15 22:40 UTC by davidjumani

Continuation of https://github.com/solo-io/gloo/pull/9195

# Description
This new feature is to add additionalLabels to helm chart

# Context
See issue [here](https://github.com/solo-io/gloo/issues/9035)

## Testing steps
I manually verified behavior by templating the helm chart with different values

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

2024-05-15 23:48 UTC, Rachael-Graham submitted a review, later dismissed

2024-05-16 14:31 UTC, davidjumani commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
Any thoughts on this ?

2024-05-16 15:09 UTC, sheidkamp reviewed
Some thoughts on the tests

2024-05-16 15:09 UTC, sheidkamp commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
I think there's 2 things to test:
* that the include template renders correctly
* that the template is included everywhere it need to be

This test addresses the first point. I agree that tests in this format for the second point would be cumbersome. Maybe we can address this with some kind of grep/shell command that can look for manual applications of `app: gloo` and `labels` that don't use the include? The command could then be added to the PR description and this comment for later reference.

2024-05-16 15:09 UTC, sheidkamp commented on install/helm/gloo/generate/values.go
> +	AdditionalLabels     map[string]string  `json:"additionalLabels,omitempty" desc:"Additional labels to add to gloo resources."`
```suggestion
	AdditionalLabels     map[string]string  `json:"additionalLabels,omitempty" desc:"Additional labels to add to all gloo resources."`
```

2024-05-16 15:33 UTC, davidjumani commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
Thanks. Found a way to expect the labels on all resources

2024-05-16 15:43 UTC, sheidkamp requested changes

2024-05-16 15:43 UTC, sheidkamp commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
I like this test, but it only covers the resources that happen to get rendered with the default helm.

Can we still add command line type of check to examine every template?

2024-05-16 15:51 UTC, davidjumani commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
The output of `helm template` is converted and checked for the required labels (just like a grep)
I've added custom helm settings to enable components that generate their own resources

2024-05-16 15:54 UTC, sheidkamp approved these changes

2024-05-16 15:54 UTC, sheidkamp commented on install/test/helm_test.go
> +			// Instead just validating that one of them has it is sufficient to ensure that the chart renders with the additional labels
Even better

2024-05-16 16:54 UTC, davidjumani commented
/kick

2024-05-16 17:15 UTC, merged