Default GatewayParameters use only valid fields for image definitions
solo-io/gloo pull request #9531
Opened 2024-05-28 16:35 UTC by jbohanon

# Description

Address flakes in CI setup due to disparity between fields available in main helm chart `Image` ([ref](https://github.com/solo-io/gloo/blob/53f2eb8ef4bc8f71525827a68a658dbd4e0384bc/install/helm/gloo/generate/values.go#L65)) and k8s gw deployer `helmImage` ([ref](https://github.com/solo-io/gloo/blob/53f2eb8ef4bc8f71525827a68a658dbd4e0384bc/projects/gateway2/deployer/values.go#L67))

_Fill out any of the following sections that are relevant and remove the others_
## API changes
- Added x field to y resource
- ...

## Code changes
- Fix error in `Foo()` function
- Add `Bar()` function
- ...

## CI changes
- Adjusted schedule for x job
- ...

## Docs changes
- Added guide about feature x to public docs
- Updated README to account for y behavior
- ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

See slack conversation [here](https://solo-io-corp.slack.com/archives/some/post)

## Interesting decisions
 
We chose to do things this way because ...

## Testing steps

I manually verified behavior by ...

## Notes for reviewers

Be sure to verify intended behavior by ...

Please proofread comments on ...

This is a complex PR and may require a huddle to discuss ...

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-05-28 19:25 UTC, sam-heilbron requested changes
Can you add a test that demonstrates this working and would fail without your template changes?

2024-05-29 16:34 UTC, sam-heilbron commented
The new tests are failing:
```
Step #1 - "run-tests": Step #7 - "run-tests":     <string>: 1.17.0-beta33-9531
Step #1 - "run-tests": Step #7 - "run-tests": to equal
Step #1 - "run-tests": Step #7 - "run-tests":     <string>: 1.0.1-dev
Step #1 - "run-tests": Step #7 - "run-tests": 
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m------------------------------[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;9m• [FAILED] [0.393 seconds][0m
Step #1 - "run-tests": Step #7 - "run-tests": [0mKubernetes Gateway API integration [38;5;243mwhen kube gateway integration is enabled [38;5;9m[1m[It] renders default GatewayParameters[0m
Step #1 - "run-tests": Step #7 - "run-tests": [38;5;243m/workspace/gloo/install/test/k8sgateway_test.go:57[0m
```

I will try to investigate later today if I have time, though I likely won't

2024-05-29 17:16 UTC, jenshu commented on install/helm/gloo/templates/_gg-helpers.tpl
> +{{- define "gloo-gateway.deployerImage" -}}
nit re: the func name and comment here - these don't necessarily need to match the deployer's internal helm values, but they need to match the fields supported in the [image proto](https://github.com/solo-io/gloo/blob/6122c73612de3bed0cfd4f1f960f33e62c4b814f/projects/gateway2/api/v1alpha1/kube/container.proto#L13) used by the GatewayParameters

2024-05-29 19:11 UTC, npolshakova commented on install/helm/gloo/templates/43-gatewayparameters.yaml
> +{{- merge $global.glooMtls.sds.image $global.image | include "gloo-gateway.deployerImage" | nindent 8 }}
Can we use the image from: `{{- $image := merge $gg.image $global.image }}` instead of `global.image`?

2024-05-29 19:12 UTC, npolshakova commented on install/test/k8sgateway_test.go
> +		JustBeforeEach(func() {
I was thinking a helm test like this: https://github.com/solo-io/gloo/blob/main/install/test/helm_test.go#L1001 (But for checking if the GatewayParameters were correctly rendered)

2024-05-29 19:13 UTC, npolshakova commented on install/test/k8sgateway_test.go
> +		JustBeforeEach(func() {
I think these new tests are also useful- but having a helm unit test is a quicker way to sanity check the render looks correct for the default values.

2024-05-29 19:26 UTC, jbohanon commented on install/helm/gloo/templates/43-gatewayparameters.yaml
> +{{- merge $global.glooMtls.sds.image $global.image | include "gloo-gateway.deployerImage" | nindent 8 }}
That image (`$gg.image`) is intended to be the envoy image. I need to clean that up but that seems like not the scope of this PR.

2024-05-29 19:27 UTC, jbohanon commented on install/test/k8sgateway_test.go
> +		JustBeforeEach(func() {
It's not structured exactly the same but let me know if the test added in https://github.com/solo-io/gloo/pull/9531/commits/bb2b93595a3291eb2553d432ecceca72e9a6aa0a covers what you were thinking

2024-05-29 19:28 UTC, jbohanon commented on install/helm/gloo/templates/_gg-helpers.tpl
> +{{- define "gloo-gateway.deployerImage" -}}
I updated the comment and helper name

2024-05-29 19:37 UTC, jenshu approved these changes

2024-05-29 19:42 UTC, npolshakova commented on install/helm/gloo/templates/43-gatewayparameters.yaml
> +{{- merge $global.glooMtls.sds.image $global.image | include "gloo-gateway.deployerImage" | nindent 8 }}
Ah- so this value is always the envoy image? https://github.com/solo-io/gloo/blob/main/install/helm/gloo/values-template.yaml#L12 Can we rename the field to envoy image in a follow up?

2024-05-29 19:42 UTC, npolshakova approved these changes

2024-05-29 19:43 UTC, jbohanon commented on install/helm/gloo/templates/43-gatewayparameters.yaml
> +{{- merge $global.glooMtls.sds.image $global.image | include "gloo-gateway.deployerImage" | nindent 8 }}
Yes, I understand the confusion

2024-05-29 19:56 UTC, sam-heilbron approved these changes

2024-05-29 19:56 UTC, merged