GGv2: Add Prometheus stats listener to Envoy
solo-io/gloo pull request #9658
Opened 2024-06-21 15:38 UTC by ilackarms

2024-06-21 17:37 UTC, sam-heilbron reviewed
looking good!

2024-06-21 17:37 UTC, sam-heilbron commented on projects/gateway2/api/v1alpha1/gateway_parameters.proto
> +  // Whether to enable the stats server. Defaults to true.
nit: Is this accurate? To me this implies that we start a server if this is on, but it's more "whether to expose metrics annotations and ports for scraping"?

2024-06-21 17:37 UTC, sam-heilbron commented on projects/gateway2/deployer/deployer_test.go
> +				Expect(dep.Spec.Template.Annotations).To(HaveKeyWithValue("prometheus.io/scrape", "true"))
🎉

2024-06-21 17:37 UTC, sam-heilbron commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  loopBackAddress: "127.0.0.1"
I like the concept of this, though I don't think I see it used anywhere. can you point to me where it's used?

2024-06-21 18:06 UTC, ilackarms commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  loopBackAddress: "127.0.0.1"
not sure what you mean (thoughi. see a typo)

2024-06-21 20:55 UTC, sam-heilbron commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  loopBackAddress: "127.0.0.1"
Where is this helm value used in our template?

2024-06-24 16:01 UTC, ilackarms commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  loopBackAddress: "127.0.0.1"
doesn't seem to actually be used anywhere not sure why we have it here

2024-06-24 17:19 UTC, nfuden commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  loopBackAddress: "127.0.0.1"
Likely it was due to being ported over and gloo-gateway no longer having the concept of a prestop graceful shutdown hook

2024-06-24 22:40 UTC, ilackarms commented
<img width="686" alt="image" src="https://github.com/solo-io/gloo/assets/5974898/d9453907-3002-4d1d-9949-a488abed0461">

With this change I can now see stats on port `9091/metrics` of the gateway proxy.

2024-06-24 22:42 UTC, ilackarms commented
had to change the default (currently non-configurable) port to 9091 since 8081 had a conflcit with our existing tests, seems unimportant, just something we need to document

2024-06-25 00:44 UTC, jbohanon requested changes

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/deployer/values.go
> +	ServiceAccount *helmServiceAccount `json:"serviceAccount,omitempty"`
Is there a reason this was added back in? We removed it in a recent PR since it's not user-configurable yet

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/deployer/deployer.go
> +	gateway := vals.Gateway
nit: the comment above the added lines is more apropos the lines it was originally above

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/deployer/deployer.go
> +			LoopbackAddress: "127.0.0.1",
Is there anywhere that we are actually overriding this with gatewayparameters-supplied values?

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/api/v1alpha1/gateway_parameters.proto
> +  .google.protobuf.StringValue loopback_address = 8;
We need to define the merge semantics for these new fields in deployer/merge.go

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
> +            address: 0.0.0.0
Is this where the configurable `loopBackAddress` was going to be implemented?

2024-06-25 00:44 UTC, jbohanon commented on projects/gateway2/helm/gloo-gateway/values.yaml
> +  stats:
Defaults should be defined on the main helm chart values-template.yaml and populated in the default gatewayparameters template (43-gatewayparameters.yaml)

2024-06-25 00:49 UTC, ilackarms commented on projects/gateway2/deployer/values.go
> +	ServiceAccount *helmServiceAccount `json:"serviceAccount,omitempty"`
ah must have been a bad merge, thanks for the catch

2024-06-25 10:12 UTC, ilackarms commented on projects/gateway2/api/v1alpha1/gateway_parameters.proto
> +  .google.protobuf.StringValue loopback_address = 8;
not a great pattern to require this, we should probably update the code to use reflection or another means to merge without needing to update `merge.go` every time we add a new field (but will follow the convention for now)

2024-06-25 14:54 UTC, lgadban commented on projects/gateway2/api/v1alpha1/gateway_parameters.proto
> +  .google.protobuf.StringValue stats_route_prefix_rewrite = 4;
do we really need all this as well?

2024-06-25 18:02 UTC, ilackarms commented on projects/gateway2/api/v1alpha1/gateway_parameters.proto
> +  .google.protobuf.StringValue stats_route_prefix_rewrite = 4;
i'm just mirroring what we have in GE already; i can remove these if we want to make it more restrictive

2024-06-25 18:18 UTC, ilackarms commented on projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml
> +            address: 0.0.0.0
no, it was meant to be used in some template fields that were removed from this PR (but exist in the gateway-proxy template in classic GE) https://github.com/solo-io/gloo/blob/main/install/helm/gloo/templates/9-gateway-proxy-configmap.yaml#L379

2024-06-25 19:04 UTC, nfuden submitted a review, later dismissed

2024-06-25 19:33 UTC, jenshu approved these changes

2024-06-25 19:33 UTC, jenshu commented on projects/gateway2/deployer/deployer_test.go
> +					// make sure the stats listener is enabled
nit: would be good to have a test that disables it too

2024-06-25 19:33 UTC, jenshu commented on projects/gateway2/deployer/values.go
> +type helmServiceAccount struct {
nit: not used

2024-06-25 19:33 UTC, jenshu commented on projects/gateway2/deployer/values.go
> +	StatsPrefixRewrite string `json:"statsPrefixRewrite,omitempty"`
nit: these could all be pointers for consistency

2024-06-25 20:39 UTC, nfuden approved these changes

2024-06-25 21:55 UTC, jenshu approved these changes

2024-06-25 21:56 UTC, jenshu commented
merge

2024-06-25 21:56 UTC, merged