WIP: Fix/enforce regex inutils
solo-io/gloo pull request #9735
Opened 2024-07-09 12:23 UTC by nfuden

# Description

Please include a high level summary of the changes.

This bug fixes ... \ This new feature can be used to ...

_Fill out any of the following sections that are relevant and remove the others_
## API changes
- Added x field to y resource
- ...

## Code changes
- Fix error in `Foo()` function
- Add `Bar()` function
- ...

## CI changes
- Adjusted schedule for x job
- ...

## Docs changes
- Added guide about feature x to public docs
- Updated README to account for y behavior
- ...

# Context

Users ran into this bug doing ... \ Users needed this feature to ...

See slack conversation [here](https://solo-io-corp.slack.com/archives/some/post)

## Interesting decisions
 
We chose to do things this way because ...

## Testing steps

I manually verified behavior by ...

## Notes for reviewers

Be sure to verify intended behavior by ...

Please proofread comments on ...

This is a complex PR and may require a huddle to discuss ...

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

2024-07-11 16:46 UTC, sheidkamp requested changes
Validated and overall looks good, but we should have some tests too.

2024-07-11 16:46 UTC, sheidkamp commented on pkg/utils/regexutils/regex.go
> +// NOTE: Call this after having checked regex with CheckRegexString.
I like the note, but there's a bunch of places where `NewRegex` is called that didn't get updated to call `CheckRegexString` first. Assuming those are out of scope,  should the note be updated with "if regex validtion is needed?"

2024-07-11 16:59 UTC, nfuden commented on pkg/utils/regexutils/regex.go
> +// NOTE: Call this after having checked regex with CheckRegexString.
I showed that each of those in oss already have checks in place. Namely we already do this for route validation and use envoy validation for transforms

2024-07-12 17:03 UTC, sheidkamp approved these changes

2024-07-12 20:38 UTC, bewebi reviewed
Looks good, one nit

2024-07-12 20:38 UTC, bewebi commented on pkg/utils/regexutils/regex.go
> +func NewRegexWithProgramSize(candidateRegex string, programsize *uint32) *envoy_type_matcher_v3.RegexMatcher {
nit: I'm not sure this name change is necessary, but if we are going to change it here, we should also change it in `NewRegexFromSettings()`

2024-07-15 13:39 UTC, sheidkamp approved these changes

2024-07-15 13:43 UTC, bewebi approved these changes

2024-07-15 16:00 UTC, merged