Cherrypick gloomtls tests
solo-io/gloo pull request #9748
Opened 2024-07-11 19:12 UTC by npolshakova

Cherrypick https://github.com/solo-io/gloo/commit/8d9df95602c506067d49db9b1447b4003b19a070

2024-07-15 11:56 UTC, jbohanon approved these changes

2024-07-16 13:26 UTC, sam-heilbron requested changes
changelog needs to be 1.17

2024-07-18 00:18 UTC, jenshu approved these changes

2024-07-18 16:46 UTC, npolshakova commented
Closing in favor of https://github.com/solo-io/gloo/pull/9777 (combines both glooctl and gloomtls tests)

2024-07-18 16:46 UTC, closed without merging