fix: allows setting Istio CA_ADDR independently
solo-io/gloo pull request #9756
Opened 2024-07-12 17:53 UTC by jlourenc

# Description

https://istio.io/latest/docs/reference/commands/pilot-agent/

The Istio documentation indicates that CA_ADDR defaults to the PROXY_CONFIG discovery address. Though it should be possible to specify a CA_ADDR that is unrelated to the discovery address.

However, Gloo helm forces these two separate fields to be aligned as it is driven from a single helm value.

This change introduces an `istioSpiffeCertProviderAddress` property resolving the problem. The default is kept as `istioDiscoveryAddress` to ensure backward compatibility.

2024-07-25 19:49 UTC, sam-heilbron commented
/test

2024-07-25 19:57 UTC, sam-heilbron requested changes
Looking good! Thanks for the contribution @jlourenc . A few small nits and a request for test additions

2024-07-25 19:57 UTC, sam-heilbron commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +changelog:
This needs to be updated to reflect the current in-flight beta release. As of this comment, beta10 (https://github.com/solo-io/gloo/releases/tag/v1.18.0-beta10) is the most recent release, which means this file needs to live in the [beta11 folder](https://github.com/solo-io/gloo/tree/main/changelog/v1.18.0-beta11).

https://github.com/solo-io/gloo/blob/main/devel/contributing/pull-requests.md#include-a-changelog-entry has some more context around Pull Requests, and changelog-bot. I'm also happy to answer any questions around it

2024-07-25 19:57 UTC, sam-heilbron commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +  - type: FIX
I think this would more aptly be considered `type: HELM` as we are introducing a new Helm API (https://docs.solo.io/gloo-edge/latest/reference/changelog/changelog_types/).
```suggestion
  - type: HELM
```

2024-07-25 19:57 UTC, sam-heilbron commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +    description: >-
If we update the type to Helm, that means that this text will show up in our user-facing changelog entries: https://docs.solo.io/gloo-edge/latest/reference/changelog/open_source/. As a result, I think including the name of the new field, and the behavior it changes if you opt into it, would be useful for others using this project

2024-07-25 19:57 UTC, sam-heilbron commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            value: {{ $spec.istioSpiffeCertProviderAddress | default $spec.istioDiscoveryAddress }}
Could you add a unit test to show what this results in by default, and when a user provides an override? https://github.com/solo-io/gloo/blob/main/install/test/helm_test.go#L3680 seems to be an area where these tests could be added

2024-07-28 18:17 UTC, jlourenc commented on install/helm/gloo/templates/7-gateway-proxy-deployment.yaml
> +            value: {{ $spec.istioSpiffeCertProviderAddress | default $spec.istioDiscoveryAddress }}
Tests added.

2024-07-28 18:18 UTC, jlourenc commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +  - type: FIX
Changelog type modified.

2024-07-28 18:18 UTC, jlourenc commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +    description: >-
Description updated. Let me know if you'd like me to tweak anything.

2024-07-28 18:19 UTC, jlourenc commented on changelog/v1.18.0-beta8/istio-spiffe-cert-provider-address.yaml
> +changelog:
Changelog file moved to `v1.18.0-beta12`.

2024-07-28 18:20 UTC, jlourenc commented
Hey @sam-heilbron , thanks for the review. I've updated the PR based on your comments. Let me know if you'd like me to change anything. Thanks!

2024-08-02 19:03 UTC, sam-heilbron reviewed
### Part 1: Fixing Static Code Analysis
Static code analysis is failing with:
```
Error: Generating code produced a non-empty diff
+ [[ 1 -ne 0 ]]
+ echo 'Error: Generating code produced a non-empty diff'
Try running 'make install-go-tools generated-code -B' then re-pushing.
+ echo 'Try running '\''make install-go-tools generated-code -B'\'' then re-pushing.'
+ git status --porcelain
 M docs/content/reference/values.txt
+ git diff
+ cat
diff --git a/docs/content/reference/values.txt b/docs/content/reference/values.txt
index 2449f1e..a86c505 100644
--- a/docs/content/reference/values.txt
+++ b/docs/content/reference/values.txt
@@ -1215,8 +1215,7 @@
 |gatewayProxies.gatewayProxy.podDisruptionBudget.kubeResourceOverride.NAME|interface||override fields in the generated resource by specifying the yaml structure to override under the top-level key.|
 |gatewayProxies.gatewayProxy.istioMetaMeshId|string||ISTIO_META_MESH_ID Environment Variable. Defaults to "cluster.local"|
 |gatewayProxies.gatewayProxy.istioMetaClusterId|string||ISTIO_META_CLUSTER_ID Environment Variable. Defaults to "Kubernetes"|
-|gatewayProxies.gatewayProxy.istioDiscoveryAddress|string||discoveryAddress field of the PROXY_CONFIG environment variable. Defaults to "istiod.istio-system.svc:15012"|
-|gatewayProxies.gatewayProxy.istioSpiffeCertProviderAddress|string||Address of the spiffe certificate provider. Defaults to istioDiscoveryAddress|
+|gatewayProxies.gatewayProxy.istioDiscoveryAddress|string|istiod.istio-system.svc:15012|discoveryAddress field of the PROXY_CONFIG environment variable. Defaults to "istiod.istio-system.svc:15012"|
 |gatewayProxies.gatewayProxy.envoyLogLevel|string||Level at which the pod should log. Options include "trace", "info", "debug", "warn", "error", "critical" and "off". Default level is info|
 |gatewayProxies.gatewayProxy.envoyStatsConfig.NAME|interface||Envoy statistics configuration, such as tagging. For more info, see https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#config-metrics-v3-statsconfig|
 |gatewayProxies.gatewayProxy.xdsServiceAddress|string||The k8s service name for the xds server. Defaults to gloo.|
+ exit 1
```

To resolve this, you should be able to run:
```
make -B generate-helm-files
```
See https://github.com/solo-io/gloo/blob/main/devel/contributing/code-generation.md for more details on the various commands. If after running/pushing that, static code analysis still fails, you should be able to run:
```
make -B generated-code
```

### Part 2: Applying Change to other Code Domains
I mentioned in the issue that I wrote up, but https://github.com/solo-io/gloo/blob/main/projects/gateway2/helm/gloo-gateway/templates/gateway/proxy-deployment.yaml#L184 also has some relevant code that could be improved with this change.

It's not strictly a requirement for this PR to merge, and I would be happy to approve your current changes. I just wanted to callout if we want to be consistent across the product with this change, updating the linked area would be valuable

2024-08-09 17:59 UTC, jlourenc commented
Hey @sam-heilbron 

I believe I have updated the documentation appropriately as well as linked the issue.

I won't be handling "Part 2", as I believe more changes than just helm are necessary here. If that's not a blocker for the PR, than I'd rather a Solo person ensure parity is put in place eventually.

2024-08-09 20:58 UTC, sam-heilbron commented
/test

2024-08-09 20:58 UTC, sam-heilbron approved these changes
LGTM! Thanks for the contribution! We'll need to update the changelog entry to live in the beta15 folder, since beta14 was released today. When that is done, changelog-bot should be happy

2024-08-09 21:43 UTC, sam-heilbron commented
I caught up with @jlourenc and he agreed it would be ok for us to update the branch to get changelog-bot, static-code-analysis and build-bot passing. I will try to do that at some point this weekend or on Monday

2024-08-13 20:38 UTC, npolshakova approved these changes

2024-08-14 17:27 UTC, sam-heilbron commented
/kick 

Logs: https://storage.googleapis.com/solo-public-build-logs/logs.html?buildid=f08b6d22-73ea-4e0d-9a75-a7f884957404
Error: 
```
Step #0 - "publish-artifacts": Step #4 - "publish-docker": 6a6995cb4e26: Layer already exists
Step #0 - "publish-artifacts": Step #4 - "publish-docker": d57032a94b7a: Pushed
Step #0 - "publish-artifacts": Step #4 - "publish-docker": 7f88af9acb24: Pushed
Step #0 - "publish-artifacts": Step #4 - "publish-docker": received unexpected HTTP status: 502 Bad Gateway
Step #0 - "publish-artifacts": Step #4 - "publish-docker": make: *** [Makefile:938: docker-push-gloo] Error 1
```

2024-08-14 17:48 UTC, merged